import type { Opportunity } from "@/domains/opportunities/types";
import type { Brief } from "@/domains/briefs/types";
import type { ChangelogEntry } from "@/domains/changelog/types";
import type { Result } from "@/domains/results/types";
import type { Competitor, CompetitorSnapshot } from "@/domains/competitors/types";
import type { CoverageItem } from "@/domains/coverage/types";
import type { WeeklySummary } from "@/domains/weekly/types";

export const opportunities: Opportunity[] = [
  {
    id: "opp-1",
    title: 'No citation in ChatGPT for "best custom home builder Palo Alto"',
    description:
      "ChatGPT consistently recommends De Mattei and Flegel's when asked about custom home builders in Palo Alto. Ritz Builders is absent across 5 test queries despite strong local presence.",
    query_text: "best custom home builder in Palo Alto",
    platforms: ["chatgpt"],
    intent_type: "commercial",
    city: "Palo Alto",
    topic: "Custom Home Building",
    tags: ["city-page", "entity-signals", "citation-gap"],
    current_status: "executing",
    priority: "critical",
    estimated_impact: "high",
    effort: "large",
    confidence: "high",
    source: "manual_audit",
    baseline_position: null,
    target_position: 1,
    target_url: "/locations/palo-alto",
    competitor_ids: ["comp-1"],
    primary_competitor_id: "comp-1",
    linked_brief_ids: ["brief-1"],
    linked_changelog_ids: ["cl-2"],
    related_opportunity_ids: ["opp-6"],
    identified_at: "2025-03-15T10:00:00Z",
    activated_at: "2025-03-21T10:00:00Z",
    captured_at: null,
    lost_at: null,
    last_verified_at: "2025-03-28T08:00:00Z",
    assessed_at: "2025-03-20T09:00:00Z",
    deferred_at: null,
    deferred_until: null,
    closed_at: null,
    close_reason: null,
    regressed_at: null,
    notes: null,
    created_at: "2025-03-15T10:00:00Z",
    updated_at: "2025-03-28T08:00:00Z",
  },
  {
    id: "opp-2",
    title: 'Missing FAQ coverage for "build on your lot Cupertino" queries',
    description:
      "Google AIO pulls FAQ content from competitor sites for build-on-your-lot queries in Cupertino. Our /services/custom-homes page has no FAQ markup.",
    query_text: "can I build a custom home on my lot in Cupertino",
    platforms: ["google_aio"],
    intent_type: "informational",
    city: "Cupertino",
    topic: "Build on Your Lot",
    tags: ["faq-schema", "content-gap"],
    current_status: "validating",
    priority: "high",
    estimated_impact: "high",
    effort: "medium",
    confidence: "medium",
    source: "manual_audit",
    baseline_position: 8,
    target_position: 1,
    target_url: "/services/custom-homes",
    competitor_ids: ["comp-2"],
    primary_competitor_id: "comp-2",
    linked_brief_ids: ["brief-2"],
    linked_changelog_ids: ["cl-1"],
    related_opportunity_ids: ["opp-5"],
    identified_at: "2025-03-14T09:00:00Z",
    activated_at: "2025-03-20T14:30:00Z",
    captured_at: null,
    lost_at: null,
    last_verified_at: "2025-03-26T08:00:00Z",
    assessed_at: "2025-03-19T10:00:00Z",
    deferred_at: null,
    deferred_until: null,
    closed_at: null,
    close_reason: null,
    regressed_at: null,
    notes: "FAQ content drafted, pending schema markup",
    created_at: "2025-03-14T09:00:00Z",
    updated_at: "2025-03-26T08:00:00Z",
  },
  {
    id: "opp-3",
    title: "Perplexity recommends competitor for luxury kitchen remodel queries",
    description:
      "Perplexity cites Harrell Remodeling's blog as the authority for luxury kitchen remodels in the South Bay. Our content on /services/kitchen-remodel is thin and lacks structured data.",
    query_text: "luxury kitchen remodel contractor Bay Area",
    platforms: ["perplexity"],
    intent_type: "commercial",
    city: null,
    topic: "Kitchen Remodel",
    tags: ["content-depth", "structured-data", "competitor-dominated"],
    current_status: "queued",
    priority: "high",
    estimated_impact: "medium",
    effort: "large",
    confidence: "medium",
    source: "competitor_watch",
    baseline_position: null,
    target_position: 3,
    target_url: "/services/kitchen-remodel",
    competitor_ids: ["comp-3"],
    primary_competitor_id: "comp-3",
    linked_brief_ids: [],
    linked_changelog_ids: [],
    related_opportunity_ids: [],
    identified_at: "2025-03-18T11:00:00Z",
    activated_at: null,
    captured_at: null,
    lost_at: null,
    last_verified_at: "2025-03-25T08:00:00Z",
    assessed_at: "2025-03-20T09:00:00Z",
    deferred_at: null,
    deferred_until: null,
    closed_at: null,
    close_reason: null,
    regressed_at: null,
    notes: null,
    created_at: "2025-03-18T11:00:00Z",
    updated_at: "2025-03-25T08:00:00Z",
  },
  {
    id: "opp-4",
    title: 'Google AIO snippet captured by De Mattei for "ADU builder San Jose"',
    description:
      "De Mattei owns the AIO featured result for ADU queries in San Jose. We have no dedicated ADU page and no schema targeting this intent.",
    query_text: "ADU builder San Jose California",
    platforms: ["google_aio"],
    intent_type: "transactional",
    city: "San Jose",
    topic: "ADU Construction",
    tags: ["new-page-needed", "schema-gap"],
    current_status: "executing",
    priority: "medium",
    estimated_impact: "medium",
    effort: "large",
    confidence: "low",
    source: "tool_alert",
    baseline_position: null,
    target_position: 1,
    target_url: null,
    competitor_ids: ["comp-1"],
    primary_competitor_id: "comp-1",
    linked_brief_ids: ["brief-3"],
    linked_changelog_ids: [],
    related_opportunity_ids: [],
    identified_at: "2025-03-20T08:00:00Z",
    activated_at: "2025-03-22T10:00:00Z",
    captured_at: null,
    lost_at: null,
    last_verified_at: null,
    assessed_at: "2025-03-21T09:00:00Z",
    deferred_at: null,
    deferred_until: null,
    closed_at: null,
    close_reason: null,
    regressed_at: null,
    notes: null,
    created_at: "2025-03-20T08:00:00Z",
    updated_at: "2025-03-22T10:00:00Z",
  },
  {
    id: "opp-5",
    title: "No structured data on /services/whole-house-remodel",
    description:
      "Service page lacks LocalBusiness, FAQPage, and Service schema. Competitors have full structured data coverage for remodel queries.",
    query_text: "whole house remodel contractor near me",
    platforms: ["google_aio", "chatgpt", "perplexity"],
    intent_type: "commercial",
    city: null,
    topic: "Whole House Remodel",
    tags: ["structured-data", "cross-platform"],
    current_status: "validating",
    priority: "medium",
    estimated_impact: "medium",
    effort: "small",
    confidence: "high",
    source: "manual_audit",
    baseline_position: 12,
    target_position: 5,
    target_url: "/services/whole-house-remodel",
    competitor_ids: [],
    primary_competitor_id: null,
    linked_brief_ids: ["brief-2"],
    linked_changelog_ids: ["cl-3"],
    related_opportunity_ids: ["opp-2"],
    identified_at: "2025-03-12T15:00:00Z",
    activated_at: "2025-03-20T16:00:00Z",
    captured_at: null,
    lost_at: null,
    last_verified_at: "2025-03-27T08:00:00Z",
    assessed_at: "2025-03-19T10:00:00Z",
    deferred_at: null,
    deferred_until: null,
    closed_at: null,
    close_reason: null,
    regressed_at: null,
    notes: "Schema implementation in progress",
    created_at: "2025-03-12T15:00:00Z",
    updated_at: "2025-03-27T08:00:00Z",
  },
  {
    id: "opp-6",
    title: 'Captured: now cited in ChatGPT for "home addition Palo Alto"',
    description:
      "After content rebuild and citation campaign, Ritz Builders is now the #2 cited result in ChatGPT for home addition queries in Palo Alto.",
    query_text: "home addition contractor Palo Alto",
    platforms: ["chatgpt"],
    intent_type: "commercial",
    city: "Palo Alto",
    topic: "Home Additions",
    tags: ["citation-win", "monitoring"],
    current_status: "captured",
    priority: "high",
    estimated_impact: "high",
    effort: "large",
    confidence: "high",
    source: "manual_audit",
    baseline_position: null,
    target_position: 1,
    target_url: "/locations/palo-alto",
    competitor_ids: [],
    primary_competitor_id: null,
    linked_brief_ids: [],
    linked_changelog_ids: ["cl-2", "cl-5"],
    related_opportunity_ids: ["opp-1"],
    identified_at: "2025-02-28T09:00:00Z",
    activated_at: "2025-03-10T09:00:00Z",
    captured_at: "2025-03-25T16:00:00Z",
    lost_at: null,
    last_verified_at: "2025-03-28T08:00:00Z",
    assessed_at: "2025-03-09T10:00:00Z",
    deferred_at: null,
    deferred_until: null,
    closed_at: null,
    close_reason: null,
    regressed_at: null,
    notes: "Monitoring for stability over next 2 weeks",
    created_at: "2025-02-28T09:00:00Z",
    updated_at: "2025-03-28T08:00:00Z",
  },
  {
    id: "opp-7",
    title: "Los Altos city page missing — zero local coverage",
    description:
      "No dedicated city page for Los Altos despite being a core service area. Competitors have dedicated pages ranking for all Los Altos builder queries.",
    query_text: "custom home builder Los Altos",
    platforms: ["google_aio", "chatgpt", "perplexity"],
    intent_type: "commercial",
    city: "Los Altos",
    topic: "Local Coverage",
    tags: ["new-page-needed", "city-coverage-gap", "high-urgency"],
    current_status: "new",
    priority: "critical",
    estimated_impact: "high",
    effort: "large",
    confidence: "high",
    source: "manual_audit",
    baseline_position: null,
    target_position: 3,
    target_url: null,
    competitor_ids: ["comp-4"],
    primary_competitor_id: "comp-4",
    linked_brief_ids: [],
    linked_changelog_ids: [],
    related_opportunity_ids: ["opp-1"],
    identified_at: "2025-03-22T09:00:00Z",
    activated_at: null,
    captured_at: null,
    lost_at: null,
    last_verified_at: null,
    assessed_at: null,
    deferred_at: null,
    deferred_until: null,
    closed_at: null,
    close_reason: null,
    regressed_at: null,
    notes: null,
    created_at: "2025-03-22T09:00:00Z",
    updated_at: "2025-03-22T09:00:00Z",
  },
];

export const briefs: Brief[] = [
  {
    id: "brief-1",
    title: "Rebuild /locations/palo-alto for AEO dominance",
    objective:
      "Restructure the Palo Alto city page with entity-optimized content, comprehensive FAQ markup, and local schema to capture AI search citations.",
    opportunity_ids: ["opp-1", "opp-6"],
    status: "in_progress",
    priority: "critical",
    brief_type: "page_rebuild",
    effort: "large",
    target_url: "/locations/palo-alto",
    target_city: "Palo Alto",
    target_topic: "Custom Home Building",
    checklist: [
      {
        id: "b1-cl-1",
        label: "Audit existing page content, schema, and internal links",
        status: "done",
        sort_order: 1,
        linked_changelog_id: null,
        completed_at: "2025-03-17T10:00:00Z",
        notes: null,
      },
      {
        id: "b1-cl-2",
        label: "Rewrite copy with entity-first structure",
        status: "done",
        sort_order: 2,
        linked_changelog_id: "cl-2",
        completed_at: "2025-03-20T14:00:00Z",
        notes: null,
      },
      {
        id: "b1-cl-3",
        label: "Implement FAQPage JSON-LD with 8-10 high-intent questions",
        status: "done",
        sort_order: 3,
        linked_changelog_id: "cl-2",
        completed_at: "2025-03-22T14:00:00Z",
        notes: null,
      },
      {
        id: "b1-cl-4",
        label: "Add LocalBusiness schema with geo coordinates",
        status: "in_progress",
        sort_order: 4,
        linked_changelog_id: null,
        completed_at: null,
        notes: null,
      },
      {
        id: "b1-cl-5",
        label: "Include project gallery with structured data",
        status: "pending",
        sort_order: 5,
        linked_changelog_id: null,
        completed_at: null,
        notes: null,
      },
      {
        id: "b1-cl-6",
        label: "Update internal links from related pages",
        status: "pending",
        sort_order: 6,
        linked_changelog_id: null,
        completed_at: null,
        notes: null,
      },
      {
        id: "b1-cl-7",
        label: "Validate with Rich Results Test",
        status: "pending",
        sort_order: 7,
        linked_changelog_id: null,
        completed_at: null,
        notes: null,
      },
      {
        id: "b1-cl-8",
        label: "Submit to Google Search Console for re-crawl",
        status: "pending",
        sort_order: 8,
        linked_changelog_id: null,
        completed_at: null,
        notes: null,
      },
    ],
    expected_outcomes: [
      {
        id: "b1-eo-1",
        description:
          "ChatGPT begins citing Ritz Builders for Palo Alto custom home queries",
        metric_type: "citation_share",
        platform: "chatgpt",
        target_value: 15,
        baseline_value: 12,
        timeframe: "2 weeks",
        verdict: "hit",
        actual_value: 18.5,
        result_id: "res-1",
        judged_at: "2025-03-25T08:00:00Z",
      },
      {
        id: "b1-eo-2",
        description:
          "Google AIO shows Palo Alto page in featured snippet position",
        metric_type: "visibility_rank",
        platform: "google_aio",
        target_value: 3,
        baseline_value: null,
        timeframe: "1 week",
        verdict: "pending",
        actual_value: null,
        result_id: null,
        judged_at: null,
      },
    ],
    linked_changelog_ids: ["cl-2"],
    related_brief_ids: ["brief-2"],
    prior_brief_id: null,
    blocked_reason: null,
    due_date: "2025-04-01",
    approved_at: "2025-03-17T09:00:00Z",
    started_at: "2025-03-17T10:00:00Z",
    blocked_at: null,
    completed_at: null,
    impact_window_ends_at: "2025-04-15T00:00:00Z",
    retrospective: null,
    created_at: "2025-03-16T10:00:00Z",
    updated_at: "2025-03-22T14:00:00Z",
  },
  {
    id: "brief-2",
    title: "Add FAQPage schema to all service pages",
    objective:
      "Implement FAQ structured data across all service pages to capture Google AIO featured results and improve AI search discoverability.",
    opportunity_ids: ["opp-2", "opp-5"],
    status: "in_progress",
    priority: "high",
    brief_type: "schema_fix",
    effort: "medium",
    target_url: null,
    target_city: null,
    target_topic: "All Services",
    checklist: [
      {
        id: "b2-cl-1",
        label: "Audit current schema coverage across service pages",
        status: "done",
        sort_order: 1,
        linked_changelog_id: null,
        completed_at: "2025-03-16T10:00:00Z",
        notes: null,
      },
      {
        id: "b2-cl-2",
        label: "Draft JSON-LD for each target service page",
        status: "done",
        sort_order: 2,
        linked_changelog_id: null,
        completed_at: "2025-03-18T14:00:00Z",
        notes: null,
      },
      {
        id: "b2-cl-3",
        label: "Implement FAQPage schema on kitchen remodel page",
        status: "done",
        sort_order: 3,
        linked_changelog_id: "cl-1",
        completed_at: "2025-03-22T14:30:00Z",
        notes: null,
      },
      {
        id: "b2-cl-4",
        label: "Implement FAQPage schema on bathroom remodel page",
        status: "done",
        sort_order: 4,
        linked_changelog_id: "cl-3",
        completed_at: "2025-03-23T09:00:00Z",
        notes: null,
      },
      {
        id: "b2-cl-5",
        label: "Implement schema on remaining service pages",
        status: "in_progress",
        sort_order: 5,
        linked_changelog_id: null,
        completed_at: null,
        notes: "Whole-house remodel page in progress",
      },
      {
        id: "b2-cl-6",
        label: "Validate each page with Rich Results Test",
        status: "pending",
        sort_order: 6,
        linked_changelog_id: null,
        completed_at: null,
        notes: null,
      },
      {
        id: "b2-cl-7",
        label: "Submit updated pages to Search Console",
        status: "pending",
        sort_order: 7,
        linked_changelog_id: null,
        completed_at: null,
        notes: null,
      },
    ],
    expected_outcomes: [
      {
        id: "b2-eo-1",
        description:
          "Google AIO shows FAQ rich results on kitchen remodel page",
        metric_type: "visibility_rank",
        platform: "google_aio",
        target_value: 5,
        baseline_value: 8,
        timeframe: "1 week",
        verdict: "hit",
        actual_value: 3,
        result_id: "res-2",
        judged_at: "2025-03-25T08:00:00Z",
      },
      {
        id: "b2-eo-2",
        description:
          "Service pages average position improves in AIO results",
        metric_type: "average_position",
        platform: "google_aio",
        target_value: 5,
        baseline_value: 7.8,
        timeframe: "2 weeks",
        verdict: "partial",
        actual_value: 4.2,
        result_id: "res-4",
        judged_at: "2025-03-25T08:00:00Z",
      },
    ],
    linked_changelog_ids: ["cl-1", "cl-3"],
    related_brief_ids: ["brief-1"],
    prior_brief_id: null,
    blocked_reason: null,
    due_date: "2025-03-28",
    approved_at: "2025-03-16T09:00:00Z",
    started_at: "2025-03-16T10:00:00Z",
    blocked_at: null,
    completed_at: null,
    impact_window_ends_at: "2025-04-10T00:00:00Z",
    retrospective: null,
    created_at: "2025-03-15T09:00:00Z",
    updated_at: "2025-03-23T09:00:00Z",
  },
  {
    id: "brief-3",
    title: "Create new ADU landing page targeting South Bay",
    objective:
      "Build a comprehensive ADU construction page targeting San Jose, Sunnyvale, and Santa Clara queries with full schema coverage.",
    opportunity_ids: ["opp-4"],
    status: "draft",
    priority: "medium",
    brief_type: "new_page",
    effort: "large",
    target_url: "/services/adu-construction",
    target_city: "San Jose",
    target_topic: "ADU Construction",
    checklist: [
      {
        id: "b3-cl-1",
        label: "Define URL slug and add to site navigation",
        status: "pending",
        sort_order: 1,
        linked_changelog_id: null,
        completed_at: null,
        notes: null,
      },
      {
        id: "b3-cl-2",
        label: "Write comprehensive page content (1,500+ words)",
        status: "pending",
        sort_order: 2,
        linked_changelog_id: null,
        completed_at: null,
        notes: null,
      },
      {
        id: "b3-cl-3",
        label:
          "Add city-specific sections for San Jose, Sunnyvale, Santa Clara",
        status: "pending",
        sort_order: 3,
        linked_changelog_id: null,
        completed_at: null,
        notes: null,
      },
      {
        id: "b3-cl-4",
        label: "Implement Service, FAQPage, and LocalBusiness schema",
        status: "pending",
        sort_order: 4,
        linked_changelog_id: null,
        completed_at: null,
        notes: null,
      },
      {
        id: "b3-cl-5",
        label: "Add ADU project gallery with structured data",
        status: "pending",
        sort_order: 5,
        linked_changelog_id: null,
        completed_at: null,
        notes: null,
      },
      {
        id: "b3-cl-6",
        label: "Build internal links to and from related pages",
        status: "pending",
        sort_order: 6,
        linked_changelog_id: null,
        completed_at: null,
        notes: null,
      },
      {
        id: "b3-cl-7",
        label: "Add page to XML sitemap",
        status: "pending",
        sort_order: 7,
        linked_changelog_id: null,
        completed_at: null,
        notes: null,
      },
      {
        id: "b3-cl-8",
        label: "Validate schema and submit for indexing",
        status: "pending",
        sort_order: 8,
        linked_changelog_id: null,
        completed_at: null,
        notes: null,
      },
    ],
    expected_outcomes: [
      {
        id: "b3-eo-1",
        description:
          "Page ranks in top 10 for 'ADU construction San Jose'",
        metric_type: "average_position",
        platform: "google_aio",
        target_value: 10,
        baseline_value: null,
        timeframe: "2 weeks",
        verdict: "pending",
        actual_value: null,
        result_id: null,
        judged_at: null,
      },
      {
        id: "b3-eo-2",
        description:
          "ChatGPT mentions Ritz Builders for ADU queries in South Bay",
        metric_type: "mention_count",
        platform: "chatgpt",
        target_value: 1,
        baseline_value: 0,
        timeframe: "3 weeks",
        verdict: "pending",
        actual_value: null,
        result_id: null,
        judged_at: null,
      },
    ],
    linked_changelog_ids: [],
    related_brief_ids: [],
    prior_brief_id: null,
    blocked_reason: null,
    due_date: "2025-04-15",
    approved_at: null,
    started_at: null,
    blocked_at: null,
    completed_at: null,
    impact_window_ends_at: null,
    retrospective: null,
    created_at: "2025-03-20T14:00:00Z",
    updated_at: "2025-03-20T14:00:00Z",
  },
  {
    id: "brief-4",
    title: "Citation campaign for luxury remodel queries",
    objective:
      "Build citation authority through directory submissions and content partnerships to improve AI search recommendations.",
    opportunity_ids: ["opp-3"],
    status: "approved",
    priority: "high",
    brief_type: "citation_campaign",
    effort: "medium",
    target_url: null,
    target_city: null,
    target_topic: "Kitchen Remodel",
    checklist: [
      {
        id: "b4-cl-1",
        label: "Audit current directory and citation presence",
        status: "done",
        sort_order: 1,
        linked_changelog_id: null,
        completed_at: "2025-03-20T11:00:00Z",
        notes: null,
      },
      {
        id: "b4-cl-2",
        label: "Prepare optimized profiles (NAP, descriptions, photos)",
        status: "pending",
        sort_order: 2,
        linked_changelog_id: null,
        completed_at: null,
        notes: null,
      },
      {
        id: "b4-cl-3",
        label: "Submit to Houzz, Yelp, Angi with optimized profiles",
        status: "pending",
        sort_order: 3,
        linked_changelog_id: null,
        completed_at: null,
        notes: "Houzz profile already optimized via cl-5",
      },
      {
        id: "b4-cl-4",
        label: "Update existing directory listings with consistent NAP",
        status: "pending",
        sort_order: 4,
        linked_changelog_id: null,
        completed_at: null,
        notes: null,
      },
      {
        id: "b4-cl-5",
        label: "Secure 2-3 guest posts on home design publications",
        status: "pending",
        sort_order: 5,
        linked_changelog_id: null,
        completed_at: null,
        notes: null,
      },
      {
        id: "b4-cl-6",
        label:
          "Create linkable resource asset on /resources/kitchen-remodel-guide",
        status: "pending",
        sort_order: 6,
        linked_changelog_id: null,
        completed_at: null,
        notes: null,
      },
      {
        id: "b4-cl-7",
        label: "Monitor submission indexing weekly",
        status: "pending",
        sort_order: 7,
        linked_changelog_id: null,
        completed_at: null,
        notes: null,
      },
    ],
    expected_outcomes: [
      {
        id: "b4-eo-1",
        description:
          "Perplexity mentions Ritz Builders for kitchen remodel queries",
        metric_type: "mention_count",
        platform: "perplexity",
        target_value: 2,
        baseline_value: 1,
        timeframe: "3 weeks",
        verdict: "hit",
        actual_value: 4,
        result_id: "res-3",
        judged_at: "2025-03-25T08:00:00Z",
      },
      {
        id: "b4-eo-2",
        description:
          "Citation share on Perplexity improves for remodel queries",
        metric_type: "citation_share",
        platform: "perplexity",
        target_value: 20,
        baseline_value: 10,
        timeframe: "6 weeks",
        verdict: "pending",
        actual_value: null,
        result_id: null,
        judged_at: null,
      },
    ],
    linked_changelog_ids: ["cl-5"],
    related_brief_ids: [],
    prior_brief_id: null,
    blocked_reason: null,
    due_date: "2025-04-30",
    approved_at: "2025-03-20T09:00:00Z",
    started_at: null,
    blocked_at: null,
    completed_at: null,
    impact_window_ends_at: null,
    retrospective: null,
    created_at: "2025-03-19T10:00:00Z",
    updated_at: "2025-03-21T09:00:00Z",
  },
  {
    id: "brief-5",
    title: "GBP optimization for all service areas",
    objective:
      "Fully optimize Google Business Profile with service area coverage, posts, and Q&A to strengthen local entity signals.",
    opportunity_ids: [],
    status: "completed",
    priority: "high",
    brief_type: "technical_fix",
    effort: "small",
    target_url: null,
    target_city: null,
    target_topic: "Local SEO",
    checklist: [
      {
        id: "b5-cl-1",
        label: "Update GBP service areas to include all target cities",
        status: "done",
        sort_order: 1,
        linked_changelog_id: "cl-4",
        completed_at: "2025-03-05T10:00:00Z",
        notes: null,
      },
      {
        id: "b5-cl-2",
        label: "Add services with descriptions",
        status: "done",
        sort_order: 2,
        linked_changelog_id: null,
        completed_at: "2025-03-07T11:00:00Z",
        notes: null,
      },
      {
        id: "b5-cl-3",
        label: "Post weekly updates for 4 weeks",
        status: "done",
        sort_order: 3,
        linked_changelog_id: null,
        completed_at: "2025-03-10T09:00:00Z",
        notes: null,
      },
      {
        id: "b5-cl-4",
        label: "Seed Q&A with top queries",
        status: "done",
        sort_order: 4,
        linked_changelog_id: null,
        completed_at: "2025-03-12T15:00:00Z",
        notes: null,
      },
      {
        id: "b5-cl-5",
        label: "Upload 20 new project photos with geo tags",
        status: "done",
        sort_order: 5,
        linked_changelog_id: null,
        completed_at: "2025-03-14T16:00:00Z",
        notes: null,
      },
    ],
    expected_outcomes: [
      {
        id: "b5-eo-1",
        description: "Local pack visibility rank improves to top 3",
        metric_type: "visibility_rank",
        platform: "google_aio",
        target_value: 3,
        baseline_value: 8,
        timeframe: "2 weeks",
        verdict: "hit",
        actual_value: 2,
        result_id: null,
        judged_at: "2025-03-28T08:00:00Z",
      },
    ],
    linked_changelog_ids: ["cl-4"],
    related_brief_ids: [],
    prior_brief_id: null,
    blocked_reason: null,
    due_date: "2025-03-15",
    approved_at: "2025-03-02T08:00:00Z",
    started_at: "2025-03-03T09:00:00Z",
    blocked_at: null,
    completed_at: "2025-03-14T17:00:00Z",
    impact_window_ends_at: "2025-03-28T00:00:00Z",
    retrospective: {
      summary:
        "GBP optimization completed ahead of schedule. All target cities now have comprehensive service area coverage.",
      what_worked:
        "Batch-uploading geo-tagged photos significantly improved engagement signals within days.",
      what_didnt:
        "Weekly GBP posts had minimal impact on rankings — organic engagement was low.",
      actual_effort: "small",
      would_repeat: true,
      follow_up_brief_id: null,
    },
    created_at: "2025-03-01T08:00:00Z",
    updated_at: "2025-03-14T17:00:00Z",
  },
];

export const changelogEntries: ChangelogEntry[] = [
  {
    id: "cl-1",
    timestamp: "2025-03-22T14:30:00Z",
    signal_type: "faq",
    asset_type: "service_page",
    url: "/services/kitchen-remodel",
    asset_name: "Kitchen Remodel Service Page",
    change_description:
      "Added FAQPage JSON-LD with 6 questions targeting high-intent kitchen remodel queries. Questions sourced from ChatGPT and Perplexity top prompts.",
    topic_targeted: "Kitchen Remodel",
    city_targeted: null,
    hypothesis:
      "FAQ schema will trigger Google AIO featured results within 3-5 days and improve AI search citation likelihood.",
    expected_impact_window: "3-5 Days",
    brief_id: "brief-2",
    opportunity_id: "opp-2",
    notes: null,
    created_at: "2025-03-22T14:30:00Z",
    updated_at: "2025-03-22T14:30:00Z",
  },
  {
    id: "cl-2",
    timestamp: "2025-03-21T10:00:00Z",
    signal_type: "page",
    asset_type: "city_page",
    url: "/locations/palo-alto",
    asset_name: "Palo Alto City Page",
    change_description:
      "Rebuilt page with entity-first structure. Added LocalBusiness schema, 8 FAQs, project gallery with ImageObject markup, and 3 testimonials with Review schema.",
    topic_targeted: "Custom Home Building",
    city_targeted: "Palo Alto",
    hypothesis:
      "Entity-rich page structure will trigger ChatGPT citation within 2 weeks as crawl indexes new structured content.",
    expected_impact_window: "1-2 Weeks",
    brief_id: "brief-1",
    opportunity_id: "opp-1",
    notes: "Major rebuild — 2,400 words of new content",
    created_at: "2025-03-21T10:00:00Z",
    updated_at: "2025-03-21T10:00:00Z",
  },
  {
    id: "cl-3",
    timestamp: "2025-03-20T16:00:00Z",
    signal_type: "technical",
    asset_type: "service_page",
    url: "/services/whole-house-remodel",
    asset_name: "Whole House Remodel Service Page",
    change_description:
      "Implemented Service schema and FAQPage JSON-LD. Fixed missing meta description. Added internal links to 4 city pages.",
    topic_targeted: "Whole House Remodel",
    city_targeted: null,
    hypothesis:
      "Structured data coverage will improve organic position from #12 to top 5 within 1-2 weeks.",
    expected_impact_window: "1-2 Weeks",
    brief_id: "brief-2",
    opportunity_id: "opp-5",
    notes: null,
    created_at: "2025-03-20T16:00:00Z",
    updated_at: "2025-03-20T16:00:00Z",
  },
  {
    id: "cl-4",
    timestamp: "2025-03-14T12:00:00Z",
    signal_type: "citation",
    asset_type: "directory_profile",
    url: null,
    asset_name: "Google Business Profile",
    change_description:
      "Updated GBP with 12 new service areas, 8 service descriptions, 20 geo-tagged project photos, and seeded Q&A with 15 top queries.",
    topic_targeted: "Local SEO",
    city_targeted: null,
    hypothesis:
      "Comprehensive GBP optimization will strengthen local entity signals and improve AI search trust factors.",
    expected_impact_window: "1-2 Weeks",
    brief_id: "brief-5",
    opportunity_id: null,
    notes: "Part of broader local SEO campaign",
    created_at: "2025-03-14T12:00:00Z",
    updated_at: "2025-03-14T12:00:00Z",
  },
  {
    id: "cl-5",
    timestamp: "2025-03-12T09:00:00Z",
    signal_type: "off_page_seo",
    asset_type: "directory_profile",
    url: null,
    asset_name: "Directory Submissions Batch 1",
    change_description:
      "Submitted optimized profiles to Houzz, Yelp, and Angi. Consistent NAP, updated descriptions with AI-search-optimized language, and 10 project photos per platform.",
    topic_targeted: "Citation Building",
    city_targeted: null,
    hypothesis:
      "Directory citations will improve Perplexity and ChatGPT citation rates within 4-6 weeks as these sources are indexed.",
    expected_impact_window: "4-6 Weeks",
    brief_id: "brief-4",
    opportunity_id: "opp-3",
    notes: null,
    created_at: "2025-03-12T09:00:00Z",
    updated_at: "2025-03-12T09:00:00Z",
  },
  {
    id: "cl-6",
    timestamp: "2025-03-25T11:00:00Z",
    signal_type: "content",
    asset_type: "homepage",
    url: "/",
    asset_name: "Homepage",
    change_description:
      "Rewrote hero section with entity-first copy. Added service area map component. Implemented Organization schema with sameAs links to all directory profiles.",
    topic_targeted: "Brand Authority",
    city_targeted: null,
    hypothesis:
      "Organization schema and entity-rich copy will strengthen brand entity recognition in AI search models.",
    expected_impact_window: "2-4 Weeks",
    brief_id: null,
    opportunity_id: null,
    notes: null,
    created_at: "2025-03-25T11:00:00Z",
    updated_at: "2025-03-25T11:00:00Z",
  },
  {
    id: "cl-7",
    timestamp: "2025-03-23T15:00:00Z",
    signal_type: "service_page",
    asset_type: "service_page",
    url: "/services/home-additions",
    asset_name: "Home Additions Service Page",
    change_description:
      "Added 1,800 words of new content covering ADU additions, second-story additions, and room additions. Included cost calculator widget and 5 project case studies.",
    topic_targeted: "Home Additions",
    city_targeted: null,
    hypothesis:
      "Comprehensive content depth will improve topical authority signals for AI search models.",
    expected_impact_window: "1-2 Weeks",
    brief_id: null,
    opportunity_id: "opp-6",
    notes: null,
    created_at: "2025-03-23T15:00:00Z",
    updated_at: "2025-03-23T15:00:00Z",
  },
];

export const results: Result[] = [
  {
    id: "res-1",
    snapshot_date: "2025-03-25",
    platform: "chatgpt",
    metric_type: "citation_share",
    metric_value: 18.5,
    previous_value: 12.0,
    delta: 6.5,
    delta_percentage: 54.2,
    topic: "Custom Home Building",
    city: "Palo Alto",
    url_measured: null,
    attributed_changelog_ids: ["cl-2"],
    notes: "First citation appearance after page rebuild",
    created_at: "2025-03-25T08:00:00Z",
  },
  {
    id: "res-2",
    snapshot_date: "2025-03-25",
    platform: "google_aio",
    metric_type: "visibility_rank",
    metric_value: 3,
    previous_value: 8,
    delta: -5,
    delta_percentage: -62.5,
    topic: "Kitchen Remodel",
    city: null,
    url_measured: "/services/kitchen-remodel",
    attributed_changelog_ids: ["cl-1"],
    notes: "FAQ schema triggered AIO featured result",
    created_at: "2025-03-25T08:00:00Z",
  },
  {
    id: "res-3",
    snapshot_date: "2025-03-25",
    platform: "perplexity",
    metric_type: "mention_count",
    metric_value: 4,
    previous_value: 1,
    delta: 3,
    delta_percentage: 300,
    topic: "Home Additions",
    city: "Palo Alto",
    url_measured: null,
    attributed_changelog_ids: ["cl-5", "cl-7"],
    notes: "Directory submissions starting to index",
    created_at: "2025-03-25T08:00:00Z",
  },
  {
    id: "res-4",
    snapshot_date: "2025-03-25",
    platform: "google_aio",
    metric_type: "average_position",
    metric_value: 4.2,
    previous_value: 7.8,
    delta: -3.6,
    delta_percentage: -46.2,
    topic: "Whole House Remodel",
    city: null,
    url_measured: "/services/whole-house-remodel",
    attributed_changelog_ids: ["cl-3"],
    notes: null,
    created_at: "2025-03-25T08:00:00Z",
  },
  {
    id: "res-5",
    snapshot_date: "2025-03-18",
    platform: "chatgpt",
    metric_type: "citation_share",
    metric_value: 12.0,
    previous_value: 8.0,
    delta: 4.0,
    delta_percentage: 50.0,
    topic: "Custom Home Building",
    city: "Palo Alto",
    url_measured: null,
    attributed_changelog_ids: [],
    notes: "Baseline measurement before page rebuild",
    created_at: "2025-03-18T08:00:00Z",
  },
  {
    id: "res-6",
    snapshot_date: "2025-03-25",
    platform: "all",
    metric_type: "ai_referrals",
    metric_value: 34,
    previous_value: 21,
    delta: 13,
    delta_percentage: 61.9,
    topic: null,
    city: null,
    url_measured: null,
    attributed_changelog_ids: [],
    notes: "Total AI referral traffic across all platforms",
    created_at: "2025-03-25T08:00:00Z",
  },
];

export const competitors: Competitor[] = [
  {
    id: "comp-1",
    name: "De Mattei Construction",
    domain: "demattei.com",
    description:
      "General contractor specializing in custom homes and remodels in the South Bay. Strong AIO presence for San Jose and Cupertino queries.",
    is_active: true,
    notes: "Primary competitor — dominant in AI search for South Bay",
    created_at: "2025-03-01T08:00:00Z",
    updated_at: "2025-03-25T08:00:00Z",
  },
  {
    id: "comp-2",
    name: "Flegel's Construction",
    domain: "flegels.com",
    description:
      "High-end design-build firm in Palo Alto. Frequently cited by ChatGPT for luxury remodel queries.",
    is_active: true,
    notes: null,
    created_at: "2025-03-01T08:00:00Z",
    updated_at: "2025-03-20T08:00:00Z",
  },
  {
    id: "comp-3",
    name: "Harrell Remodeling",
    domain: "harrellremodeling.com",
    description:
      "Design-build remodeling company. Strong blog content indexed by Perplexity. Authority on kitchen and bathroom remodel topics.",
    is_active: true,
    notes: "Content strategy is worth studying",
    created_at: "2025-03-01T08:00:00Z",
    updated_at: "2025-03-18T08:00:00Z",
  },
  {
    id: "comp-4",
    name: "Palo Alto Builders",
    domain: "paloaltobuilders.com",
    description:
      "Local builder with strong city page coverage across Peninsula cities. Ranks well for Los Altos and Mountain View queries.",
    is_active: true,
    notes: null,
    created_at: "2025-03-01T08:00:00Z",
    updated_at: "2025-03-15T08:00:00Z",
  },
  {
    id: "comp-5",
    name: "Silicon Valley Custom Homes",
    domain: "svcustomhomes.com",
    description:
      "Custom home builder with dedicated pages for every South Bay city. Strong FAQ coverage on build-on-your-lot topics.",
    is_active: true,
    notes: "Best FAQ implementation among competitors",
    created_at: "2025-03-05T08:00:00Z",
    updated_at: "2025-03-22T08:00:00Z",
  },
];

export const competitorSnapshots: CompetitorSnapshot[] = [
  {
    id: "snap-1",
    competitor_id: "comp-1",
    snapshot_date: "2025-03-25",
    platform: "chatgpt",
    visibility_rank: 2,
    citation_share: 32.5,
    mention_count: 12,
    share_of_voice: 28.0,
    top_cited_urls: [
      "demattei.com/custom-homes",
      "demattei.com/adu-construction",
    ],
    topics_present: [
      "Custom Home Building",
      "ADU Construction",
      "Kitchen Remodel",
    ],
    created_at: "2025-03-25T08:00:00Z",
  },
  {
    id: "snap-2",
    competitor_id: "comp-2",
    snapshot_date: "2025-03-25",
    platform: "chatgpt",
    visibility_rank: 1,
    citation_share: 38.0,
    mention_count: 15,
    share_of_voice: 34.0,
    top_cited_urls: [
      "flegels.com/luxury-remodel",
      "flegels.com/palo-alto-builder",
    ],
    topics_present: [
      "Luxury Remodel",
      "Custom Home Building",
      "Home Additions",
    ],
    created_at: "2025-03-25T08:00:00Z",
  },
  {
    id: "snap-3",
    competitor_id: "comp-3",
    snapshot_date: "2025-03-25",
    platform: "perplexity",
    visibility_rank: 1,
    citation_share: 42.0,
    mention_count: 18,
    share_of_voice: 38.5,
    top_cited_urls: [
      "harrellremodeling.com/blog/kitchen-remodel-guide",
      "harrellremodeling.com/services/bath-remodel",
    ],
    topics_present: ["Kitchen Remodel", "Bathroom Remodel", "Home Additions"],
    created_at: "2025-03-25T08:00:00Z",
  },
  {
    id: "snap-4",
    competitor_id: "comp-4",
    snapshot_date: "2025-03-25",
    platform: "google_aio",
    visibility_rank: 3,
    citation_share: 22.0,
    mention_count: 8,
    share_of_voice: 18.5,
    top_cited_urls: [
      "paloaltobuilders.com/los-altos",
      "paloaltobuilders.com/mountain-view",
    ],
    topics_present: ["Local Coverage", "Custom Home Building"],
    created_at: "2025-03-25T08:00:00Z",
  },
  {
    id: "snap-5",
    competitor_id: "comp-5",
    snapshot_date: "2025-03-25",
    platform: "google_aio",
    visibility_rank: 2,
    citation_share: 28.5,
    mention_count: 10,
    share_of_voice: 24.0,
    top_cited_urls: [
      "svcustomhomes.com/build-on-your-lot",
      "svcustomhomes.com/cupertino",
    ],
    topics_present: [
      "Build on Your Lot",
      "Custom Home Building",
      "ADU Construction",
    ],
    created_at: "2025-03-25T08:00:00Z",
  },
];

export const coverageItems: CoverageItem[] = [
  {
    id: "cov-1",
    category: "schema",
    item_name: "FAQPage JSON-LD on service pages",
    description:
      "All /services/* pages should have FAQPage schema with relevant questions sourced from AI search queries.",
    url: "/services/*",
    status: "partial",
    priority: "critical",
    last_checked: "2025-03-22T10:00:00Z",
    notes: "3 of 8 service pages done",
    linked_brief_id: "brief-2",
    created_at: "2025-03-10T08:00:00Z",
    updated_at: "2025-03-22T10:00:00Z",
  },
  {
    id: "cov-2",
    category: "schema",
    item_name: "LocalBusiness schema on homepage",
    description:
      "Homepage should have complete LocalBusiness schema with address, service area, and sameAs links.",
    url: "/",
    status: "complete",
    priority: "high",
    last_checked: "2025-03-25T08:00:00Z",
    notes: null,
    linked_brief_id: null,
    created_at: "2025-03-10T08:00:00Z",
    updated_at: "2025-03-25T08:00:00Z",
  },
  {
    id: "cov-3",
    category: "content",
    item_name: "City page for Los Altos",
    description:
      "Dedicated city page with local content, project gallery, and testimonials for Los Altos service area.",
    url: "/locations/los-altos",
    status: "missing",
    priority: "critical",
    last_checked: null,
    notes: "No page exists — zero coverage for Los Altos queries",
    linked_brief_id: null,
    created_at: "2025-03-10T08:00:00Z",
    updated_at: "2025-03-10T08:00:00Z",
  },
  {
    id: "cov-4",
    category: "listing",
    item_name: "GBP listing optimization",
    description:
      "Google Business Profile should have complete service list, Q&A, posts, and photo coverage.",
    url: null,
    status: "complete",
    priority: "high",
    last_checked: "2025-03-14T17:00:00Z",
    notes: "Completed as part of GBP brief",
    linked_brief_id: "brief-5",
    created_at: "2025-03-01T08:00:00Z",
    updated_at: "2025-03-14T17:00:00Z",
  },
  {
    id: "cov-5",
    category: "technical",
    item_name: "Sitemap includes all city and service pages",
    description:
      "XML sitemap should list all city pages, service pages, and project pages with correct lastmod dates.",
    url: "/sitemap.xml",
    status: "needs_update",
    priority: "medium",
    last_checked: "2025-03-20T08:00:00Z",
    notes: "Missing 3 recently created pages",
    linked_brief_id: null,
    created_at: "2025-03-10T08:00:00Z",
    updated_at: "2025-03-20T08:00:00Z",
  },
  {
    id: "cov-6",
    category: "entity",
    item_name: "Organization schema with sameAs",
    description:
      "Organization schema should include sameAs links to all directory profiles, social accounts, and Wikipedia (if available).",
    url: "/",
    status: "complete",
    priority: "medium",
    last_checked: "2025-03-25T08:00:00Z",
    notes: null,
    linked_brief_id: null,
    created_at: "2025-03-10T08:00:00Z",
    updated_at: "2025-03-25T08:00:00Z",
  },
  {
    id: "cov-7",
    category: "content",
    item_name: "ADU construction page",
    description:
      "Dedicated page for ADU construction services with cost info, permit guidance, and design options.",
    url: "/services/adu-construction",
    status: "missing",
    priority: "medium",
    last_checked: null,
    notes: "Brief drafted — awaiting approval",
    linked_brief_id: "brief-3",
    created_at: "2025-03-20T08:00:00Z",
    updated_at: "2025-03-20T08:00:00Z",
  },
  {
    id: "cov-8",
    category: "listing",
    item_name: "Houzz profile optimization",
    description:
      "Houzz profile should have complete portfolio, reviews, and service descriptions matching website copy.",
    url: null,
    status: "partial",
    priority: "medium",
    last_checked: "2025-03-12T08:00:00Z",
    notes: "Profile submitted, pending photo uploads",
    linked_brief_id: "brief-4",
    created_at: "2025-03-12T08:00:00Z",
    updated_at: "2025-03-12T08:00:00Z",
  },
  {
    id: "cov-9",
    category: "review",
    item_name: "Review schema on testimonial pages",
    description:
      "All pages with customer testimonials should have AggregateRating and individual Review schema.",
    url: null,
    status: "partial",
    priority: "high",
    last_checked: "2025-03-22T08:00:00Z",
    notes: "Implemented on Palo Alto page, pending on others",
    linked_brief_id: null,
    created_at: "2025-03-10T08:00:00Z",
    updated_at: "2025-03-22T08:00:00Z",
  },
];

export const weeklySummaries: WeeklySummary[] = [
  {
    id: "week-1",
    week_start: "2025-03-24",
    week_end: "2025-03-30",
    title: "Week of March 24, 2025",
    status: "draft",
    highlights:
      "ChatGPT citation share for Palo Alto queries up 54%. Google AIO visibility rank for kitchen remodel jumped from #8 to #3 after FAQ schema deployment. Perplexity mentions tripled for home addition queries.",
    lowlights:
      "Still no coverage for Los Altos — city page blocked on content creation. ADU page brief still in draft. Competitor De Mattei launched new landing page for San Jose ADU queries.",
    changes_count: 3,
    key_metric_deltas: {
      citation_share: 6.5,
      visibility_rank: -5,
      mention_count: 3,
      ai_referrals: 13,
    },
    top_opportunities: ["opp-1", "opp-2", "opp-6"],
    recommendations:
      "Prioritize Los Altos city page creation this week. Approve ADU brief and begin content production. Monitor ChatGPT citation stability for Palo Alto.",
    created_at: "2025-03-28T10:00:00Z",
    updated_at: "2025-03-28T10:00:00Z",
  },
  {
    id: "week-2",
    week_start: "2025-03-17",
    week_end: "2025-03-23",
    title: "Week of March 17, 2025",
    status: "published",
    highlights:
      "Palo Alto city page rebuilt with full schema coverage. FAQ schema added to kitchen remodel and whole house remodel pages. Homepage Organization schema implemented.",
    lowlights:
      "Perplexity still favors Harrell Remodeling for kitchen queries despite content improvements. Directory submissions not yet indexed.",
    changes_count: 4,
    key_metric_deltas: {
      citation_share: 4.0,
      average_position: -3.6,
    },
    top_opportunities: ["opp-1", "opp-5"],
    recommendations:
      "Continue FAQ schema rollout to remaining service pages. Begin citation campaign outreach. Monitor directory submission indexing.",
    created_at: "2025-03-23T10:00:00Z",
    updated_at: "2025-03-23T16:00:00Z",
  },
  {
    id: "week-3",
    week_start: "2025-03-10",
    week_end: "2025-03-16",
    title: "Week of March 10, 2025",
    status: "published",
    highlights:
      "GBP optimization completed — all service areas, Q&A, and photos updated. Directory submissions sent to Houzz, Yelp, and Angi. Baseline measurements established across all platforms.",
    lowlights:
      "ChatGPT citation share still low at 8% for core queries. Need content depth improvements before expecting AI search traction.",
    changes_count: 2,
    key_metric_deltas: {
      citation_share: 0,
      form_submissions: 3,
    },
    top_opportunities: ["opp-3"],
    recommendations:
      "Begin Palo Alto page rebuild. Draft FAQ content for all service pages. Establish weekly monitoring cadence.",
    created_at: "2025-03-16T10:00:00Z",
    updated_at: "2025-03-16T14:00:00Z",
  },
];

