import type { ChangeProposal } from "./contracts"; import { COPY_RULES } from "./copy-sanitize";
import { topicTokens } from "@/domains/evidence/relevance-gate";

const QUALIFIER = /\b(international(?:ly)?|excluding|from|up to|per|depending)\b/i;
const CARRIER = new Set(["include", "includes", "including", "cover", "covers", "carry", "carries", "list", "lists", "mean", "means", "meaning", "also", "such", "offer", "offers", "use", "uses", "used", "refer", "refers", "state", "states",
  "they", "them", "these", "those", "that", "this", "people", "person", "has", "have", "had", // THE REST OF THE CLOSED GRAMMAR (2026-08-22): pronouns, light verbs and quantifiers that any faithful paraphrase must use and no page's stored copy reliably prints. Live passes refused finished copy over "they", "has", "like" and "people", which is the vocabulary test this gate's own charter forbids. Every content noun, name and meaning still has to be carried by a claim and the passage it cites.
  "can", "could", "will", "would", "often", "among", "same", "like", "both", "each", "every", "other", "more", "most"]);

function figures(copy: string, bodyText: string): string[] {
  const out: string[] = [];
  const figure = (t: string): string => t.replace(/[\u2013\u2014]/g, "-").replace(/\s*-\s*/g, "-").replace(/\s+/g, " "); // A FIGURE CARRIES ITS SUBJECT OR IT IS A DIFFERENT FACT: every digit run is traced back to the stored sentence it came out of, and a qualifier that sentence carries and the copy drops changes what the number is ABOUT. DASHES ARE NOT IDENTITY. The house rule rewrites an en dash, so copy saying "7-21" never matched a body saying "7\u201321" and the whole check silently skipped the one sentence that would have refused it: the shipping line went out claiming 7-21 days off a sentence reading "International ... depending on location".
  const ranges = (t: string): string => t.replace(/\bfrom\s+(?=\d[\d,.]*\s*[-–—]\s*\d)/gi, "").replace(/(?:\bfrom\s+)?(\d[\d,.]*)\s*([A-Za-z]{1,4})?\s+to\s+(\d[\d,.]*)\s*([A-Za-z]{1,4})?/gi, // A "FROM" THAT OPENS A SPAN IS PART OF THE SPAN, WHICHEVER WAY THE SPAN IS SPELLED (live row, 2026-09-04). The fold below already strips it from "from 550 to 330 BCE"; /iran-flags/achaemenid-empire-flag writes the span with a dash, so the page's own "representing Persian power from 550-330 BCE" kept its "from", and the finished description "Achaemenid Empire Flag (550-330 BCE) with a red background and a golden Faravahar" was refused for dropping a word that narrows nothing. Two spellings of one fact are one fact. A RANGE SPELLED OUT IS THE SAME FACT AS A RANGE WITH A DASH IN IT: "from 550 to 330 BCE" narrows nothing, and reading its "from" as a qualifier refused every line naming the years its own page is about. Normalized to the form the copy would write, BEFORE the sentence is asked what it qualifies. ONE RANGE, HOWEVER IT IS SPELLED, AND UNITS COUNT (Codex, 2026-08-23): "from 550 BCE to 330 BCE" and "550-330 BCE" are the same fact, and reading the "from" as a dropped qualifier cost /iran-flags/achaemenid-empire-flag five calls and $0.026846 for a line naming the years its own page is about. Endpoints carrying the SAME unit fold together; genuinely different units (5 km to 3 miles) stay two facts, and every other qualifier is still enforced below.
    (m, a: string, ua: string | undefined, b: string, ub: string | undefined) => (!ua || !ub || ua.toLowerCase() === ub.toLowerCase()) ? `${a}-${b}${ub ? ` ${ub}` : ua ? ` ${ua}` : ""}` : m);
  const said = ranges(bodyText).split(/(?<=[.!?])\s+|\n+/).map((t) => figure(t).trim()).filter(Boolean);
  for (const line0 of ranges(copy).split(/(?<=[.!?])\s+|\n+/)) { const line = figure(line0), about = new Set(topicTokens(line)); /* THE FIGURE'S OWN ASSERTION IS WHAT IS JUDGED, so the number is matched on ITS OWN BOUNDARIES and the stored sentence is the one this copy's sentence is ABOUT (audit, 2026-09-04): `includes(n)` read a digit run as a substring, so "3" bound to a sentence about 1335 and "25" to a sentence about 250, and the qualifier of an unrelated fact was then demanded of a faithful figure. Ties keep document order, which is exactly what the first-match rule did. */
    for (const n of new Set(line.match(/\d[\d,.-]*\d|\d+/g) ?? [])) { const its = new RegExp(`(?<![\\d,.-])${n.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")}(?![\\d,.-])`); const q = QUALIFIER.exec(said.filter((s) => its.test(s)).sort((a, b) => topicTokens(b).filter((w) => about.has(w)).length - topicTokens(a).filter((w) => about.has(w)).length)[0] ?? ""); if (q && !new RegExp(`\\b${q[1]!.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")}\\b`, "i").test(line)) { out.push(`the figure's own sentence says ${q[1]!.toLowerCase()}, and the copy drops it`); break; } } } // A PAGE'S OWN WORDS ARE NOT A LIST OF THE SEARCHES THAT REACH IT. Live and Ready on the account: "Persian girl names here match persian girl names, persian names for girls, persian names girl, persian girls names, persian girl name, and unique persian girl names. People also search persian female names and female persian names." Six of those are ONE phrase reordered, and the line after it prints the name of a results-page feature. Nobody writes that, no reader gains a word from it, and it is the exact shape a search engine penalises: pasting it onto a live page costs the operator the ranking the card was bought to win. THE TEST IS PERMUTATION, not similarity: three members that reduce to the same set of content words are the same search said three ways, and a real list never does that.
  return [...new Set(out)];
}

const COPY_REFUSALS = { figures, carrier: CARRIER }; /* `owns` and `live` deleted (Stage 3, 2026-09-14): nothing read them */

const hasGrouping = (sources: readonly { says: string; groups?: readonly string[]; groupExcerpts?: readonly { heading: string }[] }[]): string[] => [...new Set(sources.flatMap((s) => (s.groups ?? []).filter((g) => g.trim() && (s.says.includes(g) || (s.groupExcerpts ?? []).some((e) => e.heading === g)))))]; // a group the source keeps as a heading of its own is carried by the words under that heading, which the quote cannot hold beside the others
const holds = {"lead": "The opening needs a complete answer paragraph that explains more than the names.", "groups": "Group the answer under one to three headings that explain how the examples were selected.", "criteria": "Each heading needs a selection criterion and explanatory prose, with children written as plain text rather than tables, bold labels or link lists.", "entities": "Entity distinctions should read as plain text under one to three groups; table scaffolds and label styling are optional at most.", "accuracy": "The accuracy questions need to be resolved before this copy is ready.", "unreviewed": "These exact words still need a review of their structure, accuracy and relevance.", "sixChecks": "The answer still needs to pass the required readiness checks for lead quality, grouped sections, factual support and query fit."};
const writerLimitations = (limitations: readonly string[]) => limitations.filter((l) => !Object.values(holds).includes(l.trim()));
const emptyMeta = (copy: string, heading: string): string[] => {
  const tokens = (t: string) => t.toLowerCase().match(/[\p{L}\p{N}]+/gu) ?? [];
  const known = new Set(tokens(`${heading} a an the is are about and of for with description details information`));
  return !copy.trim() || /\b(?:no (?:added |useful |additional )?description|description (?:not available|unavailable|missing)|nothing to describe)\b/i.test(copy)
    || (known.size > 0 && tokens(copy).every((w) => known.has(w))) ? [`${COPY_RULES.refusal.emptyMeta} without describing the subject.`] : [];
};
/* THE PACKET REGIME IS DELETED (audit, 2026-09-14): its rubric, policy, holds and grouping debt were pinned off on 2026-09-10 and shipped dead. What remains is what stored rows and live doors still read: the hold sentences stored rows carry as limitations, the grouping question the runtime still names, and the meta and figure rules. */
export const AEO_BAR = { copyRefusals: COPY_REFUSALS, groupingQuestion: "Which groups of this page’s subject does the source distinguish, and what qualifies for each?", hasGrouping, emptyMeta, holds, writerLimitations,
  sameRejectedCopy: (a: ChangeProposal, b: ChangeProposal): boolean => {
    if (a.researchOnly === true || b.researchOnly === true) return false;
    const key = (s: string) => s.normalize("NFKC").toLowerCase().replace(/[^\p{L}\p{N}]+/gu, " ").trim();
    const identity = (p: ChangeProposal) => { const c = p.recommendedChange;
      return JSON.stringify([c.kind, c.kind === "existing_edit" ? [c.field.replace(/^(section|answer_block)$/, "body"), key(c.after), c.linkTo ?? ""] : [key(c.openingAnswer), p.newPageDraft],
        (p.bundle?.components ?? []).map((x) => [x.kind, x.page ?? "", key(x.after ?? "")])]); };
    return identity(a) === identity(b);
  },
};
