import { AEO_BAR } from "./accept-worthy";
import { COPY_RULES } from "./copy-sanitize";
/** decision/completeness: THE ONE CHECK THAT ASKS WHETHER BEACON HAS FINISHED THE WORK. A customer-facing Change states exactly what to add, replace, delete, move, link, redirect or create, exactly where, and the FINAL COPY wherever copy is involved. IMPERFECT WORK STAYS VISIBLE (operator, 2026-08-15): anything short of that is a genuine opportunity still being developed, and it is RANKED and SHOWN, on the ranked queue and on Today, as a research card carrying what is known, what is still missing and what happens next. What this boundary decides is never whether the operator sees a row, only which of the three lanes it lands in, that it carries no copy to paste and no control that records it done, and that the server refuses to put it into measurement or mark it implemented until the deliverable is actually finished. PURE and derived from the deliverable ITSELF, never from the prose around it, so the queue, the card (a client component) and the server mutation all ask one question and a voice edit moves none of them. It sits beside the contract rather than inside the validator because a client bundle may reach this and may not reach that. */

import { componentIdOf, dangerousComponents } from "./contracts"; import { footprintCovers } from "./mutation-footprint"; import { fieldForComponent } from "./producers/contract";
import { copyKey, evidenceShortfall, REVIEW_CONTRACT, reviewFits, unreviewed } from "./proof";
import { domainOf, topicTokens } from "@/domains/evidence/relevance-gate";
import type { ChangeProposal } from "./contracts";
import { withholdReason } from "./authorization";

/** NO VERB LIST LIVES HERE ANY MORE. Whether copy is the finished words or a note about producing them is a question about meaning, and it was answered by spelling: a production verb near a deliverable noun. It is now answered where it is known. A PRODUCER handing over a brief says so in a typed field (`researchOnly`) as it mints the card. THE EDITOR's copy is read by decision/drafted-copy's editor contract, against the stored page and then by a judge. Only what stays deterministic for any writer is left below. */
/** A blank somebody is expected to fill in before the copy is usable, or MARKUP WHERE A WORD BELONGS: a title reading "Colors &amp; History" is not final copy, because what an operator pastes is not what a reader sees. */
const BLANK_TO_FILL = /\[[^\]]*\]|_{3,}|\b(?:NUMBER|YEAR|SOURCE|TBD|XXX+)\b|&(?:[a-zA-Z]+|#\d+|#x[0-9a-fA-F]+);/;
/** Copy that says out loud that the work has not been done. */
const OWED_NOTE = /^The exact .* lands on the next pass/; /* the drafter's "lands on the next pass" note: display, never identity, never a hold */
const SAYS_UNFINISHED = /\b(?:not been (?:drafted|read|written)|is not settled|not on this card|still owed|nothing here is|in your own words|write (?:this|it|these|them) yourself|fill (?:this|it|these) in)\b/i; /* AND AN INSTRUCTION TO WRITE IT YOURSELF (owner's editorial policy, 2026-09-06): copy that tells the operator to write the words is not the words. */

const noCopy = (t: string | null | undefined): boolean => !t || t.trim().length === 0;
/** Copy carrying a blank, or saying out loud that it is not written, is unfinished whoever wrote it. */
const notFinal = (t: string): boolean => BLANK_TO_FILL.test(t) || SAYS_UNFINISHED.test(t);

/** WHY THIS IS NOT YET A CHANGE, in plain phrases, or empty when the deliverable is complete BY ITS TYPE. A title, description or heading owes its exact final replacement. An opening or a section owes final copy AND the place it lands, which only a bundle component's `where` carries. A new page owes a publish-ready page and is NEVER title-only, so every section it names owes written copy. */

export function labelOf(s: string): { label: string; gap: string; latin: boolean } | null {
  const m = /^([\p{L}][\p{L} ]{0,22}):([^\S\n]*)(?=[^\s/])/u.exec(s);
  return m ? { label: m[1]!, gap: m[2]!, latin: /^[A-Za-z][A-Za-z ]*$/.test(m[1]!) } : null;
}
/** A LINE THAT WOULD PASTE ONTO THE PAGE AS ONE GLUED PHRASE ("Meaning:Light."). */
const glued = (t: string): boolean => { const lv = labelOf(t); return !!lv && lv.latin && lv.gap === ""; };

export function deliverableGaps(p: ChangeProposal): string[] {
  const gaps: string[] = [];
  const rewrite = COPY_RULES.pieceDebt(p); if (rewrite === null) gaps.push("the banked rewrite has an invalid plan or piece record"); else if (rewrite) gaps.push(`${rewrite} planned rewrite pieces have no copy written`); if (p.researchOnly === true) gaps.push(rewrite !== undefined ? "the rewrite is not yet qualified as complete publishable work" : p.kind === "new_page" && p.newPageDraft?.pieces.length ? "the new page is not yet qualified as complete publishable work" : "nothing has been written for it yet");
  const c = p.recommendedChange;
  if (c.kind === "new_page") {
    for (const [what, text] of [["title", c.proposedTitle], ["description", c.metaDescription], ["opening", c.openingAnswer]] as const) {
      if (noCopy(text)) gaps.push(`it carries no ${what}`);
      else if (notFinal(text)) gaps.push(`its ${what} describes the work instead of being it`);
    }
    if (c.outline.length < 3) gaps.push("it names fewer than three sections");
    const bank = p.newPageDraft, made = bank ? COPY_RULES.newPagePieces(bank) : undefined; if (made === null || bank && Array.isArray(bank.brief.sections) && bank.brief.sections.length !== c.outline.length) gaps.push("the banked new page has an ambiguous plan or piece record");
    const written = new Set((p.bundle?.components ?? []).filter((x) => /^(section|section_add|section_rewrite)$/.test(x.kind) && !noCopy(x.after) && !notFinal(x.after)).map((x) => COPY_RULES.flat(x.label))), owed = c.outline.filter((h, i) => made ? noCopy(made.get(i + 1)?.after) || notFinal(made.get(i + 1)?.after ?? "") : COPY_RULES.flat(h).length > 0 && !written.has(COPY_RULES.flat(h)));
    if (owed.length > 0) gaps.push(`${owed.length} of its ${c.outline.length} sections have no copy written`);
    return [...new Set(gaps)];
  }
  if (c.field === "schema") {
    const json = c.after.replace(/^\s*<script[^>]*>/i, "").replace(/<\/script>\s*$/i, "").trim();
    if (!json) gaps.push("it carries no structured data");
    else try { JSON.parse(json); } catch { gaps.push("its structured data is not valid JSON, so no search engine could read it"); }
    return [...new Set(gaps)];
  }
  if (noCopy(c.after)) gaps.push("it carries no copy");
  else if (notFinal(c.after)) gaps.push("it describes the work instead of being it");
  else if (glued(c.after)) gaps.push("its label runs straight into the words after it, so it would paste as one glued phrase");
  else if (typeof c.before === "string" && c.before.trim() !== "" && COPY_RULES.flat(c.after) === COPY_RULES.flat(c.before)) gaps.push("it changes nothing: the new words are the words the page already carries");
  const placed = (t: string | null | undefined): boolean => !!t && t.trim().length >= 12 && !notFinal(t);
  const parts = p.bundle?.components ?? [];
  if (parts.some((part) => (part.kind === "full_rewrite" || part.target?.mode === "whole_body") && (part.kind !== "full_rewrite" || !part.before?.trim() || !part.units?.length || part.target?.mode !== "whole_body"))) gaps.push("the whole-page replacement lacks its full-rewrite kind, complete original body, publication structure or explicit body scope");
  const said = p.bundle?.dispositions ?? [];
  const written = (pg: string): boolean => parts.some((x) => x.page === pg && !noCopy(x.after) && !notFinal(x.after));
  const owed = [...new Set([...parts.map((x) => x.page), ...said.filter((d) => d.verdict === "differentiate").map((d) => d.page)])]
    .filter((x): x is string => !!x).filter((pg) => !written(pg));
  if (owed.length > 0) gaps.push(`${owed.length} of the pages it changes have no copy written`);
  const unsaid = said.filter((d) => d.verdict !== "differentiate" && d.because.trim().length < 12).map((d) => d.page);
  if (unsaid.length > 0) gaps.push(`${unsaid.length} of the pages it names give no reason for being left alone`);
  if ((c.field === "section" || c.field === "answer_block") && !placed(c.where)
    && !(p.bundle?.components ?? []).some((x) => placed(x.where))) {
    gaps.push("where it goes on the page is not named");
  }
  return [...new Set(gaps)];
}

/** COPY THAT IS STILL AN INSTRUCTION TO WRITE COPY, in the gaps' own words: those rows are a real opportunity with nothing exact written yet. A placement nobody named is NOT here on purpose: the words exist, so the operator reads them. */
const NOT_WRITTEN = /no copy|describes the work instead|nothing has been written|carries no (?:title|description|opening)/i;
/** A STORED CAVEAT WORTH READING AS A FACT ABOUT THE WORK rather than a note beside it, FOR DISPLAY ONLY: which stored sentences print under "why this is held" versus ride along as an FYI. Deliberately the phrasings this kernel actually writes. THIS REGEX NEVER GATES ANYTHING BY ITSELF: a limitation worded to dodge every phrase here still fails on the fact, because unsettledCause, deliverableGaps and the banked-copy grounding recheck run directly on the row inside the store's own promotion (proposal-store's answerReviewedProposal), never by reading what a sentence says about itself. */
const HARD_LIMITATION = /held for review|is still owed|no words from this change|not ready to paste|paste-ready|cited authoritative source|carries no source|add (?:a |an |one |1-2 )?(?:cited |authoritative )?sources?|verify (?:this|the) (?:claim|fact)/i;
/** THE FALLBACK FOR ROWS STORED BEFORE `faults` WAS TYPED, and only those: guessing an owner from the shape of an English sentence means a reworded refusal silently changes whose problem a row is. For DISPLAY and nothing else: these never touch `blocking`, because a sentence about the work must never decide whether the work ships (the gates themselves already did). The lane printed "nothing has read them for sense yet" over the top of "it repeats what stays on the page below it", handing a known failure back as if the reader were the missing ingredient. A SAFETY hold ("this moves or hides a page") is NOT this: that one really is the operator's call. */
export const GATE_WORDS = new RegExp(`^(?:it |its copy carries no record|this rearranges|every claim|the evaluator's exact objection|missing_source|nothing on file|nothing in it beyond|the line |the only words in it|the sentence carrying the link|the route it opens|a claim here is|the evidence it names|where this copy goes|the place it says it lands|${Object.values(COPY_RULES.refusal).map((r) => r.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")).join("|")})`, "i"); /* AND THE DRAFT DOORS' OWN REFUSAL OPENERS, read from the one spelling they are composed from (audit, 2026-09-14: "where it goes is", "the words it puts on the link", "no serious editor would hand this" and eight more sat outside this pattern and rode along as caveats on Ready rows) */ // THE ONE GATE VOCABULARY: the sentences Beacon's own gates write, INCLUDING THE SIX THE SUMMARY-LINE RULES WRITE (live, 2026-09-05: /california-persian-cities/beverly-hills was promoted carrying "the only words in it this page does not share with its template siblings ..." in its limitations, read to a customer as their own caveat, because that opener was outside this pattern so neither the promotion candidate nor the finished door stripped it and it could never be re-earned), and the store's own record sentence with them (probe, 2026-09-05: two rows whose record a reading had rebuilt still carried "its copy carries no record of what it stands on", which no door stripped, so a promotion would have served it as a caveat on finished words). The replay strips them from a candidate, a finished redraft replaces them with its own pass's findings, and legacy rows with no typed faults are read through them.
const MISPLACED = "Where this copy goes can no longer be checked against the words this page has on file, so it is held for a look rather than handed over as ready to paste.";
const UNJUDGED = "The exact words are written and nothing has read them for sense yet, so this one owes your look before it counts as finished.";
/** THE ONE HOLD THAT IS GENUINELY THE OPERATOR'S CALL, named so callers can tell it from a defect Beacon owns: stamping this sentence as a typed fault would flip a safety confirmation into "Beacon must improve this". */
const DANGER = "This one moves or hides a page, so it takes the deliberate confirmation on its own page rather than a plain yes.";
/** THE ONE SENTENCE A LOST RECORD WRITES, shared by the hold below and the preservation branch that keeps such a row's words, so the two can never drift; decision/obligation matches its own copy of the phrase, as it matches `deliverableGaps`'s. */
const NO_RECORD = "its copy carries no record of what it stands on";
const SILENT_SOURCE = /https?:\/\/[^\s"';]+\s+says:?\s+""/g; /** A SOURCE THAT QUOTED NOTHING, in the string this codebase composes for a banked fact itself (`<address> says "<quotation>"`), read only on a row banked before the typed addresses existed. HOW MANY PUBLISHERS STAND BEHIND WHAT THIS COPY CLAIMS, counted by HOST at the ONE place the verdict and the finished card both read, so the number a customer is shown and the number the caveat names can never disagree. TYPED PROVENANCE FIRST (measured, 2026-09-05): the count pulled hostnames out of the banked fact's own prose, so the pre-1979 flag card read "Backed by 2 checked sources" off ONE reading whose bank row says `single_source` and whose first address quoted nothing at all, and 437 of the bank's 1,293 sources carry an empty quotation. A fact banked with its own addresses answers from them; a fact banked before they existed is read from its text with a source that says nothing dropped, which is the same rule applied to the only record that row has. */

type Advisory = { kind: string; say: string; weight: number };
const ADVISORY: readonly (Advisory & { re: RegExp })[] = [
  { kind: "conservative_wording", re: /template siblings|sibling page with the subject swapped in|ranking or register judgement/i,
    say: "Conservative wording: it stays close to what the pages built on the same template already say. Paste it, or sharpen the one line that is yours.", weight: 0.6 },
  { kind: "matches_search", re: /repeats the search instead of improving the page/i,
    say: "The wording matches the search this page is shown for, which reads plainly and wins no points for style. Paste it, or ask for a warmer line.", weight: 0.7 },
  { kind: "repeats_supported", re: /rearranges the page into one more paragraph|what a reader gains|only part of this page|belongs to a different reading|naming no evidence and no reorganized material/i,
    say: "It puts material the page already carries in a better order rather than adding a fact. Paste it if the page reads better for it.", weight: 0.5 },
  { kind: "competitor_pattern", re: /a page that competes with this one|stands on a rival page/i,
    say: "Modeled on the pages that win this search, which is a reason to try it and never proof it caused their result. The 28 day reading says whether it worked.", weight: 0.4 },
  { kind: "benefit_uncertain", re: /demand evidence alone|clicks a wording change has never been shown to recover|no longer clears it, so it stays held/i,
    say: "The gain here is not proven: demand says the page matters, not that these words beat the current ones. The 28 day reading says whether it worked.", weight: 0.4 },
  { kind: "role_uncertain", re: /held: this page's own evidence names|works on something other than .* this page's own evidence names|get no words from this change/i,
    say: "Its exact part in this page's wider problem is not settled, so treat it as one step rather than the whole fix.", weight: 0.4 },
  /* THE STORED SPELLINGS OF THE HOLDS THIS POLICY DELETED ARE READ HERE TOO (journey review, 2026-09-06): a row the old doors demoted wears their sentence in `faults` and `limitations`, and a sentence this table did not know was a defect that owed a paid corrective draft for a condition the owner now judges. */
  { kind: "reading_dated", re: /is offered here as what this page says today|readings behind this change are too old/i,
    say: "The readings behind this carry an older date than today. Check the page still reads that way before you paste.", weight: 0.5 },
];
/** The one partition, asked of one sentence. */
const advisoryOf = (why: string): Advisory | null => { const a = ADVISORY.find((x) => x.re.test(why)); return a ? { kind: a.kind, say: a.say, weight: a.weight } : null; };

export function citedPublishers(p: ChangeProposal): Set<string> { const cited = new Set((p.claims ?? []).flatMap((x) => x.supportedBy.filter((id) => id.startsWith("fact-")))); return new Set((p.supportFacts ?? []).filter((f) => cited.has(f.id)).flatMap((f) => f.sources ? f.sources.map((x) => x.url) : (f.fact.replace(SILENT_SOURCE, " ").match(/https?:\/\/[^\s"';]+/g) ?? [])).map((u) => domainOf(u)).filter(Boolean)); }
/** THE ONE READINESS VERDICT, AND WHO MAY ANSWER EACH HALF OF IT. `defects` are the eight kinds Beacon owes before it hands work over and they are the whole of what holds a row: an incomplete deliverable or a placeholder, an unusable or nonexistent placement, a fabricated citation or one off the receipt, a claim a checked source contradicts, a destructive or safety-flagged edit, an empty no-op, narration that describes the page instead of answering the reader, and a fault in the copy's binding to its version. `advisories` are the ten kinds the operator judges for themselves, each typed with the sentence they read and a weight the ranking can take. IMPERFECT WORK STAYS VISIBLE (operator, 2026-08-15) AND COMPLETE WORK STAYS OFFERED (owner, 2026-09-06): a gate decides which lane an opportunity is shown in and which controls its card carries, never whether the operator sees it, and an editorial judgement decides what the card SAYS, never whether the work is handed over. `lane` is `research` while nothing exact is written and `review` once the exact copy exists; `why` is every defect said back where the work is read; `caveats` is what the person keeps in mind; `blocking` is the first hard defect, the fast read for a card, never the sole gate: the row itself is re-asked at the one door that can write `ready` (proposal-store's answerReviewedProposal). `found` is what a caller who holds the page and the words already read (the banked-copy re-read, the canon, the actionable failures), put through THIS partition so no door keeps a refusal chain of its own. PURE, so the queue, the card, the ladder and the server action ask ONE question and no screen can offer a control the server refuses. */
export function openHold(p: ChangeProposal, also: { found?: readonly string[] } = {}): { lane: "review" | "research"; why: string[]; caveats: string[]; blocking: string | null; faulted: boolean; safetyHold: boolean; defects: string[]; advisories: Advisory[] } {
  const stands = (p.claims ?? []).length > 0 && (p.supportFacts ?? []).length > 0; /* AND A ROW WHOSE RECORD STANDS MAY NOT CARRY THE SENTENCE THAT SAYS IT HAS NONE (measured, 2026-09-05: eighteen current rows wear it, seventeen of them truthfully with no claim and no support fact, and one carries a claim and three support facts and is held for a record it holds). The sentence is written where a brief would have displaced finished words, and only a paid reading retired it, so a row whose own record answers it stayed held for a reason its own payload disproves. Asked of the row, at no cost, on every pass that reads it. */ const lims = p.limitations.filter((l) => !OWED_NOTE.test(l) && !(stands && l === NO_RECORD)); /* THE OWED NOTE IS NEVER A HOLD (reviewer, 2026-09-04): "no action needed from you until it does" read as a hard limitation, minted a redraft whose instruction was the note itself, and the obligation flipped every pass with the note */
  const gaps = deliverableGaps(p), c = p.recommendedChange, faults = (p.faults ?? lims.filter((l) => GATE_WORDS.test(l))).filter((f) => !(stands && f === NO_RECORD));
  const bodyDefects: string[] = [], heading = (p.copyStamp ?? "").split("|").slice(0, 2).join(" ").trim() || p.pageLabel;
  if (c.kind === "existing_edit" && c.field === "meta") {
    bodyDefects.push(...AEO_BAR.emptyMeta(c.after, heading));
  }
  for (const part of p.bundle?.components ?? []) if (part.kind === "meta") bodyDefects.push(...AEO_BAR.emptyMeta(part.after, heading));
  const current = (why: string): boolean => !(COPY_RULES.supersededEditorFinding(why) && unreviewed(p) == null);
  const hard = [...bodyDefects, ...gaps, ...lims.filter((l) => current(l) && HARD_LIMITATION.test(l))];
  for (const part of p.bundle?.components ?? []) if (part.sourcePack && part.sourcePack.resolved !== true) hard.push(`the ${part.label.toLowerCase()} still owes source checking before it can be copied`);
  const publicCopy = c.kind === "new_page" ? [c.openingAnswer, ...p.bundle?.components.filter((part) => /^(opening_answer|section|section_add|section_rewrite)$/.test(part.kind)).map((part) => part.after) ?? []] : c.kind === "existing_edit" && c.field !== "schema" ? [c.after, ...(p.bundle?.components.filter((part) => /^(opening_answer|section|section_add|section_rewrite|meta|title|h1|internal_link)$/.test(part.kind)).map((part) => part.after) ?? [])] : [];
  if (p.researchOnly !== true && publicCopy.some((copy) => COPY_RULES.workflow.test(copy))) hard.push("it narrates Beacon's writing task or the page instead of answering the reader");
  const anchor = c.kind === "existing_edit" && (c.field === "section" || c.field === "answer_block")
    ? /placed after (?:the heading )?"([^"]+)"/.exec(c.where ?? "")?.[1]?.trim().toLowerCase() ?? null : null;
  const placedOn = (t: string): boolean => t.toLowerCase().includes(anchor!.slice(0, 60));
  if (anchor && !(p.supportFacts ?? []).some((f) => placedOn(f.fact)) && !placedOn(p.copyStamp ?? "")) hard.push(MISPLACED);
  const short = evidenceShortfall(p); if (short) hard.push(short);
  const unfit = withholdReason(p, p.causeFinding?.cause ?? p.diagnosisCause); if (unfit) hard.push(unfit);
  if (dangerousComponents(p.bundle?.components ?? []).length > 0 && p.confirmedVersion !== confirmedVersion(p)) hard.push(DANGER);
  const additive = p.researchOnly !== true && c.kind === "existing_edit" && (c.field === "section" || c.field === "answer_block") && c.before == null && p.assignment?.standard !== "correction"; /* SHIP MODE (operator, 2026-09-10): a stored additive section refused for taste keeps its copy and surfaces with the objection as a Keep-in-mind line; safety faults still hold it. */
  const TASTE_FAULT = /^(its heading is the tracked question|it is not useful or does not read naturally|the figure's own sentence says |its "[^"]+" is a ranking or register judgement|it says [^ ]+ more than once each)/;
  const tasteSaid: string[] = [];
  const every0 = [...new Set([...hard, ...faults.filter(current), ...also.found ?? []])];
  const every = additive ? every0.filter((x) => { if (TASTE_FAULT.test(x)) { tasteSaid.push(x); return false; } return true; }) : every0;
  const said = every.filter((x) => !every.some((y) => y !== x && y.endsWith(x))); // ONE COMPLAINT IS SAID ONCE (measured, 2026-09-05): a refusal is composed with a gate opener at one door and written raw at another, both land in `faults`, and the Set kept both because the strings differ, so the account's most watched card told a reader the same thing twice. The composed form ends with the raw sentence it wraps, so the wrapped one is dropped and nothing a fuller sentence does not already say is lost. WHAT A CALLER ALREADY READ COMES IN THE SAME DOOR: the banked-copy re-read and the canon hold the page and the words, this verdict does not, and putting their findings through the ONE partition is what makes the store, the sweep, the loader and the ladder agree by construction instead of each chaining its own refusals.
  const advisories: Advisory[] = [], heldBy: string[] = [];
  for (const x of said) { const a = x === DANGER || c.kind === "new_page" && short != null && (x === short || x.endsWith(short)) ? null : advisoryOf(x); if (!a) { heldBy.push(x); continue; } if (!advisories.some((y) => y.kind === a.kind)) advisories.push(a); }
  if ((p.causeFinding?.cause ?? p.diagnosisCause) === "cannibalization" && /\d[\d,.]*\s*clicks short/i.test(p.whyItMatters ?? "") && !advisories.some((a) => a.kind === "benefit_uncertain")) advisories.push({ kind: "benefit_uncertain", say: "A modeled click gap says what these positions usually earn, never what this wording recovers. The 28 day reading says whether it worked.", weight: 0.4 }); // THE CLICKS PROMISE IS SAID, NOT HELD: this used to hold the row until the ownership work behind it was finished, which hid a finished line for a promise nobody had made on its behalf.
  const cited = new Set((p.claims ?? []).flatMap((x) => x.supportedBy.filter((id) => id.startsWith("fact-")))), publishers = cited.size > 0 ? citedPublishers(p).size : 0; // HOW MANY PUBLISHERS STAND BEHIND WHAT THIS COPY CLAIMS, counted by HOST at the ONE place the card and this verdict both read. It used to be a BAR: two publishers for a replacement or a consensus claim, one otherwise, and short of it the row was held and a reading was bought. One credible source is enough for the operator to judge, so the count is said instead.
  if (cited.size > 0 && publishers < 2 && !advisories.some((a) => a.kind === "single_source")) advisories.push({ kind: "single_source", say: publishers === 1 ? "Backed by 1 checked source. Add a second before publishing if being wrong here would cost you." : "Backed by a reading that names no publisher. Read the source before publishing if being wrong here would cost you.", weight: 0.5 });
  const dated = (p.bundle?.receipt.items ?? []).map((i) => (i.observedAt ?? "").slice(0, 10)).filter(Boolean).sort().at(-1); // THE DATE THE READINGS CARRY, SAID RATHER THAN HELD: a reading older than a freshness window used to take the whole change out of the queue, which is the policy buying nothing and hiding finished work. The card names the day instead.
  if (dated && dated < new Date(Date.parse(p.createdAt) || Date.now()).toISOString().slice(0, 10) && !advisories.some((a) => a.kind === "reading_dated")) advisories.push({ kind: "reading_dated", say: `Backed by readings last taken on ${dated}. Check the page still reads that way before you paste.`, weight: 0.5 });
  const defects = heldBy.filter((x) => x !== DANGER), blocking = hard.find((h) => heldBy.includes(h)) ?? null;
  return { lane: p.researchOnly === true || gaps.some((g) => NOT_WRITTEN.test(g)) ? "research" : "review",
    // Report every hold owner and keep advisories separate from Beacon-owned defects.
    why: heldBy.length > 0 ? heldBy : [UNJUDGED], caveats: [...tasteSaid.map((t) => `A reviewing editor objected: ${t}. Read it once yourself before pasting.`), ...advisories.map((a) => a.say), ...AEO_BAR.writerLimitations(p.limitations).filter((l) => current(l) && !GATE_WORDS.test(l) && !said.includes(l))], blocking, faulted: defects.length > 0, safetyHold: blocking === DANGER, defects, advisories };
}

/** WHY THIS CHANGE MAY NOT BE HANDED OVER AS READY, or null when it may: the first hard defect of the ONE verdict above, which is what every caller of this name already asked it for. It used to be a second refusal chain of its own (a split settled on only some of its pages, a lever that misses the diagnosed cause), and both of those are advisories now, so the name survives as the kernel's one-word reader of the verdict rather than as a second vocabulary beside it. The SAFETY confirmation answers to the operator and is never returned here. */
export const unsettledCause = (p: ChangeProposal): string | null => openHold(p).defects[0] ?? null; // the FIRST DEFECT of the one verdict, typed faults and receipt findings included (journey review, 2026-09-06): `blocking` is drawn from the hard arms alone, so a screen reading it offered an approve press on a row the store then refused for its typed fault


/** Query leadership can rotate within one semantic demand unit without changing its job. */
const slotOf = (f: string): string => (f === "answer_block" || f === "section" ? "body" : f); /** WHICH SLOT A FIELD WRITES, the field half of mutation-footprint's own table: `answer_block` and `section` are two names for ONE body edit and land on the same words. Read as the raw field, a brief minted `answer_block` and the finished section the writer handed back for that very brief were two kinds of change, so every re-mint retired the finished copy with "the kind of change moved" and put the brief back on the row: twice in one live drive (2026-09-03), both receipts still saying produced. */
const workContext = (p: ChangeProposal, bank?: ChangeProposal): unknown[] => [p.copyStamp ?? bank?.copyStamp ?? null, p.factIdentity ?? null, p.changeFamily, p.diagnosisCause ?? bank?.diagnosisCause ?? null, p.pagePath ?? bank?.pagePath ?? null, p.pageUrl ?? bank?.pageUrl ?? null, p.treatment ?? bank?.treatment ?? null, p.assignment ?? bank?.assignment ?? null];
const sameQueryGroup = (a: string | null | undefined, b: string | null | undefined): boolean => topicTokens.sameQuery(a, b) || topicTokens.semanticAtoms(a).length === 0 && topicTokens.semanticAtoms(b).length === 0 && (a ?? "").toLowerCase().replace(/[^a-z0-9]+/g, " ").trim().split(" ").sort().join(" ") === (b ?? "").toLowerCase().replace(/[^a-z0-9]+/g, " ").trim().split(" ").sort().join(" ");
const sameContext = (bank: ChangeProposal, job: ChangeProposal): boolean => sameQueryGroup(bank.primaryQuery, job.primaryQuery) && COPY_RULES.recordKey(workContext({ ...bank, treatment: bank.treatment ?? job.treatment, diagnosisCause: bank.diagnosisCause ?? job.diagnosisCause })) === COPY_RULES.recordKey(workContext(job, bank));
/** Copy, its assignment and its caveats survive only inside the same typed diagnosis snapshot. */
const sameEpoch = (bank: ChangeProposal, job: ChangeProposal): boolean => sameQueryGroup(bank.primaryQuery, job.primaryQuery) && COPY_RULES.recordKey([bank.diagnosisCause ?? null, bank.causeFinding?.cause ?? null, bank.causeFinding?.action ?? null]) === COPY_RULES.recordKey([job.diagnosisCause ?? null, job.causeFinding?.cause ?? null, job.causeFinding?.action ?? null]);
const workScopes = (p: ChangeProposal) => [...(p.recommendedChange.kind === "existing_edit" ? [{ slot: slotOf(p.recommendedChange.field), page: p.pagePath ?? null, before: p.recommendedChange.before, where: p.recommendedChange.where, target: p.recommendedChange.target, destination: p.recommendedChange.linkTo, anchor: p.recommendedChange.anchorText }] : []), ...(p.bundle?.components ?? []).map(c => ({ kind: c.kind, objective: c.objective, mechanism: c.mechanism, sourcePack: c.sourcePack, derivation: c.derivation, slot: c.kind === "schema" ? "schema" : slotOf(fieldForComponent(c.kind)), page: c.page ?? p.pagePath ?? null, before: c.before, where: c.where, target: c.target, destination: c.redirectTo, anchor: c.anchorAfter }))];
/** Unobserved placement is silence. A body's null predecessor means addition; a singleton field's null predecessor means its old line was not supplied. */
const scopesCover = (bank: ChangeProposal, job: ChangeProposal): boolean => workScopes(job).every(scope => workScopes(bank).some(held => Object.entries(scope).every(([key, value]) => value === undefined || value === null && (key !== "before" || scope.slot !== "body") || COPY_RULES.recordKey(value) === COPY_RULES.recordKey(held[key as keyof typeof held])))) && (job.bundle?.dispositions ?? []).every(d => (bank.bundle?.dispositions ?? []).some(held => d.page === held.page && d.verdict === held.verdict));
function copyIdentity(p: ChangeProposal): string {
  return COPY_RULES.recordKey([workContext(p), topicTokens.semanticAtoms(p.primaryQuery).sort(), workScopes(p), p.recommendedChange.kind === "new_page" ? ["new_page", p.recommendedChange.outline, p.recommendedChange.faqQuestions, p.recommendedChange.schemaTypes] : null,
    (p.bundle?.dispositions ?? []).map((d) => [d.page, d.verdict])]);
}
function identityMoves(prior: ChangeProposal, incoming: ChangeProposal): string {
  const moves: string[] = [];
  if ((prior.factIdentity ?? null) !== (incoming.factIdentity ?? null)) moves.push("the checked facts supporting this answer changed");
  if ((prior.copyStamp ?? null) !== (incoming.copyStamp ?? null)) moves.push("the page's own content changed under it");
  if ((prior.diagnosisCause ?? null) !== (incoming.diagnosisCause ?? null)) moves.push(CAUSE_STAMPED); else if (sameQueryGroup(prior.primaryQuery, incoming.primaryQuery) && !sameEpoch(prior, incoming)) moves.push("the diagnosis evidence changed");
  if (!sameQueryGroup(prior.primaryQuery, incoming.primaryQuery)) moves.push("the search it answers changed");
  if (COPY_RULES.recordKey(prior.assignment ?? null) !== COPY_RULES.recordKey(incoming.assignment ?? prior.assignment ?? null) || (prior.treatment ?? null) !== (incoming.treatment ?? prior.treatment ?? null)) moves.push("the assignment or treatment changed");
  if ((prior.pageUrl ?? null) !== (incoming.pageUrl ?? prior.pageUrl ?? null) || !scopesCover(prior, incoming) && workScopes(incoming).some(scope => workScopes(prior).some(held => scope.slot === held.slot && scope.page === held.page))) moves.push("the publication address, placement or predecessor changed");
  if (prior.changeFamily !== incoming.changeFamily
    || (prior.recommendedChange.kind === "existing_edit" ? slotOf(prior.recommendedChange.field) : "new_page")
      !== (incoming.recommendedChange.kind === "existing_edit" ? slotOf(incoming.recommendedChange.field) : "new_page")) moves.push("the kind of change moved");
  return moves.join("; ") || "the pages this change writes on moved";
}

const CAUSE_STAMPED = "the diagnosed cause changed";
/** THE PAID READING RIDES ITS OWN WORDS: `semanticReview.of` is the copy key; `unreviewed` accepts only while it still matches, so carrying a reading onto that key can never authorize unread words. Guarding at the caller failed: an unfinished prior returns early, so a matching key at the call site never proved the reading would survive. */
export function preferFinished(incoming: ChangeProposal, prior: ChangeProposal | null | undefined, incomingOwnsCopy = false): ChangeProposal {
  prior = prior?.tenantId === incoming.tenantId ? prior : null; const moved = !!prior && (!sameContext(prior, incoming) || !scopesCover(prior, incoming)), receipt = prior?.previousCopy && !incoming.previousCopy ? { previousCopy: moved ? { ...prior.previousCopy, attempts: 0, retiredBecause: identityMoves(prior, incoming) } : prior.previousCopy } : {};
  const row0 = incomingOwnsCopy ? { ...incoming, ...receipt } : decideFinished(incoming, prior), fresh = row0.semanticReview, old = prior?.semanticReview; let parts: NonNullable<NonNullable<ChangeProposal["semanticReview"]>["parts"]> = [];
  if (row0.kind === "existing_edit" && prior?.kind === "existing_edit") { try { const subjects = COPY_RULES.reviewSubjects(row0).subjects, candidates = [...(old?.version === REVIEW_CONTRACT ? old.parts ?? [] : []).filter((r) => !fresh?.parts?.some((x) => x.key === r.key)), ...(fresh?.parts ?? [])]; parts = candidates.filter((r, _, all) => all.filter((x) => x.key === r.key).length === 1 && !!r.review.inputKey && subjects.some((s) => reviewFits(s.one, r.review.of) && unreviewed({ ...s.one, semanticReview: r.review }) == null)); } catch { parts = []; } }
  const review = fresh ?? (old && (reviewFits(row0, old.of) || parts.length > 0) ? old : undefined), row = review ? { ...row0, semanticReview: { ...review, ...(parts.length || review.parts ? { parts } : {}) } } : row0;
  const retiredOwner = row.previousCopy?.of ? row.newPageDraft?.pieces.find(piece => `${row.newPageDraft!.brief.identity}::${piece.slot}` === row.previousCopy!.of)?.after : row.recommendedChange.kind === "existing_edit" ? row.recommendedChange.after : undefined;
  const again = !!row.previousCopy && (row.previousCopy.attempts ?? 1) > 0 && retiredOwner?.trim() === row.previousCopy.after.trim(); // A historical retirement with zero attempts on this job is not a repeated corrective draft.
  return again ? { ...row, obligation: { kind: "terminal", reason: "the writer handed back the exact words this change already retired, so it is settled rather than drafted again" } } : row;
}
/** WHETHER THE STORE'S OWN PRESERVATION RULE WOULD KEEP A FINISHED DELIVERABLE OVER THIS INCOMING JOB. Funding asks this before reserving model work; persistence asks the same rule again through `preferFinished`. Keeping this derived from the merge prevents a re-minted brief from being paid for and only then discarded as work already on file. */
export function finishedWorkCovers(incoming: ChangeProposal, finished: ChangeProposal | null | undefined): boolean {
  if (!finished || finished.tenantId !== incoming.tenantId || finished.redraftRequested || finished.researchOnly === true
    || (finished.status !== "ready" && finished.status !== "implemented_pending_verification") || deliverableGaps(finished).length > 0) return false;
  const resolved = preferFinished(incoming, finished);
  return resolved.researchOnly !== true && deliverableGaps(resolved).length === 0 && copyKey(resolved) === copyKey(finished);
}
function decideFinished(incoming0: ChangeProposal, prior00: ChangeProposal | null | undefined): ChangeProposal {
  const prior0 = prior00;
  const stamped0 = incoming0.copyStamp == null && prior0?.copyStamp ? { ...incoming0, copyStamp: prior0.copyStamp } : incoming0;
  // A CAUSE NAMED FOR THE FIRST TIME IS NOT A CAUSE THAT CHANGED, AND A CAUSE NOBODY NAMED THIS PASS IS NOT A CAUSE UNNAMED (live 16:31Z on 2026-09-04, both directions from the reviewer, 2026-09-04). The sweep producers began stamping the typed cause they had always known, the retirement below compared a recorded null against it, and one tick retired thirty-one drafted rows into their own briefs with "the diagnosed cause changed" as the receipt. The first repair covered null-to-named ONLY, which left the identical destruction available in reverse and made it LARGER than before: the demand-recovery producer mints causeless whenever the results page for its unit is not on file, and nine open rows now hold both finished copy and a cause. Silence is not a finding on either side, so the pair is reconciled once, here, before identity is compared; two DIFFERENT recorded causes still move identity exactly as before.
  const incoming = stamped0.diagnosisCause == null && prior0?.diagnosisCause != null ? { ...stamped0, diagnosisCause: prior0.diagnosisCause, ...(prior0.causeFinding ? { causeFinding: prior0.causeFinding } : {}) } : stamped0;
  const prior = prior0 && prior0.diagnosisCause == null && incoming.diagnosisCause != null ? { ...prior0, diagnosisCause: incoming.diagnosisCause, ...(incoming.causeFinding ? { causeFinding: incoming.causeFinding } : {}) } : prior0;
  const priorWords = prior?.recommendedChange.kind === "existing_edit" ? prior.recommendedChange.after.trim() : "";
  const coveredContext = prior?.bundle && !incoming.bundle ? { ...incoming, changeFamily: prior.changeFamily } : incoming; // A complete compound can cover its exact component, whose family need not name the whole bundle.
  const coversBrief = !!prior && (deliverableGaps(prior).length === 0 || !!prior.newPageDraft) && !!priorWords && footprintCovers(prior, incoming) && sameContext(prior, coveredContext) && scopesCover(prior, incoming); // Explicitly changed assignment, scope or component disposition can never borrow coverage from overlapping copy.
  const epoch = !!prior && sameEpoch(prior, incoming), sameWords = epoch && incoming.recommendedChange.kind === "existing_edit" && prior.recommendedChange.kind === "existing_edit" && !!prior.recommendedChange.after.trim() && prior.recommendedChange.after.trim() === incoming.recommendedChange.after.trim() && prior.status === "ready" && deliverableGaps(prior).length === 0;
  const finished = !!prior && prior.researchOnly !== true && deliverableGaps(prior).length === 0, sameWork = !!prior && (!finished || epoch) && (copyIdentity(prior) === copyIdentity(incoming) || coversBrief || sameWords); // Finished copy, its assignment and caveats move as one only while the typed diagnosis snapshot is unchanged; a copyless settlement retains its own obligation lifecycle.
  // THE RECEIPT OUTLIVES THE PASS THAT STAMPED IT (review, 2026-08-22): every return carries the newest retirement receipt available, so the retired words stay inspectable under whatever replaced them instead of living exactly one pass. A NEW receipt below outranks an inherited one.
  const workMoved = !!prior && !sameWork;
  const inherited = prior?.previousCopy && !incoming.previousCopy ? { previousCopy: workMoved ? { ...prior.previousCopy, attempts: 0, retiredBecause: identityMoves(prior!, incoming) } : prior.previousCopy, ...(!workMoved && (prior.faults ?? []).includes(prior.previousCopy.retiredBecause) ? { faults: [...new Set([...(incoming.faults ?? []), prior.previousCopy.retiredBecause])] } : {}) } : {}; // A refusal and its attempt count belong to the material identity that was judged; neither elapsed time nor a reminted brief resets them.
  const priorAfter = prior?.recommendedChange.kind === "existing_edit" ? prior.recommendedChange.after.trim() : "", settledStep = sameWork && (prior!.obligation?.kind === "terminal" || (prior!.obligation?.kind === "evidence" && prior!.obligation.need.reasonCode === "no_winner_to_read")) && !incoming.obligation && !prior!.redraftRequested ? { obligation: prior!.obligation } : {};
  if (!prior || !sameWork) {
    // Replacing finished words records their retirement.
    const incomingAfter = incoming.recommendedChange.kind === "existing_edit" ? incoming.recommendedChange.after.trim() : "";
    if (prior && deliverableGaps(prior).length === 0 && priorAfter && priorAfter !== incomingAfter) {
      if (incoming.previousCopy?.after === priorAfter) return incoming; // A caller's exact retirement receipt owns its actual attempt count, including a no-model reconciliation.
      return { ...incoming, previousCopy: { after: priorAfter, attempts: workMoved ? 0 : (prior.previousCopy?.attempts ?? 0) + 1, // Replacing stale work does not consume a corrective attempt on the new material identity.
        retiredBecause: identityMoves(prior, incoming), at: incoming.createdAt } };
    }
    return { ...incoming, ...inherited };
  }
  // AND A PERSON WHO READ THE WORDS AND ASKED FOR BETTER ONES OUTRANKS THE PRESERVATION RULE. Banked copy survives because a pass that did not reach a card must not destroy it, which says nothing about a card somebody read and sent back: the ask stands until a pass actually writes over it.
  if (prior.redraftRequested) return { ...incoming, ...inherited };
  // A RESEARCH BRIEF IS NEVER FINISHED WORK, however complete its sentences read (Codex, 2026-08-23): a gap-free instruction ("the work is reachability first") beat the finished /funny-farsi-phrases answer here, one second after that answer saved. Only a row that is itself a deliverable may replace one. AND A SECOND GENERATION OF THE SAME WORK DOES NOT GET TO REPLACE THE ONE THAT ALREADY PASSED. A model varies run to run, which is fine BEFORE validation and never after it: five inspected deliverables persisted as three because a later pass under the same identity re-drafted them and saved whatever it got that time, once storing "Goodbye: goodbye." over a finished answer. Identity is the whole of it, so anything that would make the old answer wrong reopens it: `workKey` folds the writer contract, the basis, the evidence hash, the treatment, the cause and the query, and `copyStamp` is the page as it was last read. A missing stamp on either side is NOT a match, so a row from before this rule is replaced exactly as it was.
  const settled = sameWords || (prior.status === "ready" && deliverableGaps(prior).length === 0 && !!prior.workKey && prior.workKey === incoming.workKey && !!prior.copyStamp && prior.copyStamp === incoming.copyStamp); // the same finished words under a moved basis, top search or page stamp are still settled (see sameWords above)
  // A review bound to the prior exact copy outranks an unreviewed re-mint; its provenance must still survive.
  const reviewedPrior = !!prior.semanticReview && reviewFits(prior, prior.semanticReview.of) && unreviewed(prior, undefined, false) == null && !(incoming.semanticReview && reviewFits(incoming, incoming.semanticReview.of)); // the reading, not the ledger: a preservation hold keeps the row in review, it never hands the words to a re-mint
  if (!settled && !reviewedPrior && ((incoming.researchOnly !== true && deliverableGaps(incoming).length === 0) || deliverableGaps(prior).length > 0 && !(prior.newPageDraft && !incoming.newPageDraft && (prior.kind === "new_page" || COPY_RULES.pieceDebt(prior) !== undefined)))) return { ...incoming, ...inherited, ...settledStep };
  // COPY NOBODY CAN TRACE IS NOT FINISHED WORK. An atomic card's words are written by the editor, which hands back every claim beside the evidence ids carrying it, and this branch banked the words and dropped the claims: all three ready cards on the live account carried `claims: null` and no persisted mapping from a sentence to the thing behind it, so nothing on the row could ever be re-checked. Banked words survive only WITH their provenance now, and copy that reached the row before this did is redrafted once rather than served on for ever as an unsupported claim. A bundle answers on its receipt instead and is left alone.
  if (prior.kind !== "new_page" && !prior.bundle && (prior.claims ?? []).length === 0) { // A BRIEF NEVER SILENTLY DISPLACES FINISHED WORDS (operator, 2026-09-02): a finished description was replaced by its own re-minted brief with no receipt. Claimless copy is held, words kept, for the reading that rebuilds its record; only a competing finished draft may take its place. THE HOLD IS NOT A FAULT ABOUT THE WORDS (incident, 2026-09-04): written as one, it sent twenty five recovered descriptions to a paid rewrite. `openHold` mints it from structure on every read, so the words keep their display caveat and the obligation ladder files a reading.
    return incoming.researchOnly === true ? { ...prior, ...inherited, status: "needs_review", faults: [...new Set([...(prior.faults ?? []), NO_RECORD])], limitations: [...new Set([...prior.limitations, NO_RECORD])] } : { ...incoming, ...inherited, ...settledStep }; } // AND A ROW IN REVIEW IS FINISHED WORK TOO (incident recovery, 2026-09-04): the hold was written for `ready` alone, so a claimless description sitting in review was displaced by its own re-minted brief with no receipt at all, which is the very loss this rule is named for and the one that would have undone the recovery above on the pass after it landed
  // AND A CLAIM POINTING AT AN ID NOBODY BANKED THE WORDS FOR IS NOT PROVENANCE EITHER. The ids resolve inside the pass that drafted the copy and nowhere else, so banked words survive only while every id their claims name has its exact quoted fact banked beside them. Copy banked before the pairs existed is redrafted once, exactly as copy banked before the claims existed was.
  const banked = new Set((prior.supportFacts ?? []).map((f) => f.id));
  if (!prior.bundle && (prior.claims ?? []).some((c) => c.supportedBy.some((id) => !banked.has(id)))) return { ...incoming, ...inherited, ...settledStep };
  // Copy-owned fields stay with banked words; current evidence and ranking still land.
  const kept: ChangeProposal = { ...incoming, ...inherited, ...(sameWords ? { createdAt: prior.createdAt, ...(prior.workKey ? { workKey: prior.workKey } : {}) } : {}), recommendedChange: prior.recommendedChange, researchOnly: prior.researchOnly ?? false, research: prior.researchOnly ? prior.research : undefined, status: prior.status, /* the same finished words are the same job: they keep their birth date and their job key, or a $0 re-mint rewrote the row every pass for a moved evidence hash (2026-09-17) */ // AND A ROW WHOSE WORDS ARE FINISHED CARRIES NO BRIEF (incident recovery, 2026-09-04): the incoming re-mint's assignment rode onto the preserved copy, so a row holding a deliverable still had an instruction to write it stored beside the words
    limitations: prior.limitations, estimatedEffortMinutes: prior.estimatedEffortMinutes };
  const fits = copyKey(kept) === copyKey(incoming); // A RECEIPT MAY ARRIVE LATE ONLY IF IT WAS WRITTEN FOR THESE WORDS: the exception claimed identity proved the copy byte-identical, but `copyIdentity` EXCLUDES the copy and `workKey` names the job, so a redraft's receipts rode the banked words (Codex, 2026-08-28)
  // Exact-copy matches refresh steps only; changed claims/facts invalidate the paid reading.
  for (const f of COPY_OWNED) {
    if (fits && f === "operatorSteps") continue; // already carrying this pass's value from `incoming`
    if (prior[f] != null) (kept as Record<string, unknown>)[f] = prior[f];
    else if (!(fits && (f === "preservation" || f === "informationGain"))) delete (kept as Record<string, unknown>)[f]; }
  // AND THE IDENTITY RIDES THE WORDS IT KEEPS (RV9 residual 3, 2026-09-05). This path keeps the prior's copy AND the prior's support and then took the incoming's `workKey` whole, so a $0 re-mint carrying no support facts stamped a key naming none onto a row holding two: the pre-1979 flag answer went from `...::draft::r5:sc2::fact-1,page-copy-1` at v192 to `...::draft::r5:sc2::` at v193 while its words, its claim and its paid reading never moved. Measured over the store the same hour: of the 72 rows whose key carries the current shape, 33 name FEWER facts than the row holds and NOT ONE names a fact the row does not, so the disagreement is one-directional and is this. ONLY the support segment moves, and only on a key of the current shape (the segment before it is the rules version), so the writer contract, the basis, the evidence hash, the treatment and the owed step still move the identity exactly as they did, a contract bump still reopens the work, and a key minted under an older shape is never rewritten.
  if (kept.bundle) return kept; // A BUNDLE'S WORK KEY BELONGS TO THE DEEP JOB THAT FUNDED IT, not to any one component's support ids. Rewriting its tail made the finished bundle cease to match that job on the next unchanged pass, which re-bought the writer and reviewer before preservation discarded their duplicate words.
  const seg = (kept.workKey ?? "").split("::"), ids = (kept.supportFacts ?? []).map((f) => f.id).sort().join(",");
  return seg.length > 1 && /^r\d/.test(seg[seg.length - 2] ?? "") && seg[seg.length - 1] !== ids ? { ...kept, workKey: [...seg.slice(0, -1), ids].join("::") } : kept;
}
/** THE FIELDS THAT BELONG TO THE BANKED COPY and must survive with it. `redraftRequested` is deliberately ABSENT: a person who asked for better words outranks preservation, and that path returns before this list is read. The day someone adds a copy-owned field to the contract and forgets it here, the typed faults lesson repeats; keep this list beside the contract change in the same commit. THAT DAY WAS 2026-09-02 AND `assignment` WAS THE FIELD: measured on the production store, 0 of the 451 stored rows on the ONE account that table holds carried an assignment, at any status. The drafting door computes one typed assignment per row and stores it, and the next $0 re-mint of the same identity takes this path, keeps the prior's copy and lets the re-mint's absent assignment ride, so a row banked under the missing-answer standard was served, judged and re-read as a restructuring within one pass. It belongs here for the same reason `faults` does: it is Beacon's own typed statement about these exact words. Being on the list also makes the 2026-09-04 rule true rather than asserted, because the `else` arm DELETES an incoming brief wherever the preserved copy carries none of its own. */
const COPY_OWNED = ["claims", "supportFacts", "operatorSteps", "bundle", "newPageDraft", "confirmedVersion", "approval", "faults", "modeledOn", "informationGain", "preservation", "preservationNotes", "draftNotes", "obligation", "assignment"] as const satisfies readonly (keyof ChangeProposal)[]; // `obligation` rides the banked words so a SETTLED verdict survives every later pass that reaches this row under the same identity; a pass that genuinely moves the identity wins whole and the ladder decides again from nothing

/** THE EXACT VERSION OF A CHANGE AN OPERATOR CAN SAY YES TO, and the ONE definition of it: the screen folds this and the server recomputes it byte for byte off the row it re-reads, so no second reading of "the same version" can exist. A confirmation is worthless unless it names WHAT was confirmed, and this used to name a third of it: the copy it replaces, where the copy lands, what survives a page move, the risks, the caveats, the steps, the reasons pages were left alone, every claim, the words behind every claim, the readings on the receipt and the days they were taken all moved without moving the version. It is now EVERYTHING MATERIAL THE OPERATOR READ. Any edit to any of it mints a different string, the stored stamp stops matching, and the stale confirmation refuses. UNORDERED SETS ARE SORTED, so re-listing the same caveats, support ids, readings or verdicts is not a rewrite; the ranking, the timestamps and the measurement figures are excluded because none of them is the change. SHORT and PURE: it folds through the same tiny fingerprint a bundle's pieces are already named by, so a server component can hand it to a browser. */
export function confirmedVersion(p: ChangeProposal): string {
  const c = p.recommendedChange, b = p.bundle, f = p.causeFinding;
  const sorted = <T>(xs: readonly T[] | undefined): T[] => [...xs ?? []].sort((x, y) => JSON.stringify(x).localeCompare(JSON.stringify(y))); // A DOOR MAY REFUSE A CHANGE; IT MAY NEVER CRASH ON ONE: the one verdict is asked of every stored row at every door now, so a legacy bundle missing an array a fresh mint always carries is stamped, never thrown on top of the operator.
  // Confirmation pins the basis and every rendered sentence, even when copy preservation keeps words.
  const material = [p.basis ?? null, p.riskLevel, copyIdentity(p), p.diagnosisCause ?? null, sorted(p.limitations.filter((l) => !OWED_NOTE.test(l))), p.operatorSteps ?? [],
    c.kind === "existing_edit" ? [c.field, c.before, c.after, c.where ?? null] : [c.proposedTitle, c.metaDescription, c.openingAnswer, c.outline, c.faqQuestions, c.schemaTypes],
    (p.claims ?? []).map((x) => [x.text, [...x.supportedBy].sort()]), sorted((p.supportFacts ?? []).map((x) => [x.id, x.fact])), p.informationGain ?? null, p.preservation ?? null, ...(p.preservationNotes ? [["preservation_notes", p.preservationNotes]] : []),
    f ? [f.cause, f.explanation, f.falsifier, sorted(f.competingExplanations.map((x) => [x.cause, x.reason])), sorted(f.notConsidered.map((x) => [x.cause, x.missing]))] : null,
    b ? [b.objective, b.metric, b.measurementPlan, sorted(b.risks), sorted(b.receipt?.missing), sorted(b.confidenceReasons), sorted((b.alternatives ?? []).map((x) => [x.option, x.reason])),
      b.components.map((x, i) => [componentIdOf(x, i), x.page ?? null, x.where ?? null, x.before, x.risk, x.redirectTo ?? null, x.objective ?? null, x.mechanism ?? null, x.anchorAfter ?? null, x.preserves ?? null, x.sourcePack ?? null, sorted(x.evidenceKeys)]),
      sorted((b.dispositions ?? []).map((d) => [d.page, d.verdict, d.because])),
      sorted((b.receipt?.items ?? []).map((i) => [i.key, i.kind, i.fact, i.observedAt, i.observationId ?? null, [...(i.observationIds ?? [])].sort(), sorted(i.sources)]))] : null];
  return componentIdOf({ kind: "confirmation", after: JSON.stringify(material) }, 0);
}
