import { componentIdOf, type BundleComponent, type BundleComponentKind, type ChangeProposal } from "./contracts"; import { canonicalUrlKey, FURNITURE_LABEL } from "@/domains/evidence/relevance-gate";
import type { SourcePacket } from "./drafted-copy"; import { fieldForComponent } from "./producers/contract";
import type { OwnedPageBody } from "@/domains/evidence/pages/owned-context"; import type { FactCheck } from "@/domains/evidence/pages/fact-checks";
import { sanitizeNullableEvidence } from "./llm/injection-sanitizer";
const losable = (u: string): boolean => !FURNITURE_LABEL.test(u.replace(/^["\u201c\u2018]+|["\u201d\u2019]+$/g, "").trim());
const carriesUnit = (unit: string, after: string): boolean => { const original = renderedText(unit), copy = renderedText(after); if (!original) return false; for (let at = copy.indexOf(original); at >= 0; at = copy.indexOf(original, at + 1)) { const end = at + original.length; if (!/[\p{L}\p{N}\p{M}_'’-]$/u.test(copy.slice(Math.max(0, at - 2), at)) && !/^[\p{L}\p{N}\p{M}_'’-]/u.test(copy.slice(end, end + 2))) return true; } return false; };
/** THE ONE LOWERCASE COMPARISON FORM (Stage 3, 2026-09-14): six files each carried their own "lowercase and collapse whitespace"; this is that one, with the curly quotes and the non-breaking space the page words carry. `renderedText` below is the case-preserving form the preservation ledger compares on. */ const flat = (s: string | null | undefined): string => (s ?? "").toLowerCase().replace(/[\s\u00a0]+/g, " ").replace(/[\u201c\u201d]/g, '"').replace(/[\u2019]/g, "'").trim();
const renderedText = (t: string): string => t.normalize("NFKC").replace(/[\u2018\u2019\u02bc]/gu, "'")
    .replace(/[\u201c\u201d]/gu, '"').replace(/\s+/gu, " ").replace(/ +([,.;:!?])/gu, "$1").trim();
const TITLE_SUFFIX = /\s(?:\||::)\s/gu; // Only a final pipe/:: title tail proven by this row's host or ancestor path is furniture; real names, links, figures and body entities remain content.
const materialLosses = (p: Pick<ChangeProposal, "recommendedChange" | "pageUrl" | "pagePath">): string[] => {
  const c = p.recommendedChange; if (c.kind !== "existing_edit" || !c.before?.trim()) return [];
  const before = c.before, after = c.after, bare = (t: string): string => t.toLowerCase().normalize("NFKD").replace(/[^\p{L}\p{N}]+/gu, ""), a = bare(after), out: string[] = [];
  for (const u of before.match(/https?:\/\/\S+|\bwww\.\S+|(?<=\s|^)\/[a-z0-9-]{2,}(?:\/[a-z0-9-]+)+/g) ?? []) if (!after.includes(u.replace(/[).,]+$/, ""))) out.push(`the link ${u.replace(/[).,]+$/, "")}`);
  for (const n of before.match(/\d[\d,.]*(?:\s?(?:%|percent|BCE|CE|AD|BC))?/g) ?? []) if (n.replace(/[^\d]/g, "").length >= 2 && !a.includes(bare(n))) out.push(`the figure ${n.trim()}`);
  const titleTailAt = c.field === "title" ? [...before.matchAll(TITLE_SUFFIX)].at(-1)?.index ?? -1 : -1, tail = titleTailAt >= 0 ? before.slice(titleTailAt).replace(TITLE_SUFFIX, "").trim() : "", compact = (s: string): string => s.toLowerCase().normalize("NFKD").replace(/[^a-z0-9]+/g, "");
  let host = "", path = p.pagePath ?? "";
  try { const u = new URL(/^https?:\/\//i.test(p.pageUrl ?? "") ? p.pageUrl! : `https://${(p.pageUrl ?? "").replace(/^\/+/, "")}`); host = u.hostname.replace(/^www\./, ""); path ||= u.pathname; } catch { /* an unreadable address proves no furniture */ }
  const hostLabels = host.split(".").slice(0, -1).filter((x) => x !== "www").map(compact).filter(Boolean), tailCompact = compact(tail), ancestors = path.split("/").filter(Boolean).slice(0, -1).map((segment) => segment.split(/[-_]+/).filter(Boolean)).filter((parts) => parts.length >= 2).map((parts) => compact(parts.join(" "))), provenTail = !!tail && (hostLabels.includes(tailCompact) || ancestors.some((ancestor) => tailCompact.includes(ancestor)));
  for (const match of before.matchAll(/(?:[\p{Lu}\p{N}][\p{L}\p{N}'’-]* ){1,5}\p{Lu}[\p{L}\p{N}'’-]+/gu)) { const phrase = match[0].trim(); if (!a.includes(bare(phrase)) && !(provenTail && (match.index ?? 0) > titleTailAt)) out.push(`"${phrase}"`); }
  return [...new Set(out)];
};
/** A PAGE QUOTATION IS MATCHED WITH EVERY SPACE REMOVED (production, 2026-09-15): three Ready link rows were demoted because their page-copy facts were cut from the old flat body_text, which glued words at heading boundaries ("ActressesExplore"), and the heading-scoped passages now separate them; both sides are compared case folded, quotes straightened and with all whitespace removed. Checked facts keep the exact rule. */
const squashed = (t: string): string => renderedText(t).toLowerCase().replace(/\s+/gu, "");
const carriesQuotation = (unit: string, text: string): boolean => { const q = squashed(unit); return !!q && squashed(text).includes(q); };
type PreservationRow = Pick<ChangeProposal, "recommendedChange" | "preservation" | "supportFacts" | "bundle" | "pageUrl" | "confirmedVersion"> & Partial<Pick<ChangeProposal, "changeFamily">> & { editor?: NonNullable<ChangeProposal["semanticReview"]>["editor"] }; type Unit = NonNullable<ChangeProposal["preservation"]>[number]; const RULING = "ruling";
function preservationShortfall(p: PreservationRow, qualified: boolean, losses: readonly string[] = [], publication: readonly BundleComponent[] = p.bundle?.components ?? []): string | null {
  if (p.recommendedChange.kind === "existing_edit" && p.bundle) {
    const c = p.recommendedChange, parts = p.bundle.components.filter((part) => COPY_RULES.bodyKinds.has(part.kind) || /^(title|h1|meta)$/.test(part.kind)), rootIsComponent = parts.some((part) => { try { return fieldForComponent(part.kind) === c.field && part.before === c.before && part.after === c.after && (part.where ?? null) === (c.where ?? null) && new URL(part.page ?? p.pageUrl ?? "", p.pageUrl ?? undefined).href === new URL(p.pageUrl ?? "").href; } catch { return false; } }), original = COPY_RULES.originalUnits(c.before ?? ""), rootLedger = rootIsComponent ? [] : (p.preservation ?? []).filter((u) => !u.of && original.some((text) => renderedText(text) === renderedText(u.text))); let ledger: NonNullable<ChangeProposal["preservation"]>;
    try { ledger = COPY_RULES.preservationOwners((p.preservation ?? []).filter((u) => !rootLedger.includes(u)), parts, p.bundle.components); } catch (e) { return e instanceof Error ? e.message : "The preservation record has no publication owner."; }
    for (const part of parts) { const id = componentIdOf(part, p.bundle.components.indexOf(part)), field = fieldForComponent(part.kind);
      let pageUrl: string; try { pageUrl = new URL(part.page ?? p.pageUrl ?? "", p.pageUrl ?? undefined).toString(); } catch { return "The preservation record has no valid publication address."; }
      const bad = preservationShortfall({ ...p, bundle: undefined, pageUrl, preservation: ledger.filter((u) => u.of === id), editor: p.editor ? { ...p.editor, preservation: p.editor.preservation?.filter((r) => r.of === id) } : undefined, recommendedChange: { kind: "existing_edit", field, before: part.before, after: part.after, units: part.units, target: part.target, where: part.where } }, qualified, [], publication); if (bad) return `In "${part.label}": ${bad}`;
    } return rootIsComponent ? null : preservationShortfall({ ...p, bundle: undefined, preservation: rootLedger, editor: p.editor ? { ...p.editor, preservation: p.editor.preservation?.filter((r) => !r.of) } : undefined }, qualified, losses, publication);
  }
  const c = p.recommendedChange; if (c.kind !== "existing_edit" || !c.before?.trim() || renderedText(c.before) === renderedText(c.after)) return null;
  const body = c.field === "section" || c.field === "answer_block", due = body ? [] : losses.length ? losses : materialLosses({ ...p, pagePath: "" }), { units, ledger, byRecord, cites, lands } = unitLedger(p, qualified, publication, due);
  if (body && units.length <= 1 && p.changeFamily === "factual_correction") return null; /* A ONE-LINE CORRECTION OWES NO PER-UNIT LEDGER (Stage 3, 2026-09-14): the before is one unit and the replacement is its disposition, proved by the claim ruling against the fact ids it names; a title, a description and a heading owe none either, only the earning words `losses` carries */
  const entryFor = (text: string) => { const entries = ledger.filter((u) => renderedText(u.text) === renderedText(text)); return entries.length === 1 ? entries[0] : undefined; };
  const unverified = (u: Unit): string | null => {
    const record = byRecord(u); if (record !== RULING) return record;
    const readings = p.editor?.preservation?.filter((r) => renderedText(r.text) === renderedText(u.text)) ?? [], r = readings[0];
    if (readings.length === 0 && u.disposition === "moved") return "moves material to a destination that does not carry it";
    if (readings.length === 0 && u.disposition === "kept") return "says it keeps material the new copy no longer carries"; /* a literal keep is checked on the words alone; only a nonliteral keep needs the reviewer to quote the survivor */
    if (!qualified || readings.length !== 1 || !r?.verified || r.disposition !== u.disposition || r.to !== (u.to ?? null)) return "has no verified per-unit preservation ruling for these exact words, source evidence and destination";
    if (r.by.some((id) => !(u.by ?? []).includes(id) || !cites({ by: [id] }) )) return "cites evidence outside this unit's own supporting facts";
    if (u.disposition === "kept") return r.after && carriesUnit(r.after, c.after) ? null : "says it keeps material the new copy no longer carries";
    if (u.disposition === "corrected") return cites(u) && r.by.length > 0 && r.after && carriesUnit(r.after, c.after) ? null : "corrects material without a source-supported delivered replacement";
    if (u.disposition === "moved") return r.after && lands(u, r.after) ? null : "moves material to a destination that does not carry it";
    const proved = u.basis === "duplicate_of" || u.basis === "replaced_by" ? !!r.after && lands(u, r.after) : u.basis === "owner_confirmed" ? !!p.confirmedVersion : (u.basis === "obsolete" || u.basis === "unsupported") && cites(u) && r.by.length > 0;
    return proved ? null : "removes material without a basis this door can check";
  };
  for (const u of ledger) { const bad = unverified(u); if (bad) return `it ${bad}: "${u.text.slice(0, 60)}"`; }
  const required = body ? units.filter(losable) : due.filter(losable);
  for (const text of required) if (!carriesUnit(text, c.after)) { const entry = entryFor(text), bad = entry ? unverified(entry) : "neither says it nor accounts for it: every original unit needs its own preservation disposition"; if (bad) return `it replaces a passage saying "${text.slice(0, 60)}" and ${bad}`; }
  return body && (c.where ?? "").includes("absorbs the duplicated entries") && !ledger.length ? "it says it absorbs the entries below it without naming one of them" : null;
}
/** WHAT THE RECORD ALONE PROVES ABOUT EACH LEDGER ENTRY, shared by the door that refuses and the prompt that asks: null when proved (a literal keep, a move or a duplicate removal whose destination carries the exact words, an owner-confirmed removal, a correction on a correction row that names its facts), a refusal in the reader's words, or RULING when only the reviewer can say (a nonliteral keep, a correction, a removal that stands on a fact). The reviewer is then asked for exactly that residue and nothing else. */
function unitLedger(p: PreservationRow, qualified: boolean, publication: readonly BundleComponent[], losses: readonly string[] = []) {
  const c = p.recommendedChange as Extract<ChangeProposal["recommendedChange"], { kind: "existing_edit" }>, units = [...new Set([...COPY_RULES.originalUnits(c.before ?? ""), ...losses])], ledger = p.preservation ?? [], banked = new Set((p.supportFacts ?? []).map((f) => f.id));
  const cites = (u: { by?: readonly string[] }): boolean => !!u.by?.length && u.by.every((id) => banked.has(id) && !COPY_RULES.briefing.test(id));
  const placeOf = (u: { to?: string }) => { const places = COPY_RULES.destinations([u], publication).filter(({ part }) => COPY_RULES.bodyKinds.has(part.kind)); return places.length === 1 ? places[0]!.part : null; };
  const lands = (u: { text: string; to?: string }, quote: string): boolean => { const part = placeOf(u); if (!part) return false;
    try { return new URL(part.page ?? p.pageUrl ?? "", p.pageUrl ?? undefined).origin === new URL(p.pageUrl ?? "").origin && carriesUnit(quote, part.after); } catch { return false; } };
  const byRecord = (u: Unit): string | null => {
    if (!units.some((text) => renderedText(text) === renderedText(u.text))) return "names material outside the exact predecessor";
    if (u.disposition === "kept") return carriesUnit(u.text, c.after) ? null : RULING;
    if (u.disposition === "corrected") return !cites(u) || (p.changeFamily === "factual_correction" && !qualified) ? "corrects material without naming the banked facts that carry that correction" : p.changeFamily === "factual_correction" ? null : RULING; /* A FACTUAL CORRECTION IS PROVED BY ITS QUOTE-BOUND CLAIM RULING (restored, audit 2026-09-14): its reviewer rules claim by claim against the exact fact ids and returns no per-unit ledger */
    if (u.disposition === "moved") return lands(u, u.text) ? null : !placeOf(u) ? "moves material to a destination that does not carry it" : RULING;
    const relocated = u.basis === "duplicate_of" || u.basis === "replaced_by"; if (!(relocated ? !!placeOf(u) : u.basis === "owner_confirmed" ? !!p.confirmedVersion : (u.basis === "obsolete" || u.basis === "unsupported") && cites(u))) return "removes material without a basis this door can check";
    return u.basis === "owner_confirmed" || relocated && lands(u, u.text) ? null : RULING; };
  return { units, ledger, byRecord, cites, lands };
}
/** THE UNITS THE REVIEWER MUST RULE ON, numbered in the prompt: every ledger entry the record cannot prove or refuse by itself. Empty means the reviewer owes no preservation ruling at all. */
const preservationResidue = (p: PreservationRow, publication: readonly BundleComponent[] = []): Unit[] => { const c = p.recommendedChange; if (c.kind !== "existing_edit" || !c.before?.trim()) return []; const body = c.field === "section" || c.field === "answer_block", { units, ledger, byRecord } = unitLedger(p, true, publication, body ? [] : materialLosses({ ...p, pagePath: "" })); return body && units.length <= 1 && p.changeFamily === "factual_correction" ? [] : ledger.filter((u) => byRecord(u) === RULING); };
/** A reviewer cannot repair an absent unit or an invalid destination. Refuse those records before buying its reading. */
const preservationPreflight = (p: PreservationRow, publication: readonly BundleComponent[] = []): string | null => {
  const c = p.recommendedChange; if (c.kind !== "existing_edit" || !c.before?.trim()) return null;
  const body = c.field === "section" || c.field === "answer_block", due = body ? [] : materialLosses({ ...p, pagePath: "" }), { ledger, byRecord } = unitLedger(p, true, publication, due);
  if (body) { for (const u of ledger) { const bad = byRecord(u); if (bad && bad !== RULING) return `it ${bad}: "${u.text.slice(0, 60)}"`; if (u.disposition !== "kept") continue;
      const losses = materialLosses({ recommendedChange: { ...c, before: u.text }, pageUrl: p.pageUrl, pagePath: "" }), hardLoss = u.why?.trim() ? losses.find((text) => /^the (?:link|figure) /.test(text)) : losses.find(losable);
      const namedLoss = [...u.text.matchAll(/["\u201c]([^"\u201d]+)["\u201d]\s+meaning\b/giu)].map((m) => m[1]!.trim().replace(/[,.!?;:]+$/, "")).find((term) => term.length >= 3 && /^[\p{L}\p{M}'’-]+$/u.test(term) && !carriesUnit(term, c.after));
      if (hardLoss || namedLoss) return `it says it keeps ${hardLoss ?? `"${namedLoss}"`} but the new copy does not carry it`; } return null; }
  for (const u of ledger) { const bad = byRecord(u); if (bad && bad !== RULING) return `it ${bad}: "${u.text.slice(0, 60)}"`; }
  for (const text of due.filter(losable)) if (!carriesUnit(text, c.after) && ledger.filter(u => renderedText(u.text) === renderedText(text)).length !== 1)
    return `it replaces a passage saying "${text.slice(0, 60)}" and neither says it nor accounts for it: every original unit needs its own preservation disposition`;
  return null;
};
/** An owned page can count its own items; it cannot certify an external-world metric, even when an old wrong-subject description repeated the number. */
const META_QUANTITY = /(?<![\p{L}\p{N}])\d[\d,.]*(?:\s*(?:-|–|—|to)\s*\d[\d,.]*)?%?(?![\p{L}\p{N}])/giu;
const metaQuantities = (text: string): string[] => [...text.matchAll(META_QUANTITY)].flatMap((m) => { const around = text.slice(Math.max(0, m.index - 48), m.index + m[0].length + 32).toLowerCase(), metric = /\b(?:life\s*span|lifespan|life expectancy|age at death|mortality|survival|population|birth rate|death rate)\b/.test(around) ? "world" : /\b(?:years?|months?|days?|hours?|km|miles?|rank(?:ed|ing)?|top|percent)\b|%/.test(around) ? "measure" : null; return metric ? [`${metric}:${(m[0].match(/\d[\d,.]*/g) ?? []).map((n) => n.replace(/,/g, "")).join(":")}`] : []; });
const newMetaQuantityGap = (p: Pick<ChangeProposal, "recommendedChange" | "claims" | "supportFacts" | "pageUrl">): string | null => {
  const edit = p.recommendedChange; if (edit.kind !== "existing_edit" || edit.field !== "meta") return null;
  const asserted = [...new Set(metaQuantities(edit.after))]; if (!asserted.length) return null;
  const own = (() => { try { return new URL(p.pageUrl ?? "").hostname.replace(/^www\./, ""); } catch { return ""; } })();
  const subjectOverlap = (claim: string, quote: string): boolean => { const stop = new Set(["about", "average", "median", "years", "months", "days", "hours", "death", "lifespan", "population", "source", "study", "found", "gives", "which", "these", "their", "page"]), words = (s: string) => s.toLowerCase().match(/[\p{L}]{5,}/gu)?.filter((w) => !stop.has(w)) ?? []; return words(claim).some((w) => words(quote).includes(w)); };
  const supported = (key: string): boolean => (p.claims ?? []).some((claim) => metaQuantities(claim.text).includes(key) && claim.supportedBy.some((id) => /^fact-\d+$/.test(id) && (p.supportFacts ?? []).some((fact) => fact.id === id && [...fact.fact.matchAll(/(?:(scholarly|dictionary|encyclopedia|reference|news|publisher)\s+)?(https?:\/\/[^\s"']+)\s+says:?\s*"([^"]+)"/g)].some((m) => { const kind = fact.sources?.find((s) => s.url === m[2])?.kind ?? m[1] ?? ""; if (!/^(scholarly|dictionary|encyclopedia|reference|news)$/.test(kind)) return false; let host = ""; try { host = new URL(m[2]!).hostname.replace(/^www\./, ""); } catch { return false; } return !!own && !!host && host !== own && !host.endsWith(`.${own}`) && !own.endsWith(`.${host}`) && metaQuantities(m[3]!).includes(key) && subjectOverlap(claim.text, m[3]!); }))));
  return asserted.some((key) => !supported(key)) ? "a world metric in this description has no matching claim-level checked source; the page's own heading or body cannot confirm it" : null;
};
function accountWrongSubjectMeta(d: { actionType: string; beforeText: string | null; finalCopy: string; preservation?: ChangeProposal["preservation"]; supportFacts: NonNullable<ChangeProposal["supportFacts"]>; evidenceIdsUsed: readonly string[] }, packet: SourcePacket, proof: { before: string; named: string; actual: string }): void {
  if (d.actionType !== "meta" || d.beforeText !== proof.before || packet.metaDescription !== proof.before || !flat(d.finalCopy).includes(flat(proof.actual))) return;
  const losses = materialLosses({ recommendedChange: { kind: "existing_edit", field: "meta", before: proof.before, after: d.finalCopy }, pageUrl: packet.targetUrl, pagePath: "" }), merged = d.preservation?.length === 1 ? d.preservation[0] : null, whole = merged && renderedText(merged.text) === renderedText(proof.before);
  const named = merged && losses.length === 1 && /^"[^"]+"$/.test(losses[0]!) && renderedText(merged.text) === renderedText(losses[0]!.slice(1, -1)) && renderedText(proof.before).includes(renderedText(merged.text)) && !renderedText(proof.before).includes(renderedText(losses[0]!)) && merged.by?.every((id) => /^page-(?:h1|copy-\d+)$/.test(id) && !!packet.evidence[id]);
  if (!merged || merged.disposition !== "removed" || !(whole && ["unsupported", "replaced_by"].includes(merged.basis ?? "") || named && merged.basis === "unsupported" && !merged.to && !!merged.by?.length && !packet.truncated)) return;
  const actual = flat(proof.actual), own = Object.entries(packet.evidence).filter(([id, fact]) => /^page-(?:h1|copy-\d+)$/.test(id) && flat(fact).includes(actual));
  if (!losses.length || !own.some(([id]) => id === "page-h1") || !own.some(([id]) => /^page-copy-/.test(id)) || named && !merged.by?.some((id) => own.some(([source]) => source === id && /^page-copy-\d+$/.test(source)))) return;
  const by = [...new Set([...own.map(([id]) => id), ...(named ? merged.by ?? [] : [])])], recorded = new Set(d.supportFacts.map((f) => f.id));
  d.supportFacts = [...d.supportFacts, ...by.filter((id) => !recorded.has(id)).map((id) => ({ id, fact: packet.evidence[id]! }))];
  d.evidenceIdsUsed = [...new Set([...d.evidenceIdsUsed, ...by])];
  if (named) { d.preservation = [{ ...merged, text: losses[0]!, by }]; return; }
  d.preservation = losses.map((text) => ({ text, disposition: "removed", basis: "unsupported", by, why: `The complete current article identifies ${proof.actual}; this old description instead concerns ${proof.named}.` }));
}

const UUID = /\b[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}(?:\.\.\.)?\b/i;

/** True when the text carries at least one id-shaped token. The one validator treats that as a hard safety trip: an operator is never handed a raw id as if it were copy. */
export function containsUuid(text: string | null | undefined): boolean {
  return !!text && UUID.test(text);
}

/** A written web address, told from ordinary prose by its public suffix: the generic suffixes in real use plus ANY two-letter country code. Narrowed by CODE_SUFFIX, because "Node.js" and "README.md" are file names, not websites, and throwing away a whole draft over one would read as nonsense. Broad on purpose: an address I never showed the model is a fabricated source, and a suffix list is the only thing standing between that and copy. */
export const HOST_RE = /\b[a-z0-9][a-z0-9-]+(?:\.[a-z0-9-]+)*\.(?:[a-z]{2}|com|org|net|edu|gov|mil|int|info|biz|name|pro|dev|app|xyz|online|site|store|shop|tech|blog|cloud|agency|studio|media|news|live|world|club|space|design|digital|wiki|guru|travel|press|recipes|expert|center|life|today|guide|tips|reviews|directory|academy|institute|foundation|community|network|systems|solutions|services|company|group|team|works|example)\b/gi;
const CODE_SUFFIX = /\.(?:js|ts|py|rb|go|rs|kt|cs|sh|md)$/i;
export const AUTOPUBLISH_RE = /\b(auto-?publish|automatically (?:publish|post|upload|push|goes? live)|(?:publish|post|upload|push)ed automatically|i will (?:publish|post|upload|push|handle publishing|put this .{0,20}live)|i(?:'ll| will) (?:take care of|handle) (?:the )?publish|goes? live (?:by itself|on its own|automatically)|puts? (?:it|this|the page) live for you|publishes? (?:it|this) for you)\b/i;
const SPELLED_PROPORTION_RE = /\b(?:per ?cent|percent)\b|\b(?:one|two|three|four|five|six|seven|eight|nine|ten|half|most|nearly all|almost all)\s+(?:in|out of)\s+(?:two|three|four|five|ten|100|10)\b/i;
function bodyCopy(units: NonNullable<BundleComponent["units"]>): string {
  return units.map((unit) => unit.kind === "paragraph" ? unit.text : unit.kind === "heading" ? unit.level === 1 ? unit.text : `${"#".repeat(unit.level)} ${unit.text}`
    : unit.kind === "table" ? `| ${unit.columns.map(tableCell).join(" | ")} |\n| ${unit.columns.map(() => "---").join(" | ")} |\n${unit.rows.map((row) => `| ${row.map(tableCell).join(" | ")} |`).join("\n")}`
      : unit.items.map((text, i) => `${unit.kind === "ordered_list" ? `${i + 1}.` : "-"} ${text}`).join("\n")).join("\n\n");
}
const tableCell = (text: string): string => text.replace(/\s*\n\s*/g, " ").replace(/\|/g, "\\|").trim();
function publicationWhere(target: NonNullable<BundleComponent["target"]>): string {
  if (target.mode === "whole_body") return "Replace the entire visible main-content body with this complete copy; retain the page headline, title tag, description, navigation and structured data unless separately changed.";
  if (target.mode === "opening") return "At the start of the main content, immediately after the page headline and before its existing opening.";
  return target.mode === "after_section" ? `After the entire section headed "${target.anchor}", before the next section of the same or higher level.`
    : target.mode === "under_heading" ? `Immediately under the heading "${target.anchor}", before its existing content.`
      : target.mode === "after_block" ? `Immediately after the complete content block containing "${target.anchor}".`
        : `Replace the recorded original copy ${target.anchorKind === "heading" ? `inside the section headed "${target.anchor}"` : `in the content block containing "${target.anchor}"`}; preserve the rest of that section.`;
}
/** THE SENTENCES THAT SAY A READING IS OWED, written in ONE place (audit, 2026-09-14): proof's `unreviewed` composes them and the obligation ladder reads them, so a stale one on file (raw, or wrapped by the sweep's "did not pass the re-read" opener) is a reading to take and never a paid redraft to buy, whatever sentence the live verdict composes today. */
const REVIEW_HOLDS = { acceptance: "the exact copy, assignment and sources have no complete editor acceptance on file, so the preserved words owe a review", correction: "Beacon's own sense review has not read this correction yet, so it waits for that reading rather than for the operator to do Beacon's checking.", contract: "the reading on file was made under an older review contract, so it is read again before these words are offered", support: "nothing on file says the sources it cites actually support what it claims, so it is held until Beacon's own reviewer has read them together", component: "the words this change would put on the page have not been read against the sources they name, so it is held until Beacon's own reviewer has read them together", wording: "this looks like a wording-only change, so Beacon's reviewer must confirm the meaning genuinely moves before it is offered" } as const;
const PAGE_STATE = { capture: "the complete current page is not available to the reviewer, so no paid reading can refresh this copy safely", whole: "the page's own words have moved since this was read against the whole page, so whether the page already says what this adds is no longer known", target: "the passage this replaces is no longer the passage the page carries, so it is held until it is read against the page as it stands" } as const;
/** THE OPENERS OF THE REFUSALS THE DRAFT DOORS WRITE (audit, 2026-09-14): each door composes its sentence from these and completeness partitions a stored sentence beginning with one as a FAULT, never a caveat on a Ready row. One spelling, so a reworded refusal can never slip into the caveats. */
const REFUSAL = { place: "where it goes is", anchor: "the words it puts on the link are not in the sentence", foreign: "the page it links to is not one this account owns", unnamed: "one of its claims names no evidence", asked: "the assignment asked for", additive: "this assignment adds copy and deletes nothing", replaces: "the words it says it replaces are not on the stored page", repeats: "every line of it is already on this page", emptyMeta: "The description is empty or repeats the heading", editor: "no serious editor would hand this", operator: "an operator could not act on it as written" } as const;
export const COPY_RULES = { codeSuffix: CODE_SUFFIX, proportion: SPELLED_PROPORTION_RE, reviewHolds: REVIEW_HOLDS, reviewHold: (why: string): boolean => Object.values(REVIEW_HOLDS).some((s) => why === s || why.endsWith(`: ${s}`)), pageState: PAGE_STATE, pageStateReason: (why: string): boolean => Object.values(PAGE_STATE).some((s) => why === s || why.endsWith(`: ${s}`)),
  invalidFacts: (facts: readonly FactCheck[]): unknown[] => facts.map(f => [f.page, f.statementKey, f.subject, f.current, f.proposed, f.confidence, f.verdict, f.pageContentHash, f.rulesVersion, f.sources.map(s => [s.kind, s.url, s.says, s.support, s.readHash, s.groups, s.groupExcerpts])]).sort((a, b) => JSON.stringify(a).localeCompare(JSON.stringify(b))),
  invalidMaterial: (p: ChangeProposal, key = p.workKey ?? "", sourceHash?: string): string => { const parts = key.split("::"), at = parts.findLastIndex((part) => /^r\d/.test(part)), hashAt = parts.findIndex((part, i) => i >= 2 && i < at && /^[a-f0-9]{16}$/.test(part)), source = at > 0 ? [...parts.slice(0, at - 1).filter((_, i) => i !== hashAt || !sourceHash), parts[at]].join("::") : key, c = p.recommendedChange, stable = (v: unknown): unknown => v == null ? v : JSON.parse(JSON.stringify(v, (_k, x) => typeof x === "string" ? x.replace(/\b\d[\d,]*(?:\.\d+)?\s+(?:searches?|impressions?|clicks?|times?)\s+in\s+90\s+days\b/gi, "current demand in 90 days") : x)); return COPY_RULES.recordKey([source, sourceHash ?? null, stable(p.assignment), p.factIdentity ?? null, c.kind === "existing_edit" ? [c.field, c.before, stable(c.after), c.where, c.target, c.linkTo] : c]); },
  preservation: preservationShortfall, preservationPreflight, preservationResidue, accountWrongSubjectMeta, newMetaQuantityGap, preservationFinding: (why: string): boolean => /(?:^|: )it replaces a passage saying .*every original unit needs its own preservation disposition$/.test(why), materialLosses, renderedText, carriesUnit, flat, refusal: REFUSAL, /** THE ONE DESCRIPTION WIDTH (Stage 3, 2026-09-14): the brief, the writer's rule and the gate's ceiling each carried their own number (155, 155, 165); Google renders about this many characters before it truncates. `descriptionCeiling` is the gate's ceiling on a stored row (audit, 2026-09-15): the target is 155, and a Ready description of 156 to 165 is malformed for nothing. */ descriptionChars: 155, descriptionCeiling: 165,
  bankedEvidence: (p: SourcePacket, banked: NonNullable<ChangeProposal["supportFacts"]>, current: boolean): Pick<SourcePacket, "evidence" | "evidenceSources" | "evidenceHistory" | "evidenceFindings"> => {
    const evidence = { ...p.evidence }, sources = { ...p.evidenceSources }, findings = { ...p.evidenceFindings }, history: NonNullable<ChangeProposal["supportFacts"]>[number][] = [], reserved = new Set([...Object.keys(evidence), ...banked.map(f => f.id)]), unread = !current && !p.bodyText.trim() && !(p.title ?? "").trim() && !(p.h1 ?? "").trim() && p.headings.length === 0;
    const sourceOf = (id: string) => p.evidenceSources?.[id] ?? (/^fact-(\d+)$/.test(id) ? p.checkedSources?.[Number(id.slice(5)) - 1] : undefined), sourceKey = (quoted: NonNullable<ChangeProposal["supportFacts"]>[number]["sources"] | undefined) => JSON.stringify((quoted ?? []).map(s => JSON.stringify([s.url, s.kind])).sort());
    for (const f of banked) { const fresh = evidence[f.id], freshSources = sourceOf(f.id), owned = /^page-(?:copy|title|h1|heading)/.test(f.id), observed = !p.unpublished && (current ? carriesQuotation(f.fact, /^page-copy/.test(f.id) ? p.bodyText : /^page-title/.test(f.id) ? p.title ?? "" : /^page-h1/.test(f.id) ? p.h1 ?? "" : /^page-heading/.test(f.id) ? p.headings.join("\n") : fresh ?? "") : unread) /* a page quotation stands while the page as read now carries it; a page nobody could read this pass contradicts nothing, so the banked words are read as banked; a stale or partial page in hand cannot vouch */, matching = /^fact-/.test(f.id) && !!f.sources?.length && Object.entries(p.evidence).some(([id, text]) => /^fact-/.test(id) && renderedText(text) === renderedText(f.fact) && sourceKey(sourceOf(id)) === sourceKey(f.sources) && (!f.finding || p.evidenceFindings?.[id]?.tenantId === f.finding.tenantId && p.evidenceFindings[id]?.page === f.finding.page && p.evidenceFindings[id]?.statementKey === f.finding.statementKey)), eligible = owned ? observed : !/^draft-so-far/.test(f.id) && (/^fact-/.test(f.id) && (f.finding || f.sources?.length) ? matching : fresh == null || renderedText(fresh) === renderedText(f.fact)); /* LEGACY LINEAGE IS NOT A DEBT (audit, 2026-09-14): a checked fact banked before typed sources and findings existed carries neither, so it can never match a current finding; it is read exactly as every other banked id, replaced only where the packet holds different words under its id, and the judge still reads it against its claim. A fact that names its quoting source or its finding must match the current packet on them. */
      if (fresh != null && (renderedText(fresh) !== renderedText(f.fact) || /^fact-/.test(f.id) && sourceKey(freshSources) !== sourceKey(f.sources))) { let n = 1; while (reserved.has(`${f.id}-current-${n}`)) n++; const id = `${f.id}-current-${n}`; reserved.add(id); evidence[id] = fresh; if (freshSources) sources[id] = freshSources; if (findings[f.id]) findings[id] = findings[f.id]!; } delete sources[f.id]; delete findings[f.id]; /* THE PACKET KEEPS ITS ORDER (audit, 2026-09-14): a banked id is written in place, never deleted and re-added, or it moves to the end of the packet and the first id carrying an anchor flaps between page-title and page-h1 on every reload */
      if (eligible) { evidence[f.id] = f.fact; const quoted = f.sources?.length ? f.sources : freshSources; if (quoted) sources[f.id] = quoted; if (f.finding) findings[f.id] = f.finding; } else { delete evidence[f.id]; history.push(f); }
    } for (const [id, text] of Object.entries(evidence)) if (/^fact-/.test(id) && !banked.some(f => f.id === id) && banked.some(f => /^fact-/.test(f.id) && !history.includes(f) && evidence[f.id] === f.fact && renderedText(text) === renderedText(f.fact) && sourceKey(sources[id] ?? sourceOf(id)) === sourceKey(f.sources) && (!f.finding || findings[id]?.tenantId === f.finding.tenantId && findings[id]?.page === f.finding.page && findings[id]?.statementKey === f.finding.statementKey))) { delete evidence[id]; delete sources[id]; delete findings[id]; } return { evidence, evidenceSources: sources, evidenceFindings: findings, ...(history.length ? { evidenceHistory: history } : {}) };
  },
  briefing: /^(?:rival|competitor)[-\d]|^win(?:\d|pattern)|^serp\d/,
  bodyKinds: new Set<BundleComponentKind>(["section", "section_add", "section_rewrite", "opening_answer", "full_rewrite", "restructure", "entity_expansion", "table_or_list_add", "paragraph_correction", "factual_correction", "new_page"]),
  bodyCopy, where: publicationWhere,
  originalUnits: (before: string): string[] => before.split(/(?<=[.!?])\s+|\s*[\n\u2022|]\s*|\s+[-\u2013\u2014]\s+/u).map((u) => u.trim()).filter(Boolean), /* A UNIT IS A SENTENCE, A LINE, A BULLET OR A TABLE CELL (restored, audit 2026-09-14): the sentence segmenter never splits before a lowercase word, so a call to action after a full stop hid inside the sentence before it and no ledger entry could ever name it; list-shaped pages are rows and cells, not prose */
  preservationKey: (ledger: NonNullable<ChangeProposal["preservation"]>) => ledger.map((u) => u.of ? [u.text, u.disposition, u.why ?? null, u.to ?? null, u.basis ?? null, [...u.by ?? []].sort(), u.of] : u),
  destinations: (ledger: readonly { to?: string }[], publication: readonly BundleComponent[]) => publication.map((part, i) => ({ part, id: componentIdOf(part, i) })).filter(({ part, id }) => ledger.some((u) => u.to && [id, part.target?.anchor, part.where].includes(u.to))),
  preservationOwners: (ledger: NonNullable<ChangeProposal["preservation"]>, parts: readonly BundleComponent[], all: readonly BundleComponent[] = parts): NonNullable<ChangeProposal["preservation"]> => ledger.map((u) => {
    const owners = parts.filter((part) => COPY_RULES.originalUnits(part.before ?? "").some((text) => renderedText(text) === renderedText(u.text)) && (!u.of || componentIdOf(part, all.indexOf(part)) === u.of));
    if (owners.length !== 1) throw new Error("The banked preservation record needs one exact original-component owner before any review can be bought; all copy is preserved."); return u.of ? u : { ...u, of: componentIdOf(owners[0]!, all.indexOf(owners[0]!)) };
  }),
  joinedEditor: (entries: readonly { editor?: NonNullable<ChangeProposal["semanticReview"]>["editor"]; of?: string; remap?: (by: readonly string[]) => string[] }[]): NonNullable<ChangeProposal["semanticReview"]>["editor"] => entries.length && entries.every((e) => COPY_RULES.accepted(e.editor)) ? { ...entries[0]!.editor!, usefulAndNatural: entries.every((e) => e.editor!.usefulAndNatural), notes: entries.map((e) => e.editor!.notes).join(" ").slice(0, 300), preservation: entries.flatMap((e) => (e.editor!.preservation ?? []).map((r) => ({ ...r, by: e.remap ? e.remap(r.by) : [...r.by], ...(e.of ? { of: e.of } : {}) }))) } : undefined,
  recordKey: (record: unknown): string => JSON.stringify(record, (_key, value: unknown) => value && typeof value === "object" && !Array.isArray(value) ? Object.fromEntries(Object.entries(value).sort(([a], [b]) => a < b ? -1 : a > b ? 1 : 0)) : value),
  newPageSourceBound: (bank: NonNullable<ChangeProposal["newPageDraft"]>): boolean => bank.brief.kind === "new_page" && typeof bank.brief.identity === "string" && typeof bank.brief.material === "string" && typeof bank.brief.patternFingerprint === "string" && Array.isArray(bank.brief.sourceIndex) && bank.brief.sourceIndex.length > 0,
  newPagePieces: (bank: NonNullable<ChangeProposal["newPageDraft"]>): Map<number, typeof bank.pieces[number]> | null => {
    const sections = bank.brief.sections; if (!Array.isArray(sections) || sections.some(s => !s || typeof s.heading !== "string" || !s.heading.trim())) return null;
    const heads = sections.map(s => renderedText(s.heading).toLowerCase()), made = new Map<number, typeof bank.pieces[number]>();
    if (bank.brief.identity != null) { try { const identity = JSON.parse(String(bank.brief.identity)); if (!Array.isArray(identity) || identity.length !== 5 || COPY_RULES.recordKey(identity[4]) !== COPY_RULES.recordKey(sections)) return null; } catch { return null; } }
    for (const [n, piece] of bank.pieces.entries()) { const heading = renderedText(piece.heading ?? "").toLowerCase(), matches = heads.flatMap((h, i) => h === heading ? [i + 1] : []), slot = piece.slot ?? (n === 0 && !matches.length && (!heading || heading === renderedText(String(bank.brief.proposedTitle ?? "")).toLowerCase()) ? 0 : matches.length === 1 ? matches[0] : undefined);
      if (slot == null || !Number.isInteger(slot) || slot < 0 || slot > sections.length || made.has(slot) || slot > 0 && heading !== heads[slot - 1] || slot === 0 && heading && heading !== renderedText(String(bank.brief.proposedTitle ?? "")).toLowerCase()) return null; made.set(slot, piece.slot == null ? { ...piece, slot } : piece);
    } return made;
  },
  pieceDebt: (p: ChangeProposal): number | null | undefined => { const bank = p.newPageDraft; if (p.kind !== "existing_edit" || !bank || !["full_rewrite", "body_meta"].includes(String(bank.brief.kind))) return undefined; const { headings, identity, owed } = bank.brief, compound = bank.brief.kind === "body_meta"; if (typeof identity !== "string" || !/^[a-f0-9]{64}$/.test(identity) || !compound && (!Array.isArray(headings) || !headings.length || headings.some((h) => typeof h !== "string" || !h.trim())) || !Array.isArray(owed)) return null; const slots = compound ? [0, 1] : [0, ...(headings as string[]).map((_, i) => i + 1)], done = bank.pieces.map((piece) => piece.slot); if (new Set(done).size !== done.length || done.some((slot) => slot == null || !slots.includes(slot)) || bank.pieces.some((piece) => (piece.slot !== 1 || !compound) && (!piece.units?.length || piece.after !== bodyCopy(piece.units)) || compound && (!piece.assignment || !piece.claims.length || piece.claims.some(claim => claim.supportedBy.some(id => piece.supportFacts.filter(fact => fact.id === id).length !== 1)) || COPY_RULES.accepted(piece.editor) && (piece.reviewOf !== COPY_RULES.pieceKey(piece) || piece.review.length !== piece.claims.length || piece.claims.some((claim, i) => !COPY_RULES.ruling(claim, piece.review, i))) || !COPY_RULES.accepted(piece.editor) && (piece.editor != null || piece.reviewOf != null || piece.review.length > 0)))) return null; const missing = slots.filter((slot) => !done.includes(slot)); return JSON.stringify(owed) === JSON.stringify(missing) ? missing.length : null; },
  reviewParts: (p: ChangeProposal): BundleComponent[] => (p.bundle?.components ?? []).filter((part) => p.recommendedChange.kind === "new_page" ? /^(opening_answer|section|section_add|section_rewrite)$/.test(part.kind) : /^(opening_answer|answer_block|section|section_add|section_rewrite|full_rewrite|restructure|table_or_list_add|paragraph_correction|factual_correction|entity_expansion|source_update|internal_link_add|internal_links|title|h1|meta)$/.test(part.kind)),
  reviewProgress: (p: ChangeProposal): number[] => COPY_RULES.reviewParts(p).flatMap((part) => { const id = componentIdOf(part, p.bundle!.components.indexOf(part)), indices = (p.claims ?? []).map((claim, i) => ({ claim, i })).filter((x) => x.claim.of === id); return indices.length && indices.every(({ claim, i }) => COPY_RULES.ruling(claim, p.semanticReview?.claims ?? [], i) != null) ? indices.map((x) => x.i) : []; }).sort((a, b) => a - b),
  reviewSubjects: (p: ChangeProposal, requireClaims = true): { row: ChangeProposal; subjects: { indices: { claim: NonNullable<ChangeProposal["claims"]>[number]; n: number }[]; one: ChangeProposal; pendingBody?: string }[] } => {
    const parts = COPY_RULES.reviewParts(p), all = p.bundle?.components ?? [], url = (p.pageUrl ?? p.pagePath ?? "").trim(), ids = parts.map((part) => componentIdOf(part, all.indexOf(part))), claims = (p.claims ?? []).map((claim) => { if (ids.includes(claim.of ?? "")) return claim; const owners = parts.filter((part) => claim.text.trim() && part.after.includes(claim.text.trim())); return owners.length === 1 ? { ...claim, of: ids[parts.indexOf(owners[0]!)] } : claim; }), preservation = COPY_RULES.preservationOwners(p.preservation ?? [], parts, all), row = claims.some((claim, i) => claim.of !== p.claims![i]!.of) || preservation.some((u, i) => u !== p.preservation![i]) ? { ...p, claims, ...(preservation.length ? { preservation } : {}) } : p;
    const mapped = parts.map((_, i) => claims.map((claim, n) => ({ claim, n })).filter((x) => x.claim.of === ids[i])); if (requireClaims && mapped.some((indices) => !indices.length) || new Set(mapped.flatMap((indices) => indices.map((x) => x.n))).size !== claims.length) throw new Error("The banked copy is preserved, but a publication component lacks its own claim mapping; reconstruct that record before buying any review.");
    try { return { row, subjects: parts.map((part, i) => { const pageUrl = part.page ? new URL(part.page, url).toString() : url, field = fieldForComponent(part.kind), indices = mapped[i]!, local = indices.map(({ claim }) => ({ text: claim.text, supportedBy: [...claim.supportedBy] })), preservation = (row.preservation ?? []).filter((record) => record.of === ids[i]).map(({ of: _owner, ...record }) => record), used = new Set([...local.flatMap((claim) => claim.supportedBy), ...preservation.flatMap((record) => record.by ?? [])]); if (!/^https?:$/.test(new URL(pageUrl).protocol)) throw new Error("invalid publication address"); const one: ChangeProposal = { ...row, kind: "existing_edit", pageUrl, pagePath: new URL(pageUrl).pathname.replace(/\/+$/, "") || "/", bundle: undefined, semanticReview: undefined, ...(part.kind === "full_rewrite" ? { changeFamily: "full_rewrite", preservationNotes: part.preserves ?? row.preservationNotes } : {}), claims: local, preservation, supportFacts: (row.supportFacts ?? []).filter((fact) => used.has(fact.id)), recommendedChange: { kind: "existing_edit", field, before: part.before, after: part.after, units: part.units, target: part.target, where: part.where, ...(/^(internal_link_add|internal_links)$/.test(part.kind) ? { linkTo: part.redirectTo, anchorText: part.anchorAfter } : {}) }, ...(row.assignment ? { assignment: { ...row.assignment, page: pageUrl, ...(/^(title|h1|meta)$/.test(field) ? { standard: "summary", treatment: "field", shape: undefined } : {}) } } : {}) }, opening = parts.find((x) => x.kind === "opening_answer" && canonicalUrlKey(x.page ? new URL(x.page, url).toString() : url) === canonicalUrlKey(pageUrl)); return { indices, one, ...(part.kind === "meta" && opening ? { pendingBody: opening.after } : {}) }; }) }; } catch { throw new Error("Every component needs a valid publication address before any review can be bought; all banked copy is preserved."); }
  },
  ruling: (claim: { supportedBy: readonly string[] }, rulings: NonNullable<ChangeProposal["semanticReview"]>["claims"] | undefined, i: number) => { const matches = rulings?.filter((r) => r.i === i) ?? [], r = matches[0]; return matches.length === 1 && r?.entailed && r.by.length > 0 && r.by.every((id) => claim.supportedBy.includes(id)) ? r : undefined; },
  target: (anchor: string, headings: readonly string[], operation: "opening" | "replace" | "answer" | "add"): NonNullable<BundleComponent["target"]> => {
    if (operation === "opening") return { mode: "opening", anchorKind: null, anchor: null };
    const anchorKind = headings.some((h) => h.trim() === anchor.trim()) ? "heading" : "passage";
    return { mode: operation === "replace" ? "replace" : anchorKind === "passage" ? "after_block" : operation === "answer" ? "under_heading" : "after_section", anchorKind, anchor };
  },
  publication: (piece: { after: string; units?: BundleComponent["units"]; target?: BundleComponent["target"] }, heading?: string | null): Pick<BundleComponent, "after" | "units" | "target" | "where"> => {
    const placement = piece.target ? { target: piece.target, where: publicationWhere(piece.target) } : {};
    if (!piece.units) return { after: heading ? `${heading}\n\n${piece.after}` : piece.after, ...placement };
    const first = piece.units[0], units: NonNullable<BundleComponent["units"]> = heading && !(first?.kind === "heading" && first.level === 2 && first.text === heading)
      ? [{ kind: "heading", level: 2, text: heading }, ...piece.units] : piece.units;
    return { units, after: bodyCopy(units), ...placement };
  },
  publisher: "PUBLISHER ROLE: publication copy speaks for the owning site to its reader, not as an outside reviewer of that site. State the subject's supported information directly. Attribute genuine external evidence when its identity and words support the claim; do not cite the owning page or publisher as an independent authority for its own copy. Do not invent first-hand experience, tests or credentials. Decide meaning in context: territorial divisions, scientific grouping and practical sorting can explain the subject; descriptions of how an article groups its material explain the container. Summary and repositioning work may honestly describe supported coverage. Body work otherwise delivers the answer, not a tour of page furniture. NEVER WRITE these shapes, each of which is refused by a fixed rule before any editor reads it: 'this page', 'this guide', 'this timeline', 'our site'; 'the page groups / lists / covers / names / shows'; 'X here means', 'X here are', 'here runs'; 'is covered by', 'shows the flag for', 'the matching page'; a definition whose right side repeats its left ('an Iranian singer means an Iranian singer'); a sentence that repeats the passage it lands under; and in a description or title, any word about search, searchers, readers looking, or the description itself. Keep assignment instructions, evidence commentary and AI self-talk out of publication content. Such role failures make wouldHandToCustomer false, not merely a style caveat. Useful form and depth follow the reader task, never a verb ban or sentence quota.",
  supersededEditorFinding: (why: string): boolean => /(?:^|: )(?:it points at the page instead of answering|it talks about the page instead of teaching the reader, so it is rewritten under the entity-first brief|it only re-says what the page already says, so it is rewritten under the entity-first brief to add specifics|it opens by restating what the page already says: lead with the checked fact this section exists to add, and keep the page's own material behind it|most of what it says is already on the page: this is the page's own material with a fact attached, not a section that adds one)$/.test(why),
  pageEvidence: (passages: readonly string[], selected: string, budget: number, faq?: { query: string; pairs: OwnedPageBody["faqs"] }): { evidence: Record<string, string>; truncated: boolean } => {
    const evidence: Record<string, string> = {}, normalize = (t: string): string => t.replace(/\s+/g, " ").trim(); let room = budget, n = 0, truncated = false;
    const question = (t: string): string => normalize(t).toLowerCase().replace(/[?？]+$/, ""), pair = faq?.pairs?.find((f) => f.answerComplete === true && question(f.question) === question(faq.query));
    const answer = pair ? `${pair.question}\n${pair.answer}` : ""; if (answer.length > budget || passages.join(" ").length > budget && selected.length > budget) truncated = true;
    const held = answer && answer.length <= budget ? answer : passages.join(" ").length > budget && selected.length <= budget ? selected : "";
    if (held) { evidence[`page-copy-${++n}`] = held; room -= held.length; truncated ||= held !== answer; }
    for (const t of passages) { if (held && normalize(held).includes(normalize(t))) continue; if (room < t.length) { truncated = true; continue; } evidence[`page-copy-${++n}`] = t; room -= t.length; }
    return { evidence, truncated };
  },
  packet: (p: SourcePacket): string => { // THE PAGE IS SENT ONCE (audit, 2026-09-14): page.body carried the whole page, page-copy-N carried it again as the citable index and the assignment rode both in the assignment lines and here, so a body call was 50,000 plus characters and the judge repeated it. The page-copy ids stay the citable index, page.body holds only the passages no id covers, and the assignment lives in its lines alone; the judge reads this same packet.
    const norm = (t: string): string => t.replace(/\s+/g, " ").trim(), copies = Object.entries(p.evidence).filter(([id]) => /^page-copy-/.test(id)).map(([, t]) => norm(t)), rest = p.bodyText.split(/\n+/).map(norm).filter((t) => t && !copies.some((c) => c.includes(t))).join("\n");
    return JSON.stringify({ history: p.evidenceHistory?.map(f => ({ id: f.id, text: f.fact, sources: f.sources ?? [], role: "historical_not_claim_support" })), targeting: p.demand, companion: p.pendingBody ? { ...p.pendingBody, role: "draft_not_claim_support" } : undefined, comparison: p.comparison ? { queries: p.comparison.queries, focus: p.comparison.focus, verdict: p.comparison.verdict, owned: p.comparison.owned ? { url: p.comparison.owned.url, bodyKey: p.comparison.owned.bodyKey, heldWhole: p.comparison.owned.heldWhole && sanitizeNullableEvidence(p.comparison.owned.held) === p.comparison.owned.held } : undefined, winners: p.comparison.winners.map((w, i) => { const held = sanitizeNullableEvidence(w.held) ?? ""; return { ...w, held, heldWhole: w.heldWhole && held === w.held, id: `rival-${i + 1}`, role: "research_not_claim_support" }; }) } : undefined, page: { url: p.targetUrl, title: p.title, h1: p.h1, meta: p.metaDescription, headings: p.headings, body: rest.slice(0, 24000), ...(copies.length ? { bodyIndex: "the page-copy ids under evidence hold the rest of this page in document order" } : {}), partial: !!p.truncated || rest.length > 24000, unpublished: !!p.unpublished }, evidence: Object.entries(p.evidence).map(([id, text]) => ({ id, text, role: /^(?:rival|serp|case)-/.test(id) ? "research_not_claim_support" : /^draft-so-far/.test(id) || p.unpublished && /^page-/.test(id) ? "draft_not_claim_support" : /^(?:fact-|page-|owned-page)/.test(id) ? "claim_support" : "context_not_claim_support", sources: p.evidenceSources?.[id] ?? (/^fact-(\d+)$/.test(id) ? p.checkedSources?.[Number(id.slice(5)) - 1] ?? [] : []) })) }); },
  grounding: (p: SourcePacket): string => Object.entries(p.evidence).filter(([id]) => /^(?:fact-|page-|owned-page)/.test(id) && !(p.unpublished && /^page-/.test(id))).map(([, text]) => text).join("\n"),
  pieceKey: (p: Pick<NonNullable<ChangeProposal["newPageDraft"]>["pieces"][number], "heading" | "after" | "units" | "claims" | "supportFacts"> & Partial<Pick<NonNullable<ChangeProposal["newPageDraft"]>["pieces"][number], "before" | "preservation" | "gain" | "assignment" | "draftNotes">> & { target?: BundleComponent["target"] }): string => JSON.stringify([p.heading, p.after, p.claims, p.supportFacts, ...(p.units ? [p.units] : []), ...(p.target ? [p.target] : []), ...(p.before != null ? [["predecessor", p.before]] : []), ...(p.preservation?.length ? [["preservation", COPY_RULES.preservationKey(p.preservation)]] : []), ...(p.gain ? [["gain", p.gain]] : []), ...(p.draftNotes?.length ? [["draft_notes", p.draftNotes]] : []), ...(p.assignment ? [["assignment", COPY_RULES.recordKey(p.assignment)]] : [])]),
  accepted: (e: NonNullable<ChangeProposal["semanticReview"]>["editor"]): boolean => !!e && e.contested !== true && [e.pageFit, e.placementCorrect, e.resolvesDiagnosis, e.implementableNow, e.improvesPage, e.wouldHandToCustomer].every((x) => x === true),
  workflow: /\b(?:a clear answer should|this (?:draft|copy)|the copy below|(?:this|the) (?:page|section|answer) (?:should|will|needs to)|update the section|sharpen it for|stored copy|source packet|supportedBy|claim ids|grounding packet|in the evidence)\b|\b(?:as an AI|(?:I|we)(?:'ll| will| need to| should| can) (?:draft|write|rewrite|revise|update|generate|provide|return)|return (?:the )?JSON|(?:add|insert|replace|rewrite|update|draft|write) (?:this|the|an?|a new) (?:section|paragraph|heading|answer block|meta description|copy))\b/im };
