import { load } from "cheerio";
import { topicTokens } from "@/domains/evidence/relevance-gate";
import { isCurrent } from "@/domains/evidence/freshness";
import type { OwnedPageBody } from "@/domains/evidence/pages/owned-context";
import type { ChangeProposal } from "./contracts";
import { COPY_RULES } from "./copy-sanitize";

const absolute = (url: string): string => /^https?:\/\//i.test(url) ? url : `https://${url}`;
const sameAddress = (left: string, right: string | null | undefined): boolean => { try { if (!right) return false; const a = new URL(absolute(left)), b = new URL(absolute(right)); return a.protocol === b.protocol && a.hostname.replace(/^www\./, "") === b.hostname.replace(/^www\./, "") && a.port === b.port && a.pathname === b.pathname && a.search === b.search; } catch { return false; } };
const sourceCurrent = (body: OwnedPageBody | null | undefined, url: string, now: Date): body is OwnedPageBody => !!body?.pageId && !!body.contentHash && !!body.captureId && body.captureId === body.latestCaptureId && body.version === "current" && body.completeness === "complete" && body.sourceCapture?.complete === true && isCurrent("owned_page", body.fetchedAt, now.getTime()) && sameAddress(url, body.url) && sameAddress(url, body.finalUrl);
export const articlePassages = (body: OwnedPageBody | null | undefined): string[] => {
  if (!body) return [];
  const $ = load(body.sourceCapture?.mainHtml ?? ""), clean = (s: string) => s.replace(/\s+/g, " ").trim(), named = new Set([body.h1, body.title, ...body.headings].filter(Boolean).map(s => clean(s!).toLowerCase()));
  const blocks = $("p,li,blockquote,div.wixui-rich-text").toArray().filter(node => ![node, ...$(node).parents().toArray()].some(parent => /product|merch|shop|related|repeater|card/i.test($(parent).attr("class") ?? ""))).map(node => clean($(node).text())).filter(text => text.length >= 35);
  return body.passages.flatMap((text, i) => { const part = body.passageMeta?.[i], heading = clean(part?.heading ?? ""); return !!part && !part.id.endsWith("#0") && named.has(heading.toLowerCase()) && !/product|shop|hoodie|t-shirt|mug|sticker|related/i.test(heading) ? blocks.filter(block => clean(text).includes(block) && !body.cardTexts.some(card => clean(card).includes(block))) : []; });
};
const exactBlock = (self: OwnedPageBody | null, anchor: string | null | undefined): string | null => { if (!self?.sourceCapture?.complete || self.completeness !== "complete" || self.version !== "current" || !anchor) return null; const $ = load(self.sourceCapture.mainHtml), clean = (s: string) => s.replace(/\s+/g, " ").trim(), needle = clean(anchor), content = (node: Parameters<typeof $>[0]) => clean($(node).text()), hits = $("p,li,blockquote,div.wixui-rich-text").toArray().filter(node => content(node).includes(needle) && !$(node).find("p,li,blockquote,div.wixui-rich-text").toArray().some(child => content(child).includes(needle))); return hits.length === 1 && content(hits[0]!).split(needle).length === 2 ? content(hits[0]!) : null; };
const targetFacts = (target: OwnedPageBody | null | undefined, sourceUrl: string, linkTo: string | null | undefined): Record<string, string> | null => { try { const url = new URL(linkTo ?? "", absolute(sourceUrl)).toString(); if (!linkTo || !target || target.version !== "current" || target.completeness !== "complete" || target.sourceCapture?.complete !== true || !sameAddress(url, target.url) || !sameAddress(url, target.finalUrl)) return null; const names = new Set(topicTokens(`${target.title ?? ""} ${target.h1 ?? ""}`)), seen = new Set<string>(); return Object.fromEntries(articlePassages(target).flatMap((p) => p.split(/(?<=[.!?])\s+/)).map((s) => s.replace(/\s+/g, " ").trim()).filter((s) => { const key = s.toLowerCase(); if (seen.has(key)) return false; seen.add(key); return s.length >= 35 && s.length <= 450 && topicTokens(s).filter((w) => !names.has(w)).length >= 2; }).map((s, i) => [`owned-page-target-copy-${i + 1}`, `${linkTo} says: ${s}`])); } catch { return null; } };
const linkState = (body: OwnedPageBody, paragraph: string, phrase: string, to: string): "none" | "exact" | "other" => { try { const $ = load(body.sourceCapture!.mainHtml), clean = (s: string) => s.replace(/\s+/g, " ").trim(), blocks = $("p,li,blockquote,div.wixui-rich-text").toArray().filter(node => clean($(node).text()) === paragraph && !$(node).find("p,li,blockquote,div.wixui-rich-text").toArray().some(child => clean($(child).text()) === paragraph)); if (blocks.length !== 1) return "other"; const links = $(blocks[0]!).find("a[href]").toArray(); return links.length === 0 ? "none" : links.length === 1 && clean($(links[0]!).text()) === phrase && sameAddress(new URL($(links[0]!).attr("href")!, body.url).toString(), new URL(to, body.url).toString()) ? "exact" : "other"; } catch { return "other"; } };
function proposal(card: ChangeProposal, source: OwnedPageBody | null | undefined, target: OwnedPageBody | null | undefined, now: Date): ChangeProposal | null {
  const to = card.recommendedChange.kind === "existing_edit" ? card.recommendedChange.linkTo : null, url = card.pageUrl ?? "", facts = targetFacts(target, url, to); if (!to || !sourceCurrent(source, url, now) || !target || !facts || !sourceCurrent(target, new URL(to, absolute(url)).toString(), now)) return null;
  const targetWords = new Set(topicTokens(`${target.title} ${target.h1} ${articlePassages(target).join(" ")}`)), titleWords = new Set(topicTokens(`${target.title} ${target.h1}`));
  if (card.recommendedChange.kind === "existing_edit" && card.recommendedChange.linkMode === "in_place") { const c = card.recommendedChange, phrase = c.anchorText ?? "", paragraph = c.before ?? "", own = card.supportFacts?.find(f => f.id === "page-copy-in-place" && f.fact === paragraph), dest = card.supportFacts?.find(f => facts[f.id] === f.fact && topicTokens(phrase).every(w => topicTokens(f.fact).includes(w))); return source.contentHash === c.linkSourceHash && articlePassages(source).some(p => p.includes(paragraph)) && exactBlock(source, phrase) === paragraph && c.after === paragraph && c.units?.length === 1 && c.units[0]?.kind === "paragraph" && c.units[0].text === paragraph && c.target?.mode === "replace" && c.target.anchorKind === "passage" && c.target.anchor === paragraph && linkState(source, paragraph, phrase, to) !== "other" && !!own && !!dest && card.claims?.some(claim => claim.text === phrase && claim.supportedBy.includes(own.id) && claim.supportedBy.includes(dest.id)) ? card : null; }
  const $ = load(source.sourceCapture!.mainHtml), clean = (s: string) => s.replace(/\s+/g, " ").trim(), sourceArticle = articlePassages(source), blocks = $("p,li,blockquote,div.wixui-rich-text").toArray().filter(node => !$(node).find("p,li,blockquote,div.wixui-rich-text").length && !$(node).find("a[href]").length && sourceArticle.some(p => p.includes(clean($(node).text()))));
  const options: { phrase: string; paragraph: string; score: number }[] = [];
  for (const node of blocks) { const paragraph = clean($(node).text()), tokens = [...paragraph.matchAll(/[\p{L}\p{N}]+(?:[-’'][\p{L}\p{N}]+)*/gu)]; for (let i = 0; i < tokens.length; i++) for (let n = 2; n <= 5 && i + n <= tokens.length; n++) { const phrase = paragraph.slice(tokens[i]!.index!, tokens[i + n - 1]!.index! + tokens[i + n - 1]![0].length), terms = topicTokens(phrase); if (terms.length < 2 || !topicTokens(tokens[i]![0]).length || !topicTokens(tokens[i + n - 1]![0]).length || !/^[\p{L}\p{N}’' -]+$/u.test(phrase) || !terms.every(w => targetWords.has(w)) || !terms.some(w => titleWords.has(w)) || source.vocabulary.split(phrase).length !== 2 || !Object.values(facts).some(f => terms.every(w => topicTokens(f).includes(w)))) continue; options.push({ phrase, paragraph, score: terms.length }); } }
  options.sort((a, b) => b.score - a.score || b.phrase.length - a.phrase.length); const { phrase, paragraph } = options[0] ?? {}; if (!phrase || !paragraph || exactBlock(source, phrase) !== paragraph || options.some(o => o !== options[0] && o.score === options[0]!.score && o.phrase !== phrase && !phrase.includes(o.phrase))) return null;
  const other = Object.entries(facts).find(([, fact]) => topicTokens(phrase).every(w => topicTokens(fact).includes(w)))!;
  const place = { mode: "replace" as const, anchorKind: "passage" as const, anchor: paragraph }, edit = { kind: "existing_edit" as const, field: "section" as const, before: paragraph, after: paragraph, units: [{ kind: "paragraph" as const, text: paragraph }], target: place, linkTo: to, anchorText: phrase, linkMode: "in_place" as const, linkSourceHash: source.contentHash!, where: COPY_RULES.where(place) };
  return { ...card, status: "ready", researchOnly: false, research: undefined, obligation: undefined, assignment: undefined, semanticReview: undefined, informationGain: undefined, bundle: undefined, faults: [], limitations: [], estimatedEffortMinutes: 3, recommendedChange: edit, claims: [{ text: phrase, supportedBy: ["page-copy-in-place", other[0]] }], supportFacts: [{ id: "page-copy-in-place", fact: paragraph }, { id: other[0], fact: other[1] }], operatorSteps: [`Open the site editor on ${card.pagePath}`, `Find the exact paragraph shown under Now and select only "${phrase}"`, `Link those existing words to ${to}; leave the paragraph's wording and all other content untouched`, "Mark implemented after the exact anchor and destination are live"] };
}
const reason = (p: ChangeProposal, source: OwnedPageBody | null, target: OwnedPageBody | null): string | null => proposal(p, source, target, new Date()) ? null : "The exact current paragraph, phrase, destination or source support has moved; recapture it before offering this link.";
const LINK_PLACEMENT = { exactBlock, targetFacts, proposal, reason }; export default LINK_PLACEMENT;
