import { load } from "cheerio";
import { topicTokens } from "@/domains/evidence/relevance-gate";
import { isCurrent } from "@/domains/evidence/freshness";
import type { OwnedPageBody } from "@/domains/evidence/pages/owned-context";
import type { ChangeProposal } from "./contracts";
import { COPY_RULES } from "./copy-sanitize";

const absolute = (url: string): string => /^https?:\/\//i.test(url) ? url : `https://${url}`;
const sameAddress = (left: string, right: string | null | undefined): boolean => { try { if (!right) return false; const a = new URL(absolute(left)), b = new URL(absolute(right)); return a.protocol === b.protocol && a.hostname.replace(/^www\./, "") === b.hostname.replace(/^www\./, "") && a.port === b.port && a.pathname === b.pathname && a.search === b.search; } catch { return false; } };
const sourceCurrent = (body: OwnedPageBody | null | undefined, url: string, now: Date): body is OwnedPageBody => !!body?.pageId && !!body.contentHash && !!body.captureId && body.captureId === body.latestCaptureId && body.version === "current" && body.completeness === "complete" && body.sourceCapture?.complete === true && isCurrent("owned_page", body.fetchedAt, now.getTime()) && sameAddress(url, body.url) && sameAddress(url, body.finalUrl);
export const articlePassages = (body: OwnedPageBody | null | undefined): string[] => {
  if (!body) return [];
  const $ = load(body.sourceCapture?.mainHtml ?? ""), clean = (s: string) => s.replace(/\s+/g, " ").trim(), named = new Set([body.h1, body.title, ...body.headings].filter(Boolean).map(s => clean(s!).toLowerCase()));
  const blocks = $("p,li,blockquote,div.wixui-rich-text").toArray().filter(node => ![node, ...$(node).parents().toArray()].some(parent => /product|merch|shop|related|repeater|card/i.test($(parent).attr("class") ?? ""))).map(node => clean($(node).text())).filter(text => text.length >= 35);
  return body.passages.flatMap((text, i) => { const part = body.passageMeta?.[i], heading = clean(part?.heading ?? ""); return !!part && !part.id.endsWith("#0") && named.has(heading.toLowerCase()) && !/product|shop|hoodie|t-shirt|mug|sticker|related/i.test(heading) ? blocks.filter(block => clean(text).includes(block) && !body.cardTexts.some(card => clean(card).includes(block))) : []; });
};
const exactBlock = (self: OwnedPageBody | null, anchor: string | null | undefined): string | null => { if (!self?.sourceCapture?.complete || typeof self.sourceCapture.mainHtml !== "string" || !self.sourceCapture.mainHtml.trim() || self.completeness !== "complete" || self.version !== "current" || !anchor) return null; const $ = load(self.sourceCapture.mainHtml), clean = (s: string) => s.replace(/\s+/g, " ").trim(), needle = clean(anchor), content = (node: Parameters<typeof $>[0]) => clean($(node).text()), hits = $("p,li,blockquote,div.wixui-rich-text").toArray().filter(node => content(node).includes(needle) && !$(node).find("p,li,blockquote,div.wixui-rich-text").toArray().some(child => content(child).includes(needle))); return hits.length === 1 && content(hits[0]!).split(needle).length === 2 ? content(hits[0]!) : null; };
const targetFacts = (target: OwnedPageBody | null | undefined, sourceUrl: string, linkTo: string | null | undefined): Record<string, string> | null => { try { const url = new URL(linkTo ?? "", absolute(sourceUrl)).toString(); if (!linkTo || !target || target.version !== "current" || target.completeness !== "complete" || target.sourceCapture?.complete !== true || !sameAddress(url, target.url) || !sameAddress(url, target.finalUrl)) return null; const names = new Set(topicTokens(`${target.title ?? ""} ${target.h1 ?? ""}`)), seen = new Set<string>(); return Object.fromEntries(articlePassages(target).flatMap((p) => p.split(/(?<=[.!?])\s+/)).map((s) => s.replace(/\s+/g, " ").trim()).filter((s) => { const key = s.toLowerCase(); if (seen.has(key)) return false; seen.add(key); return s.length >= 35 && s.length <= 450 && topicTokens(s).filter((w) => !names.has(w)).length >= 2; }).map((s, i) => [`owned-page-target-copy-${i + 1}`, `${linkTo} says: ${s}`])); } catch { return null; } };
const linkState = (body: OwnedPageBody, paragraph: string, phrase: string, to: string): "none" | "exact" | "other" => { try { const $ = load(body.sourceCapture!.mainHtml), clean = (s: string) => s.replace(/\s+/g, " ").trim(), blocks = $("p,li,blockquote,div.wixui-rich-text").toArray().filter(node => clean($(node).text()) === paragraph && !$(node).find("p,li,blockquote,div.wixui-rich-text").toArray().some(child => clean($(child).text()) === paragraph)); if (blocks.length !== 1) return "other"; const links = $(blocks[0]!).find("a[href]").toArray(); return links.length === 0 ? "none" : links.length === 1 && clean($(links[0]!).text()) === phrase && sameAddress(new URL($(links[0]!).attr("href")!, body.url).toString(), new URL(to, body.url).toString()) ? "exact" : "other"; } catch { return "other"; } };
function mutationPreservation(card: ChangeProposal, source: OwnedPageBody, paragraph: string, fresh: boolean): ChangeProposal | null {
  if (!fresh && !COPY_RULES.preservationPreflight(card)) return card;
  const prior = card.preservation ?? []; if (prior.some(u => u.disposition !== "kept" || u.of || u.to || !exactBlock(source, u.text))) return null;
  const history = prior.length || card.preservationNotes ? [`Historical predecessor contract before exact in-place link ownership (does not authorize this mutation): ${COPY_RULES.recordKey({ preservation: prior, preservationNotes: card.preservationNotes ?? null, supportFacts: card.supportFacts ?? [], semanticReview: card.semanticReview ?? null })}`] : [];
  return { ...card, preservation: COPY_RULES.originalUnits(paragraph).map(text => ({ text, disposition: "kept", why: "The in-place link changes no paragraph wording.", basis: "owner_confirmed", by: ["page-copy-in-place"] })), preservationNotes: undefined, draftNotes: [...new Set([...(card.draftNotes ?? []), ...history])], ...(!fresh ? { status: "needs_review" as const, obligation: { kind: "review" as const }, limitations: [...new Set([...card.limitations, COPY_RULES.reviewHolds.capture])] } : {}) };
}
function proposal(card: ChangeProposal, source: OwnedPageBody | null | undefined, target: OwnedPageBody | null | undefined, now: Date): ChangeProposal | null {
  const to = card.recommendedChange.kind === "existing_edit" ? card.recommendedChange.linkTo : null, url = card.pageUrl ?? "", facts = targetFacts(target, url, to); if (!to || !sourceCurrent(source, url, now) || !target || !facts || !sourceCurrent(target, new URL(to, absolute(url)).toString(), now) || source.tenantId !== card.tenantId || target.tenantId !== card.tenantId || !COPY_RULES.captureProof(source, now.getTime()).length || !COPY_RULES.captureProof(target, now.getTime()).length) return null;
  const identity = (text: string): string => { const dated = text.trim(), tail = /\s(?:\||::|[–—-])\s(.+)$/.exec(dated), compact = (s: string) => s.toLowerCase().replace(/[^a-z0-9]/g, ""); return tail && new URL(absolute(target.url)).hostname.replace(/^www\./, "").split(".").slice(0, -1).map(compact).includes(compact(tail[1]!)) ? dated.slice(0, tail.index).trim() : dated; };
  const periods = /\(\s*(?:\d{4}|\d{1,4}\s*(?:BCE|BC|CE|AD)|\d{1,4}\s*[–—-]\s*(?:\d{1,4}|present|current)(?:\s*(?:BCE|BC|CE|AD))?)(?:\s*[–—-]\s*(?:\d{1,4}|present|current)(?:\s*(?:BCE|BC|CE|AD))?)?\s*\)/gi, base = (s: string): string => identity(s).replace(periods, "").trim();
  const label = base(target.h1 || target.title || ""), subject = topicTokens.semanticAtoms(label), titleWords = new Set(topicTokens.semanticAtoms(target.title || target.h1));
  const aliasesOf = (fact: string): string[] => { const reading = fact.slice(fact.indexOf(" says: ") + 7), alias = reading.match(/^(.*?)\s+(?:is|are|was|were)\s+(?:(?:historically|also|commonly|widely)\s+)?(?:known as|called|named)\s+(.+)$/i), name = alias && topicTokens.sameQuery(base(alias[1]!), label) ? alias[2]!.split(/[;,.!?]|\b(?:which|that|while|whereas|although|but)\b/i)[0]!.trim() : ""; return name ? [name.replace(/\s*\([^)]*\)\s*/g, " ").trim(), ...[...name.matchAll(/\(([^)]*)\)/g)].map(m => m[1]!)].filter(Boolean) : []; };
  const contains = (text: string, words: readonly string[]): boolean => !!words.length && (" " + topicTokens.semanticAtoms(text).join(" ") + " ").includes(" " + words.join(" ") + " ");
  const years = (text: string): number[] => [...text.matchAll(/\b(\d{1,4})(?:\s*(BCE|BC|CE|AD))?\b/gi)].map(m => Number(m[1]) * (/^BC/i.test(m[2] ?? "") ? -1 : 1));
  const namesOwner = (phrase: string, fact: string, paragraph: string): boolean => { const terms = topicTokens.semanticAtoms(phrase), clause = paragraph.split(/[.!?;]|\b(?:but|whereas|while|unlike)\b/i).find(s => s.includes(phrase)) ?? "", aliases = aliasesOf(fact), exactAlias = aliases.some(a => topicTokens.sameQuery(phrase, a)), owner = subject.slice(0, -1), context = clause.slice(Math.max(0, clause.toLowerCase().indexOf(subject[0] ?? ""))), supplied = years([...(context.match(periods) ?? []), ...(context.match(/\b(?:in|from|during|between)\s+\d{1,4}\s*(?:BCE|BC|CE|AD)\b|\b(?:in|from|during|between)\s+\d{3,4}\s*[–—-]\s*\d{3,4}(?:\s*(?:BCE|BC|CE|AD))?/gi) ?? [])].join(" ")), interval = years(((target.h1 || target.title || "").match(periods) ?? []).join(" ")), relative = /\b(after|post|before|pre)[ -]*(\d{1,4})(?:\s*(BCE|BC|CE|AD))?\b/i.exec(clause), bound = relative ? Number(relative[2]) * (/^BC/i.test(relative[3] ?? "") ? -1 : 1) : 0, reference = clause.toLowerCase().includes(label.toLowerCase()) ? label : phrase, referenceAt = clause.toLowerCase().indexOf(reference.toLowerCase()), present = /\b(?:current|present[- ]day|today's)\s*$/i.test(clause.slice(0, referenceAt)) || /^\s+(?:today|currently|now)\b/i.test(clause.slice(referenceAt + reference.length));
    if (!subject.length || !subject.every(w => titleWords.has(w)) || !terms.every(w => topicTokens.semanticAtoms(fact.slice(fact.indexOf(" says: ") + 7)).includes(w)) || interval.length && (present && Math.max(...interval) < now.getUTCFullYear() || supplied.some(y => y < Math.min(...interval) || y > Math.max(...interval)) || relative && (/after|post/i.test(relative[1]!) ? bound >= Math.max(...interval) : bound <= Math.min(...interval)))) return false;
    const direct = terms.includes(subject[0]!) && terms.every(w => subject.includes(w)) && (contains(clause, subject) || contains(clause, [subject.at(-1)!, ...owner])), qualifiedAlias = terms.includes(subject[0]!) && aliases.some(a => { const name = a.replace(/^the\s+/i, ""), words = topicTokens.semanticAtoms(name), prefix = phrase.toLowerCase().endsWith(name.toLowerCase()) ? phrase.slice(0, -name.length).trim() : ""; return words.length > 0 && !!prefix && prefix.split(/\s+/).every(w => topicTokens.semanticAtoms(w).length > 0 && topicTokens.semanticAtoms(w).every(t => owner.includes(t))) && terms[0] === subject[0] && terms.every(w => subject.includes(w) || words.includes(w)); }), sourceAlias = aliasesOf(` says: ${clause}`).some(a => topicTokens.sameQuery(a, phrase)), used = clause.match(/^\s*(?:The\s+)?(.+?)\s+(?:used|flew|adopted|carried)\s+(?:the\s+)?(.+?)\s*[,.]?$/i), sourceOwner = sourceAlias || !!used && topicTokens.sameQuery(used[1]!, owner.join(" ")) && topicTokens.sameQuery(used[2]!, phrase);
    return direct || qualifiedAlias || exactAlias && (sourceOwner || terms[0] === subject[0] && terms.some(w => !owner.includes(w)));
  };
  const phraseWords = Math.max(label.split(/\s+/).length, ...Object.values(facts).flatMap(f => aliasesOf(f).map(a => a.split(/\s+/).length + label.split(/\s+/).length)));
  if (card.recommendedChange.kind === "existing_edit" && card.recommendedChange.linkMode === "in_place") { const captures = COPY_RULES.joinedCaptures([COPY_RULES.captureProof(source, now.getTime()), COPY_RULES.captureProof(target, now.getTime())]), c = card.recommendedChange, phrase = c.anchorText ?? "", paragraph = c.before ?? "", own = card.supportFacts?.find(f => f.id === "page-copy-in-place" && f.fact === paragraph), dest = card.supportFacts?.find(f => facts[f.id] === f.fact && namesOwner(phrase, f.fact, paragraph)); return source.contentHash === c.linkSourceHash && articlePassages(source).some(p => p.includes(paragraph)) && exactBlock(source, phrase) === paragraph && c.after === paragraph && c.units?.length === 1 && c.units[0]?.kind === "paragraph" && c.units[0].text === paragraph && c.target?.mode === "replace" && c.target.anchorKind === "passage" && c.target.anchor === paragraph && linkState(source, paragraph, phrase, to) !== "other" && !!own && !!dest && card.claims?.some(claim => claim.text === phrase && claim.supportedBy.includes(own.id) && claim.supportedBy.includes(dest.id)) ? (() => { const owned = mutationPreservation(card, source, paragraph, false); return !owned || owned !== card ? owned : COPY_RULES.sameCaptures(card.reviewedCaptures, captures) ? card : { ...card, reviewedCaptures: captures }; })() : null; }
  const $ = load(source.sourceCapture!.mainHtml), clean = (s: string) => s.replace(/\s+/g, " ").trim(), sourceArticle = articlePassages(source), blocks = $("p,li,blockquote,div.wixui-rich-text").toArray().filter(node => !$(node).find("p,li,blockquote,div.wixui-rich-text").length && !$(node).find("a[href]").length && sourceArticle.some(p => p.includes(clean($(node).text()))));
  const options: { phrase: string; paragraph: string; score: number }[] = [];
  for (const node of blocks) { const paragraph = clean($(node).text()), tokens = [...paragraph.matchAll(/[\p{L}\p{N}]+(?:[-’'][\p{L}\p{N}]+)*/gu)]; for (let i = 0; i < tokens.length; i++) for (let n = 1; n <= phraseWords && i + n <= tokens.length; n++) { const phrase = paragraph.slice(tokens[i]!.index!, tokens[i + n - 1]!.index! + tokens[i + n - 1]![0].length), terms = topicTokens.semanticAtoms(phrase); if (terms.length === 0 || !topicTokens(tokens[i]![0]).length || !topicTokens(tokens[i + n - 1]![0]).length || !/^[\p{L}\p{N}’' -]+$/u.test(phrase) || source.vocabulary.split(phrase).length !== 2 || !Object.values(facts).some(f => namesOwner(phrase, f, paragraph))) continue; options.push({ phrase, paragraph, score: terms.length }); } }
  options.sort((a, b) => b.score - a.score || b.phrase.length - a.phrase.length); const { phrase, paragraph } = options[0] ?? {}; if (!phrase || !paragraph || exactBlock(source, phrase) !== paragraph || options.some(o => o !== options[0] && o.score === options[0]!.score && o.phrase !== phrase && !phrase.includes(o.phrase))) return null;
  const other = Object.entries(facts).find(([, fact]) => namesOwner(phrase, fact, paragraph))!;
  const place = { mode: "replace" as const, anchorKind: "passage" as const, anchor: paragraph }, edit = { kind: "existing_edit" as const, field: "section" as const, before: paragraph, after: paragraph, units: [{ kind: "paragraph" as const, text: paragraph }], target: place, linkTo: to, anchorText: phrase, linkMode: "in_place" as const, linkSourceHash: source.contentHash!, where: COPY_RULES.where(place) };
  const owned = mutationPreservation(card, source, paragraph, true); if (!owned) return null;
  return { ...owned, pageUrl: source.url, reviewedCaptures: COPY_RULES.joinedCaptures([COPY_RULES.captureProof(source, now.getTime()), COPY_RULES.captureProof(target, now.getTime())]), status: "ready", researchOnly: false, research: undefined, obligation: undefined, assignment: undefined, semanticReview: undefined, informationGain: undefined, bundle: undefined, faults: [], limitations: [], estimatedEffortMinutes: 3, recommendedChange: edit, claims: [{ text: phrase, supportedBy: ["page-copy-in-place", other[0]] }], supportFacts: [{ id: "page-copy-in-place", fact: paragraph }, { id: other[0], fact: other[1] }], operatorSteps: [`Open the site editor on ${card.pagePath}`, `Find the exact paragraph shown under Now and select only "${phrase}"`, `Link those existing words to ${to}; leave the paragraph's wording and all other content untouched`, "Mark implemented after the exact anchor and destination are live"] };
}
const reason = (p: ChangeProposal, source: OwnedPageBody | null, target: OwnedPageBody | null): string | null => proposal(p, source, target, new Date()) ? null : "The exact current paragraph, phrase, destination or source support has moved; recapture it before offering this link.";
const LINK_PLACEMENT = { exactBlock, targetFacts, proposal, reason }; export default LINK_PLACEMENT;
