/** THE CAUSE PRODUCERS. A named cause reaches a producer, it works off the structure the ladder read, every component survives the REAL validator, a cause with no producer refuses in its own words, a drafter that will not land is a refusal, thin evidence never reaches a drafter, and wording keeps its own path. */
import { describe, it, expect, vi, beforeEach, afterEach } from "vitest";
import type { EvidenceSnapshot, OwnedPageEvidence } from "@/domains/evidence/snapshot";
import { emptyResearchEvidence } from "@/domains/evidence/funnel/research-evidence";
import { answerIntelOf } from "@/domains/evidence/answer-intel"; import type { TopicInvestigation } from "@/domains/evidence/topic-investigation";
import type { OwnedCandidate } from "@/domains/decision/owned-coverage";
import type { DecidedTopic } from "@/domains/decision/coverage-pass";
import type { WinningPattern } from "@/domains/decision/winning-pattern";
import { validateProposal } from "@/domains/decision/validate-proposal"; import { provenSurvivor } from "@/domains/decision/split"; import { withholdReason } from "@/domains/decision/authorization"; import { applyDraftedCopy, demandOf, writerKindOf } from "@/domains/decision/drafted-copy"; import { substantiveGapOf } from "@/domains/decision/diagnosis"; import { pageHashOf } from "@/domains/evidence/pages/fact-check-run"; import { VERIFICATION_RULES_VERSION } from "@/domains/evidence/pages/fact-checks"; import { DRAFT_BUDGET } from "@/domains/decision/draft-budget"; import { nextObligation } from "@/domains/decision/obligation"; import { componentIdOf } from "@/domains/decision/contracts"; import { copyKey } from "@/domains/decision/proof"; import { openHold } from "@/domains/decision/completeness";
import { deserializeChangeProposal, serializeChangeProposal } from "@/domains/decision/contracts"; import { researchingCards } from "@/domains/decision/authorization"; import type { CauseFinding } from "@/domains/decision/diagnosis";
import type { CompleteFn } from "@/domains/decision/llm/structured-drafter";
vi.mock("@/domains/decision/llm/adjudicator-budget", () => ({ checkBudget: async () => ({ allowed: true, remaining: 10 }), recordSpend: async () => {} }));
/** THE ONE SEAM THAT HANDS A BUILDER A PIECE CARRYING TYPED PROVENANCE. `packetForBody`, the packet both the new-page and bundle paths use, sets no `checkedSources` yet, so a real piece on those paths carries none and the merge below could never be exercised against live data; the piece is given the shape a checked reading really banks, and the assertion is about what the row assembled from it keeps. */
const quoted = vi.hoisted(() => ({ on: false, at: [{ url: "https://source.example/a", kind: "encyclopedia" }] }));
vi.mock("@/domains/decision/drafted-copy", async (orig) => { const real = await orig<Record<string, unknown>>(); type Piece = { supportFacts: readonly { id: string; fact: string }[] } | null;
  return { ...real, draftFieldForPage: async (...a: unknown[]): Promise<Piece> => { const piece = await (real.draftFieldForPage as (...x: unknown[]) => Promise<Piece>)(...a);
    return piece && quoted.on ? { ...piece, supportFacts: piece.supportFacts.map((f) => ({ ...f, sources: quoted.at })) } : piece; } }; });
vi.mock("@/domains/decision/llm/winner-memory", () => ({ buildWinnerFewShots: async () => "", buildWinnerFewShotsWithPattern: async () => ({ fragment: "", patternHint: null }) }));
import { proofOf } from "@/domains/decision/proof"; import type { ChangeProposal } from "@/domains/decision/contracts";
import { produceBundleForSnapshot, type OwnedBody } from "@/domains/decision/produce-bundle"; import { buildNewPageProposal } from "@/domains/decision/new-page"; import { evidenceShortfall } from "@/domains/decision/proof";
const TENANT = "fixture-tenant"; const NOW = new Date("2026-08-01T00:00:00.000Z"); const URL = "fixture-content.example/rain-barrels";
const OPENING = "Collecting water at home starts with knowing what one storm actually brings you."; // ── the drafted answers the seam hands back, each grounded in words the evidence already carries ──
/** WHAT A SECTION AND AN OPENING NOW COME BACK CARRYING: the claim it makes, the stored id that carries it, and the reviewer's ruling on exactly that claim. A bundle's substantive pieces go through the ONE canonical editor, so a fixture that answered a second section drafter is answering a question nobody asks any more. */
const cited = (user: string): string => (user.includes("owned-page-1") ? "owned-page-1" : "page-heading-1"); // the sibling page where this account holds one, and the page's own heading where it does not
const JUDGED = (id: string) => ({ pageFit: true, resolvesDiagnosis: true, claims: [{ i: 0, by: [id], entailed: true }], usefulAndNatural: true, placementCorrect: true, implementableNow: true, improvesPage: true, wouldHandToCustomer: true, notes: "It says where a full barrel's overflow goes, which this page never said.", resolution: "none" });
const ANSWER = "Rain barrel sizing depends on your roof area and the rain one storm brings. The bigger the roof, the faster a barrel fills, so pick one that holds what a heavy storm delivers and plan where the overflow goes.";
const TAIL = { evidenceRefs: [{ source: "gsc", detail: "real page demand" }], confidence: "high", risks: [], operatorSteps: ["Paste the copy"], proofPlan: { metrics: ["clicks"], windowsDays: [7, 14, 28], controls: "untouched pages" } };
const TITLE_AFTER = "Rain barrel sizing: gallons per storm by roof area";
/** Records every draft kind bought, so "spent nothing" is provable rather than assumed. */
const bought: string[] = [];
const seam = (over: { atomic?: unknown; judged?: unknown } = {}): CompleteFn => async ({ kind, user }) => { bought.push(kind);
  if (kind === "editor_judgement") return { value: (over.judged ?? JUDGED(cited(user))) as never };
  return { value: (over.atomic ?? { field: "answer_block", before: null, after: ANSWER, naturalHeading: (/under the heading "(.*?)"/.exec(user) ?? [])[1] ?? "Where the overflow goes",
    placementAnchor: "Rain Barrels", claims: [{ text: "Barrel sizes vary.", supportedBy: [cited(user)] }], implementationMinutes: 15, rationale: "The opening never says what the search is about.", ...TAIL }) as never };};
const page = (over: Partial<OwnedPageEvidence> = {}): OwnedPageEvidence => ({ url: URL, content: { title: "Rain Barrels", metaDescription: null, h1: "Rain Barrels", h2: [], outline: ["Rain barrel sizing", "Roof area and gallons"], schemaTypes: [], hasFaq: false, faqCount: 0, wordCount: 900, internalLinks: [], fetchedAt: "2026-07-20T00:00:00.000Z" },
  search: { clicks90d: 120, impressions90d: 9000, ctr90d: 0.013, position90d: 3, topQueries: [{ query: "rain barrel sizing", impressions: 6000, clicks: 90, position: 3 }] }, engagement: null, friction: null, aiCitations: { count: 0, distinctPrompts: 0, engines: [] }, ...over });
const snapshot = (over: Partial<EvidenceSnapshot> = {}): EvidenceSnapshot => ({ scope: { tenantId: TENANT, site: "fixture-content.example", builtAt: NOW.toISOString() }, aiCitations: { ownedCited: 0, competitorCited: 0, engines: [], rowsScanned: 0 }, sources: [], competitors: [], keywordDemand: [], questionDemand: [], intentClusters: [], cannibalization: [], contentGaps: [],
  internalLinkOpportunities: [], evidenceHash: "fixture", research: emptyResearchEvidence(), ownedPages: [page(), page({ url: SIBLING, content: { ...page().content!, title: "Gutter guards", h1: "Gutter guards", outline: ["Gutter guards"] }, search: { clicks90d: 5, impressions90d: 100, ctr90d: 0.05, position90d: 4, topQueries: [{ query: "gutter guards", impressions: 100, clicks: 5, position: 4 }] } })], ...over });
/** ANOTHER PAGE OF THIS ACCOUNT, WITH ITS WORDS ON FILE: the one thing a page cannot say about itself, and the id a body claim may actually stand on. */
const SIBLING = "fixture-content.example/gutter-guards";
const BODY: ReadonlyMap<string, OwnedBody> = new Map([["fixture-content.example/rain-barrels", { openingSample: OPENING, fetchedAt: "2026-07-20T00:00:00.000Z", cardTexts: ["Roof area and gallons"], entityNames: [], headings: ["Barrel sizes", "Winter care"], completeness: "complete", internalLinks: [], metaDescription: null }],
  [SIBLING, { openingSample: "Gutter guards keep leaves out of a downspout.", fetchedAt: "2026-07-20T00:00:00.000Z", cardTexts: [], entityNames: [], headings: ["Gutter guards"], passages: ["Gutter guards keep leaves out of the downspout, so a barrel fills with water rather than debris."], completeness: "complete", internalLinks: [], metaDescription: null }]]);
const pattern = (over: Partial<WinningPattern> = {}): WinningPattern => ({ archetype: "informational_guide", commonHeadings: [{ heading: "Sizing by roof area", seenOn: [0, 1, 2] }], commonEntities: [], questionsAnswered: [], openingPattern: "they answer the sizing question in the first line", disagreements: [], ownedGaps: [], uniqueNotCommon: [],
  winners: 3, publishers: ["gardenguide.example", "waterwise.example", "downspout.example"], fingerprint: "abc123", ...over });
const candidate = (): OwnedCandidate => ({ url: URL, path: "/rain-barrels", title: "Rain Barrels", h1: "Rain Barrels", wordCount: 900,
  outlineLength: 2, openingSample: OPENING, entities: [], fetchedAt: null, bodyHeld: true, strongSignals: 1,
  signals: [{ kind: "gsc_exact_query", strength: "strong", basis: "rain barrel sizing", detail: "Google already shows this page for that search." }] });
const investigation = (): TopicInvestigation => ({ key: "inv_rain", aliasKeys: [], label: "rain barrel sizing", demandBasis: "search", groupedBy: [],
  queries: ["rain barrel sizing"], keywords: [], trackedPrompts: [], fanOuts: [], answerIntel: answerIntelOf([]), exactSerps: [], serpFreshness: "current",
  demand: { monthlySearchVolume: 4400, queriesWithVolume: 1, gscImpressions: 6000, difficulty: null, intent: "informational", trackedPrompts: 0, fanOuts: 0, engines: [] },
  distinctResultDomains: 8, resultDomains: [], pageType: "informational_guide", pageTypeVotes: [], serpCoherence: "coherent",
  winners: [], distinctWinners: 3, currentReadableWinners: 3, missingEvidence: [], nextAcquisition: null, diminishing: false });
const decided = (p: WinningPattern | null): DecidedTopic => ({
  investigation: investigation(), candidates: [candidate()], reading: null,
  decision: { verdict: "improve_existing", topicKey: "inv_rain", ownedUrls: [URL], evidenceKeys: ["demand"], missing: [],
    alternativesRuledOut: [{ alternative: "Write a new page for this", reason: "Your own page already answers this search." }],
    explanation: "I would sharpen the page you already have rather than add another that competes with it.", ...(p ? { pattern: p } : {}) } });
const OPTS = { now: NOW, bypassCache: true, bodyByUrl: BODY };
beforeEach(() => { process.env.OPENAI_API_KEY = "test-key"; bought.length = 0; });
afterEach(() => { delete process.env.OPENAI_API_KEY; });
describe("a named cause produces the change that fixes it", () => {
  it("writes the opening the page never had, and it survives the real validator", async () => {
    const out = await produceBundleForSnapshot(snapshot(), { ...OPTS, complete: seam(), coverage: decided(pattern()) }); expect(out.status).toBe("bundled"); if (out.status !== "bundled") return; const p = out.proposal; const b = p.bundle!;
    expect(p.diagnosisCause).toBe("weak_opening"); // the REAL fired cause, never the hardcoded wording one
    expect(b.components.map((c) => c.kind)).toEqual(["opening_answer"]); expect(b.components[0]!.before).toBe(OPENING);     expect(b.components[0]!.after).toBe(ANSWER); expect(p.recommendedChange).toEqual({ kind: "existing_edit", field: "answer_block", before: OPENING, after: ANSWER }); expect(p.opportunityType).toBe("Answer the search in the page's first lines");
    const keys = new Set(b.receipt.items.map((i) => i.key)); expect(b.components[0]!.evidenceKeys.length).toBeGreaterThan(0); // every cited key is a receipt line the operator can actually read
    for (const k of b.components[0]!.evidenceKeys) expect(keys.has(k)).toBe(true);
    expect(validateProposal(p, { evidenceText: b.receipt.items.map((i) => i.fact).join(" ") }).verdict).not.toBe("rejected"); expect(deserializeChangeProposal(serializeChangeProposal(p))).toEqual(p); // THROUGH THE REAL VALIDATOR, not a mock of it, and a round trip through the one decoder
    expect([b.objective, b.measurementPlan, ...b.risks, ...b.components.map((c) => `${c.label} ${c.after} ${c.where} ${c.objective} ${c.mechanism}`)].join(" ")).not.toMatch(/[–—]|experiment|control group|baseline|SERP/i); });
  it("writes one section per subject the winning pages agree on and this page leaves out, each answering for itself", async () => {
    const p2 = pattern({ commonHeadings: [{ heading: "Gutter guards keep debris out", seenOn: [0, 1, 2] }, { heading: "Chaining a container", seenOn: [0, 1] }] }); const out = await produceBundleForSnapshot(snapshot(), { ...OPTS, complete: seam(), coverage: decided(p2) }); expect(out.status).toBe("bundled"); if (out.status !== "bundled") return; const b = out.proposal.bundle!;
    expect(out.proposal.diagnosisCause).toBe("incomplete_coverage"); expect(b.components.map((c) => c.kind)).toEqual(["section_add", "section_add"]);
    for (const c of b.components) { // section_add is OUTSIDE the grandfathered kinds, so all four answers are owed or the validator rejects the whole change
      expect(c.where).toBeTruthy(); expect(c.objective).toBeTruthy(); expect(c.mechanism).toBeTruthy(); expect(c.measurementPlan).toBeTruthy(); expect(c.after).toContain(ANSWER);}
    expect(validateProposal(out.proposal, { evidenceText: b.receipt.items.map((i) => i.fact).join(" ") }).verdict).not.toBe("rejected");
    expect(bought.filter((k) => k === "atomic_edit")).toHaveLength(2); // one call per section, never a third, and every one of them through the ONE canonical editor
    expect(out.proposal.claims!.map((x) => x.of)).toEqual(b.components.map((c, i) => componentIdOf(c, i))); // AND EACH PIECE CARRIES ITS OWN AUTHORIZATION, named by the piece it belongs to: one section's ruling can never stand in for the next one's.
    expect(out.proposal.semanticReview!.of).toBe(copyKey(out.proposal)); expect(openHold(out.proposal).blocking).toBeNull(); /** ONE TYPED GAP PER SECTION, AND NEVER THE SAME ONE TWICE (operator, 2026-09-02): work split into sections owes each section its own missing proposition, and a second section closing a gap another already closes hands the reader the same answer under two headings. */ expect(new Set(b.components.map((c) => c.objective)).size, "the two sections carry two distinct gaps").toBe(2); const overlap = await produceBundleForSnapshot(snapshot(), { ...OPTS, complete: seam(), coverage: decided(pattern({ commonHeadings: [{ heading: "Gutter guards keep debris out", seenOn: [0, 1, 2] }, { heading: "Gutter guards keep the debris out of gutters", seenOn: [0, 1] }] })) }); expect(overlap.status === "bundled" ? [overlap.proposal.bundle!.components.length, overlap.proposal.bundle!.alternatives.some((a) => a.reason.includes("two sections closing one gap"))] : ["not bundled"], "and the second section closing a gap the first already closes is dropped by name").toEqual([1, true]);
  });
  it("never calls a subject absent that the held page carries in a later passage", async () => {
    const deep = new Map([[URL, { ...BODY.get(URL)!, passages: [...Array.from({ length: 8 }, (_, i) => `Paragraph ${i + 1} of ordinary prose.`), "Gutter guards keep debris out, and chaining a container carries the overflow away."] }]]);
    const out = await produceBundleForSnapshot(snapshot(), { ...OPTS, bodyByUrl: deep, complete: seam(), coverage: decided(pattern({ commonHeadings: [{ heading: "Gutter guards keep debris out", seenOn: [0, 1, 2] }, { heading: "Chaining a container", seenOn: [0, 1] }] })) });
    expect(out.status === "bundled" && out.proposal.diagnosisCause).toBe("weak_opening"); }); // both are on the page, so nothing accuses it of leaving them out
  it("refuses honestly when the drafter will not land, and ships no empty component", async () => {
    const out = await produceBundleForSnapshot(snapshot(), { ...OPTS, complete: seam({ atomic: {} }), coverage: decided(pattern()) }); expect(out.status).toBe("none"); if (out.status !== "none") return; expect(out.reason).toBe("No opening for this page passed its own checks, so nothing is handed over rather than filler.");
    expect(bought).toEqual(["atomic_edit", "atomic_edit"]); // it tried, and the retry is the drafter's own, not a second change
  });
  it("says why it is producing nothing for a cause no copy can fix, in the ladder's own words", async () => {
    const out = await produceBundleForSnapshot(snapshot(), { ...OPTS, complete: seam(), coverage: decided(pattern()), measuringPagePaths: ["/rain-barrels"] }); expect(out.status).toBe("none"); if (out.status !== "none") return; expect(out.reason).toBe("The change you applied here is still being measured, so nothing is stacked on top of it.");
    expect(bought).toEqual([]); // a cause with no producer costs nothing
  });
  /** A REBUILD IS EARNED BY CAUSES THAT FIRED, never by ones checked and RULED OUT: counting the whole list told the operator "2 separate things are wrong" where the second clause contradicted the evidence. */ describe("a rebuild is earned by what fired", () => {
    const REBUILT = ANSWER.replace("a heavy storm delivers", "a heavy storm brings"); const rebuildSeam: CompleteFn = async ({ kind, user }) => { bought.push(kind); // The cause's OWN producer can write nothing, so the rebuild is reachable; the rebuild's own sections do land, because a rebuild that cannot write the whole page now emits nothing at all. No superlative in the rebuilt copy: this fixture supplies no opening pattern, so "the first" would be an ungrounded claim and the factual firewall would rightly refuse the whole rebuild.
      if (kind === "editor_judgement") return { value: JUDGED(cited(user)) as never };
      if (user.includes("Rewrite the first lines")) return { value: { field: "answer_block", before: null, after: ANSWER, naturalHeading: "Where the overflow goes", placementAnchor: "Rain Barrels", claims: [{ text: "Barrel sizes vary.", supportedBy: [cited(user)] }], implementationMinutes: 15, rationale: "The opening never says what the search is about.", ...TAIL } as never };
      return user.includes("being rebuilt") ? { value: { field: "answer_block", before: null, after: REBUILT, naturalHeading: (/under the heading "(.*?)"/.exec(user) ?? [])[1] ?? "Overflow", placementAnchor: "Rain Barrels", claims: [{ text: "Barrel sizes vary.", supportedBy: [cited(user)] }], implementationMinutes: 15, rationale: "The page is being rebuilt.", ...TAIL } as never } : { value: {} as never }; };
    const gaps = { ownedGaps: [{ gap: "None of this page covers overflow", seenOn: [0, 1] }], openingPattern: "" };
    const rebuildOf = async (...heads: string[]) => produceBundleForSnapshot(snapshot(), { ...OPTS, complete: rebuildSeam,
      coverage: decided(pattern({ ...gaps, commonHeadings: heads.map((heading) => ({ heading, seenOn: [0, 1, 2] })) })) });
    it("rebuilds when a SECOND structural cause genuinely fired, and ships the whole page or nothing", async () => {
      const out = await rebuildOf("Chaining a second container", "Gutter guards keep debris out"); // subjects this page carries none of: it fires
      expect(out.status).toBe("bundled"); if (out.status !== "bundled") return; const b = out.proposal.bundle!; const c = b.components[0]!; expect(b.components.map((x) => x.kind)).toEqual(["full_rewrite"]);
      expect(c.after.startsWith(ANSWER)).toBe(true); expect(c.after).toContain(REBUILT); // THE COPY, NOT A PLAN: the page's own opening, then every section the winners agree on, in order.
      expect(c.mechanism).toContain("2 things are wrong at once");
      expect(bought.filter((k) => k === "editor_judgement")).toHaveLength(3); // the opening and the two sections the rebuild wrote, each read for sense by the ONE evaluator // BOTH SECTIONS THE WINNERS AGREE ON were bought, and neither was shipped as an unwritten heading.
      expect(out.proposal.status).toBe("needs_review"); expect(openHold(out.proposal).blocking).toContain("have not been read against the sources they name"); // A REBUILD ASSEMBLED FROM SEVERAL AUTHORIZED PIECES IS NOT ITSELF AUTHORIZED: its own copy is nobody's ruled claim, so the door holds it and says so instead of letting the pieces vouch for the whole.
    });
    it("never rebuilds when every competing explanation was RULED OUT", async () => {
      const out = await rebuildOf("Rain barrel sizing"); // a subject this page already covers: it does not fire
      expect(out.status).toBe("none"); if (out.status !== "none") return; expect(out.reason).toBe("No section that would close the gap on the winning pages passed its own checks, so nothing is handed over rather than filler."); }); });
  /** A SPLIT IS AN INVESTIGATION UNTIL THE EVIDENCE NAMES THE SURVIVOR, and the merge that does ship names it, names what moves, and keeps the two-step hold: downgrading a merge's danger took that hold off the one change that needs it AND made the stored row fail re-validation as mislabelled. */ it("writes no merge while the survivor is unproven, then hands over the proven one and holds it for review", async () => {
    const RIVAL = "fixture-content.example/rain-barrel-guide"; const world = (rival: OwnedPageEvidence[]) => snapshot({ ownedPages: [page(), ...rival], cannibalization: [{ query: "rain barrel sizing", note: "two of your own pages", competingUrls: [URL, RIVAL] }] });
    const split = (a: [number | null, number | null], b: [number | null, number | null]) => provenSurvivor([{ url: URL, clicks: a[0], impressions: 900, position: a[1] }, { url: RIVAL, clicks: b[0], impressions: 400, position: b[1] }]); // THE EARNINGS ARE ALREADY ON FILE, so the survivor is decided from them and never deferred: the page I hold figures for is kept, an equal pair is settled by position, and a page I hold nothing for settles nothing.
    expect([split([12, 4], [3, 2]), split([0, 4], [0, 9]), split([12, 4], [null, null]), split([4, 3], [4, 3]), split([null, null], [null, null])]).toEqual([URL, URL, null, null, null]);
    const unproven = await produceBundleForSnapshot(world([]), { ...OPTS, complete: seam(), coverage: decided(pattern()) }); // ONE-SIDED KNOWLEDGE SETTLES NOTHING: a page I hold no row for is unmeasured, not behind, and sending it away for good on my ignorance is the one mistake here I could not undo
    expect([unproven.status, unproven.status === "none" && unproven.reason.includes("not proof that either takes the other's clicks")]).toEqual(["none", true]);
    const rival = page({ url: RIVAL, content: { ...page().content!, title: "Rain barrel guide", h1: "Rain barrel guide", outline: ["Barrel sizes", "Winter care"] }, // PROVEN: both pages' own figures for that exact search, and both pages' current words on file.
      search: { clicks90d: 20, impressions90d: 900, ctr90d: 0.02, position90d: 9, topQueries: [{ query: "rain barrel sizing", impressions: 900, clicks: 20, position: 9 }] } });
    const out = await produceBundleForSnapshot(world([rival]), { ...OPTS, complete: seam(), coverage: decided(pattern()),
      bodyByUrl: new Map([...BODY, [RIVAL, { ...BODY.get(URL)!, headings: ["Barrel sizes", "Winter care"] }]]) });
    expect(out.status).toBe("bundled"); if (out.status !== "bundled") return; const p = out.proposal; const b = p.bundle!; const c = b.components[0]!; expect([p.diagnosisCause, p.status, p.riskLevel]).toEqual(["cannibalization", "needs_review", "high"]); // a question, never a paste, priced as the lever it is
    expect([c.kind, c.risk, c.redirectTo]).toEqual(["consolidation", "dangerous", "/rain-barrels"]); expect(c.after).toContain("/rain-barrels earns 90 clicks from that search against 20 on /rain-barrel-guide");
    expect(p.operatorSteps).toEqual(["Check /rain-barrels already says everything /rain-barrel-guide says: nothing on file there is missing from it", "Redirect /rain-barrel-guide to /rain-barrels for good", 'Come back here and mark it done, about 90 minutes of work in all, and clicks and average position for "rain barrel sizing" get read across all 2 addresses']);
    expect(b.receipt.items.find((i) => i.key === "demand-competing")!.fact).toContain("/rain-barrel-guide takes 20 clicks from 900 views at about position 9"); expect(c.evidenceKeys).toContain("demand-competing"); // the comparison that proves it is a line the operator can read, and the component cites it
    const again = validateProposal(p, { evidenceText: b.receipt.items.map((i) => i.fact).join(" ") }); // AND THROUGH THE VALIDATOR AGAIN on exactly the shape stored: an unmarked lever is rejected as mislabelled.
    expect([again.verdict, again.reasons.join(" ").includes("confirm it before you make the change"), bought]).toEqual(["needs_review", true, []]); });
  /** THE ASSEMBLED ROW IS GATED, NOT ONLY ITS PIECES: the per-component gate reads a synthetic proposal that carries no cause and no limitations, so a cause pointing at a receipt line nobody wrote sailed past it. */ it("refuses to ship an assembled change whose cause points at a receipt line the receipt never carried", async () => {
    const { bodyByUrl: _drop, ...noBody } = OPTS; void _drop; const out = await produceBundleForSnapshot(snapshot(), { ...noBody, complete: seam(), coverage: decided(pattern()) }); // No body on file, so the opening this cause read came off the comparison and the receipt has no line for it.
    expect([out.status, out.status === "none" && out.reason.includes("No opening for this page passed its own checks"), bought]).toEqual(["none", true, []]); }); // AND A PAGE WHOSE OWN WORDS ARE NOT ON FILE BUYS NO BODY COPY AT ALL (2026-08-30): the canonical editor judges what a section adds against the page it lands on, so with no page in hand there is nothing to judge against and nothing is written rather than written blind.
  it("never reaches a drafter on evidence too thin to name a cause", async () => {
    const out = await produceBundleForSnapshot(snapshot(), { ...OPTS, complete: seam() }); // no pattern, so no cause that needs one is even considered
    expect([out.status, bought, out.status === "none" && out.reason.includes("The results page for that search has not been read yet")]).toEqual(["none", [], true]); }); });
/** A DOOR ANSWERS FOR ITS OWN CASE: a page selected because an engine skipped it, whose answer I no longer hold, is refused in that door's words. The wrong reason is worse than no reason, and neither is drafted. */
/** A NEW PAGE EARNS THE SAME AUTHORIZATION AS A SECTION, OR IT STAYS INTERNAL. Coverage adjudication authorizes the NEED and the results pages the FORMAT; neither authorizes a sentence, so every piece of the finished page is written and ruled by the ONE canonical editor and every material claim rests on a checked source or another page this account owns. */ describe("a researched new page is authorized piece by piece", () => {
  const HEADS = ["Sizing a barrel to a roof", "Where the overflow goes", "Chaining a second barrel"];
  const BRIEF = { proposedTitle: "How rain barrel sizing works", metaDescription: "What size rain barrel a roof needs, and where the overflow goes once a storm has filled it right up.",
    openingAnswer: "A rain barrel is sized to the roof that feeds it, and the overflow needs somewhere to go once a storm fills it.",
    whyExistingPagesLose: `Your page ${URL} covers barrels in general and never sizes one, so stretching it would bury the answer.`,
    sections: HEADS.map((heading) => ({ heading, covers: "Answer this plainly for a reader.", evidenceKeys: ["demand"] })),
    sourceRequirements: [], factRequirements: [], internalLinks: [], faqQuestions: [], headKeys: ["demand"] };
  const pageSeam = (write = true): CompleteFn => async ({ kind, user }) => { bought.push(kind);
    if (kind === "new_page_brief") return { value: BRIEF as never };
    if (kind === "editor_judgement") return { value: JUDGED(cited(user)) as never }; const heading = (/Write the section headed "(.*?)"/.exec(user) ?? [])[1] ?? BRIEF.proposedTitle;
    return { value: (write || heading !== HEADS[2] ? { field: "answer_block", before: null, after: ANSWER, naturalHeading: heading, placementAnchor: BRIEF.proposedTitle, claims: [{ text: "Barrel sizes vary.", supportedBy: [cited(user)] }], implementationMinutes: 15, rationale: "The page owes this section.", ...TAIL } : {}) as never }; };
  const topic: DecidedTopic = { investigation: investigation(), candidates: [candidate()], reading: null,
    decision: { verdict: "create_new", topicKey: "inv_rain", ownedUrls: [], evidenceKeys: ["demand"], missing: [],
      alternativesRuledOut: [{ alternative: "Strengthen a page you already have", reason: "No page of yours comes up for this at all." }], explanation: "No page of yours answers this, and the pages that win it agree on what one has to cover." } };
  /** TYPED PROVENANCE SURVIVES THE MERGE ONTO THE ROW (measured, 2026-09-05): two of the three supportFacts builders rebuilt each fact as `{ id, fact }`, so every address a reading actually quoted was stripped on the way from the authorized piece to the stored change, and the publisher count fell back to hostnames parsed out of the fact's own prose. */
  it.each(["fixture-tenant", "second-tenant"])("carries the addresses a reading quoted from the piece that read them onto the row a new page and a bundle are assembled from, on %s", async (acct) => {
    quoted.on = true;
    try {
      const page = await buildNewPageProposal(topic, acct, { complete: pageSeam(), now: NOW, bypassCache: true });
      expect(page.status, "the page builds").toBe("built"); if (page.status !== "built") return;
      expect((page.proposal.supportFacts ?? []).length > 0 && (page.proposal.supportFacts ?? []).every((f) => (f.sources ?? []).length === 1), "every fact the new page banks keeps the address its reading quoted and what kind of source it is").toBe(true);
      const out = await produceBundleForSnapshot({ ...snapshot(), scope: { tenantId: acct, site: "fixture-content.example", builtAt: NOW.toISOString() } }, { ...OPTS, complete: seam(), coverage: decided(pattern()) });
      expect(out.status, "the bundle builds").toBe("bundled"); if (out.status !== "bundled") return;
      expect((out.proposal.supportFacts ?? []).length > 0 && (out.proposal.supportFacts ?? []).every((f) => (f.sources ?? []).length === 1), "and so does every fact a bundle banks").toBe(true);
      quoted.on = false;
      const bare = await buildNewPageProposal(topic, acct, { complete: pageSeam(), now: NOW, bypassCache: true });
      expect(bare.status === "built" && (bare.proposal.supportFacts ?? []).every((f) => f.sources === undefined), "and a piece that quoted nothing writes no empty provenance").toBe(true);
    } finally { quoted.on = false; } });
  it("writes and rules every piece against another page of this account, and refuses to hand over part of a page", async () => {
    const built = await buildNewPageProposal(topic, TENANT, { complete: pageSeam(), now: NOW, bypassCache: true }); expect(built.status).toBe("built"); if (built.status !== "built") return; const p = built.proposal;
    expect(bought.filter((k) => k === "atomic_edit")).toHaveLength(4); // the opening and all three sections, through the ONE canonical editor and never a second drafter
    const kinds = p.bundle!.components.map((c) => c.kind), pieces = new Set(p.claims!.map((c) => c.of)); expect([kinds, pieces.size]).toEqual([["title", "meta", "opening_answer", "section"], 2]); // the opening answers for the opening piece, every section for the section piece, and neither for the other
    expect(p.claims!.every((c) => c.supportedBy.every((id) => id.startsWith("owned-page")))).toBe(true); expect([evidenceShortfall(p), openHold(p).blocking], "a complete page whose every claim is carried earns the same verdict a section earns").toEqual([null, null]);
    const own = { ...p, claims: p.claims!.map((c) => ({ ...c, supportedBy: ["page-copy-1"] })) }; // the same page, every claim standing on the page's own drafted words, read and ruled exactly as it stands
    const unsupported = { ...own, semanticReview: { ...p.semanticReview!, of: copyKey(own), claims: p.semanticReview!.claims.map((r) => ({ ...r, by: ["page-copy-1"] })) } }; expect(openHold(unsupported).blocking, "and a page standing on its own words alone stays internal").toContain("rests on nothing checked");
    expect(openHold(unsupported).need?.reasonCode, "carrying the exact source requirement the runtime already fetches").toBe("claim_unsupported"); const partial = await buildNewPageProposal(topic, TENANT, { complete: pageSeam(false), now: NOW, bypassCache: true });
    expect([partial.status, partial.status === "none" && partial.reason.includes("still owed")]).toEqual(["none", true]); }); // part of a page is not worth handing over
});
describe("every door answers for its own evidence", () => {
  const DOOR = { door: "cannibalization" as "coverage_verdict" | "cannibalization" | "recent_decline", entry: "I gave this page my deepest read because two of your own pages come up for it.",
    evidence: { query: "rain barrel sizing", engine: null as string | null, promptText: null as string | null, competingUrls: [] as string[], window: null as string | null } };
  const refused = async (over: Partial<typeof DOOR>): Promise<string> => {
    const out = await produceBundleForSnapshot(snapshot(), { ...OPTS, complete: seam(), door: { ...DOOR, ...over } });
    return out.status === "none" ? out.reason : `expected a refusal, got ${JSON.stringify(out)}`;};
  it("names what THAT door is missing and never falls back to the click sentence", async () => {
    expect(await refused({ door: "cannibalization" })).toContain("which pages those are is not settled"); expect(await refused({ door: "recent_decline" })).toContain("one 90 day total"); expect(await refused({ door: "coverage_verdict" })).toContain("named it as the page of yours to improve"); expect(await refused({ evidence: { ...DOOR.evidence, query: " " } })).toContain("no longer names the search it was about");
    for (const door of ["cannibalization", "recent_decline", "coverage_verdict"] as const) {
      expect(await refused({ door })).not.toMatch(/losing enough clicks|[–—]|experiment|control group|baseline|SERP/i);}
    expect(bought).toEqual([]); // a door that cannot show its own case never reaches a drafter
  }); });
describe("the wording cause keeps the path it has always had", () => {
  const SERP = { ...emptyResearchEvidence(), serpEvidence: [{ observedAt: null, query: "rain barrel sizing", aiOverview: [], aiMode: [], paa: [], related: [],
    organic: [{ rank: 1, domain: "gardenguide.example", url: "https://gardenguide.example/a", title: "Rain barrel sizing guide" },
      { rank: 2, domain: "waterwise.example", url: "https://waterwise.example/b", title: "Sizing a rain barrel by roof area" },
      { rank: 3, domain: "fixture-content.example", url: "https://fixture-content.example/rain-barrels", title: "Rain Barrels" }] }] };
  const titleSeam: CompleteFn = async ({ kind }) => { bought.push(kind); return { value: { field: "title", before: null, after: TITLE_AFTER, rationale: "The current copy does not say what the page answers.", ...TAIL } as never }; };
  it("produces the same title change, the same label, the same effort and the same risk as before", async () => {
    const out = await produceBundleForSnapshot(snapshot({ research: SERP }), { now: NOW, bypassCache: true, complete: titleSeam }); expect(out.status).toBe("bundled");
    if (out.status !== "bundled") return; const p = out.proposal; expect(p.bundle!.components.map((c) => c.kind)).toEqual(["title"]);
    expect(p.recommendedChange).toEqual({ kind: "existing_edit", field: "title", before: "Rain Barrels", after: TITLE_AFTER }); expect(p.opportunityType).toBe("Rewrite the page that already has the demand"); expect([p.diagnosisCause, p.estimatedEffortMinutes, p.riskLevel, p.status]).toEqual(["ctr_snippet", 1, "low", "ready"]);
    expect(p.bundle!.risks[0]).toBe("Changing a title moves where the page ranks while search engines re-read it, so give this the full 28 days before you judge it."); expect(p.bundle!.risks[1]).toBe("This page's full body text is not on file, so read each line once before you paste it."); expect(bought).toEqual(["atomic_edit"]); });
  it("refuses a headline for a door that never measured a click, and buys nothing writing it", async () => {
    const door = { door: "coverage_verdict" as const, entry: "I gave this page my deepest read because my comparison named it.", evidence: { query: "rain barrel sizing", engine: null, promptText: null, competingUrls: [] as string[], window: null } };
    const out = await produceBundleForSnapshot(snapshot({ research: SERP }), { ...OPTS, complete: titleSeam, door, coverage: decided(pattern({ commonHeadings: [{ heading: "Rain barrel sizing", seenOn: [0, 1, 2] }], openingPattern: "" })) }); expect(out.status === "none" && out.reason).toContain("coverage of what it is missing, not a new headline"); expect(bought).toEqual([]); }); });
/** A FALL IS A SIZE, NOT A LEVER (2026-08-13). The deep read never handed the ladder the two windows, so the ONE door opened on a fall re-diagnosed every fallen page as if nothing about it had been measured, and the cause it names carried a refusal where its producer belongs. Every lever is asked BY NAME now, nothing falls through to more copy, and the research card standing in for the change survives its own results page arriving instead of leaving the queue the day the evidence lands. */ describe("a page that slipped down the results", () => {
  const DECLINE = { clicksNow: 60, clicksPrior: 300, positionNow: 9.4, positionPrior: 4.1, impressionsNow: 6100, impressionsPrior: 6200 }; const DOOR = { door: "recent_decline" as const, entry: "e", evidence: { query: "rain barrel sizing", engine: null, promptText: null, competingUrls: [] as string[], window: "the four weeks to 2026-07-28, against the four weeks before" } };
  const RES = { ...emptyResearchEvidence(), serpEvidence: [{ observedAt: null, query: "rain barrel sizing", aiOverview: [], aiMode: [], paa: [], related: [], organic: [{ rank: 1, domain: "gardenguide.example", url: "https://gardenguide.example/a", title: "Sizing a rain barrel" }, { rank: 2, domain: "waterwise.example", url: "https://waterwise.example/b", title: "Rain barrel sizing" }] }] };
  const fall = (over: Record<string, unknown> = {}) => produceBundleForSnapshot(snapshot({ research: RES }), { ...OPTS, complete: seam(), door: DOOR, decline: DECLINE, ...over }); const FELL: CauseFinding = { cause: "ranking_loss", action: null, evidenceKeys: ["demand-exact"], competingExplanations: [], notConsidered: [], falsifier: "f", explanation: "This page fell from position 4.1 to 9.4." };
  it("names the ONE page above it whose words are not on file, having ruled out every other lever, and the card for it outlives the results page landing", async () => {
    const out = await fall(); expect(out.status).toBe("none"); if (out.status !== "none") return;
    expect(out.reason).toBe('gardenguide.example sits at position 1 for "rain barrel sizing", above this page, and none of its words are on file, so what it does that this page does not cannot be named. Read https://gardenguide.example/a and the exact change lands here.');
    expect((out.considered ?? []).map((c) => c.option)).toEqual(["Settle which of your pages owns this search", "A sharper title or description", "Rebuild this page for what people searching it want", "Cover what the winning pages all cover", "Answer the search in this page's first lines"]);
    expect([out.considered!.map((c) => c.reason).join(" "), bought]).toEqual([expect.not.stringMatching(/write more|add more copy|[–—]/i), []]); // no lever the evidence could pick, so no drafter was ever paid
    const cards = researchingCards({ tenantId: TENANT, now: NOW, basis: null, pages: [page()], judged: [{ cause: FELL, recoverableClicks: 240, pageUrl: URL, query: "rain barrel sizing", gap: "recent_decline" }], queryKeyOf: (q) => q, skip: new Set<string>(), serpQueryKeys: new Set(["rain barrel sizing"]), blocked: new Map([[URL, { reason: out.reason, considered: out.considered }]]) }); // THE CARD SURVIVES THE EVIDENCE ARRIVING: it is gated on there being no card for this page, never on nobody having bought that search's results page.
    expect([cards.length, cards[0]!.recommendedChange, cards[0]!.research?.missing, cards[0]!.limitations[0], cards[0]!.operatorSteps![0]], "the assignment lives in the research field and the copy field says only that its words are not written").toEqual([1, { kind: "existing_edit", field: "section", before: null, after: "The exact wording has not been written yet." }, out.reason, "Nothing here is ready to paste: this card is research, not an edit.", out.reason]); });
  it("never requires a reading of a robots-blocked winner: the requirement moves to the next unread page instead of minting the same impossible acquisition forever", async () => {
    const RES2 = { ...RES, winningPages: [{ url: "https://gardenguide.example/a", domain: "gardenguide.example", engines: [], examplePrompts: [], appearances: [], extract: null,
      readOutcome: { state: "robots_blocked" as const, at: "2026-07-01T00:00:00.000Z", retryAfter: "2036-07-01T00:00:00.000Z" } }] };
    const out = await produceBundleForSnapshot(snapshot({ research: RES2 as never }), { ...OPTS, complete: seam(), door: DOOR, decline: DECLINE }); expect(out.status).toBe("none"); if (out.status !== "none") return; expect(out.requirement).toEqual({ kind: "competitor_page", query: "rain barrel sizing", url: "https://waterwise.example/b", reasonCode: "winner_unread" }); });
  it("writes the subject the winning pages agree on rather than refusing the fall, and the rejected levers travel with it", async () => {
    const out = await fall({ coverage: decided(pattern({ commonHeadings: [{ heading: "Gutter guards keep debris out", seenOn: [0, 1, 2] }] })) }); expect(out.status).toBe("bundled"); if (out.status !== "bundled") return; expect([out.proposal.diagnosisCause, out.proposal.bundle!.components.map((c) => c.kind)]).toEqual(["ranking_loss", ["section_add"]]);
    expect(out.proposal.bundle!.alternatives.map((a) => a.option)).toContain("A sharper title or description"); }); });
/** A CONTENT GAP IS DIAGNOSED, NEVER COUNTED (operator, 2026-09-01). Word count authorized this card twice, first a flat 200 then a demand-scaled floor, and both were the same mistake: a 150-word page can be complete and a 1,500-word one can miss the question that matters. What authorizes an expansion is a NAMED missing subject the winners of this page's own search agree on carrying and the page's stored outline does not; the card names the exact subjects, and "add N words" is gone from the product's mouth. */ describe("an expansion is authorized by a named missing subject, never a word count", () => {
  const pageOf = (words: number, outline: string[]): OwnedPageEvidence => ({
    url: "https://fixture-content.example/comedians", content: { title: "Iranian comedians", metaDescription: "d", h1: "Iranian comedians", h2: [], outline, schemaTypes: [], hasFaq: false, faqCount: 0, wordCount: words, internalLinks: [], fetchedAt: "2026-07-20T00:00:00.000Z" },
    search: { clicks90d: 10, impressions90d: 22_509, ctr90d: 0.01, position90d: 8, topQueries: [{ query: "iranian comedians", impressions: 22_509, clicks: 10, position: 8 }] }, engagement: null, friction: null, aiCitations: { count: 0, distinctPrompts: 0, engines: [] } });
  const research = { ...emptyResearchEvidence(),
    serpEvidence: [{ observedAt: null, query: "iranian comedians", aiOverview: [], aiMode: [], paa: [], related: [], organic: [
      { rank: 1, domain: "a.example", url: "https://a.example/1", title: "Best Iranian comedians" }, { rank: 2, domain: "b.example", url: "https://b.example/2", title: "Iranian comedy stars" }] }], // winners that NAME the page's subject: the fit gate refuses a results page about something else
    winningPages: [
      { url: "https://a.example/1", domain: "a.example", engines: [], examplePrompts: [], appearances: [], extract: { title: "C", h1: null, wordCount: 900, headings: ["Stand-up specials to watch", "Where to see live shows"], faqCount: 0, entityNames: [], openingSample: "", hasList: true }, extractState: "current" },
      { url: "https://b.example/2", domain: "b.example", engines: [], examplePrompts: [], appearances: [], extract: { title: "C2", h1: null, wordCount: 800, headings: ["Stand-up specials to watch"], faqCount: 0, entityNames: [], openingSample: "", hasList: false }, extractState: "current" }] };
  const run = async (page: OwnedPageEvidence, r: unknown) => { vi.resetModules();
    vi.doMock("@/domains/decision/proposal-store", async (orig) => ({ ...(await orig<Record<string, unknown>>()), loadChangeProposals: async () => new Map() }));
    return (await import("@/domains/decision/producers/extra")).extraQueueCards({ tenantId: TENANT, snapshot: snapshot({ ownedPages: [page], research: r as never }) as never, now: NOW, reads: { left: 0 }, persist: false }); };
  /** A CARD THAT CARRIES NO CAUSE IS A CARD THE SCREEN CANNOT EXPLAIN (live, 2026-09-04). Thirty-two live descriptions were minted off a named defect in the page's own line and carried none, so the receipt printed "No cause is named for it yet" over a finding the card's own headline states, and the wording gate went on holding every replacement "until a diagnosis names what is wrong with the current description". */ it("mints the missing description carrying its own typed cause, so the receipt explains it and never says nothing is named", async () => {
    const bare = { ...pageOf(900, ["Iranian comedians"]), content: { ...pageOf(900, ["Iranian comedians"]).content!, metaDescription: null } };
    const card = (await run(bare, research)).cards.find((c) => c.id.endsWith("::missing_description"))!;
    const seen = (p: ChangeProposal) => proofOf({ ...p, rankingReceipt: { score: 1, directional: true, basis: "no proven click figure", factors: [] } }).ranksHere ?? "";
    expect([card.causeFinding?.cause, card.diagnosisCause, card.causeFinding?.evidenceKeys.length ?? 0, seen(card).includes("carries no description of its own"), seen(card).includes("No cause is named")], "the finding the card was made from, said in the ladder's own vocabulary, and printed instead of the shrug").toEqual(["ctr_snippet", "ctr_snippet", 2, true, false]);
    expect(seen({ ...card, causeFinding: undefined, diagnosisCause: undefined }), "and the shrug is exactly what a causeless row still prints, so this proves the cause and not the clause").toContain("No cause is named"); });
  it("a results page about a different subject shapes nothing here, whatever it contains", async () => {
    const foreign = { ...research, serpEvidence: [{ ...research.serpEvidence[0]!, organic: [{ rank: 1, domain: "a.example", url: "https://a.example/1", title: "Premier league fixtures this week" }, { rank: 2, domain: "b.example", url: "https://b.example/2", title: "Stadium seating guide" }] }] };
    const out = await run(pageOf(150, ["Iranian comedians"]), foreign); expect(out.cards.some((c) => c.id.endsWith("::thin_page")), "winners that never name this page's subject authorize no shaping").toBe(false); });
  it("mints the card naming the winners' shared subject the page lacks, and word count decides nothing either way", async () => {
    const short = await run(pageOf(150, ["Iranian comedians"]), research); // 150 words, but the SUBJECT is missing: minted, and the card names it
    const card = short.cards.find((c) => c.id.endsWith("::thin_page")); expect([!!card, card?.research?.missing?.includes("Stand-up specials to watch") ?? false, (card?.recommendedChange as { after?: string } | undefined)?.after], "minted naming the exact missing subject, never a word target, in the TYPED BRIEF: `after` means the exact copy to paste, so a card with no copy yet says exactly that there").toEqual([true, true, "The exact wording has not been written yet."]);
    expect(card?.research?.missing ?? "", "no word count is ever the instruction").not.toMatch(/\d+\s*(?:to|-)\s*\d+\s*words|words to/);
    const covered = await run(pageOf(150, ["Iranian comedians", "Stand-up specials to watch", "Where to see live shows"]), research); // SAME 150 words, subjects carried: no card
    expect(covered.cards.some((c) => c.id.endsWith("::thin_page")), "a page carrying the winners' subjects mints nothing at any length").toBe(false);
    const noSerp = await run(pageOf(150, ["Iranian comedians"]), emptyResearchEvidence()); // no stored results page: no named gap is possible, so nothing is minted
    expect(noSerp.cards.some((c) => c.id.endsWith("::thin_page")), "no results page, no diagnosis, no card").toBe(false); });
});
/** SUPPRESSION IS BY THE MUTATION A ROW WRITES (operator, 2026-08-31). Page plus action family let ONE measuring section on /cities block every further section that page could earn, whatever its topic: the site's two largest expansion opportunities were invisible behind rows about different subjects. The footprint separates body topics, so only a genuine collision suppresses. */ describe("a standing section on one topic never suppresses a new section on another", () => {
  it("mints the second topic's card beside a measuring first topic, and still refuses a true duplicate", async () => {
    const at = "https://fixture-content.example/cities"; const standing = { id: `${TENANT}::/cities::existing_edit::ai_answer_gap`, tenantId: TENANT, kind: "existing_edit" as const, pagePath: "/cities", pageUrl: at, pageLabel: "Cities", primaryQuery: "best cities in iran", opportunityType: "Capture clicks",
      changeFamily: "section", status: "implemented_pending_verification" as const, researchOnly: false, whyItMatters: "w", estimatedEffortMinutes: 5, riskLevel: "low" as const, confidence: "medium" as const, limitations: [], evidence: { query: "best cities in iran", hints: [], evidenceRefCount: 1 }, impactScore: 10, upsidePerMonth: null, publish: "manual" as const, createdAt: "2026-07-25T00:00:00.000Z",
      recommendedChange: { kind: "existing_edit" as const, field: "section" as const, before: null, after: "Shiraz, Isfahan and Tabriz each reward a different kind of visit." } } as never;
    vi.resetModules(); vi.doMock("@/domains/decision/proposal-store", async (orig) => ({ ...(await orig<Record<string, unknown>>()), loadChangeProposals: async () => new Map([[(standing as { id: string }).id, standing]]) }));
    const { extraQueueCards } = await import("@/domains/decision/producers/extra"); const page = { url: at, content: { title: "Cities of Iran", metaDescription: "d", h1: "Cities of Iran", h2: [], outline: ["Cities of Iran"], schemaTypes: [], hasFaq: false, faqCount: 0, wordCount: 500, internalLinks: [], fetchedAt: "2026-07-20T00:00:00.000Z" },
      search: { clicks90d: 100, impressions90d: 28_847, ctr90d: 0.003, position90d: 9, topQueries: [{ query: "cities in iran", impressions: 28_847, clicks: 100, position: 9 }] }, engagement: null, friction: null, aiCitations: { count: 0, distinctPrompts: 0, engines: [] } };
    const serp = { ...emptyResearchEvidence(), serpEvidence: [{ observedAt: null, query: "cities in iran", aiOverview: [], aiMode: [], paa: [], related: [], organic: [{ rank: 1, domain: "rival.example", url: "https://rival.example/a", title: "Cities" }, { rank: 2, domain: "other.example", url: "https://other.example/b", title: "Cities 2" }] }],
      winningPages: [ // the diagnosed contract needs a NAMED missing subject the winners agree on, not a word count
        { url: "https://rival.example/a", domain: "rival.example", engines: [], examplePrompts: [], appearances: [], extractState: "current", extract: { title: "C", h1: null, wordCount: 900, headings: ["Largest cities by population"], faqCount: 0, entityNames: [], openingSample: "", hasList: true } },
        { url: "https://other.example/b", domain: "other.example", engines: [], examplePrompts: [], appearances: [], extractState: "current", extract: { title: "C2", h1: null, wordCount: 800, headings: ["Largest cities by population"], faqCount: 0, entityNames: [], openingSample: "", hasList: false } }] };
    const out = await extraQueueCards({ tenantId: TENANT, snapshot: snapshot({ ownedPages: [page], research: serp as never }) as never, now: NOW, reads: { left: 0 }, persist: false }); expect(out.cards.some((c) => c.id.endsWith("::thin_page") && c.pagePath === "/cities"), "the 500-word page under 28,847 impressions earns its expansion card despite the measuring section on another topic").toBe(true); });
});
/** THE PAGE'S OWN UNANSWERED DEMAND IS BODY WORK (operator, 2026-09-02). The largest opportunities on a live account are questions Google already sends a page and the page never answers: 29,965 impressions on a flag page that never says "before", 6,927 asking which animal is Iran's national one. No cause payload names one, so no producer minted a body card for them and they never entered the paid plan at all. AND THE MINT READS WHAT THE WALK READS (reviewer, 2026-09-02): the same stored body, the same checked statements and the same ownership ruling, so a card is never minted off a title and settled terminal seconds later, and the typed step it lands with is the one on file next pass. */ describe("a search a page earns and never answers becomes one funded answer block", () => {
  const pg = (path: string, title: string, rows: Array<[string, number, number?]>, imps: number): OwnedPageEvidence => ({ url: `https://fixture-content.example${path}`, content: { title, metaDescription: "d", h1: title, h2: [], outline: [], schemaTypes: [], hasFaq: false, faqCount: 0, wordCount: 900, internalLinks: [], fetchedAt: "2026-07-20T00:00:00.000Z" }, search: { clicks90d: 10, impressions90d: imps, ctr90d: 0.01, position90d: 8, topQueries: rows.map(([query, impressions, position]) => ({ query, impressions, clicks: 1, ...(position === undefined ? {} : { position }) })) as never }, engagement: null, friction: null, aiCitations: { count: 0, distinctPrompts: 0, engines: [] } });
  const FLAG = pg("/iran-flags/history", "Iran Islamic Republic Flag History", [["iran flag before 1979", 1214, 8]], 29_965), CAT = pg("/iran-animals/asiatic-cheetah", "Asiatic Cheetah", [["iran national animal", 3502, 8], ["national animal of iran", 2846, 8], ["what is the national animal of iran", 579, 8]], 14_467), TEH = pg("/tehran", "Tehran", [["capital of iran", 310, 8], ["iran capital", 129, 8]], 8531), PHRASES = pg("/funny-farsi-phrases", "Funny Farsi Phrases", [["kire khar meaning", 174, 8]], 54_820), KIT = pg("/jersey-evolution", "Iran World Cup Kit Evolution", [["iran kit history", 261, 8]], 9343), NAMES = pg("/persian-girl-names", "Persian Girl Names And Their Meanings: Bahar, Delnaz", [["what does bahar mean", 800, 8]], 12_000), CARPET = pg("/iran-carpets", "Iran Carpets", [["what is the largest carpet factory in iran", 900, 8]], 12_000), LABELS = pg("/iran-history", "Iran History", [["what are the historical facts about iran", 700, 8]], 9000); // "history" and "mean" are labels for what these pages already are and no section closes a label; "factory" is a subject the stem list used to swallow whole; "historical" and "facts" are labels again, which the inflection rule alone never reached
  const stored = (path: string, passage: string): [string, unknown] => [`fixture-content.example${path}`, { url: `https://fixture-content.example${path}`, openingSample: passage, fetchedAt: "2026-07-20T00:00:00.000Z", cardTexts: [], entityNames: [], headings: [], passages: [passage], completeness: "complete", internalLinks: [], metaDescription: null, title: "", h1: "", vocabulary: "" }];
  const standingBody = (status: string) => ({ id: `${TENANT}::/iran-animals/asiatic-cheetah::existing_edit::ai_answer_gap`, tenantId: TENANT, kind: "existing_edit" as const, pagePath: "/iran-animals/asiatic-cheetah", pageUrl: CAT.url, pageLabel: "Asiatic Cheetah", primaryQuery: "iran national animal", opportunityType: "o", changeFamily: "section", status, researchOnly: false, whyItMatters: "w", estimatedEffortMinutes: 5, riskLevel: "low" as const, confidence: "medium" as const, limitations: [], evidence: { query: "iran national animal", hints: [], evidenceRefCount: 1 }, impactScore: 10, upsidePerMonth: null, publish: "manual" as const, createdAt: "2026-07-25T00:00:00.000Z", recommendedChange: { kind: "existing_edit" as const, field: "section" as const, before: null, after: "The Asiatic cheetah is Iran's national animal." } });
  const run = async (pages: OwnedPageEvidence[], standing: unknown[] = [], bodies: Array<[string, unknown]> = [], cann: unknown[] = [], miss?: "no_capture" | "read_failed") => { vi.resetModules();
    vi.doMock("@/domains/decision/proposal-store", async (orig) => ({ ...(await orig<Record<string, unknown>>()), loadChangeProposals: async () => new Map((standing as { id: string }[]).map((r) => [r.id, r])) })); vi.doMock("@/domains/evidence/pages/owned-context", async (orig) => ({ ...(await orig<Record<string, unknown>>()), loadOwnedPageBodies: async (_t: string, urls: string[], misses?: Map<string, string>) => { if (miss) for (const u of urls) misses?.set(u.replace(/^https?:\/\//, ""), miss); return new Map(bodies as [string, never][]); } }));
    const out = await (await import("@/domains/decision/producers/extra")).extraQueueCards({ tenantId: TENANT, snapshot: snapshot({ ownedPages: pages, cannibalization: cann as never }) as never, now: NOW, reads: { left: 0 }, persist: false });
    return out.cards.filter((c) => c.id.endsWith("::missing_answer")); };
  it("mints one research card a page, ranked on the whole demand behind the answer, declares them all and buys nothing", async () => { const cards = await run([FLAG, CAT, TEH, PHRASES, KIT, NAMES, LABELS]); const cat = cards.find((c) => c.pagePath === "/iran-animals/asiatic-cheetah")!;
    const answered = await run([FLAG, CAT, TEH, PHRASES, KIT, NAMES, LABELS], [], [stored("/persian-girl-names", "Bahar means spring in Persian, and Delnaz means beloved."), stored("/iran-history", "Iran's history runs from Elam through the Achaemenids to the Islamic Republic.")]);
    expect([cards.length, cards.map((c) => c.pagePath), answered.map((c) => c.pagePath)], "one card a page, strongest demand first, and A PAGE CLAIMS NO ABSENCE UNTIL ITS OWN WORDS ARE ON FILE: with nothing captured every asking search is unknown and owes the capture, and once the words are there the two pages whose own passages answer the search in one place mint nothing at all").toEqual([6, ["/iran-animals/asiatic-cheetah", "/iran-flags/history", "/persian-girl-names", "/iran-history", "/tehran", "/funny-farsi-phrases"], ["/iran-animals/asiatic-cheetah", "/iran-flags/history", "/tehran", "/funny-farsi-phrases"]]);
    expect([cat.primaryQuery, cat.changeFamily, cat.treatment, cat.researchOnly, cat.diagnosisCause, cat.opportunityType.includes("6,927 searches"), (cat.impactScore ?? 0) > 0, withholdReason(cat, "incomplete_coverage"), writerKindOf(cat), withholdReason({ ...cat, treatment: undefined, recommendedChange: { kind: "existing_edit", field: "answer_block", before: null, after: "NAME (SOUND) is the Persian word for spring." } } as never, "incomplete_coverage") == null, withholdReason({ ...cat, bundle: { components: [{ kind: "opening_answer", before: null, after: "y", evidenceKeys: [], risk: "low" }] } } as never, "incomplete_coverage") != null], "the strongest unanswered search, an answer block the boundary admits for THIS card alone and the plan reads as editor work, research until a source lands, the three ways one answer is asked counted together, and the bundle carrying an opening still held back; a treatmentless body answer is NOT (reviewer, 2026-09-03): filing a headless answer under its real field must not decide what it may treat, and demand recovery and suggested edits both mint body rows with no treatment at all, so the field-name guard is gone and the gain gates police whether such a row adds anything").toEqual(["iran national animal", "answer_block", "add_answer_section", true, "incomplete_coverage", true, true, null, "answer", true, true]);
    const budget = DRAFT_BUDGET.plan({ jobs: cards.map((c) => ({ key: DRAFT_BUDGET.keyOf(c), family: "editor" as const, impact: c.impactScore ?? 0, calls: DRAFT_BUDGET.DELIVERABLE_CALLS })), candidates: cards.length, calls: 30 }); let bought = 0; const owed: string[] = []; const rows = await applyDraftedCopy(cards as never, { tenantId: TENANT, snapshot: snapshot({ ownedPages: [FLAG, CAT, TEH, PHRASES] }) as never, now: NOW, budget, owe: (k: string) => owed.push(k), complete: async () => (bought += 1, { value: {} }) } as never);
    expect([budget.declared.length, budget.funded.length, bought], "every card declared, every one funded by rank, and not one paid call made on the way").toEqual([6, 6, 0]); const owes = (r: { obligation?: unknown }) => (r.obligation as { kind: string; need?: { kind: string } } | undefined);
    expect([rows.every((r) => r.researchOnly === true), rows.map((r) => owes(r)?.need?.kind), owed.length, rows.map((r) => nextObligation(r)), cards.map((c) => nextObligation(c))], "every row comes back research owing exactly one typed reading of its own page, never a source for a page whose words are not on file; the same reading is filed on the key the runtime buys from, once per page this pass actually holds; and the un-walked mint already answers that reading, so a second pass writes the same row rather than stamping a draft over it").toEqual([true, rows.map(() => "page_source"), 4, rows.map((r) => r.obligation), rows.map((r) => r.obligation)]); });
  it("mints nothing behind a body change already on file for that answer, whether it is waiting to be read or already being measured", async () => { expect([(await run([CAT], [standingBody("needs_review")])).length, (await run([CAT], [standingBody("implemented_pending_verification")])).length], "one mutation, one row: a change already writing this page's answer to this search is not written twice, and a shipment under measurement is left alone").toEqual([0, 0]);
    expect((await run([CAT], [{ ...standingBody("needs_review"), id: `${TENANT}::/iran-animals/asiatic-cheetah::existing_edit::other`, primaryQuery: "asiatic cheetah habitat" }])).length, "and a body change about another question suppresses nothing").toBe(1); });
  it("reads the whole stored page, lets a real subject past the label list, ranks a row with no position, and gives one search to one page", async () => { expect([(await run([CARPET])).length, (await run([CARPET], [], [stored("/iran-carpets", "Iran's largest carpet factory is the Tehran works.")])).length], "the one absent word is a subject no label governs, and the same page mints nothing once its own stored words answer the search").toEqual([1, 0]);
    const noPos = pg("/tehran", "Tehran", [["capital of iran", 310]], 8531), cities = pg("/iran-cities", "Iran Cities", [["capital of iran", 300, 4]], 5000); expect((await run([noPos]))[0]!.impactScore, "a winning row with no position ranks on the best receipt position this page holds rather than on nothing").not.toBe(null);
    expect([(await run([noPos, cities], [], [], [{ query: "capital of iran", competingUrls: [noPos.url, cities.url], impressions: 610, clicks: 2 }])).map((c) => c.pagePath), (await run([cities, noPos])).map((c) => c.pagePath)], "the page the ladder proves owns the search is the only one that answers it, and with no ladder entry the page with the most demand for it takes the card whatever order the snapshot lists them in").toEqual([["/iran-cities"], ["/tehran"]]);
    expect([(await run([CARPET], [], [], [], "read_failed")).length, (await run([CARPET], [], [], [], "no_capture")).length, (await run([pg("/iran-tea", "Iran Tea", [["what is the national drink of iran", 12, 8], ["is tea grown in iran", 9, 8]], 900)])).length], "I COULD NOT LOOK IS NOT THIS PAGE DOES NOT ANSWER: a page whose body read refused is unknown and mints nothing, one with nothing on file still mints and owes its own capture, and a handful of impressions is noise on any page, because the floor is asked of the SEARCH").toEqual([0, 1, 0]);
    const SNAKE = "This entry profiles a venomous snake of the Persian plateau.", COBRA = pg("/iran-animals/persian-cobra", "Persian Cobra", [["are there cobras in iran", 900, 8]], 12_000), hires = (verdict: string, rulesVersion = 5) => (substantiveGapOf({}, demandOf(COBRA, stored("/iran-animals/persian-cobra", SNAKE)[1] as never, [{ page: "/iran-animals/persian-cobra", statementKey: "gap", subject: "are there cobras in iran", current: "", proposed: "Iran has AH-1 Cobra attack helicopters.", verdict, confidence: "confirmed", state: "checked", rulesVersion, sourceReadAt: NOW.toISOString(), evidenceBasis: null, pageContentHash: pageHashOf(SNAKE), pageLocator: "missing", sources: [{ url: "https://en.wikipedia.org/x", kind: "encyclopedia", says: "Iran operates AH-1 Cobra attack helicopters." }], agreement: "single_source", literal: null, usage: null, alsoAt: [], note: "", checkedAt: NOW.toISOString() }] as never, null, TENANT))?.owed as { need?: { kind: string } } | undefined)?.need?.kind;
    expect([hires("undecidable"), hires("page_correct"), hires("page_correct", VERIFICATION_RULES_VERSION)], "THE HIRE REFUSES WHAT THE DOOR REFUSES: a confirmed reading the judge would not call an answer never becomes this page's fact, so the row keeps owing a source, only an answer about this page's own subject hires the writer, and a question judged under the rules that let the helicopter sentence stand hires nobody until it is judged again").toEqual(["factual_source", undefined, "factual_source"]); });
});

/** THE VERDICT IS WHAT THE PAGE IS DOING WITH THE SEARCH, NEVER WHICH WORDS IT LACKS (probe 7, 2026-09-05). Two synthetic accounts, unrelated subjects, nothing in here names a real customer, language or page family. */
describe("a search a page already earns is classified against the page's own passages", () => {
  const OWNED = (t: string, path: string, title: string, rows: Array<[string, number]>): OwnedPageEvidence => ({ url: `https://${t}.example${path}`, content: { title, metaDescription: "d", h1: title, h2: [], outline: [], schemaTypes: [], hasFaq: false, faqCount: 0, wordCount: 400, internalLinks: [], fetchedAt: NOW.toISOString() }, search: { clicks90d: 1, impressions90d: 900, ctr90d: 0.01, position90d: 8, topQueries: rows.map(([query, impressions]) => ({ query, impressions, clicks: 0, position: 8 })) }, engagement: null, friction: null, aiCitations: { count: 0, distinctPrompts: 0, engines: [] } });
  const BODY = (t: string, path: string, title: string, passages: string[], complete = true): unknown => ({ url: `https://${t}.example${path}`, title, h1: title, metaDescription: null, headings: [], passages, vocabulary: "", cardTexts: [], faqs: [], entityNames: [], internalLinks: [], openingSample: passages[0] ?? null, fetchedAt: NOW.toISOString(), completeness: complete ? "complete" : "partial", contentHash: "h", heldNote: null });
  const verdictOf = (t: string, path: string, title: string, rows: Array<[string, number]>, passages: string[], complete = true): string =>
    substantiveGapOf({}, demandOf(OWNED(t, path, title, rows), BODY(t, path, title, passages, complete) as never, [], null, t))?.kind ?? "answered";
  const SITES = [
    { t: "tenant-one", path: "/rock-pools", title: "Rock pools of the north coast: starfish, mussels and winter water", answered: "are there starfish in rock pools", one: "Starfish cling to rock pools all along the north coast and feed on mussels at low tide.",
      spread: "how cold is the water in winter", also: "how cold is the winter water", a: "The water here stays under ten degrees.", b: "Winter storms scour the ledges.", promised: "which mussels live in the north coast pools", absent: "how deep is the harbour channel" },
    { t: "tenant-two", path: "/bordado", title: "Bordado stitches: punto cadena, thread counts and border widths", answered: "what does punto cadena mean", one: "Punto cadena means chain stitch, worked as a row of linked loops.",
      spread: "how many threads does a wide border take", also: "how many wide borders take threads", a: "A border uses six threads.", b: "Wide panels are worked flat.", promised: "how many threads does a border count take", absent: "which loom weaves the widest cloth" },
  ];
  it.each(SITES)("answers, scatters, promises, misses or does not know, on $t", (s) => {
    const at = (q: string, passages: string[], complete = true, n = 900): string => verdictOf(s.t, s.path, s.title, [[q, n]], passages, complete);
    expect([at(s.answered, [s.one]), at(s.spread, [s.a, s.b]), at(s.promised, []), at(s.absent, [s.a, s.b]), at(s.answered, [s.one], false)],
      "one passage carrying what the search names is an answer and owes no paragraph even when a word of the question is missing from the page; the same answer in pieces is a restructuring; a title that says it where no passage delivers it is a false promise; a search nothing on the page carries is missing; and a page whose own words are not all on file is not known either way")
      .toEqual(["answered", "scattered_answer", "false_page_promise", "missing_answer", "unknown_capture"]);
    const owed = (kind: string, complete: boolean): unknown => (substantiveGapOf({}, demandOf(OWNED(s.t, s.path, s.title, [[s.absent, 900]]), BODY(s.t, s.path, s.title, [s.a], complete) as never, [], null, s.t))?.owed as { need?: { kind: string } } | undefined)?.need?.kind ?? kind;
    expect([owed("none", true), owed("none", false)], "a missing answer with nothing checked on file is research for a source, and an unread page is research for its own capture").toEqual(["factual_source", "page_source"]);
    expect([verdictOf(s.t, s.path, s.title, [[s.spread, 20]], [s.a, s.b]), verdictOf(s.t, s.path, s.title, [[s.spread, 20], [s.also, 20]], [s.a, s.b])],
      "two ways of asking one question are one thing a reader wants to know, so the floor is asked of the group and never of a single phrasing").toEqual(["answered", "scattered_answer"]);
  });
  it.each(SITES)("a relational word the searcher used must be matched by the text that claims to answer, on $t", (s) => {
    /* "iran flag before 1979" read as answered by a passage about the flag SINCE 1979 (reviewer, 2026-09-05): the page's own subject words satisfied the ratio and the one word carrying the question was absent. */
    const subject = s.t === "tenant-one" ? "rock pools" : "bordado stitches", since = `The ${subject} have changed twice since 1990.`, at = (q: string, passages: string[]): string => verdictOf(s.t, s.path, s.title, [[q, 900]], passages);
    expect([at(`${subject} before 1990`, [since]), at(`${subject} after 1990`, [`The ${subject} have changed twice after 1990.`]), at(`${subject} before 1990`, [`In 1990 the ${subject} were nothing like today.`, `Before 1990 they were wider.`])],
      "a passage about what the subject has been since a date does not answer what it was before it, however many of the subject's own words it repeats; a passage carrying the searcher's relational word answers; and the relational word in one passage beside the subject in another is a restructuring")
      .toEqual(["missing_answer", "answered", "scattered_answer"]); });
  it.each(SITES)("a word that names the SHAPE of the answer is asked of neither side of the coverage rule, on $t", (s) => {
    /* THE ONE-WORD REPAIR NO TEST DEFENDED (round-three reviewer, mutation proof, 2026-09-05): `relates` was taken from the whole ask while the subject list had the shape words removed, so a word like "meaning" was struck out of the denominator and left in the numerator, and a page answering the question in its own words was called missing for not carrying the label. Reverting that one word left all 1,432 tests green, on a line with no headroom. This is the counterexample: the label is dropped from BOTH sides, and a relational word that names no shape is still required by the pin above. */
    const subject = s.t === "tenant-one" ? "rock pools" : "bordado stitches", said = s.t === "tenant-one" ? "Rock pools are hollows in the ledge that hold seawater between the tides." : "Bordado stitches are worked as rows of linked loops across a stretched cloth.";
    const at = (q: string, passages: string[]): string => verdictOf(s.t, s.path, s.title, [[q, 900]], passages);
    expect([at(`${subject} meaning`, [said]), at(`${subject} history`, [said]), at(`${subject} versus canvas work`, [said])],
      "a search asking what the subject means is answered by a passage that says what it is, whatever word it says it in; the same holds for a label naming a shape of answer; and a relational word that names a comparison rather than a shape is still owed literally")
      .toEqual(["answered", "answered", "missing_answer"]); });
  it.each(SITES)("names the opportunity instead of briefing the writer at the customer, and lets a zero suppress the clause that ranks it, on $t", async (s) => {
    /* TWO DEFECTS THE RENDERED APP CAUGHT ON 2026-09-05, both on the same live card. Four applied descriptions were recorded as "Write a real description on <address>: 5 pages share one templated line", which is the writer's brief with a raw address in it, printed where the customer reads what the work IS. And the reason under it said a page "is the busiest of them at 0 impressions in 90 days", which ranks a page on a figure that says it ranks nothing. */
    vi.resetModules(); vi.doMock("@/domains/decision/proposal-store", async (orig) => ({ ...(await orig<Record<string, unknown>>()), loadChangeProposals: async () => new Map() }));
    const kin = (n: number, i: number): OwnedPageEvidence => ({ url: `https://${s.t}.example/group/${i}`, content: { title: `Entry ${i}`, metaDescription: `Everything worth knowing about entry ${i}, gathered here with the notes and the details that go with each one.`, h1: `Entry ${i}`, h2: [], outline: [], schemaTypes: [], hasFaq: false, faqCount: 0, wordCount: 400, internalLinks: [], fetchedAt: NOW.toISOString() }, search: { clicks90d: 0, impressions90d: n, ctr90d: 0, position90d: 9, topQueries: n > 0 ? [{ query: `entry ${i}`, impressions: n, clicks: 0, position: 9 }] : [] }, engagement: null, friction: null, aiCitations: { count: 0, distinctPrompts: 0, engines: [] } });
    const pages = [140, 0, 12, 9, 7].map(kin), out = await (await import("@/domains/decision/producers/extra")).extraQueueCards({ tenantId: s.t, snapshot: { ...snapshot({ ownedPages: pages }), scope: { tenantId: s.t, site: `${s.t}.example`, builtAt: NOW.toISOString() } } as never, now: NOW, reads: { left: 0 }, persist: false });
    const at = (i: number): ChangeProposal => out.cards.find((c) => c.pagePath === `/group/${i}` && c.id.endsWith("::missing_description"))!;
    expect([at(0).opportunityType, /(^|\s)\//.test(at(0).opportunityType), /^(?:Write|Read|Give|Cover|Link|Answer|Bring|Add|Rewrite) /.test(at(0).opportunityType)],
      "the name says what the work is and for whom, carries no address a person would have to decode, and never opens as an order to the writer")
      .toEqual(["A search description of this page's own, where 5 pages share one line", false, false]);
    expect([at(0).whyItMatters.includes("is the busiest of them at 140 impressions in 90 days"), /busiest/.test(at(1).whyItMatters), /0 impressions/.test(at(1).whyItMatters)],
      "a real figure ranks the page it belongs to, and the page with no figure at all keeps the sentence its evidence carries and loses the clause that ranked it")
      .toEqual([true, false, false]); });
  it.each(SITES)("counts a figure the page's own captured words already carry as delivered rather than asking a person to confirm it, on $t", (s) => {
    const line = `${s.title.split(":")[0]}: the 40+ entries this page keeps, with what each one is for.`;
    const canon = (pageBodyText: string): string[] => validateProposal({ id: `${s.t}::${s.path}::existing_edit::missing_description`, tenantId: s.t, kind: "existing_edit", pagePath: s.path, pageUrl: `https://${s.t}.example${s.path}`, pageLabel: s.title, primaryQuery: s.answered, opportunityType: "o", changeFamily: "meta", status: "needs_review", researchOnly: false, whyItMatters: "w", estimatedEffortMinutes: 1, riskLevel: "low", confidence: "medium", limitations: [], evidence: { query: s.answered, hints: [], evidenceRefCount: 1 }, impactScore: 1, upsidePerMonth: null, publish: "manual", createdAt: NOW.toISOString(), recommendedChange: { kind: "existing_edit", field: "meta", before: "Old line.", after: line } } as never, { pageBodyText, now: NOW }).reasons;
    expect([canon(`${s.one} There are 40+ entries listed here.`).some((r) => /count/i.test(r)), canon(s.one).some((r) => /count/i.test(r)), canon("").join(" ").includes("\u2014")],
      "a count the page carries in any punctuation is delivered and the canon says nothing; a count nothing on file carries still asks a person; and no refusal this canon writes carries a dash").toEqual([false, true, false]); });
});
