import { describe, expect, it } from "vitest"; import { componentIdOf, deserializeChangeProposal, serializeChangeProposal, type BundleComponent, type ChangeProposal } from "@/domains/decision/contracts";
import withDerivedFaqSchema from "@/domains/decision/derived-schema"; import type { OwnedPageBody } from "@/domains/evidence/pages/owned-context"; import proposalIdentity from "@/domains/decision/proposal-identity"; import { COPY_RULES } from "@/domains/decision/copy-sanitize";
const URL = "https://fixture.example/heriz", ANSWER = "Heriz rugs are woven in East Azerbaijan.";
const copy = (answer = ANSWER): string => `## Where are Heriz rugs made?\n\n${answer}`;
const fact = { key: "page-copy-1", fact: "Heriz rugs are woven in East Azerbaijan.", observedAt: null, kind: "page_extract" as const };
const component = (answer = ANSWER): BundleComponent => ({ kind: "section", label: "Where are Heriz rugs made?", before: "Heriz rugs are made in Iran.", after: copy(answer),
  units: [{ kind: "heading", level: 2, text: "Where are Heriz rugs made?" }, { kind: "paragraph", text: answer }], target: { mode: "replace", anchorKind: "heading", anchor: "Where are Heriz rugs made?" }, where: 'Replace the recorded original copy inside the section headed "Where are Heriz rugs made?"; preserve the rest of that section.', evidenceKeys: [fact.key], risk: "review" });
const proposal = (over: Partial<ChangeProposal> = {}): ChangeProposal => ({
  id: "t::/heriz::existing_edit::section", tenantId: "t", kind: "existing_edit", pagePath: "/heriz", pageUrl: URL, pageLabel: "Heriz", primaryQuery: "where are heriz rugs made", opportunityType: "Answer the question", changeFamily: "section", status: "ready", researchOnly: false,
  recommendedChange: { kind: "existing_edit", field: "section", before: "Heriz rugs are made in Iran.", after: component().after, units: component().units, target: component().target, where: component().where }, whyItMatters: "The answer should be complete.", estimatedEffortMinutes: 5, riskLevel: "low", confidence: "high", limitations: [], evidence: { query: "where are heriz rugs made", hints: [], evidenceRefCount: 1 }, impactScore: 10, upsidePerMonth: null, modeledOn: "the stored results page", claims: [{ text: ANSWER, supportedBy: [fact.key] }], supportFacts: [{ id: fact.key, fact: fact.fact }], publish: "manual", createdAt: "2026-09-19T00:00:00.000Z",
  bundle: { objective: "Answer the question completely.", metric: "qualified clicks", scope: { queries: ["where are heriz rugs made"], prompts: [] }, components: [component()], receipt: { items: [fact], missing: [], freshestObservedAt: null }, alternatives: [], risks: [], confidenceReasons: [], measurementPlan: "Measure after implementation." }, ...over });
const body = (jsonLd: string[] = []): OwnedPageBody => ({ tenantId: "t", url: URL, finalUrl: URL, pageId: "heriz", captureId: "heriz-v1", latestCaptureId: "heriz-v1", captureVersion: 1, title: "Heriz rugs", h1: "Heriz rugs", metaDescription: null, headings: ["Where are Heriz rugs made?"], passages: ["Heriz rugs are made in Iran."], openingSample: null, vocabulary: "Heriz rugs are made in Iran.", cardTexts: [], faqs: [{ question: "Where are Heriz rugs made?", answer: "Heriz rugs are made in Iran.", source: "html_section", answerComplete: true }], entityNames: [], internalLinks: [],
  sourceCapture: { version: 1, sourceRevision: "body-v1", mainHtml: "<main><h2>Where are Heriz rugs made?</h2><p>Heriz rugs are made in Iran.</p></main>", jsonLd, complete: true }, fetchedAt: "2026-09-19T00:00:00.000Z", completeness: "complete", contentHash: "body-v1", heldNote: "", version: "current" });
describe("visible copy and its derived FAQ schema", () => {
  it("keeps exact FAQ copy, sources and schema dependency revisions when unrelated work splits away", () => {
    const held = body(), section = component(), title: BundleComponent = { kind: "title", label: "Accurate title", before: held.title, after: "Heriz rugs from East Azerbaijan", evidenceKeys: [fact.key], risk: "safe" };
    const original = proposal({ reviewedCaptures: COPY_RULES.captureProof(held, Date.parse(held.fetchedAt!)), claims: [{ text: ANSWER, supportedBy: [fact.key], of: componentIdOf(section, 1) }], bundle: { ...proposal().bundle!, components: [title, section] } });
    const made = withDerivedFaqSchema(original, held), schema = made.bundle!.components[2]!, parent = serializeChangeProposal(made), rows = proposalIdentity.atomicRows(made), decoded = rows.map(row => deserializeChangeProposal(serializeChangeProposal(row))), linked = decoded[1]!;
    expect([made.id, schema.derivation?.operation, rows.map(row => row.bundle!.components.map(part => part.kind)), decoded.every(Boolean)]).toEqual(["t::/heriz::existing_edit::section::faq-sync-v1", "add", [["title"], ["section", "schema"]], true]);
    expect(JSON.parse(schema.after).mainEntity[0].acceptedAnswer.text).toBe(ANSWER); expect(deserializeChangeProposal(parent)?.bundle?.components[2]?.derivation).toEqual(schema.derivation);
    expect(linked.bundle!.components[1]!.derivation).toEqual({ ...schema.derivation, dependsOn: schema.derivation!.dependsOn.map(d => ({ ...d, componentId: componentIdOf(section, 0) })) });
    expect([linked.claims, linked.supportFacts, linked.reviewedCaptures]).toEqual([[{ ...made.claims![0], of: componentIdOf(section, 0) }], made.supportFacts, made.reviewedCaptures]); expect(linked.reviewedCaptures).toHaveLength(1);
    expect(serializeChangeProposal(made)).toBe(parent); expect(original.bundle!.components).toEqual([title, section]); expect(withDerivedFaqSchema(made, held)).toBe(made);
  });

  it("replaces an existing FAQ block from the finished copy and removes it only with its visible question", () => {
    const old = JSON.stringify({ "@context": "https://schema.org", "@type": "FAQPage", mainEntity: [{ "@type": "Question", name: "Where are Heriz rugs made?", acceptedAnswer: { "@type": "Answer", text: "Heriz rugs are made in Iran." } }] });
    const changed = withDerivedFaqSchema(proposal(), body([old])).bundle!.components[1]!;
    expect([changed.derivation?.operation, JSON.parse(changed.after).mainEntity[0].acceptedAnswer.text]).toEqual(["replace", ANSWER]);
    const removal = component("Remove this question from the visible page."); removal.kind = "section_remove"; removal.units = undefined;
    const removed = withDerivedFaqSchema(proposal({ bundle: { ...proposal().bundle!, components: [removal] } }), body([old]));
    expect([removed.bundle!.components[1]!.derivation?.operation, removed.bundle!.components[1]!.after, deserializeChangeProposal(serializeChangeProposal(removed)) != null]).toEqual(["remove", "", true]); const full = { ...component(), kind: "full_rewrite" as const, after: ANSWER, units: [{ kind: "paragraph" as const, text: ANSWER }], target: { mode: "whole_body" as const, anchorKind: null, anchor: null }, where: COPY_RULES.where({ mode: "whole_body", anchorKind: null, anchor: null }) }, whole = proposal({ changeFamily: "full_rewrite", recommendedChange: { ...(proposal().recommendedChange as Extract<ChangeProposal["recommendedChange"], { kind: "existing_edit" }>), kind: "existing_edit", after: ANSWER, units: full.units, target: full.target, where: full.where }, bundle: { ...proposal().bundle!, components: [full] } }), empty = { ...body([old]), faqs: [] }, synced = withDerivedFaqSchema(whole, empty); expect([synced.bundle!.components[1]!.derivation?.operation, synced.bundle!.components[1]!.derivation?.dependsOn[0]?.componentId]).toEqual(["remove", componentIdOf(full, 0)]);
  });

  it("keeps unrelated work unchanged and holds an unresolved whole-body FAQ transition without discarding its copy", () => {
    const fresh = proposal(), newPage = { ...fresh, kind: "new_page" as const, recommendedChange: { kind: "new_page" as const, proposedTitle: "Heriz rugs", metaDescription: "A complete guide to Heriz rugs and their weaving tradition.", openingAnswer: "Heriz rugs come from East Azerbaijan in Iran.", outline: ["History"], faqQuestions: [], schemaTypes: [] } }, block = JSON.stringify({ "@context": "https://schema.org", "@type": "FAQPage", mainEntity: [] });
    expect(withDerivedFaqSchema(newPage, body())).toBe(newPage); expect(withDerivedFaqSchema(fresh, { ...body(), completeness: "partial" })).toBe(fresh); expect(withDerivedFaqSchema(fresh, body([block, block]))).toBe(fresh);
    const full = { ...component(), kind: "full_rewrite" as const, target: { mode: "whole_body" as const, anchorKind: null, anchor: null }, where: COPY_RULES.where({ mode: "whole_body", anchorKind: null, anchor: null }) }, whole = proposal({ changeFamily: "full_rewrite", recommendedChange: { ...(fresh.recommendedChange as Extract<ChangeProposal["recommendedChange"], { kind: "existing_edit" }>), kind: "existing_edit", target: full.target, where: full.where }, bundle: { ...fresh.bundle!, components: [full] } });
    const graph = JSON.stringify({ "@context": "https://schema.org", "@graph": [{ "@type": "WebPage", "@id": URL }, { "@type": "FAQPage", mainEntity: [{ "@type": "Question", name: "Where are Heriz rugs made?", acceptedAnswer: { "@type": "Answer", text: "Heriz rugs are made in Iran." } }] }] });
    const removal = { ...full, after: ANSWER, units: [{ kind: "paragraph" as const, text: ANSWER }] }, removed = proposal({ ...whole, recommendedChange: { ...(whole.recommendedChange as Extract<ChangeProposal["recommendedChange"], { kind: "existing_edit" }>), kind: "existing_edit", after: ANSWER, units: removal.units }, bundle: { ...whole.bundle!, components: [removal] } });
    const tableUnits = [full.units![0]!, { kind: "table" as const, columns: ["Region", "Country"], rows: [["East Azerbaijan", "Iran"]] }, { kind: "heading" as const, level: 2 as const, text: "Unanswered question?" }], staleSchema: BundleComponent = { kind: "schema", label: "Unchanged FAQ", before: graph, after: graph, evidenceKeys: [fact.key], risk: "safe" };
    for (const [row, held] of [[whole, body([block, block])], [{ ...whole, bundle: { ...whole.bundle!, components: [{ ...full, after: `${full.after}\n\n${full.after}`, units: [...full.units!, ...full.units!] }] } }, body([graph])], [{ ...whole, bundle: { ...whole.bundle!, components: [{ ...full, after: COPY_RULES.bodyCopy(tableUnits), units: tableUnits }] } }, body([graph])], [{ ...whole, bundle: { ...whole.bundle!, components: [{ ...full, after: COPY_RULES.bodyCopy([...tableUnits.slice(0, -1), ...full.units!]), units: [...tableUnits.slice(0, -1), ...full.units!] }] } }, body([graph])], [{ ...whole, bundle: { ...whole.bundle!, components: [{ ...full, after: `${full.after}\n\n## Unanswered question?\n\n### Heading without an answer`, units: [...full.units!, { kind: "heading" as const, level: 2 as const, text: "Unanswered question?" }, { kind: "heading" as const, level: 3 as const, text: "Heading without an answer" }] }] } }, body([graph])], [removed, body([graph])], [{ ...whole, bundle: { ...whole.bundle!, components: [full, staleSchema] } }, body([graph])], [{ ...whole, bundle: { ...whole.bundle!, components: [{ ...full, after: "## Unanswered question?", units: [{ kind: "heading" as const, level: 2 as const, text: "Unanswered question?" }] }] } }, body([graph])]] as [ChangeProposal, OwnedPageBody][]) { const kept = withDerivedFaqSchema(row, held); expect([kept.status, kept.obligation?.kind, kept.bundle, kept.semanticReview, deserializeChangeProposal(serializeChangeProposal(kept)) != null]).toEqual(["needs_review", "redraft", row.bundle, undefined, true]); }
    const expanded = { ...full, after: `${full.after}\n\n## How are Heriz rugs woven?\n\n${ANSWER}`, units: [...full.units!, { kind: "heading" as const, level: 2 as const, text: "How are Heriz rugs woven?" }, { kind: "paragraph" as const, text: ANSWER }] }, incompleteGraph = withDerivedFaqSchema({ ...whole, bundle: { ...whole.bundle!, components: [expanded] } }, body([graph])); expect([incompleteGraph.status, incompleteGraph.obligation?.kind]).toEqual(["needs_review", "redraft"]); const made = withDerivedFaqSchema(whole, body()); expect([made.bundle!.components[1]!.derivation?.dependsOn[0]?.componentId, withDerivedFaqSchema(made, body()) === made]).toEqual([componentIdOf(full, 0), true]);
    const unchanged = { ...full, after: copy("Heriz rugs are made in Iran."), units: [{ kind: "heading" as const, level: 2 as const, text: full.label }, { kind: "paragraph" as const, text: "Heriz rugs are made in Iran." }] }, same = { ...whole, bundle: { ...whole.bundle!, components: [unchanged] } }; expect(withDerivedFaqSchema(same, body([graph, graph]))).toBe(same); const bad = { ...staleSchema, before: graph, after: graph.replace("Iran.", "Canada.") }, faqAlone = JSON.stringify({ "@context": "https://schema.org", "@type": "FAQPage", mainEntity: JSON.parse(graph)["@graph"][1].mainEntity }); expect(withDerivedFaqSchema({ ...same, bundle: { ...same.bundle!, components: [unchanged, { ...staleSchema, after: faqAlone }] } }, body([graph])).obligation?.kind).toBe("redraft"); expect(withDerivedFaqSchema({ ...same, bundle: { ...same.bundle!, components: [unchanged, bad] } }, body([graph])).obligation?.kind).toBe("redraft"); expect(withDerivedFaqSchema({ ...made, bundle: { ...made.bundle!, components: [...made.bundle!.components, bad] } }, body()).obligation?.kind).toBe("redraft"); const organization: BundleComponent = { ...staleSchema, before: null, after: JSON.stringify({ "@context": "https://schema.org", "@type": "Organization", name: "Heriz rug research" }) }, together = withDerivedFaqSchema({ ...whole, bundle: { ...whole.bundle!, components: [full, organization] } }, body()); expect([together.bundle!.components[1], together.bundle!.components[2]?.derivation?.rule, withDerivedFaqSchema(together, body()) === together]).toEqual([organization, "visible_faq_pairs_v1", true]);
    const unrelated = component("A new paragraph about rug dyes."); unrelated.units = [{ kind: "paragraph", text: unrelated.after }]; unrelated.target = { mode: "after_section", anchorKind: "heading", anchor: "Natural dyes" }; expect(withDerivedFaqSchema(proposal({ bundle: { ...fresh.bundle!, components: [unrelated] } }), body()).bundle!.components).toHaveLength(1);
  });
});
