import { describe, it, expect, vi, beforeEach, afterEach } from "vitest";
beforeEach(() => vi.stubEnv("NEXT_PUBLIC_BEACON_AEO_PACKET", "1"));
afterEach(() => vi.unstubAllEnvs());
const fix = vi.hoisted(() => ({ map: new Map<string, unknown>(), rows: [] as unknown[] })), bodies = fix, facts = fix;
vi.mock("@/lib/logger", () => ({ log: { debug: () => {}, info: () => {}, warn: () => {}, error: () => {} } }));
vi.mock("@/domains/decision/llm/adjudicator-budget", () => ({ checkBudget: async () => ({ allowed: true, remaining: 10 }), recordSpend: async () => {} }));
vi.mock("@/domains/decision/llm/winner-memory", () => ({ buildWinnerFewShots: async () => "", buildWinnerFewShotsWithPattern: async () => ({ fragment: "", patternHint: null }) }));
vi.mock("@/domains/evidence/pages/fact-checks", async (o) => ({ ...(await o<Record<string, unknown>>()), readFactChecks: async () => facts.rows }));
vi.mock("@/domains/evidence/pages/owned-context", async (o) => ({ ...(await o<Record<string, unknown>>()), loadOwnedPageBodies: async () => bodies.map }));
vi.mock("@/domains/account", () => ({ loadBusinessProfile: async () => null, getTenant: async () => ({ id: "t", domain: "fixture.example", growth_goal: null }), basisTag: () => "basis_test" }));
const passState = vi.hoisted(() => ({ snapshot: null as unknown })); vi.mock("@/domains/evidence/snapshot-loader", () => ({ loadEvidenceSnapshot: async () => passState.snapshot })); vi.mock("@/domains/decision/llm/gateway", async (o) => ({ ...(await o<Record<string, unknown>>()), creditBreakerHeld: async () => false })); import { produceProposalsForTenant } from "@/domains/decision/produce-proposals"; import { emptyResearchEvidence } from "@/domains/evidence/funnel/research-evidence"; import { applyDraftedCopy, deliverableFailures, draftFieldForPage, reviewFinishedCopy, staleCopyReasons } from "@/domains/decision/drafted-copy"; import { nextObligation } from "@/domains/decision/obligation"; import { openHold, preferFinished } from "@/domains/decision/completeness";
import { DRAFT_BUDGET } from "@/domains/decision/draft-budget"; import { editorialStandard, evidenceShortfall, REVIEW_CONTRACT, copyKey } from "@/domains/decision/proof"; import { canonicalUrlKey } from "@/domains/evidence/snapshot"; import { deserializeChangeProposal, serializeChangeProposal, type ChangeProposal } from "@/domains/decision/contracts";
const NOW = new Date("2026-09-05T00:00:00.000Z"); const SITES = [
  { t: "tenant-one", url: "https://alpha.example/tide-pools", label: "Tide Pools", q: "tide pool safety", title: "Tide Pools", h1: "Tide Pools",
    ask: "how cold is the water in tide pools", answer: "The water in a tide pool holds close to the ocean temperature until the sun warms the shallowest of them.",
    figured: "The water in a tide pool holds close to the ocean temperature until the sun warms the shallowest of them, and one shore survey counted 3157 pools along it.",
    narrow: "depth of pools", narrowAnswer: "Most pools along this shore sit under a foot of water at low tide.", word: "Anemone", wrong: "a plant that grows in gardens.", right: "a stinging animal fixed to the rock.",
    heads: ["When to visit", "What lives there", "Tide pool safety"], lines: ["Tide pools open up at low tide and close over again as the water returns.", "Sea stars, anemones and hermit crabs live in the shallow pools along this shore.", "The rocks stay slick for hours after the tide turns, which is when most falls happen."],
    unheld: "Seal pupping closures", section: "Tide pool safety", boast: "This shore has the best tide pools on the coast, and the rock shelves stay slick for hours after the tide turns, which is when nearly every fall happens and when a visitor should take the most care." },
  { t: "tenant-two", url: "https://beta.example/bordado", label: "Bordado", q: "puntadas de bordado", title: "Bordado a mano", h1: "Bordado a mano",
    ask: "cuanto hilo lleva un bastidor de bordado", answer: "Un bastidor mediano lleva alrededor de tres metros de hilo por cada motivo bordado.",
    figured: "Un bastidor mediano lleva alrededor de tres metros de hilo por cada motivo bordado, y un censo del taller conto 3157 madejas en un ano.",
    narrow: "grosor del hilo", narrowAnswer: "El hilo de algodon se separa en seis hebras de grosor parejo.", word: "Bastidor", wrong: "una tela suelta que se borda.", right: "un aro que tensa la tela.",
    heads: ["Materiales", "Puntadas", "Puntadas de bordado"], lines: ["El bordado a mano se trabaja sobre tela tensada en un bastidor.", "La puntada de tallo se usa para contornos y la de nudo frances para los puntos.", "El hilo de algodon se separa en hebras antes de enhebrar la aguja."],
    unheld: "Tension con contrapesos", section: "Puntadas de bordado", boast: "El taller vende la caja que su fabricante llama the best embroidery starter kit, con hilo de algodon, agujas de tres grosores y tela cortada a medida para el primer bastidor." },
];
type Site = (typeof SITES)[number]; const bodyOf = (s: Site) => ({ url: s.url, title: s.title, h1: s.h1, metaDescription: "Old line.", vocabulary: "", headings: s.heads, passages: s.lines, completeness: "complete" as const, version: "current" as const, contentHash: "h", fetchedAt: NOW.toISOString() });
const snapOf = (s: Site) => ({ ownedPages: [{ url: s.url, content: { wordCount: 400, title: s.title, h1: s.h1, outline: s.heads }, search: null }], research: {}, sources: [], scope: { tenantId: s.t, site: new URL(s.url).host } });
const card = (s: Site, over: Partial<ChangeProposal> = {}): ChangeProposal => ({ id: `${s.t}::${new URL(s.url).pathname}::existing_edit::x`, tenantId: s.t, kind: "existing_edit", pagePath: new URL(s.url).pathname, pageUrl: s.url, pageLabel: s.label,
  primaryQuery: s.q, opportunityType: "Capture clicks", changeFamily: "meta", status: "needs_review", researchOnly: false, recommendedChange: { kind: "existing_edit", field: "meta", before: "Old line.", after: "Write a description for this page." },
  whyItMatters: "w", estimatedEffortMinutes: 1, riskLevel: "low", confidence: "medium", limitations: [], evidence: { query: s.q, hints: [], evidenceRefCount: 1 }, impactScore: 10, upsidePerMonth: null, modeledOn: "the stored results page for this search", publish: "manual", createdAt: NOW.toISOString(), ...over });
const PASS = { aeoPacket: { leadAnswer: true, groupedH2s: true, defendedClaims: true, entityBlock: true, boundedScope: true, h1QueryAlignment: true }, pageFit: true, resolvesDiagnosis: true, usefulAndNatural: true, placementCorrect: true, implementableNow: true, improvesPage: true, wouldHandToCustomer: true, notes: "It says what this page answers.", resolution: "none" };
const rule = (cs: readonly { supportedBy: readonly string[] }[]) => cs.map((c, i) => ({ i, by: [...c.supportedBy], entailed: true })), TAIL = { evidenceRefs: [{ source: "gsc", detail: "real page demand" }], confidence: "high", risks: [], operatorSteps: ["Replace the field"], proofPlan: { metrics: ["clicks"], windowsDays: [7, 14, 28], controls: "untouched pages" }, rationale: "r", uncertaintyOrOmitted: [], implementationMinutes: 1 };
  const reading = async (s: Site, ask = s.ask, answer = s.answer) => { const { rulesVersionFor } = await import("@/domains/evidence/pages/fact-checks"), { pageHashOf } = await import("@/domains/evidence/pages/fact-check-run"), b = bodyOf(s);
    return { page: new URL(s.url).pathname, statementKey: "asked", subject: ask, current: "", proposed: answer, literal: null, usage: null, sources: [{ url: "https://ref.example/guide", kind: "encyclopedia", says: answer, groups: ["River mammals", "Wetland birds", "Poetry in the archive", "Painting in the archive"].filter((g) => answer.includes(g)) }], agreement: "single_source", confidence: "confirmed", verdict: "page_correct", alsoAt: [], note: "",
      pageContentHash: pageHashOf([b.title, b.h1, ...b.headings, ...b.passages].join("\n")), pageLocator: null, sourceReadAt: NOW.toISOString(), state: "checked", rulesVersion: rulesVersionFor({ subject: ask, current: "" }), evidenceBasis: null, checkedAt: NOW.toISOString() }; };
const run = async (s: Site, c: ChangeProposal, draft: Record<string, unknown> | ((field: string) => Record<string, unknown>), verdict: Record<string, unknown> | null | "throw" = PASS, rows: unknown[] = [], body: Record<string, unknown> = bodyOf(s), snap: Record<string, unknown> = snapOf(s)) => {
  let emitted: Record<string, unknown> = typeof draft === "function" ? {} : draft;
  bodies.map = new Map([[canonicalUrlKey(s.url), body]]); facts.rows = rows; const owed: unknown[] = [], settled = new Map<string, unknown>(), notes: string[] = [], why = new Map<string, string>(), unsettled = new Set<string>(), seen: { kind: string; text: string }[] = [];
  const out = await applyDraftedCopy([c], { tenantId: s.t, snapshot: snap as never, now: NOW, refusals: why, unsettled, owe: (_k: string, n: unknown) => owed.push(n), resolved: settled as never,
    note: (_k: string, o: string, w?: string) => notes.push(`${o}:${w ?? ""}`), budget: DRAFT_BUDGET.plan({ jobs: [{ key: c.pagePath!, family: "editor", impact: 9, calls: DRAFT_BUDGET.DELIVERABLE_CALLS }], candidates: 1, calls: 30 }),
    complete: async ({ kind, system, user }: { kind: string; system: string; user: string }) => { seen.push({ kind, text: `${system}\n${user}` });
      if (kind !== "editor_judgement") { emitted = typeof draft === "function" ? draft(/Field to edit: (\w+)/.exec(user)?.[1] ?? "") : draft; return { value: emitted }; }
      if (verdict === "throw") throw new Error("the reader of meaning never answered");
      return verdict ? { value: { ...verdict, claims: rule((emitted.claims ?? []) as never) } } : { error: "no answer", retryable: true }; } } as never);
  return { row: out[0]!, owed, settled: [...settled.values()], notes, why: [...why.values()], unsettled: [...unsettled], judged: seen.filter((x) => x.kind === "editor_judgement").map((x) => x.text), wrote: seen.filter((x) => x.kind !== "editor_judgement").map((x) => x.text) };
};
describe("the editorial standard one edit is judged by", () => {
  it.each(SITES)("$t: essential acceptance, both faces: a grounded addition lands whole, and an unresolved diagnosis blocks it again", async (s) => {
    const mk = (over: Partial<ChangeProposal> = {}) => card(s, { changeFamily: "section", treatment: "add_answer_section", recommendedChange: { kind: "existing_edit", field: "answer_block", before: null, after: "The exact wording has not been written yet." }, ...over } as Partial<ChangeProposal>);
    const draft = { field: "answer_block", before: null, after: `${s.answer} ${s.lines[0]} ${s.lines[1]}`,
      ...TAIL, placementAnchor: s.h1, naturalHeading: "The direct answer", measurementTarget: s.q, claims: [{ text: s.answer, supportedBy: ["fact-1"] }, { text: `${s.lines[0]} ${s.lines[1]}`, supportedBy: ["page-copy-1", "page-copy-2"] }] };
    const at = `https://rival-${s.t}.example/page`, held = s.lines.join(" ");
    const seen = { url: at, domain: `rival-${s.t}.example`, engines: [], examplePrompts: [], appearances: [{ query: s.q }], extract: { title: "Winner", h1: null, wordCount: 900, headings: [s.unheld], faqCount: 0, entityNames: [], mainText: held, truncated: false, heldChars: held.length, totalChars: held.length } };
    const demand = { ...snapOf(s), ownedPages: [{ ...snapOf(s).ownedPages[0], search: { clicks90d: 1, impressions90d: 900, ctr90d: 0.01, position90d: 8, topQueries: [{ query: s.q, impressions: 900, clicks: 0, position: 8 }] } }], research: { winningPages: [seen], serpEvidence: [{ query: s.q, observedAt: null, organic: [{ rank: 1, url: at, domain: seen.domain, title: null }], aiOverview: [], aiMode: [], paa: [], related: [] }] } };
    const good = await run(s, mk(), draft, PASS, [await reading(s)], bodyOf(s), demand);
    const hold = openHold(good.row);
    const packet = (text: string) => JSON.parse(/^SHARED EVIDENCE PACKET.*?: (.*)$/m.exec(text)![1]!); expect(packet(good.wrote.find((text) => text.includes("SHARED EVIDENCE PACKET"))!)).toEqual(packet(good.judged[0]!)); expect(good.row.supportFacts?.every((f) => packet(good.wrote.find((text) => text.includes("SHARED EVIDENCE PACKET"))!).evidence.some((e: { id: string; text: string; sources: unknown }) => e.id === f.id && e.text === f.fact && (!f.sources || JSON.stringify(e.sources) === JSON.stringify(f.sources))))).toBe(true);
    expect(packet(good.judged[0]!).comparison.winners[0]).toMatchObject({ id: "rival-1", url: at, role: "research_not_claim_support", held, read: true, truncated: false, heldWhole: true });
    const witness = `${s.q}\n${s.lines[0]} ${s.lines[1]} The boundary is seasonal, not permanent.\nBoundary | Area\nSeasonal | The named area`, passages = [...Array(20).fill("Background archival material unrelated to the requested answer. ".repeat(14)), witness], longBody = { ...bodyOf(s), passages, vocabulary: passages.join("\n\n") };
    const { pageHashOf } = await import("@/domains/evidence/pages/fact-check-run"), fact = { ...await reading(s), pageContentHash: pageHashOf([longBody.title, longBody.h1, ...longBody.headings, ...passages].join("\n")) };
    const deep = await run(s, mk(), draft, PASS, [fact], longBody, demand), written = packet(deep.wrote.find((t) => t.includes("SHARED EVIDENCE PACKET"))!), judged = packet(deep.judged[0]!);
    expect([passages.join(" ").length > 12000, deep.wrote.some((t) => t.includes("THE OWNED PAGE") && t.includes(witness)), !written.comparison.owned.heldWhole && deep.wrote.some((t) => t.includes("THE OWNED PAGE") && t.includes(written.comparison.owned.bodyKey)), written.evidence.some((e: { id: string; text: string }) => e.id.startsWith("page-copy-") && e.text.includes(witness)), written.evidence.filter((e: { id: string }) => e.id.startsWith("page-copy-")).reduce((n: number, e: { text: string }) => n + e.text.length, 0) <= 12000, written.page.partial], "late owned answers reach comparison, citable writer evidence and review under unchanged budgets, never a false whole-page reading").toEqual([true, true, true, true, true, true]); expect(written).toEqual(judged);
    expect(openHold({ ...good.row, supportFacts: good.row.supportFacts?.map((f) => ({ ...f, sources: f.sources?.map((s) => ({ ...s, url: "https://different.example/source" })) })) }).defects.some((why) => why.includes("complete editor acceptance"))).toBe(true);
    expect([good.row.status, good.row.researchOnly === true, hold.defects, (good.row.recommendedChange as { after?: string }).after?.includes(s.lines[0]!) ?? false, good.row.claims?.every((c) => c.supportedBy.every((id) => id.startsWith("page-") || id.startsWith("fact-") || id.startsWith("rival-") || id.startsWith("serp-") || id.startsWith("owned-"))) ?? false, nextObligation(good.row)],
      "the grounded addition is COMPLETE ACTIONABLE READY WORK: ready status, not research, zero defects on the one verdict, its own copy, every claim on a packet id, and nothing owed").toEqual(["ready", false, [], true, true, null]);
    for (const fault of ["it does not resolve the diagnosed problem this change exists to fix", "no serious editor would hand this to a customer", "it points at the page instead of answering", "most of what it says is already on the page"]) {
      const stale = { ...good.row, faults: [fault] };
      expect(openHold(stale).defects, "the serving contract must not soften an essential copy failure after the writer refused it").toContain(fault);
      expect(nextObligation(stale)?.kind).toBe("redraft");
    }
    for (const leak of ["A clear answer should explain the subject.", "I will draft the missing section now.", "The FAQ also pairs the names with their meanings."]) { const bad = await run(s, mk(), { ...draft, after: `${draft.after} ${leak}` }, PASS, [await reading(s)], bodyOf(s), demand); expect([bad.row.status === "ready", bad.why.some((why) => why.includes("narrates Beacon"))], JSON.stringify({ leak, why: bad.why, faults: bad.row.faults })).toEqual([false, true]); }
    const blocked = await run(s, mk({ id: `${s.t}::${new URL(s.url).pathname}::existing_edit::blocked-essential` }), draft, { ...PASS, resolvesDiagnosis: false, notes: "It is fine prose that answers a different question than the one diagnosed." }, [await reading(s)], bodyOf(s), demand);
    expect([blocked.row.researchOnly === true || (blocked.row.recommendedChange as { after?: string }).after === "The exact wording has not been written yet." || (blocked.row.faults ?? []).length > 0, blocked.why.join(" ").includes("does not resolve the diagnosed problem") || (blocked.row.faults ?? []).join(" ").includes("does not resolve the diagnosed problem")],
      "the same copy under an unresolved-diagnosis verdict is BLOCKED with the essential reason on record, never caveated through (wc20)").toEqual([true, true]);
    for (const [flip, word] of [["placementCorrect", "placement on the page is wrong"], ["implementableNow", "cannot be applied as written"]] as const) {
      const held = await run(s, mk({ id: `${s.t}::${new URL(s.url).pathname}::existing_edit::blocked-${flip}` }), draft, { ...PASS, [flip]: false }, [await reading(s)], bodyOf(s), demand);
      expect([held.row.status === "ready", held.why.join(" ").includes(word) || (held.row.faults ?? []).join(" ").includes(word)], `${flip}: false is ESSENTIAL on its own: the draft is blocked with its exact reason even when every other verdict is positive`).toEqual([false, true]); } });

  for (const s of SITES) {
    it(`${s.t}: a summary that adds no new fact is finished work, and the standard it was judged by is stored on the row`, async () => {
      const r = await run(s, card(s), { field: "meta", before: "Old line.", after: `${s.lines[0]} ${s.lines[1]}`.slice(0, 150), ...TAIL, placementAnchor: s.h1, naturalHeading: null, measurementTarget: s.q, claims: [{ text: s.lines[0]!, supportedBy: ["page-copy-1"] }] });
      expect([r.row.status, r.why, r.row.assignment?.standard, r.owed.length], "a faithful summary lands, nothing refuses it, the row records the standard it answered to, and no research was bought").toEqual(["ready", [], "summary", 0]); expect(r.judged[0]?.includes("SUMMARY LINE") && !r.judged[0]?.includes("DIAGNOSED MISSING ANSWER"), "the reader of meaning is given the summary standard and is never handed the missing-answer rule as well").toBe(true); });
    it(`${s.t}: a verbless noun-phrase title and a question title both pass every door`, async () => {
      const t = (after: string) => run(s, card(s, { changeFamily: "title", recommendedChange: { kind: "existing_edit", field: "title", before: s.title, after: "Write a title." } }),
        { field: "title", before: s.title, after, ...TAIL, placementAnchor: s.h1, naturalHeading: null, measurementTarget: s.q, claims: [{ text: after, supportedBy: ["page-title"] }] });
      const noun = await t(`${s.title}: ${s.heads[0]} and ${s.heads[1]}`), ask = await t(`${s.title}: ${s.heads[1]}?`);
      expect([noun.row.status, noun.why, ask.row.status, ask.why], "neither the missing verb nor the question mark is a defect at any door Beacon owns").toEqual(["ready", [], "ready", []]); });
    const c = card(s, { changeFamily: "section", primaryQuery: s.q, treatment: "rewrite_existing_section", causeFinding: { cause: "retrieved_not_cited", action: null, evidenceKeys: ["k1"], competingExplanations: [], notConsidered: [], falsifier: "f", explanation: "The answer is spread across three passages.", payload: { cause: "retrieved_not_cited", engine: "chatgpt", promptText: s.q, missing: s.lines[2]!, aeoKind: "scattered_answer" } } as never, recommendedChange: { kind: "existing_edit", field: "section", before: null, after: "Reorganise what this page already says." },
      assignment: { page: s.url, standard: "restructuring", treatment: "restructure", gapKind: "scattered_answer", propositions: [s.lines[2]!], diagnosedGap: s.lines[2]!, mustLeadWith: s.lines[2]!, opening: "open with the whole answer", format: "one to three sentences", intent: [s.q], supportingFacts: [], pageContext: ["page-copy-1"], forbidden: [], rivals: [], briefing: [], mayReuse: "the page's own words", mustPreserve: "every heading", mustNotRepeat: "the page's own entries", placement: "additive", completionTest: "a reader can lift it whole" } });
    it(`${s.t}: a section on a subject this page carries nothing of owes that source and hires no writer`, async () => {
      const at = `https://rival-${s.t}.example/page`, held = s.lines.join(" ");
      const seen = { url: at, domain: `rival-${s.t}.example`, engines: [], examplePrompts: [], appearances: [{ query: s.q }], extract: { title: "Winner", h1: null, wordCount: 900, headings: [s.unheld], faqCount: 0, entityNames: [], mainText: held, truncated: false, heldChars: held.length, totalChars: held.length } };
      const snap = { ...snapOf(s), ownedPages: [{ ...snapOf(s).ownedPages[0], search: { clicks90d: 1, impressions90d: 900, ctr90d: 0.01, position90d: 8, topQueries: [{ query: s.q, impressions: 900, clicks: 0, position: 8 }] } }], research: { winningPages: [seen], serpEvidence: [{ query: s.q, observedAt: null, organic: [{ rank: 1, url: at, domain: seen.domain, title: null }], aiOverview: [], aiMode: [], paa: [], related: [] }] } };
      const r = await run(s, card(s, { changeFamily: "section", treatment: "add_answer_section", recommendedChange: { kind: "existing_edit", field: "section", before: null, after: "The exact wording has not been written yet." } }), {}, PASS, [], bodyOf(s), snap);
      expect([r.wrote.length > 0, r.wrote.filter((t) => !t.includes("READING two or more web pages side by side")).length, r.owed, r.row.researchOnly, (r.row.obligation as { need?: unknown } | undefined)?.need, r.row.status], "a subject this page carries nothing of is WRITTEN NOW from the winner's own section as briefing (operator, 2026-09-12, the observation rung writes first): the writer is hired, nothing is owed, and the rival-claim caveat carries the honesty") .toEqual([true, 2, [], false, undefined, "needs_review"]); });
  }
  const S = SITES[0]!;
  const meta = (after: string) => ({ field: "meta", before: "Old line.", after, ...TAIL, placementAnchor: S.h1, naturalHeading: null, measurementTarget: S.q, claims: [{ text: after, supportedBy: ["page-copy-1"] }] });
  it("an editorial weakness buys a revision and never research, while a missing answer really does send the runtime to buy one", async () => {
    const weak = await run(S, card(S), meta(`${S.lines[0]}`), { ...PASS, usefulAndNatural: false, notes: "it reads like a caption, not a description", resolution: "acquire_factual_source" });
    expect([weak.row.status, weak.owed.length, weak.settled.length, weak.why[0]?.includes("it reads like a caption")], "the weakness comes back as the exact objection the next draft writes against, and not one cent of research is minted off a matter of taste").toEqual(["needs_review", 0, 0, true]);
    const gap = card(S, { changeFamily: "section", treatment: "add_answer_section", causeFinding: { cause: "retrieved_not_cited", action: null, evidenceKeys: ["k1"], competingExplanations: [], notConsidered: [], falsifier: "f", explanation: "The page never says how cold the water runs.", payload: { cause: "retrieved_not_cited", engine: "chatgpt", promptText: S.q, missing: "how cold the water runs in winter", aeoKind: "missing_information" } } as never, recommendedChange: { kind: "existing_edit", field: "section", before: null, after: "Add the missing answer." },
      assignment: { page: S.url, standard: "missing_answer", treatment: "section", gapKind: "missing_answer", propositions: ["how cold the water runs in winter"], diagnosedGap: "how cold the water runs in winter", mustLeadWith: "the water temperature", opening: "open with the answer", format: "a heading, then sentences", intent: [S.q], supportingFacts: [], pageContext: [], forbidden: [], rivals: [], briefing: [], mayReuse: "nothing", mustPreserve: "every heading", mustNotRepeat: "the page's own entries", placement: "additive", completionTest: "a reader knows the temperature" } });
    const owedOne = await run(S, gap, { field: "answer_block", before: null, after: S.lines[1]!, ...TAIL, placementAnchor: S.h1, naturalHeading: "What lives in the pools", measurementTarget: S.q, claims: [{ text: S.lines[1]!, supportedBy: ["page-copy-2"] }] },
      { ...PASS, improvesPage: false, notes: "it names nothing the page does not already say", resolution: "acquire_factual_source" });
    expect([owedOne.row.status, owedOne.owed.length > 0, owedOne.settled.length > 0], "the same failed box on the standard that genuinely owes information does send the runtime to get it").toEqual(["needs_review", true, true]); });
  it("a transport failure is not a verdict: no fault, no research, and the page comes back retryable", async () => {
    for (const v of [null, "throw"] as const) { const r = await run(S, card(S), meta(S.lines[0]!), v);
      expect([r.row.faults ?? [], r.owed.length, r.settled.length, r.unsettled.length > 0, r.notes.some((n) => n.startsWith("retryable_blocked"))], "nothing about the copy is banked, nothing is bought, and the card is filed as work nobody settled rather than work Beacon refused").toEqual([[], 0, 0, true, true]); } });
  it("the standard the writer was briefed with is the one the row stores, the re-read takes and the serving door asks", async () => {
    const r = await run(S, card(S), meta(`${S.lines[0]} ${S.lines[1]}`.slice(0, 150)));
    const stored = r.row; expect(stored.assignment?.standard, "the pass stores it").toBe("summary");
    expect(editorialStandard({ field: "meta", assignment: stored.assignment, changeFamily: stored.changeFamily }), "the typed selector every door calls answers the same thing").toBe("summary");
    bodies.map = new Map([[canonicalUrlKey(S.url), bodyOf(S)]]);
    const seen: string[] = []; const re = await reviewFinishedCopy(stored, { tenantId: S.t, now: NOW, complete: (async ({ system }: { system: string }) => (seen.push(system), { value: { ...PASS, claims: (stored.claims ?? []).map((c, i) => ({ i, by: [...c.supportedBy], entailed: true })) } })) as never });
    expect([seen[0]?.includes("SUMMARY LINE"), re.row?.semanticReview?.version], "the paid re-read is given the same standard, and banks its reading under the contract already on file").toEqual([true, REVIEW_CONTRACT]); expect(staleCopyReasons(stored, new Map([[canonicalUrlKey(S.url), bodyOf(S) as never]]), [], { title: S.title, h1: S.h1, metaDescription: "Old line.", outline: S.heads }), "and the serving door, reading the same standard, keeps the words").toEqual([]); });
  it("quality round: a stored additive section that narrates the page, or only re-says it, is retired to a redraft under the entity-first brief, and a fact-backed one is left alone", async () => {
    const { staleCopyReasons } = await import("@/domains/decision/drafted-copy"), { DRAFT_BUDGET } = await import("@/domains/decision/draft-budget");
    const s0 = SITES[0]!, body = bodyOf(s0), bodies = new Map([[canonicalUrlKey(s0.url), body]]);
    const base = card(s0, { researchOnly: false, changeFamily: "section" });
    const mk = (after: string, supportedBy: string[]) => ({ ...base, claims: [{ text: after.slice(0, 60), supportedBy }], supportFacts: supportedBy.map((id) => ({ id, fact: "x" })), recommendedChange: { kind: "existing_edit" as const, field: "section" as const, before: null, after } });
    const narrates = mk("The page also calls out several figures. Use the category links for the deeper lists.", ["page-copy-1"]);
    const resays = mk(`${s0.lines[0] ?? "The reserve holds animals."}`, ["page-copy-1"]);
    const teaches = mk("Anahita is the Persian goddess of fertility and water, first attested in Achaemenid inscriptions from the fifth century BCE at Persepolis.", ["fact-1"]);
    const why = (p0: ReturnType<typeof mk>) => staleCopyReasons(p0 as never, bodies as never, []);
    const r1 = why(narrates), r2 = why(resays), r3 = why(teaches);
    expect([r1.some((w) => /rewritten under the entity-first brief/.test(w) && DRAFT_BUDGET.HARD_REFUSAL.test(w)), r2.some((w) => /add specifics/.test(w) && DRAFT_BUDGET.HARD_REFUSAL.test(w)), r3.filter((w) => /entity-first/.test(w))],
      "narration and zero-gain retire hard, so the sweep routes them to previousCopy plus a redraft instead of a review downgrade; a section teaching new specifics from a checked fact passes untouched").toEqual([true, true, []]);
  });
  it("retires the objection the owner judges for themselves whatever standard wrote it, and leaves every other stored row exactly as it was", () => {
    const RETIRED = "it repeats the search instead of improving the page", REAL = "it lands in the wrong place";
    const stored = (over: Partial<ChangeProposal>) => card(S, { status: "needs_review", recommendedChange: { kind: "existing_edit", field: "meta", before: "Old line.", after: "A finished description of this page." }, ...over });
    expect(nextObligation(stored({ faults: [RETIRED] })), "a summary is judged on the line it replaces and can never be handed that sentence again, so it owes no paid rewrite for it").toBeNull(); expect(nextObligation(stored({ faults: [RETIRED, REAL] }))?.kind, "a real fault standing beside it is untouched").toBe("redraft"); expect(nextObligation(stored({ faults: [REAL] }))?.kind, "and a row that never carried the retired sentence is not touched at all").toBe("redraft");
    for (const over of [{}, { changeFamily: "section", recommendedChange: { kind: "existing_edit" as const, field: "section" as const, before: null, after: "A finished section.", where: 'A new section headed "H"' } }] as Partial<ChangeProposal>[]) expect([nextObligation(stored({ ...over, faults: [RETIRED] })), openHold(stored({ ...over, faults: [RETIRED] })).advisories.map((a) => a.kind).filter((x) => x === "matches_search")], "matches_search is advisory on every standard, never a paid rewrite").toEqual([null, ["matches_search"]]);
    const reviewed = stored({ changeFamily: "factual_correction", claims: [{ text: "c", supportedBy: ["fact-1"] }], supportFacts: [{ id: "fact-1", fact: "f" }] });
    expect(nextObligation({ ...reviewed, semanticReview: { of: copyKey(reviewed), version: REVIEW_CONTRACT, claims: [{ i: 0, by: ["fact-1"], entailed: true }] } }), "and a reading banked under the contract on file is not re-bought: the editorial rules moved, the evidence contract did not").toBeNull(); });
  it.each(SITES)("retires the promise objection where the row's own record of the page carries the word, keeps it where the page never says it, and asks nothing of a row that holds no record at all, on $t", (s) => {
    const promise = (w: string) => `it calls the subject "${w}", a word this page's own copy never carries, so the line promises a searcher warmth, fame or growth nothing on file backs`;
    const carried = s.heads[0]!.split(" ")[0]!, never = "zzqx", stamp = `${s.title}|${s.h1}|${s.heads[0]}|${s.heads.join(">")}`;
    const held = (over: Partial<ChangeProposal>) => card(s, { status: "needs_review", recommendedChange: { kind: "existing_edit", field: "meta", before: "Old line.", after: "A finished description of this page." }, ...over });
    expect(nextObligation(held({ copyStamp: stamp, faults: [promise(carried)] })), "the page's own last-read words carry the word, so the objection is history and no corrective draft is owed for it").toBeNull(); expect(nextObligation(held({ copyStamp: stamp, faults: [promise(never)] })), "a word the page really never says keeps its objection and its redraft").toEqual({ kind: "redraft", attempt: 1, instruction: promise(never) }); expect(nextObligation(held({ faults: [promise(carried)] })), "and a row holding no record of the page retires nothing, because a door that has read nothing cannot say what the page never says").toEqual({ kind: "redraft", attempt: 1, instruction: promise(carried) }); expect(nextObligation(held({ copyStamp: stamp, faults: [promise(carried), "it lands in the wrong place"] }))?.kind, "a real fault standing beside it is untouched").toBe("redraft"); expect(nextObligation(held({ recommendedChange: { kind: "existing_edit", field: "meta", before: `Old line about ${carried}.`, after: "A finished description." }, faults: [promise(carried)] })), "and the line this change replaces is part of the record too").toBeNull(); expect(nextObligation(held({ supportFacts: [{ id: "page-copy-1", fact: s.lines[0]! }], faults: [promise(s.lines[0]!.split(" ")[1]!)] })), "as are the passages the row banked as the page's own").toBeNull(); });
  it.each(SITES)("lets a reorganization of the page's own material answer for the passage it replaces, and holds every other replacement to every unit, on $t", (s) => {
    const before = `${s.lines[0]} ${s.lines[1]}`, after = `${s.heads[1]}. ${s.lines[2]}`;
    const reorganized = card(s, { changeFamily: "section", status: "needs_review",
      recommendedChange: { kind: "existing_edit", field: "section", before, after, where: `Replaces the existing passage under "${s.heads[0]}"` },
      claims: [{ text: `The page groups this under ${s.heads[1]}.`, supportedBy: ["page-copy-1", "page-copy-2"] }],
      supportFacts: [{ id: "page-copy-1", fact: s.lines[0]! }, { id: "page-copy-2", fact: s.lines[1]! }],
      informationGain: { adds: "puts the page's own material in one place a reader can scan", by: ["page-copy-1", "page-copy-2"], pageWhole: true } });
    const read = (p: ChangeProposal): ChangeProposal => ({ ...p, semanticReview: { aeoPacket: PASS.aeoPacket, of: copyKey(p), version: REVIEW_CONTRACT, materialChange: true, claims: (p.claims ?? []).map((x, i) => ({ i, by: [...x.supportedBy], entailed: true })) } });
    expect(evidenceShortfall(read(reorganized)), "a gain made only of this page's own units, read against the whole page, answers for the passage it reorganizes").toBeNull();
    const outside = { ...reorganized, claims: [{ text: `The page groups this under ${s.heads[1]}.`, supportedBy: ["fact-1"] }], supportFacts: [{ id: "fact-1", fact: `an encyclopedia says ${s.heads[1]}` }],
      informationGain: { adds: "adds a checked fact the page never carried", by: ["fact-1"], pageWhole: true } } as ChangeProposal;
    expect(evidenceShortfall(read(outside)), "a replacement carrying anything from outside the page still accounts for every unit it drops").toContain("neither says it nor accounts for it"); expect(evidenceShortfall(read({ ...reorganized, informationGain: { ...reorganized.informationGain!, pageWhole: false } })), "a gain judged against part of the page is refused before the exemption is even asked").toContain("only part of this page");
    const linked = read({ ...reorganized, recommendedChange: { ...reorganized.recommendedChange, linkTo: s.url } as ChangeProposal["recommendedChange"], informationGain: { ...reorganized.informationGain!, pageWhole: false } });
    expect(evidenceShortfall(linked), "and link work skips the gain checks entirely, so the exemption asks the whole-page question itself rather than trusting a door that never ran").toContain("neither says it nor accounts for it"); expect(evidenceShortfall(read({ ...reorganized, claims: [{ text: "c", supportedBy: ["rival-1"] }], supportFacts: [{ id: "rival-1", fact: "a competing page covers it" }], informationGain: { ...reorganized.informationGain!, by: ["rival-1"] } })), "briefing is not the page's own material and never reaches the exemption").toContain("competes with this one");
    const correction = card(s, { changeFamily: "factual_correction", status: "needs_review", recommendedChange: { kind: "existing_edit", field: "section", before: `${s.word}: ${s.wrong} ${s.heads[2]} today.`, after: `${s.word}: ${s.right}` },
      preservation: [{ text: `${s.word}: ${s.wrong}`, disposition: "corrected", by: ["fact-1"], why: "the source of record says so" }], claims: [{ text: "c", supportedBy: ["fact-1"] }], supportFacts: [{ id: "fact-1", fact: `an encyclopedia says ${s.right}` }] });
    expect(evidenceShortfall(read(correction)), "and a correction owes no gain receipt at all, so it never reaches the exemption and still answers for what it drops around the mistake").toContain("neither says it nor accounts for it"); });
});
describe("the standard says what the work is, and the id says where the words came from", () => {
  const ASSIGN = (over: Record<string, unknown>): ChangeProposal["assignment"] => ({ page: "p", treatment: "section", gapKind: "missing_answer", propositions: ["p"], diagnosedGap: "p", mustLeadWith: "p", opening: "o", format: "f", intent: [], supportingFacts: [], pageContext: [], forbidden: [], rivals: [], briefing: [], mayReuse: "n", mustPreserve: "n", mustNotRepeat: "n", placement: "additive", completionTest: "t", ...over } as ChangeProposal["assignment"]);
  const POINTS = "it points at the page instead of answering";
  it.each(SITES)("lets a page whose title promises what it never delivers say what it does today, and refuses the same sentence from every other kind of body work, on $t", (s) => {
    const body = (standard: string): ChangeProposal => card(s, { changeFamily: "section", claims: [{ text: "c", supportedBy: ["page-copy-1"] }], supportFacts: [{ id: "page-copy-1", fact: s.lines[0]! }],
      recommendedChange: { kind: "existing_edit", field: "section", before: null, after: `This guide covers ${s.heads[1]!.toLowerCase()} and nothing else, so a reader looking for anything wider is in the wrong place.`, where: 'A new section headed "H"' }, assignment: ASSIGN({ standard, gapKind: standard === "repositioning" ? "false_page_promise" : "missing_answer" }) });
    const reasons = (standard: string): string[] => staleCopyReasons(body(standard), new Map([[canonicalUrlKey(s.url), bodyOf(s)]]) as never, [], { title: s.title, h1: s.h1, outline: s.heads } as never, false, []);
    expect([reasons("repositioning").includes(POINTS), reasons("missing_answer").includes(POINTS), reasons("restructuring").includes(POINTS)],
      "the honest treatment of a false promise IS a sentence about what this page delivers, so the container rule is not asked of it, and it is asked of every other body standard exactly as before").toEqual([false, true, true]); });
  it.each(SITES)("refuses copy that presents the page instead of answering, at the writer's door and on the banked row, and takes the same words as a sentence that states the answer, on $t", async (s) => {
    const parts = `${s.heads[0]!.toLowerCase()}, ${s.heads[1]!.toLowerCase()} and ${s.heads[2]!.toLowerCase()}`;
    const narrated = `${s.label} is presented here as a grouped list of ${parts}, with one short entry for each of them.`, answered = `${s.label} includes ${parts}, with one short entry for each of them.`;
    const gap = card(s, { changeFamily: "section", treatment: "add_answer_section", recommendedChange: { kind: "existing_edit", field: "section", before: null, after: "Add the missing answer." },
      causeFinding: { cause: "retrieved_not_cited", action: null, evidenceKeys: ["k1"], competingExplanations: [], notConsidered: [], falsifier: "f", explanation: "e", payload: { cause: "retrieved_not_cited", engine: "chatgpt", promptText: s.q, missing: s.lines[2]!, aeoKind: "missing_information" } } as never });
    const wrote = async (after: string): Promise<string[]> => deliverableFailures({ actionType: "answer_block", targetUrl: s.url, finalCopy: after, beforeText: null, naturalHeading: s.heads[0], placementAnchor: s.h1, measurementTarget: s.q, claims: [], evidenceIdsUsed: [], uncertaintyOrOmitted: [] } as never, { targetUrl: s.url, title: s.title, h1: s.h1, bodyText: s.lines.join(" "), headings: s.heads, evidence: {}, trackedQuestion: s.q, ownedPaths: [], bannedTerms: [], demand: { preserve: [], vocabulary: [] }, assignment: ASSIGN({ standard: "missing_answer", shape: "inline_addition" }) } as never);
    const stored = (after: string): string[] => staleCopyReasons(card(s, { changeFamily: "section", claims: [{ text: "c", supportedBy: ["page-copy-1"] }], supportFacts: [{ id: "page-copy-1", fact: s.lines[0]! }],
      recommendedChange: { kind: "existing_edit", field: "section", before: null, after, where: 'A new section headed "H"' }, assignment: ASSIGN({ standard: "missing_answer" }) }), new Map([[canonicalUrlKey(s.url), bodyOf(s)]]) as never, [], { title: s.title, h1: s.h1, outline: s.heads } as never, false, []);
    expect([(await wrote(narrated)).some((r) => r.includes(POINTS)), (await wrote(answered)).some((r) => r.includes(POINTS)), stored(narrated).includes(POINTS), stored(answered).includes(POINTS)],
      "the writer is refused for narrating the page before a cent is spent reading the copy for sense, a stored row of that shape goes back for a corrective redraft instead of standing, and the identical subjects said as an answer pass both doors").toEqual([true, false, true, false]); });
  it.each(SITES)("refuses a sentence whose main clause arranges its subject at both doors, in the present tense or the past, and takes the same subjects stated as a fact, carried inside a quotation, or asked as a question, on $t", async (s) => {
    const parts = `${s.heads[0]!.toLowerCase()}, ${s.heads[1]!.toLowerCase()} and ${s.heads[2]!.toLowerCase()}`;
    const CASES = [`${s.label} groups its items by category, not as one flat list, and each category holds one short entry for the reader.`,
      `${s.label} is divided into four sections, and each one of them holds a short entry a reader can take away.`,
      `${s.label} centres on ${parts}, with one short entry for each of them.`, `${s.label} includes ${parts}, with one short entry for each of them.`,
      `${s.label} carries the survey line "the shore is divided into three shelves" word for word, and every one of them holds ${parts}.`,
      `A reader who asks how to sort the ${s.heads[1]!.toLowerCase()} finds every step in one place. ${s.lines[1]}`,
      `Those items were previously split across separate headings, and each of them now sits in one place.`, `${s.label} was previously grouped, and a reader had to hunt through it.`,
      `${s.heads[2]} is scattered across three sections.`, `${s.label} was spread over several sections before today.`, `${s.label} was divided into four parts until today, and one of them held every entry.`,
      `The paste was spread over the surface and left to dry, which is what gives it the colour.`, `${s.label} was once named after the craft itself, and the name has not changed since.`,
      `The strands are separated by hand before the work begins.`];
    const gap = card(s, { changeFamily: "section", treatment: "add_answer_section", recommendedChange: { kind: "existing_edit", field: "section", before: null, after: "Add the missing answer." },
      causeFinding: { cause: "retrieved_not_cited", action: null, evidenceKeys: ["k1"], competingExplanations: [], notConsidered: [], falsifier: "f", explanation: "e", payload: { cause: "retrieved_not_cited", engine: "chatgpt", promptText: s.q, missing: s.lines[2]!, aeoKind: "missing_information" } } as never });
    const verdicts: boolean[] = [];
    for (const after of CASES) { const wrote = { why: deliverableFailures({ actionType: "answer_block", targetUrl: s.url, finalCopy: after, beforeText: null, naturalHeading: s.heads[0], placementAnchor: s.h1, measurementTarget: s.q, claims: [], evidenceIdsUsed: [], uncertaintyOrOmitted: [] } as never, { targetUrl: s.url, title: s.title, h1: s.h1, bodyText: s.lines.join(" "), headings: s.heads, evidence: {}, trackedQuestion: s.q, ownedPaths: [], bannedTerms: [], demand: { preserve: [], vocabulary: [] }, assignment: ASSIGN({ standard: "missing_answer", shape: "inline_addition" }) } as never) };
      verdicts.push(wrote.why.some((r) => r.includes(POINTS)), staleCopyReasons(card(s, { changeFamily: "section", claims: [{ text: "c", supportedBy: ["page-copy-1"] }], supportFacts: [{ id: "page-copy-1", fact: s.lines[0]! }],
        recommendedChange: { kind: "existing_edit", field: "section", before: null, after, where: 'A new section headed "H"' }, assignment: ASSIGN({ standard: "restructuring" }) }), new Map([[canonicalUrlKey(s.url), bodyOf(s)]]) as never, [], { title: s.title, h1: s.h1, outline: s.heads } as never, false, []).includes(POINTS)); }
    expect(verdicts, "an arrangement statement is refused before a cent is spent on reading it for sense and again on the banked row it was serving from, whatever the subject and whatever tense it narrates in, and a factual verb, a quoted sentence, a reader's own question and a thing genuinely spread over a surface or separated by hand are untouched at both doors").toEqual([true, true, true, true, false, false, false, false, false, false, false, false, true, true, true, true, true, true, true, true, true, true, false, false, false, false, false, false]); });
  it.each(SITES)("owes the results page for a search whose winners were never read, keeps the settlement where they were read and carry nothing, and hires the writer where one carries something, on $t", async (s) => {
    const W = `https://winner-${s.t}.example/page`, novel = s.t === "tenant-one"
      ? "The water in these tide pools drops to four degrees each February, when the anemones seal themselves shut against the frost."
      : "Un bastidor de veinte centimetros lleva hilo de seda japonesa, tenido en frio antes de enhebrar la aguja.";
    const snap = (mainText: string | null): Record<string, unknown> => ({ ...snapOf(s), research: mainText == null ? {} : { serpEvidence: [{ query: s.ask, observedAt: null, organic: [{ rank: 1, url: W, domain: "winner.example", title: null }], aiOverview: [], aiMode: [], paa: [], related: [] }],
        winningPages: [{ url: W, domain: "winner.example", engines: [], examplePrompts: [], appearances: [{ query: s.ask }], extract: { title: "Winner", h1: null, wordCount: 900, headings: [], faqCount: 0, entityNames: [], mainText, truncated: false, heldChars: mainText.length, totalChars: mainText.length } }] },
      ownedPages: [{ url: s.url, content: { wordCount: 400, title: s.title, h1: s.h1, outline: s.heads }, search: { clicks90d: 1, impressions90d: 900, ctr90d: 0.01, position90d: 8, topQueries: [{ query: s.ask, impressions: 900, clicks: 0, position: 8 }] } }] });
    const lost = (w?: "none" | "unread" | "read"): ChangeProposal => card(s, { changeFamily: "section", primaryQuery: s.ask, researchOnly: true, diagnosisCause: "ranking_loss", evidence: { query: s.ask, hints: [], evidenceRefCount: 1 },
      ...(w ? { winnersOnFile: w } : {}), recommendedChange: { kind: "existing_edit", field: "section", before: null, after: "The exact wording has not been written yet." } });
    const answering = { ...bodyOf(s), passages: [...s.lines, s.answer] };
    const draft = { field: "answer_block", before: null, after: novel, ...TAIL, placementAnchor: s.h1, naturalHeading: s.heads[0]!, measurementTarget: s.ask, claims: [{ text: novel, supportedBy: ["page-copy-1"] }] };
    const none = await run(s, lost("none"), draft, PASS, [], answering, snap(null)), quiet = await run(s, lost("read"), draft, PASS, [], answering, snap(s.answer)), names = await run(s, lost("read"), draft, PASS, [], answering, snap(novel));
    const unstamped = await run(s, lost(), draft, PASS, [], answering, snap(null));
    expect([none.row.obligation, none.owed.map((n) => [(n as { kind: string }).kind, (n as { query: string }).query, (n as { reasonCode: string }).reasonCode]), none.wrote.length, quiet.row.obligation, quiet.owed.length, quiet.wrote.length, names.owed.length, names.wrote.length > 0, unstamped.row.obligation, unstamped.owed.length], "unread winners owe serp; read-empty settles; substantive winner writes; unstamped same off research").toEqual([{ kind: "evidence", need: { kind: "serp", query: s.ask, reasonCode: "no_winner_to_read" } }, [["serp", s.ask, "no_winner_to_read"]], 0, { kind: "terminal", reason: "no substantive gap named" }, 0, 0, 0, true, { kind: "evidence", need: { kind: "serp", query: s.ask, reasonCode: "no_winner_to_read" } }, 1]); });
  it.each(SITES)("tells the writer a claim names at most eight ids and only the ones that carry it, and buys one attempt for an answer the schema cannot take, on $t", async (s) => {
    const nine = ["page-copy-1", "page-copy-2", "page-copy-3", "page-copy-4", "page-copy-5", "page-copy-6", "page-copy-7", "page-copy-8", "page-copy-9"];
    const r = await run(s, card(s), { field: "meta", before: "Old line.", after: `${s.lines[0]} ${s.lines[1]}`.slice(0, 150), ...TAIL, placementAnchor: s.h1, naturalHeading: null, measurementTarget: s.q, claims: [{ text: s.lines[0]!, supportedBy: nine }] });
    bodies.map = new Map([[canonicalUrlKey(s.url), bodyOf(s)]]); const asked: string[] = []; // AND A CALL THAT NEVER CAME BACK IS NOT A BODY THAT CANNOT BE USED: a transport failure keeps every corrective round it has today, so nothing here turns an outage into a settled refusal.
    await applyDraftedCopy([card(s)] as never, { tenantId: s.t, snapshot: snapOf(s) as never, now: NOW, budget: DRAFT_BUDGET.plan({ jobs: [{ key: DRAFT_BUDGET.keyOf(card(s)), family: "editor" as const, impact: 9, calls: DRAFT_BUDGET.DELIVERABLE_CALLS }], candidates: 1, calls: 30 }),
      complete: async ({ kind }: { kind: string }) => (kind === "editor_judgement" ? { value: PASS } : (asked.push(kind), { error: "the gateway did not answer", retryable: true })) } as never);
    expect([r.wrote.length, r.wrote[0]!.includes("AT MOST 8 IDS"), r.wrote[0]!.includes("never every id you were handed"), r.wrote[1]!.includes("supportedBy"), r.why[0]!.includes("schema_invalid"), r.row.status, asked.length], "eight-id cap; schema break settles once; transport keeps rounds").toEqual([2, true, true, true, true, "needs_review", 6]); });
  it.each(SITES)("hands complete captured answers to the primary writer once, within budget, never as draft claim support, on $t", async (s) => {
    const { extractPageSnapshot } = await import("@/domains/evidence/pages/extractor"), { COPY_RULES } = await import("@/domains/decision/copy-sanitize"), answer = `${s.answer} `.repeat(15).trim();
    const captured = extractPageSnapshot(`<main><h1>${s.h1}</h1><p>${s.lines[0]}</p><details><summary>${s.q}?</summary>${answer}</details></main>`, s.url, "p", s.t), f = captured.faqs[0]!;
    const drafted = { ...bodyOf(s), passages: [s.lines[0]!], vocabulary: s.lines[0]!, faqs: [{ question: f.question, answer: f.answer_text!, source: f.source, answerComplete: f.answer_complete }] }, asked: string[] = [];
    const ask = async (unpublished: boolean, complete = true) => { asked.length = 0; await draftFieldForPage({ field: "answer_block", body: { ...drafted, faqs: drafted.faqs.map((x) => ({ ...x, answerComplete: complete })) } as never, query: s.q, ownedPaths: [], minutes: 5, evidenceHints: [], brief: "Write the section.", unpublished }, { tenantId: s.t, now: NOW, complete: async ({ user }: { user: string }) => (asked.push(user), { error: "none", retryable: false }) } as never); return JSON.parse(/^SHARED EVIDENCE PACKET.*?: (.*)$/m.exec(asked[0]!)![1]!); };
    const madeUp = await ask(true), observed = await ask(false), sample = await ask(false, false), pair = `${f.question}\n${answer}`;
    expect([madeUp.evidence.some((e: { id: string; role: string }) => e.id === "draft-so-far-1" && e.role === "draft_not_claim_support"), madeUp.evidence.some((e: { id: string }) => e.id.startsWith("page-copy-")), observed.evidence.some((e: { text: string; role: string }) => e.text === pair && e.role === "claim_support"), sample.evidence.some((e: { text: string }) => e.text === pair), observed.page.body]).toEqual([true, false, true, false, s.lines[0]]);
    const oversized = COPY_RULES.pageEvidence(drafted.passages, "x".repeat(13000), 12000, { query: s.q, pairs: [{ ...drafted.faqs[0]!, answer: "y".repeat(13000), source: "html_details" }] });
    expect([oversized.truncated, Object.values(oversized.evidence).reduce((n, t) => n + t.length, 0) <= 12000, Object.values(oversized.evidence).includes(s.lines[0]!)]).toEqual([true, true, true]); });
  const HEADWORD = "it opens with the search words as a label and a colon";
  it.each(SITES)("refuses the search phrase used as a label on a missing answer, takes the same content as a reader's sentence, and leaves every other standard's colon alone, on $t", (s) => {
    const said = (standard: string, after: string): string[] => staleCopyReasons(card(s, { changeFamily: "section", claims: [{ text: "c", supportedBy: ["page-copy-1"] }], supportFacts: [{ id: "page-copy-1", fact: s.lines[0]! }],
      recommendedChange: { kind: "existing_edit", field: "section", before: null, after, where: 'A new section headed "H"' }, assignment: ASSIGN({ standard }) }), new Map([[canonicalUrlKey(s.url), bodyOf(s)]]) as never, [], { title: s.title, h1: s.h1, outline: s.heads } as never, false, []);
    const labelled = `${s.q}: ${s.lines[2]}`, readerly = s.lines[2]!;
    expect([said("missing_answer", labelled).some((r) => r.includes(HEADWORD)), said("missing_answer", readerly).some((r) => r.includes(HEADWORD)), said("restructuring", labelled).some((r) => r.includes(HEADWORD)), said("summary", labelled).some((r) => r.includes(HEADWORD))],
      "missing_answer refuses search-as-label; other standards do not").toEqual([true, false, false, false]); });
  it.each(SITES)("hands the same refusal to the writer at the door the next paid redraft is briefed from, on $t", async (s) => {
    const gap = card(s, { changeFamily: "section", treatment: "add_answer_section", recommendedChange: { kind: "existing_edit", field: "section", before: null, after: "Add the missing answer." },
      causeFinding: { cause: "retrieved_not_cited", action: null, evidenceKeys: ["k1"], competingExplanations: [], notConsidered: [], falsifier: "f", explanation: "e", payload: { cause: "retrieved_not_cited", engine: "chatgpt", promptText: s.q, missing: s.lines[2]!, aeoKind: "missing_information" } } as never });
    const wrote = async (after: string) => (await run(s, gap, { field: "answer_block", before: null, after, ...TAIL, placementAnchor: s.h1, naturalHeading: s.heads[0]!, measurementTarget: s.q, claims: [{ text: after, supportedBy: ["page-copy-3"] }] })).why;
    expect([(await wrote(`${s.q}: ${s.lines[2]}`)).some((r) => r.includes(HEADWORD)), (await wrote(s.lines[2]!)).some((r) => r.includes(HEADWORD))],
      "writer door refuses search-as-label before judge spend").toEqual([true, false]); });
  it.each(SITES)("keeps the standard the writer was briefed with on the words it was briefed for when a later pass re-mints the same change, and lets no re-mint's brief ride onto finished copy, on $t", async (s) => {
    const line = `${s.lines[0]} ${s.lines[1]}`.slice(0, 150);
    const drafted = (await run(s, card(s), { field: "meta", before: "Old line.", after: line, ...TAIL, placementAnchor: s.h1, naturalHeading: null, measurementTarget: s.q, claims: [{ text: line, supportedBy: ["page-copy-1"] }] })).row;
    const remint = (row: ChangeProposal): ChangeProposal => ({ ...card(s), researchOnly: true, changeFamily: row.changeFamily, recommendedChange: { ...row.recommendedChange, after: "The exact wording lands on the next funded pass." } as never, research: { missing: "the exact wording", next: "the next funded pass writes it" } });
    const kept = preferFinished(remint(drafted), drafted);
    const answer = card(s, { changeFamily: "section", claims: [{ text: s.lines[2]!, supportedBy: ["page-copy-1"] }], supportFacts: [{ id: "page-copy-1", fact: s.lines[0]! }], assignment: ASSIGN({ standard: "missing_answer" }),
      recommendedChange: { kind: "existing_edit", field: "answer_block", before: null, after: s.lines[2]!, where: 'A new section headed "H"' } });
    const keptAnswer = preferFinished(remint(answer), answer), brief = preferFinished({ ...remint(answer), assignment: answer.assignment }, { ...answer, assignment: undefined });
    expect([drafted.assignment?.standard, kept.recommendedChange.kind === "existing_edit" ? kept.recommendedChange.after : "", kept.assignment?.standard,
      keptAnswer.assignment?.standard, editorialStandard({ field: "answer_block", link: false, assignment: keptAnswer.assignment, changeFamily: keptAnswer.changeFamily }), brief.assignment?.standard ?? "none"],
      "standard survives remint with finished words; brief without prior assignment is dropped").toEqual(["summary", line, "summary", "missing_answer", "missing_answer", "none"]); });
  it.each(SITES)("refuses the search words as a label on an answer block under any standard, and keeps the standard's own scope for a section under its own heading, on $t", (s) => {
    const said = (field: "answer_block" | "section", standard: string): string[] => staleCopyReasons(card(s, { changeFamily: "section", claims: [{ text: "c", supportedBy: ["page-copy-1"] }], supportFacts: [{ id: "page-copy-1", fact: s.lines[0]! }],
      recommendedChange: { kind: "existing_edit", field, before: null, after: `${s.q}: ${s.lines[2]}`, where: 'A new section headed "H"' }, assignment: ASSIGN({ standard }) }), new Map([[canonicalUrlKey(s.url), bodyOf(s)]]) as never, [], { title: s.title, h1: s.h1, outline: s.heads } as never, false, []);
    expect([said("answer_block", "restructuring").some((r) => r.includes(HEADWORD)), said("answer_block", "summary").some((r) => r.includes(HEADWORD)), said("section", "restructuring").some((r) => r.includes(HEADWORD)), said("section", "missing_answer").some((r) => r.includes(HEADWORD))],
      "answer_block refuses search-as-label; section follows standard").toEqual([true, true, false, true]); });
  it.each([false, true, "answer"])("empty/weak page writes body and meta together without re-funding a stored answer, weak=%s", async (weak) => {
    const s = { ...SITES[0]!, q: SITES[0]!.ask, lines: weak ? ["Tide pools lie along this rocky shore."] : [], heads: [] }, c = card(s, weak === "answer" ? { changeFamily: "answer_block", treatment: "add_answer_section", recommendedChange: { kind: "existing_edit", field: "answer_block", before: null, after: "Write the answer." } } : {});
    const snap = { ...snapOf(s), ownedPages: [{ ...snapOf(s).ownedPages[0]!, content: { ...snapOf(s).ownedPages[0]!.content, wordCount: weak ? 8 : 0 } }] }; const emit = (field: string) => ({ ...TAIL, field, before: field === "meta" ? "Old line." : null, after: s.answer, naturalHeading: null, placementAnchor: s.h1, measurementTarget: s.q, claims: [{ text: s.answer, supportedBy: ["fact-1"] }] });
    const r = await run(s, c, emit, PASS, [await reading(s)], bodyOf(s), snap); expect([r.row.status, r.row.bundle?.components.map((x) => [x.kind, x.after]), openHold(r.row).defects], r.why.join("; ")).toEqual(["ready", [["opening_answer", s.answer], ["meta", s.answer]], []]);
    const stamped = { ...r.row, assignment: { ...r.row.assignment!, checkedGroups: ["River mammals", "Wetland birds"] } }, banked = deserializeChangeProposal(serializeChangeProposal(stamped))!, judged = { n: 0 };
    expect([deserializeChangeProposal(serializeChangeProposal({ ...banked, factIdentity: '[["asked","t"]]' }))?.factIdentity, banked.assignment?.checkedGroups, banked.recommendedChange.kind === "existing_edit" ? banked.recommendedChange.field : "", staleCopyReasons(banked, bodies.map as never, [], { ...snap.ownedPages[0]!.content, metaDescription: "Old line." }), openHold(banked).defects]).toEqual(['[["asked","t"]]', ["River mammals", "Wetland birds"], expect.stringMatching(/^(?:answer_block|section)$/), [], [expect.stringContaining("complete editor acceptance")]]);
    const reread = await reviewFinishedCopy(banked, { tenantId: s.t, now: NOW, judge: async (d) => (judged.n++, { ...PASS, claims: rule(d.claims) }) as never }), kept = preferFinished({ ...card(s), id: banked.id, researchOnly: true, factIdentity: banked.factIdentity, copyStamp: banked.copyStamp, diagnosisCause: banked.diagnosisCause, recommendedChange: { kind: "existing_edit", field: "meta", before: "Old line.", after: "The exact wording lands on the next funded pass." } }, banked);
    expect([judged.n, reread.row && openHold(reread.row).defects, openHold({ ...banked, bundle: { ...banked.bundle!, components: banked.bundle!.components.slice(1) } }).defects.length > 0, kept.bundle?.components.length, (kept.recommendedChange as { after: string }).after, kept.previousCopy?.retiredBecause ?? null]).toEqual([2, [], true, 2, s.answer, null]);
    { passState.snapshot = { ...snap, competitors: [], keywordDemand: [], questionDemand: [], intentClusters: [], cannibalization: [], contentGaps: [], internalLinkOpportunities: [], aiCitations: { ownedCited: 0, competitorCited: 0, engines: [], rowsScanned: 0 }, research: emptyResearchEvidence(), evidenceHash: "fixture", ownedPages: [{ ...snap.ownedPages[0]!, content: { ...snap.ownedPages[0]!.content, internalLinks: [], schemaTypes: [] }, aiCitations: { count: 0, distinctPrompts: 0, engines: [] } }] };
      const context = (rows: ChangeProposal[]) => new Map<string, unknown>([[`proposals:rows:${s.t}`, Promise.resolve(new Map(rows.map((row) => [row.id, row])))], [`cards:extra:${s.t}`, Promise.resolve({ run: { cards: [c], complete: false, held: [], needsOwnPage: [], families: [] } })], [`cards:factual:${s.t}`, Promise.resolve({ cards: [], complete: false })], [`cards:recovery:${s.t}`, Promise.resolve({ cards: [], complete: false, window: { earlyDays: 0, earlyFrom: null, earlyTo: null }, losses: [] })]]), complete = vi.fn(async () => ({ error: "No second writer or judge may be hired", retryable: false })), options = { now: NOW, produce: true, persist: false, maxDrafts: 1, complete };
      const before = await produceProposalsForTenant(s.t, { ...options, shared: context([]) }); expect(before.paid.funded).toContain(DRAFT_BUDGET.keyOf(c)); complete.mockClear(); const again = await produceProposalsForTenant(s.t, { ...options, shared: context([banked]) }); expect([again.paid.funded, complete.mock.calls.length]).toEqual([[], 0]);
      const store = await import("@/domains/decision/proposal-store"), save = vi.spyOn(store, "saveChangeProposal").mockResolvedValue("saved");
      for (const researchOnly of [false, true]) for (const after of ["no added description", "", "Joojeh Kabob"]) {
        const stored = { ...banked, id: `${s.t}::/persian-kabobs/joojeh-kabob::existing_edit::x`, status: "ready" as const, researchOnly, bundle: undefined, pagePath: "/persian-kabobs/joojeh-kabob", pageUrl: "https://alpha.example/persian-kabobs/joojeh-kabob", primaryQuery: "joojeh kabob", pageLabel: "Joojeh Kabob", copyStamp: "Joojeh Kabob|Joojeh Kabob|", recommendedChange: { kind: "existing_edit" as const, field: "meta" as const, before: "Old line.", after: after! } };
        save.mockClear(); await produceProposalsForTenant(s.t, { ...options, persist: true, maxDrafts: 0, shared: context([stored]) }); expect(save.mock.calls.filter(([p]) => p.id === stored.id).at(-1)?.[0].status === "needs_review", JSON.stringify({ after, researchOnly, holds: openHold(stored).defects, saves: save.mock.calls.map(([p]) => [p.id, p.status]) })).toBe(true); expect(complete).not.toHaveBeenCalled();
      } save.mockRestore(); }
    for (const bad of ["no added description", "", s.h1]) { const failed = await run(s, { ...c, status: "ready" }, (field) => field === "meta" ? { ...emit(field), after: bad } : emit(field), PASS, [await reading(s)], bodyOf(s), snap); expect(failed.row.status).not.toBe("ready"); }
    for (const completeness of ["complete", "partial"]) { const headingOnly = { ...s, lines: [s.h1], heads: [] }, refused = await run(headingOnly, card(headingOnly, { status: "ready" }), {}, PASS, [], { ...bodyOf(headingOnly), completeness }); expect([refused.wrote.length, refused.row.status]).toEqual([0, "needs_review"]); } expect((await run(s, c, emit, PASS, [], bodyOf(s), snap)).row.status).not.toBe("ready"); });
  it("a populated page still owing missing_answer refuses premature meta", async () => {
    const s = SITES[0]!, c = card(s, { causeFinding: { cause: "retrieved_not_cited", payload: { cause: "retrieved_not_cited", missing: s.ask, aeoKind: "missing_answer" } } as never }), r = await run(s, c, {}); expect(r.row.status).not.toBe("ready"); expect(r.wrote.every((x) => !x.includes("Field to edit: meta"))).toBe(true); });
  it.each(SITES)("refuses a figure that stands only in the brief or in a rival's briefing line, and takes the same figure where the checked reading the copy cites carries it, on $t", async (s) => {
    const FIGURE = "3157", NUMBER = `This draft says "${FIGURE}"`, winner = (s: Site) => ({ url: `https://winner.example${new URL(s.url).pathname}`, domain: "winner.example", engines: [], examplePrompts: [], appearances: [{ query: s.q }, { query: s.ask }], extract: { title: s.title, h1: null, wordCount: Number(FIGURE), headings: [s.ask], sections: [{ heading: s.ask, text: s.figured }], mainText: `${s.q} is discussed in the guide. `.repeat(150) + `${s.ask}\n${s.figured}`, truncated: false, faqCount: 0, entityNames: [], openingSample: "", hasList: false } });
    const c = card(s, { changeFamily: "section", treatment: "add_answer_section", recommendedChange: { kind: "existing_edit", field: "section", before: null, after: "Add the missing answer." }, causeFinding: { cause: "retrieved_not_cited", action: null, evidenceKeys: ["k1"], competingExplanations: [], notConsidered: [], falsifier: "f", explanation: "This page is asked for a search it never answers.", payload: { cause: "retrieved_not_cited", engine: "chatgpt", promptText: s.q, missing: s.ask, aeoKind: "missing_information" } } as never });
    const draft = { field: "answer_block", before: null, after: s.figured, ...TAIL, placementAnchor: s.h1, naturalHeading: null, measurementTarget: s.q, claims: [{ text: s.figured, supportedBy: ["fact-1"] }] }; // the assignment asks for an inline addition, so the words carry no heading of their own
    const asked = { ...snapOf(s), ownedPages: [{ ...snapOf(s).ownedPages[0]!, search: { clicks90d: 0, impressions90d: 0, ctr90d: 0, position90d: 6, topQueries: [{ query: s.ask, impressions: Number(FIGURE), clicks: 0, position: 6 }] } }] };
    const briefed = await run(s, c, draft, PASS, [await reading(s)], bodyOf(s), asked);
    const bank = { serpEvidence: [{ query: s.q, organic: [{ rank: 1, url: winner(s).url }] }], winningPages: [winner(s)] };
    const carried = await run(s, c, draft, PASS, [await reading(s, s.ask, s.figured)], bodyOf(s), { ...asked, research: bank });
    const rivalled = await run(s, c, draft, PASS, [await reading(s)], bodyOf(s),
      { ...snapOf(s), research: bank });
    expect([briefed.row.status !== "ready" && briefed.why.some((w) => w.includes(FIGURE)), rivalled.row.status !== "ready" && rivalled.why.some((w) => w.includes(FIGURE)), carried.why, carried.row.status],
      "a figure only the diagnosis printed and a figure only a rival's line carries are both refused as ungrounded, and the same figure inside the reading the copy cites is the one that stands").toEqual([true, true, [], "ready"]);
    expect(rivalled.wrote.join(" ").includes("rival-1"), "the rival line still reaches the writer as briefing, which is exactly the text that may not ground the claim").toBe(true);
    const packet = (t: string) => JSON.parse(/^SHARED EVIDENCE PACKET.*?: (.*)$/m.exec(t)![1]!), p = packet(carried.judged[0]!); expect(p).toEqual(packet(carried.wrote.find((t) => t.includes("SHARED EVIDENCE PACKET"))!)); expect([p.comparison.focus, p.comparison.winners[0].held.includes(s.figured), p.comparison.winners[0].role, p.comparison.winners[0].heldWhole]).toEqual([[s.ask], true, "research_not_claim_support", false]); });
  it.each(SITES)("keeps every word a bound reading is recognised by, so presenting it as a sentence never sends a writable answer back to buy another source, on $t", async (s) => {
    const { demandOf } = await import("@/domains/decision/drafted-copy"), { GAIN } = await import("@/domains/decision/draft-resolution"), { topicTokens } = await import("@/domains/evidence/relevance-gate"), r = await reading(s);
    const page = { url: s.url, content: { wordCount: 400, title: s.title, h1: s.h1, outline: s.heads }, search: { clicks90d: 0, impressions90d: 0, ctr90d: 0, position90d: 0, topQueries: [{ query: s.ask, impressions: 120, clicks: 0, position: 6 }] } };
    const one = demandOf(page as never, bodyOf(s) as never, [r] as never, null, s.t).facts[0]!, said = new Set(topicTokens(one.fact));
    expect(demandOf(page as never, { ...bodyOf(s), headings: [s.answer], vocabulary: s.answer } as never, [], null, s.t).passages, "headings and duplicated vocabulary are not additional answering passages").toEqual(s.lines);
    expect([bodyOf(s), { ...bodyOf(s), completeness: "sample_only" }, { ...bodyOf(s), version: "stale_known_good" }, { ...bodyOf(s), version: undefined }].map((b) => [demandOf(page as never, b as never, [], null, s.t).complete, GAIN.resolution("acquire_factual_source", snapOf(s) as never, card(s), page as never, b as never, []).resolution]), "current complete evidence advances; partial, stale or unknown freshness owes page evidence before buying facts").toEqual([[true, "acquire_serp"], [false, "acquire_page_source"], [false, "acquire_page_source"], [false, "acquire_page_source"]]);
    expect([one.id, one.fact.startsWith(`${s.ask}:`), one.fact.startsWith(s.answer), topicTokens(s.ask).every((w) => said.has(w))],
      "the id is untouched, the search no longer labels the sentence, the sentence leads, and every word the gap reader asks a bound fact to carry is still in the string, which is why the search rides behind the sentence instead of being dropped").toEqual(["fact-1", false, true, true]); });
  const gloss = async (s: Site) => { const { deriveSupport, claimTypeOf } = await import("@/domains/evidence/pages/claim-support"), { rulesVersionFor } = await import("@/domains/evidence/pages/fact-checks"), { pageHashOf } = await import("@/domains/evidence/pages/fact-check-run"), b = bodyOf(s), page = new URL(s.url).pathname, says = `${s.word}: ${s.right}`;
    const c = { tenantId: s.t, page, statementKey: "gloss", pageLocator: null, subject: s.word, claimKind: claimTypeOf(s.word, s.wrong, null), current: s.wrong, proposed: s.right, url: "https://ref.example/entry", kind: "dictionary" as const, quote: says, titleContext: null };
    return { page, statementKey: "gloss", subject: s.word, current: s.wrong, proposed: s.right, literal: null, usage: null, sources: [{ url: c.url, kind: "dictionary", says, support: deriveSupport(c) }], agreement: "single_source", confidence: "confirmed", verdict: "page_imprecise", alsoAt: [], note: "",
      pageContentHash: pageHashOf([b.title, b.h1, ...b.headings, ...b.passages].join("\n")), pageLocator: null, sourceReadAt: NOW.toISOString(), state: "checked", rulesVersion: rulesVersionFor({ subject: s.word, current: s.wrong }), evidenceBasis: null, checkedAt: NOW.toISOString() }; };
  it.each(SITES)("shows a checked reading as the reader's sentence however few words its search carries, keeps a correction's own subject in front of it, and moves nothing about which version a reading is banked under, on $t", async (s) => {
    const { demandOf } = await import("@/domains/decision/drafted-copy"), { topicTokens } = await import("@/domains/evidence/relevance-gate");
    const { rulesVersionFor, MISSING_ANSWER_RULES_VERSION: RV, VERIFICATION_RULES_VERSION: CV } = await import("@/domains/evidence/pages/fact-checks"), { asksAQuestion } = await import("@/domains/evidence/pages/claim-support");
    const page = { url: s.url, content: { wordCount: 400, title: s.title, h1: s.h1, outline: s.heads }, search: { clicks90d: 0, impressions90d: 0, ctr90d: 0, position90d: 0, topQueries: [{ query: s.narrow, impressions: 120, clicks: 0, position: 6 }] } }, bare = s.right.replace(/\.$/, "");
    const one = async (rows: unknown[]): Promise<string> => demandOf(page as never, bodyOf(s) as never, rows as never, null, s.t).facts[0]?.fact ?? ""; const thin = await one([await reading(s, s.narrow, s.narrowAnswer)]), part = await one([await reading(s, s.word, bare)]), quoted = await one([await reading(s, s.word, `"${bare}."`)]), fixed = await one([await gloss(s)]);
    const gap = card(s, { changeFamily: "section", treatment: "add_answer_section", recommendedChange: { kind: "existing_edit", field: "section", before: null, after: "Add the missing answer." },
      causeFinding: { cause: "retrieved_not_cited", action: null, evidenceKeys: ["k1"], competingExplanations: [], notConsidered: [], falsifier: "f", explanation: "e", payload: { cause: "retrieved_not_cited", engine: "chatgpt", promptText: s.q, missing: s.narrow, aeoKind: "missing_information" } } as never });
    const wrote = (await run(s, gap, { field: "answer_block", before: null, after: s.narrowAnswer, ...TAIL, placementAnchor: s.h1, naturalHeading: s.heads[0]!, measurementTarget: s.narrow, claims: [{ text: s.narrowAnswer, supportedBy: ["fact-1"] }] }, PASS, [await reading(s, s.narrow, s.narrowAnswer)])).wrote.join("\n");
    const leads = wrote.slice(wrote.indexOf("MUST LEAD WITH"), wrote.indexOf("SUPPORTING FACTS")), said = new Set(topicTokens(thin));
    expect([asksAQuestion(s.narrow), asksAQuestion(s.ask), rulesVersionFor({ subject: s.narrow, current: "" }), rulesVersionFor({ subject: s.ask, current: "" }),
      thin.startsWith(`${s.narrow}:`), thin.startsWith(s.narrowAnswer), thin.includes(`This is about "${s.narrow}".`), topicTokens(s.narrow).every((w) => said.has(w)),
      part.startsWith(`${s.word}: ${bare}`), part.includes("This is about"), quoted.startsWith(`"${bare}."`), quoted.includes(`This is about "${s.word}".`),
      fixed.startsWith(`${s.word}: ${s.right}`), fixed.includes("This is about"), leads.includes(s.narrowAnswer), leads.includes(`${s.narrow}:`)],
      "the width rule still refuses the three-word search and still calls the long one a question, and both are banked under exactly the versions they were, so nothing about banking moved; the narrow search never stands in front of its own answer, the answer leads, the search rides behind it, and every word the gap reader binds a fact by is still in the string; a gloss that only reads behind its headword keeps that headword in front and takes nothing behind it, while the same headword answered by a sentence closing on a quotation mark leads with that sentence; a correction of words this page publishes keeps the page's own name in front; and the one line telling the writer what to open with carries the answer sentence and never the search words").toEqual([false, true, CV, RV, false, true, true, true, true, false, true, true, true, false, true, false]); });
  it.each(SITES)("reads a possessive as the name it possesses, so a draft naming this page's own subject is not refused for a word the page prints, and a name the page never prints is still refused, on $t", async (s) => {
    const { entityGrounded, checkFactualEntailment } = await import("@/domains/decision/drafts/factual-entailment"), head = s.label.split(" ")[0]!, body = `${s.label} ${s.lines.join(" ")}`, seen = body.toLowerCase();
    const kept = checkFactualEntailment({ draftText: `${head}'s water is what a visitor asks about.`, pageBodyText: body, query: s.q }), refused = checkFactualEntailment({ draftText: "Kelp Forest Reserve protects them.", pageBodyText: body, query: s.q });
    expect([entityGrounded(`${head}'s`, seen), entityGrounded(`${head}\u2019s`, seen), entityGrounded(`${s.label}'`, seen), entityGrounded(head, seen), entityGrounded("Kelp Forest Reserve", seen),
      kept.entailed, kept.violations, refused.entailed, refused.violations.length, refused.violations[0]?.includes("Check it before you paste"), /\bI\b|\bmy data\b/.test(refused.violations.join(" "))],
      "a straight apostrophe, a curly one and a plural possessive all name the thing the page names, the bare name is unchanged, and a name this page never prints is still refused; the whole gate lets a possessive of the page's own subject through with nothing to say about it, still refuses an invented name, still tells the operator what to do about it, and says none of it in the first person").toEqual([true, true, true, true, false, true, [], false, 1, true, false]); });
  it.each(SITES)("lets a replacement keep the exact ranking word the words it replaces already carry, and refuses every wider one at both doors, on $t", async (s) => {
    const body = { ...bodyOf(s), passages: [...s.lines, `${s.section} ${s.boast}`] }, keeps = `${s.boast} ${s.lines[2] ?? s.lines[0]}`, wider = `${s.lines[0]} It is the leading shore of its kind anywhere.`;
    const rewriting = (over: Record<string, unknown> = {}) => card(s, { primaryQuery: s.section, changeFamily: "section", treatment: "rewrite_existing_section", recommendedChange: { kind: "existing_edit", field: "section", before: null, after: "Rewrite the section." },
      causeFinding: { cause: "retrieved_not_cited", action: null, evidenceKeys: ["k1"], competingExplanations: [], notConsidered: [], falsifier: "f", explanation: "e", payload: { cause: "retrieved_not_cited", engine: "chatgpt", promptText: s.section, missing: s.narrow, aeoKind: "missing_information" } } as never, ...over });
    const draft = (after: string) => ({ field: "section", before: null, after, ...TAIL, placementAnchor: s.section, naturalHeading: null, measurementTarget: s.section, claims: [{ text: s.lines[0]!, supportedBy: ["page-copy-1"] }] });
    const kept = await run(s, rewriting(), draft(keeps), PASS, [], body), over = await run(s, rewriting(), draft(wider), PASS, [], body);
    const added = await run(s, rewriting({ treatment: "add_answer_section" }), draft(keeps), PASS, [], body);
    const fw = (x: { why: string[] }) => x.why.some((w) => w.includes("firewall:superlative")), canon = (x: { why: string[] }) => x.why.some((w) => w.includes("superlative claim"));
    expect([fw(kept), canon(kept), kept.wrote.join("\n").includes("keeping that exact word is keeping what the page already says"), fw(over), fw(added) === false],
      "a replacement keeping the ranking word its own replaced passage carries passes the writer's firewall and the canon's quality gate, and the prompt that orders it to keep that passage's words says so at the line where the order is given; a ranking word that passage does not carry is still refused at the writer's door; an ADDITION defers the firewall and the superlative rides the card as a caveat instead (operator, 2026-09-11, one pass)").toEqual([false, false, true, true, true]); });
  it.each(SITES)("keeps every sentence one of its own gates wrote out of the operator's caveats while the hold and the obligation still say what is owed, on $t", (s) => {
    const gate = "it did not pass the read of its own words: nothing in it beyond the page heading names something this page's own words carry", note = "Read off the last stored copy of each page, so a description rewritten since that read is not counted here.";
    const held = card(s, { faults: [gate], limitations: [gate, note, "its copy carries no record of what it stands on"], claims: [{ text: s.lines[0]!, supportedBy: ["fact-1"] }], supportFacts: [{ id: "fact-1", fact: `${s.lines[0]} https://example.org says so` }], recommendedChange: { kind: "existing_edit", field: "meta", before: "Old line.", after: s.lines[1]! } });
    const hold = openHold(held);
    expect([hold.caveats, hold.why.includes(gate), nextObligation(held)?.kind, (nextObligation(held) as { instruction?: string } | null)?.instruction],
      "what is left for a person to keep in mind is the sentence written for a person and the count of sources behind the words; the gate's own sentence and the store's own record sentence are both gone from it, the hold still names the gate's sentence, and the typed next step still carries it word for word as the objection to write against").toEqual([["Backed by 1 checked source. Add a second before publishing if being wrong here would cost you.", note], true, "redraft", gate]); });
  it.each(SITES)("hands its own family count back to the caller on every branch, including the one where it refuses nothing, on $t", (s) => {
    const at = (slug: string) => `${new URL(s.url).origin}/family/${slug}`, kinBody = (slug: string) => ({ ...bodyOf(s), url: at(slug), title: `${s.title} ${slug}`, h1: `${s.title} ${slug}` });
    const mine = kinBody("self"), sibs = [kinBody("two"), kinBody("three")], inventory = [mine.url, ...sibs.map((b) => b.url)];
    const ask = (held: typeof sibs, inv: readonly string[]): { asked: number; loaded: number } => { const out = { asked: -1, loaded: -1 };
      staleCopyReasons(card(s, { pageUrl: mine.url, pagePath: "/family/self", recommendedChange: { kind: "existing_edit", field: "meta", before: "Old line.", after: `${s.lines[1]}` } }), new Map(held.map((b) => [canonicalUrlKey(b.url), b])) as never, [], { title: mine.title, h1: mine.h1, outline: s.heads } as never, false, [], inv, out); return out; };
    expect([ask([mine, sibs[0]!], inventory), ask([mine, ...sibs], inventory), ask([mine, ...sibs], []), ask(sibs, inventory)],
      "a short family reports what the inventory names and what the caller handed over, a complete family reports the same two numbers rather than leaving the caller to recompute them, a caller that cannot say what the family is has its window taken as the whole of it, and a page whose own body was never read asked its family nothing").toEqual([{ asked: 2, loaded: 1 }, { asked: 2, loaded: 2 }, { asked: 2, loaded: 2 }, { asked: 0, loaded: 0 }]); });
  it.each(SITES)("banks each checked reading with the addresses that quoted it and what kind of source each one is, drops the address that quoted nothing, and keeps all of it through the reading that approves the words, on $t", async (s) => {
    const quiet = { ...(await reading(s)), sources: [{ url: "https://ref.example/guide", kind: "encyclopedia", says: s.answer }, { url: "https://quiet.example/x", kind: "publisher", says: "  " }] };
    const gap = card(s, { changeFamily: "section", treatment: "add_answer_section", recommendedChange: { kind: "existing_edit", field: "section", before: null, after: "Add the missing answer." },
      causeFinding: { cause: "retrieved_not_cited", action: null, evidenceKeys: ["k1"], competingExplanations: [], notConsidered: [], falsifier: "f", explanation: "e", payload: { cause: "retrieved_not_cited", engine: "chatgpt", promptText: s.q, missing: s.ask, aeoKind: "missing_information" } } as never });
    const row = (await run(s, gap, { field: "answer_block", before: null, after: s.answer, ...TAIL, placementAnchor: s.h1, naturalHeading: null, measurementTarget: s.q, claims: [{ text: s.answer, supportedBy: ["fact-1"] }] }, PASS, [quiet])).row;
    const banked = (row.supportFacts ?? []).find((f) => f.id === "fact-1");
    expect([banked?.sources, (row.supportFacts ?? []).find((f) => f.id !== "fact-1")?.sources],
      "the reading's own quoting address is banked with the kind of source it is, the address that quoted nothing is not banked at all, and the page's own words carry no publisher")
      .toEqual([[{ url: "https://ref.example/guide", kind: "encyclopedia" }], undefined]);
    const { citedPublishers } = await import("@/domains/decision/completeness");
    const kept = await reviewFinishedCopy({ ...row, claims: undefined, status: "needs_review" } as never, { tenantId: s.t, now: NOW, judge: async () => ({ aeoPacket: PASS.aeoPacket, pageFit: true, claims: [{ i: 0, by: ["fact-1"], entailed: true }], usefulAndNatural: true, placementCorrect: true, resolvesDiagnosis: true, implementableNow: true, improvesPage: true, wouldHandToCustomer: true, notes: "The exact checked source supports these banked words.", resolution: "none" } as never) });
    expect([(kept.row?.supportFacts ?? []).find((f) => f.id === "fact-1")?.sources, citedPublishers(kept.row as never).size, citedPublishers(row).size],
      "a reading that rebuilds the record of what each sentence stands on keeps the provenance the row already held, so the publisher count does not fall back to prose the moment a row is read")
      .toEqual([[{ url: "https://ref.example/guide", kind: "encyclopedia" }], 1, 1]); });
});
describe("the deadline the editor asks before it starts a call", () => {
  for (const s of SITES) {
    const draft = { field: "meta", before: "Old line.", after: `${s.lines[0]} ${s.lines[1]}`.slice(0, 150), ...TAIL, placementAnchor: s.h1, naturalHeading: null, measurementTarget: s.q, claims: [{ text: s.lines[0]!, supportedBy: ["page-copy-1"] }] };
    const drive = async (stopBy: number, jump: number | null) => {
      bodies.map = new Map([[canonicalUrlKey(s.url), bodyOf(s)]]); facts.rows = [];
      const c = card(s), kinds: string[] = [], unsettled = new Set<string>(), why = new Map<string, string>();
      await applyDraftedCopy([c], { tenantId: s.t, snapshot: snapOf(s) as never, now: NOW, stopBy, unsettled, refusals: why,
        budget: DRAFT_BUDGET.plan({ jobs: [{ key: c.pagePath!, family: "editor", impact: 9, calls: DRAFT_BUDGET.DELIVERABLE_CALLS }], candidates: 1, calls: 30 }),
        complete: async ({ kind }: { kind: string }) => { kinds.push(kind); if (jump != null && kinds.length === 1) vi.setSystemTime(jump);
          return kind === "editor_judgement" ? { value: { ...PASS, claims: rule(draft.claims) } } : { value: draft }; } } as never);
      return { kinds, unsettled: [...unsettled], why: [...why.values()].join(" ") };
    };
    it(`${s.t}: a box that closes while the writer is in flight buys no reading of the words, and the card is owed rather than refused`, async () => {
      vi.useFakeTimers({ toFake: ["Date"] }); const at = Date.now();
      const cut = await drive(at + 300_000, at + 600_000); vi.setSystemTime(at); const ran = await drive(at + 600_000, null); vi.useRealTimers();
      expect([cut.kinds, cut.unsettled.length, cut.why.includes("time box ended before this call could start")], "the writer's call finished and the reading of meaning was never started, so nothing was bought past the box and the card is owed again at its own rank").toEqual([["atomic_edit"], 1, true]);
      expect([ran.kinds, ran.unsettled], "a box with room ahead of it starts both calls exactly as before").toEqual([["atomic_edit", "editor_judgement"], []]); });
  }
});
