/** RV2 review: a settled row whose winners nobody has read, driven through the REAL pass, on two synthetic accounts with unrelated subjects. The row's own results page IS on file (that is what "unread" means: a results page bought for the group, nothing read off it), which is the production shape B5's due-work change is about. What the pass writes onto the row, and what reaches the runtime's buying list, is asked here. */
import { describe, it, expect, beforeEach, vi } from "vitest";
import type { ChangeProposal } from "@/domains/decision/contracts";
import type { EvidenceSnapshot } from "@/domains/evidence/snapshot";
const store = vi.hoisted(() => ({ rows: new Map<string, ChangeProposal>(), withdrawn: new Set<string>() })); const env = vi.hoisted(() => ({ snap: null as unknown, calls: 0, checked: [] as unknown[], bodies: null as Map<string, unknown> | null, saves: 0, race: false }));
vi.mock("@/domains/decision/llm/adjudicator-budget", () => ({ checkBudget: async () => ({ allowed: true, remaining: 10 }), recordSpend: async () => {} }));
vi.mock("@/domains/decision/llm/winner-memory", () => ({ buildWinnerFewShots: async () => "", buildWinnerFewShotsWithPattern: async () => ({ fragment: "", patternHint: null }) }));
vi.mock("@/domains/decision/proposal-store", async (orig) => ({ ...(await orig<Record<string, unknown>>()), loadChangeProposals: async () => store.rows,
  terminalWorkKeys: async () => new Set<string>(), terminalProposalHistory: async () => ({ fingerprints: new Set<string>(), legacyMutationKeys: new Set<string>() }),
  saveChangeProposal: async (p: ChangeProposal, _t?: unknown, keep?: (r: ChangeProposal) => void, expected?: ChangeProposal) => { if (expected && env.race) { env.race = false; store.rows.set(p.id, { ...expected, status: "implemented_pending_verification" }); return "blocked"; } if (expected && store.rows.get(p.id) !== expected) return "blocked"; store.rows.set(p.id, p); env.saves++; keep?.(p); return "saved"; },
  withdrawnProposalIds: async () => store.withdrawn, withdrawChangeProposal: async () => "retired" as const }));
vi.mock("@/domains/evidence/snapshot-loader", () => ({ loadEvidenceSnapshot: async () => env.snap }));
vi.mock("@/domains/evidence/pages/fact-checks", async (orig) => ({ ...(await orig<Record<string, unknown>>()), readFactChecks: async () => env.checked }));
vi.mock("@/domains/evidence/pages/owned-context", async (orig) => ({ ...(await orig<Record<string, unknown>>()), loadOwnedPageBodies: async () => { if (!env.bodies) throw new Error("no body store in this fixture"); return env.bodies; } }));
vi.mock("@/domains/account", () => ({ loadBusinessProfile: async () => null, getTenant: async () => ({ id: "acct-reef", domain: "acct-reef.example", growth_goal: null }), basisTag: () => "basis_rv2" }));
import { emptyResearchEvidence } from "@/domains/evidence/funnel/research-evidence";
import { shapeBackingOf, topicSourceFacts } from "@/domains/decision/drafted-copy"; import { DRAFT_BUDGET } from "@/domains/decision/draft-budget"; import { COPY_RULES } from "@/domains/decision/copy-sanitize"; import { claimIdentity, pageHashOf } from "@/domains/evidence/pages/fact-check-run"; import { claimTypeOf, deriveSupport } from "@/domains/evidence/pages/claim-support"; import { canonicalUrlKey } from "@/domains/evidence/snapshot"; import { authorizedCorrections, rulesVersionFor, type FactCheck } from "@/domains/evidence/pages/fact-checks";
import { nextObligation } from "@/domains/decision/obligation";
const NOW = new Date("2026-09-06T09:00:00.000Z");
const SITES = [
  { t: "acct-reef", page: "/tide-pool-guide", q: "tide pool safety", lead: ["Tide pool safety for families", "Tide pool safety rules", "Tide pool safety and the rocks"] },
  { t: "acct-loom", page: "/blackwork-stitches", q: "blackwork stitch order", lead: ["Blackwork stitch order explained", "Blackwork stitch order for beginners", "Blackwork stitch order and tension"] },
] as const;
const owned = (s: (typeof SITES)[number]) => ({ url: `${s.t}.example${s.page}`, content: { title: "Guide", metaDescription: null, h1: "Guide", h2: [], outline: ["What to bring"], schemaTypes: [], hasFaq: false, faqCount: 0, wordCount: 900, internalLinks: [], fetchedAt: "2026-09-01T00:00:00.000Z" },
  search: { clicks90d: 40, impressions90d: 3000, ctr90d: 0.013, position90d: 9, topQueries: [{ query: s.q, impressions: 3000, clicks: 40, position: 9 }] }, engagement: null, friction: null, aiCitations: { count: 0, distinctPrompts: 0, engines: [] } });
const snapshot = (s: (typeof SITES)[number], titles: readonly string[]): EvidenceSnapshot => ({
  scope: { tenantId: s.t, site: `${s.t}.example`, builtAt: NOW.toISOString() }, aiCitations: { ownedCited: 0, competitorCited: 0, engines: [], rowsScanned: 0 },
  sources: [], competitors: [], keywordDemand: [], questionDemand: [], intentClusters: [], cannibalization: [], contentGaps: [], internalLinkOpportunities: [], evidenceHash: "rv2",
  research: { ...emptyResearchEvidence(), serpEvidence: [{ query: s.q, observedAt: "2026-09-05T00:00:00.000Z", organic: titles.map((title, i) => ({ rank: i + 1, domain: `rival-${i + 1}.example`, url: `https://rival-${i + 1}.example/x`, title })), aiOverview: [], aiMode: [], paa: [], related: [] }] } as never,
  ownedPages: [owned(s)] as never,
} as never);
/** The producer's own card, byte for byte the shape demand-recovery mints (producers/demand-recovery.ts:141). */
const card = (s: (typeof SITES)[number], over: Partial<ChangeProposal> = {}): ChangeProposal => ({
  id: `${s.t}::${s.page}::existing_edit::demand_recovery`, tenantId: s.t, kind: "existing_edit", pagePath: s.page,
  pageUrl: `https://${s.t}.example${s.page}`, pageLabel: s.page, primaryQuery: s.q, opportunityType: "Rebuild lost ground",
  changeFamily: "section", status: "needs_review", winnersOnFile: "unread", treatment: "add_answer_section",
  diagnosisCause: "ranking_loss", causeFinding: { cause: "ranking_loss", action: "act_existing_page", evidenceKeys: ["gsc"], competingExplanations: [{ cause: "ctr_snippet", reason: "the click rate held while the position fell" }], falsifier: "If the page returns to its old position and the clicks do not follow, the ground was not the cause.", explanation: "The page slid on its own results for this search.", notConsidered: [] } as never,
  recommendedChange: { kind: "existing_edit", field: "section", before: null, after: "The exact wording has not been written yet." },
  researchOnly: true, research: { missing: "Strengthen this page's coverage of the search it lost.", next: "The exact wording lands here once the editor writes it." },
  whyItMatters: "This page lost clicks on a search it used to earn.", operatorSteps: [], estimatedEffortMinutes: 30,
  riskLevel: "low", confidence: "low", limitations: ["The loss is measured from this account's own history."],
  evidence: { query: s.q, hints: [], evidenceRefCount: 1 }, impactScore: 400, upsidePerMonth: null,
  basis: "basis_rv2", publish: "manual", createdAt: NOW.toISOString(), copyStamp: "Guide|Guide||What to bring", ...over });
const drive = async (s: (typeof SITES)[number], titles: readonly string[], unresolved = false, recoveryComplete = true) => {
  vi.resetModules();
  vi.doMock("@/domains/decision/producers/demand-recovery", () => ({ demandRecoveryCards: async () => ({ cards: recoveryComplete ? [card(s, unresolved ? { diagnosisCause: "no_problem", causeFinding: { ...card(s).causeFinding!, cause: "no_problem", action: null }, treatment: undefined, obligation: { kind: "evidence", need: { kind: "competitor_page", query: s.q, reasonCode: "no_winner_to_read" } } } : {})] : [], complete: recoveryComplete, window: { earlyDays: 400, earlyFrom: null, earlyTo: null }, losses: [] }) }));
  const other = card(s, { id: `${s.t}::${s.page}-two::existing_edit::ai_answer_gap`, pagePath: unresolved ? s.page : `${s.page}-two`, pageUrl: `https://${s.t}.example${s.page}${unresolved ? "" : "-two"}`, primaryQuery: `${s.q} at night`, winnersOnFile: undefined, obligation: undefined, impactScore: 10 });
  vi.doMock("@/domains/decision/producers/extra", () => ({ extraQueuePass: async () => ({ run: { cards: [other], complete: true, held: [], needsOwnPage: [], families: ["ai_answer_gap"] }, unitLoad: null }) }));
  const { produceProposalsForTenant: run } = await import("@/domains/decision/produce-proposals");
  env.snap = snapshot(s, titles);
  return run(s.t, { now: NOW, bypassCache: true, produce: true, maxDrafts: unresolved ? 8 : 0, maxCalls: 20, persist: true, complete: async () => { env.calls++; return { value: {} }; } } as never);
};
beforeEach(() => { store.rows.clear(); env.calls = 0; env.saves = 0; env.checked = []; env.bodies = null; env.race = false; });
describe("the reading a settled row owes, through the pass that writes the row", () => {
  it("binds a newly checked external proposition to saved copy and invalidates its old review without replacing unrelated evidence", async () => { const s = SITES[0], sentence = "Iran's national animal is the Asiatic cheetah.", page = `https://${s.t}.example${s.page}`, body = { url: page, title: "Guide", h1: "Guide", headings: [], passages: [sentence], version: "current", completeness: "complete", contentHash: "capture-1", fetchedAt: NOW.toISOString() }, gapRow = card(s, { id: `${s.t}::${s.page}::existing_edit::title_external`, researchOnly: false, changeFamily: "title", recommendedChange: { kind: "existing_edit", field: "title", before: "Guide", after: "Asiatic Cheetah: Iran's National Animal" }, claims: [{ text: "The page is about Asiatic Cheetah and answers Iran's national animal.", supportedBy: ["page-copy-1"] }], supportFacts: [{ id: "page-copy-1", fact: sentence }], semanticReview: { version: 7, of: "old", claims: [], editor: { accepted: true } } as never, basis: "basis_rv2::d9", faults: ["it replaces a passage saying \"Guide\" and neither says it nor accounts for it: every original unit needs its own preservation disposition"], limitations: ["Preserve the old heading."] }); const gap = COPY_RULES.newExternalAuthorityGap(gapRow)!;
    const key = claimIdentity(gap.proposition, "", "missing"), url = "https://reference.example/asiatic-cheetah", support = deriveSupport({ tenantId: s.t, page: s.page, statementKey: key, pageLocator: "missing", subject: gap.proposition, claimKind: claimTypeOf(gap.proposition, sentence, "missing"), current: "", proposed: sentence, url, kind: "encyclopedia", quote: sentence, titleContext: null }); expect(support).not.toBeNull(); const fact: FactCheck = { page: s.page, statementKey: key, subject: gap.proposition, current: "", proposed: sentence, literal: null, usage: null, sources: [{ url, kind: "encyclopedia", says: sentence, support: support! }], agreement: "single_source", confidence: "likely", verdict: "page_correct", alsoAt: [], note: "", pageContentHash: pageHashOf([body.title, body.h1, ...body.headings, ...body.passages].join("\n")), pageLocator: "missing", sourceReadAt: NOW.toISOString(), state: "checked", rulesVersion: rulesVersionFor({ subject: gap.proposition, current: "" }), evidenceBasis: gapRow.basis ?? null, checkedAt: NOW.toISOString() };
    store.rows.set(gapRow.id, gapRow); env.checked = [fact]; env.bodies = new Map([[canonicalUrlKey(page), body]]); await drive(s, s.lead); const saved = store.rows.get(gapRow.id)!; expect([saved.claims?.some(c => c.text === sentence && c.supportedBy.some(id => /^fact-/.test(id))), saved.supportFacts?.some(f => f.finding?.statementKey === key), saved.semanticReview, saved.limitations.includes("Preserve the old heading."), saved.faults?.some(f => f.includes("every original unit needs its own preservation disposition")), COPY_RULES.newExternalAuthorityGap(saved)]).toEqual([true, true, undefined, true, true, null]);
    await drive(s, s.lead); expect([store.rows.get(gapRow.id)?.claims, store.rows.get(gapRow.id)?.supportFacts?.filter(f => /^fact-/.test(f.id)).length, env.calls]).toEqual([saved.claims, 1, 0]);
    for (const invalid of [{ ...fact, pageContentHash: "stale" }, { ...fact, evidenceBasis: "old-basis" }, { ...fact, page: "/other-page" }, { ...fact, proposed: "Iran's national animal is not the Asiatic cheetah." }]) { store.rows.set(gapRow.id, gapRow); env.checked = [invalid]; await drive(s, s.lead); expect(store.rows.get(gapRow.id)?.supportFacts?.some(f => /^fact-/.test(f.id))).not.toBe(true); }
    const qualifiedText = `${sentence} It was formerly recognized.`, qualifiedSupport = deriveSupport({ tenantId: s.t, page: s.page, statementKey: key, pageLocator: "missing", subject: gap.proposition, claimKind: claimTypeOf(gap.proposition, qualifiedText, "missing"), current: "", proposed: qualifiedText, url, kind: "encyclopedia", quote: qualifiedText, titleContext: null }), mismatch: FactCheck = { ...fact, proposed: qualifiedText, sources: [{ url, kind: "encyclopedia", says: qualifiedText, support: qualifiedSupport! }] }; expect([qualifiedSupport != null, authorizedCorrections([mismatch], { pageContentHash: fact.pageContentHash, evidenceBasis: fact.evidenceBasis, body: sentence }, s.t).length]).toEqual([true, 1]); store.rows.set(gapRow.id, gapRow); env.checked = [mismatch]; await drive(s, s.lead); const corrected = store.rows.get(gapRow.id)!; expect([nextObligation(corrected)?.kind, corrected.faults?.some(f => f.includes("checked answer to the exact external proposition")), corrected.supportFacts?.some(f => /^fact-/.test(f.id)), env.calls]).toEqual(["redraft", true, false, 0]); await drive(s, s.lead); expect(nextObligation(store.rows.get(gapRow.id)!)?.kind).toBe("redraft");
    store.rows.set(gapRow.id, gapRow); env.checked = [fact]; env.race = true; await drive(s, s.lead); expect([store.rows.get(gapRow.id)?.status, store.rows.get(gapRow.id)?.supportFacts?.some(f => /^fact-/.test(f.id))]).toEqual(["implemented_pending_verification", false]);
    const second = "Iran's official wildlife symbol is the Asiatic cheetah.", both = { ...body, passages: [sentence, second] }, root = { ...gapRow, recommendedChange: { kind: "existing_edit" as const, field: "title" as const, before: "Guide", after: "Asiatic Cheetah: Iran's National Animal and Official Wildlife Symbol" }, claims: [...gapRow.claims!, { text: second, supportedBy: ["page-copy-1"] }], supportFacts: [{ id: "page-copy-1", fact: `${sentence} ${second}` }] }, hash = pageHashOf([both.title, both.h1, ...both.headings, ...both.passages].join("\n")); expect(nextObligation(root)).toEqual(expect.objectContaining({ kind: "evidence" })); const supplied = topicSourceFacts([{ ...fact, pageContentHash: hash }], s.t)[0]!; expect([COPY_RULES.newExternalAuthorityGap(root)?.proposition, COPY_RULES.newExternalAuthorityGap({ ...root, claims: [...root.claims, { text: sentence, supportedBy: ["fact-1"] }], supportFacts: [...root.supportFacts, supplied] })]).toEqual([sentence, expect.objectContaining({ phrase: "Official" })]); store.rows.set(root.id, root); env.bodies = new Map([[canonicalUrlKey(page), both]]); env.checked = [{ ...fact, pageContentHash: hash }]; await drive(s, s.lead); const first = store.rows.get(root.id)!; expect([first.supportFacts?.filter(f => /^fact-/.test(f.id)).length, COPY_RULES.newExternalAuthorityGap(first)?.phrase.toLowerCase()]).toEqual([1, "official"]);
    const secondKey = claimIdentity(second, "", "missing"), secondUrl = "https://reference.example/official-wildlife-symbol", secondSupport = deriveSupport({ tenantId: s.t, page: s.page, statementKey: secondKey, pageLocator: "missing", subject: second, claimKind: claimTypeOf(second, second, "missing"), current: "", proposed: second, url: secondUrl, kind: "encyclopedia", quote: second, titleContext: null }); expect(secondSupport).not.toBeNull(); env.checked = [{ ...fact, pageContentHash: hash }, { ...fact, statementKey: secondKey, subject: second, proposed: second, pageContentHash: hash, sources: [{ url: secondUrl, kind: "encyclopedia", says: second, support: secondSupport! }] }]; await drive(s, s.lead); const finished = store.rows.get(root.id)!; expect([finished.supportFacts?.filter(f => /^fact-/.test(f.id)).length, COPY_RULES.newExternalAuthorityGap(finished), finished.semanticReview, env.calls]).toEqual([2, null, undefined, 0]);
  });
  it.each(SITES)("$t: the ladder's own answer for this row is the owed reading of its winners", (s) => {
    expect(nextObligation(card(s, { obligation: { kind: "terminal", reason: "no substantive gap named" } })))
      .toEqual({ kind: "evidence", need: { kind: "competitor_page", query: s.q, reasonCode: "no_winner_to_read" } });
  });
  it.each(SITES)("$t: the placeholder line of a research row is backed by no ranked title, so nothing answers the ladder in its place", (s) => {
    expect(shapeBackingOf(snapshot(s, s.lead), s.q, "The exact wording has not been written yet."), "a brief holds no line for the ranked titles to back").toBeNull();
  });
  it.each(SITES.flatMap(s => [false, true].map(unresolved => ({ ...s, unresolved }))))("$t/$unresolved: the pass writes that owed reading onto the row and hands it to the runtime's buying list", async (s) => {
    const settled = card(s, { obligation: { kind: "terminal", reason: "no substantive gap named" } });
    store.rows.set(settled.id, s.unresolved ? { ...settled, researchOnly: false, obligation: { kind: "draft" } } : settled); const oldTitle = { ...settled, id: `${settled.id}@title`, researchOnly: false, obligation: { kind: "draft" as const }, recommendedChange: { kind: "existing_edit" as const, field: "title" as const, before: "Guide", after: "An old title based only on the historical click decline" } }; if (s.unresolved) store.rows.set(oldTitle.id, oldTitle);
    const out = await drive(s, s.lead, s.unresolved);
    const kept = store.rows.get(settled.id)!; if (s.unresolved) { expect(out.proposals.filter(p => p.pagePath === s.page).map(p => p.primaryQuery)).toEqual(expect.arrayContaining([s.q, `${s.q} at night`])); expect([out.paid.declared.includes(DRAFT_BUDGET.keyOf(oldTitle)), out.paid.declared.includes(DRAFT_BUDGET.keyOf(settled)), env.calls, store.rows.get(oldTitle.id)?.recommendedChange]).toEqual([false, false, 0, oldTitle.recommendedChange]); const failedRead = await drive(s, s.lead, true, false); expect([failedRead.paid.declared.includes(DRAFT_BUDGET.keyOf(oldTitle)), env.calls, store.rows.get(oldTitle.id)?.recommendedChange]).toEqual([false, 0, oldTitle.recommendedChange]); }
    expect([kept.obligation, (out.paid.evidenceOwed ?? []).map((n) => [n.kind, n.query, n.reasonCode])],
      "the row on file says which reading it is waiting on, and that reading reaches the one list the runtime's buy loops read")
      .toEqual([{ kind: "evidence", need: { kind: "competitor_page", query: s.q, reasonCode: "no_winner_to_read" } }, [...(s.unresolved ? [["page_source", s.q, "acquire_page_source"]] : []), ["competitor_page", s.q, "no_winner_to_read"]]]);
    if (s.unresolved) { const owed = out.paid.evidenceOwed?.find((n) => n.kind === "page_source"), owner = store.rows.get(owed?.unlocks?.proposalId ?? ""); expect([owed?.unlocks, owner?.workKey, owner?.basis, owner?.obligation]).toEqual([{ proposalId: `${s.t}::${s.page}-two::existing_edit::ai_answer_gap`, step: "draft" }, owed?.workKey, "basis_rv2::d9", { kind: "evidence", need: { kind: "page_source", query: s.q, url: owed?.url, reasonCode: "acquire_page_source" } }]); }
    else { const owed = out.paid.evidenceOwed?.find((n) => n.kind === "competitor_page"), owner = store.rows.get(owed?.unlocks?.proposalId ?? ""); expect([owed?.workKey, owner?.workKey, owner?.basis, owner?.obligation]).toEqual([owner?.workKey, owed?.workKey, "basis_rv2::d9", { kind: "evidence", need: { kind: "competitor_page", query: s.q, reasonCode: "no_winner_to_read" } }]); }
  });
  it.each(SITES)("$t: and two passes over the same evidence leave the row saying the same thing", async (s) => {
    const settled = card(s, { obligation: { kind: "terminal", reason: "no substantive gap named" } });
    store.rows.set(settled.id, settled);
    await drive(s, s.lead); const first = store.rows.get(settled.id)!.obligation;
    await drive(s, s.lead); const second = store.rows.get(settled.id)!.obligation;
    expect([first, second], "nothing about this row's evidence moved between the two passes, so its typed next step may not move either").toEqual([second, second]);
  });
});
