import { describe, it, expect, beforeEach, vi, afterEach } from "vitest";
beforeEach(() => vi.stubEnv("NEXT_PUBLIC_BEACON_AEO_PACKET", "1")); afterEach(() => vi.unstubAllEnvs()); const db = vi.hoisted(() => ({ rows: [] as Record<string, unknown>[], client: {} as Record<string, unknown>, page: null as unknown }));
vi.mock("@/domains/evidence/pages/owned-context", async (real) => ({ ...(await real() as object), loadOwnedPageBodies: async () => ({ get: () => db.page }) })); // the reviewer now reads the PAGE; the stored capture is the fixture
vi.mock("@/lib/persistence/supabase", () => ({ getSupabaseAdmin: () => db.client }));
vi.mock("@/lib/logger", () => ({ log: { debug: () => {}, info: () => {}, warn: () => {}, error: () => {} } })); import { nextObligation } from "@/domains/decision/obligation"; import { deliverableGaps, openHold, preferFinished } from "@/domains/decision/completeness";
import { deliverableFailures, staleCopyReasons } from "@/domains/decision/drafted-copy"; import { COPY_RULES } from "@/domains/decision/copy-sanitize"; import type { OwnedPageBody } from "@/domains/evidence/pages/owned-context";
import { proposalFingerprint, readQueuePage, queueLaneCounts, saveChangeProposal, transitionProposalToImplemented } from "@/domains/decision/proposal-store"; import { AEO_BAR } from "@/domains/decision/accept-worthy"; import { copyKey, REVIEW_CONTRACT, unreviewed } from "@/domains/decision/proof";
import { readFileSync } from "node:fs"; import { actionableProposalFailures } from "@/domains/decision/validate-proposal"; import { supabaseFake } from "../helpers/supabase-fake"; import { deserializeChangeProposal, serializeChangeProposal, type ChangeProposal } from "@/domains/decision/contracts";
Object.assign(db.client, supabaseFake({ rows: () => db.rows }), { rpc: async () => ({ data: "saved", error: null }) });
const held = (): ChangeProposal => ((db.rows[0]!.payload as { proposal: ChangeProposal }).proposal);
const row = (over: Partial<ChangeProposal> = {}): ChangeProposal => ({ id: "t::/p::existing_edit::title", tenantId: "t", kind: "existing_edit", pagePath: "/p", pageUrl: "https://fixture.example/p", pageLabel: "P", primaryQuery: "q", opportunityType: "Capture clicks", changeFamily: "title", status: "ready", researchOnly: false, recommendedChange: { kind: "existing_edit", field: "title", before: "Old", after: "A finished title for this page" }, whyItMatters: "w", estimatedEffortMinutes: 1, riskLevel: "low", confidence: "medium", limitations: [], evidence: { query: "q", hints: [], evidenceRefCount: 1 }, impactScore: 10, upsidePerMonth: null, modeledOn: "the stored results page for this search", publish: "manual", createdAt: "2026-09-02T00:00:00.000Z", ...over });
describe("the typed next step a stored change owes", () => {
  it("owes nothing on a finished row, however its caveats happen to be worded", () => expect(nextObligation(row({ limitations: ["it reads a little flat to me", "this rearranges the page"] }))).toBeNull());
  it("keeps a page quotation cut across a heading boundary, and files support still owed as a reading rather than a redraft", () => {
    const url = "https://fixture.example/iranian-actors", glued = "Iranian Actors and ActressesExplore the talent of the best", link = row({ pageUrl: url, pagePath: "/iranian-actors", status: "ready", changeFamily: "internal_link_add", claims: [{ text: "See the Parthian Empire flag.", supportedBy: ["page-copy-1"] }], supportFacts: [{ id: "page-copy-1", fact: glued }], recommendedChange: { kind: "existing_edit", field: "section", before: null, after: "See the Parthian Empire flag.", linkTo: "/parthian-empire-flag" } }), owed = "it cites a page quotation not observed in the current reading, so its source support is still owed";
    const bodies = new Map([[url, { url, title: "Iranian Actors", h1: "Iranian Actors", metaDescription: null, headings: ["Iranian Actors and Actresses"], passages: ["Iranian Actors and Actresses", "Explore the talent of the best Iranian actresses"], openingSample: null, vocabulary: "", cardTexts: [], faqs: [], entityNames: [], internalLinks: [], fetchedAt: null, completeness: "complete", contentHash: "h", heldNote: "", version: "current" } as OwnedPageBody]]);
    expect([staleCopyReasons(link, bodies, [], null).filter((w) => /not observed|not attached/.test(w)), nextObligation({ ...link, status: "needs_review", faults: [owed, "it cites a source that is not attached to it, so a reader could not check what it says"], limitations: [owed] })], "the heading-scoped passages still carry the old flat quotation once every space is removed, and a quotation nobody observed is a reading owed, never a rewrite").toMatchObject([[], { kind: "evidence", need: { kind: "page_source", url, reasonCode: "source_support_unconfirmed" } }]); });
  it("partitions the draft doors' own refusal openers as faults, never as caveats on a Ready row", () => { const hold = openHold(row({ limitations: [`${COPY_RULES.refusal.place} a paragraph rather than a place on the page`, "The description is empty or repeats the heading without describing the subject.", "reads a little flat"] })); expect([hold.faulted, hold.defects.length, hold.caveats.filter((c) => /where it goes|repeats the heading/.test(c))], "two stored refusals hold the row and neither rides along as a caveat").toEqual([true, 2, []]); });
  it("keeps a new page out of every card lane until all of its planned sections are written", () => {
    const page = row({ id: "t::/new::new_page::topic", kind: "new_page", changeFamily: "new_page", recommendedChange: { kind: "new_page", proposedTitle: "Persian Flags", metaDescription: "The flags of Persia and Iran, dynasty by dynasty, with the dates each one flew.", openingAnswer: "Persia flew a lion and sun banner for most of its recorded history.", outline: ["Achaemenid banners", "Safavid flag", "Qajar flag"], faqQuestions: [], schemaTypes: [] },
      bundle: { objective: "o", metric: "clicks", scope: { queries: [], prompts: [] }, measurementPlan: "m", risks: [], confidenceReasons: [], alternatives: [], dispositions: [], receipt: { items: [], missing: [], freshestObservedAt: null }, components: [{ kind: "section", label: "Achaemenid banners", before: null, after: "Achaemenid banners are covered here in two finished sentences. Both say something a reader can check.", evidenceKeys: [], risk: "safe" }] } });
    expect([deliverableGaps(page), nextObligation(page), openHold(page).lane], "two owed sections keep the page in research, not Ready and not To do").toEqual([["2 of its 3 sections have no copy written"], { kind: "sections", owed: 2 }, "research"]); });
  it("a section landing on a page reopens that page's schema row for re-derivation, leaves another page's alone, and only a status transition of the landed row is a landing", async () => {
    db.rows = []; const block = JSON.stringify({ "@context": "https://schema.org", "@type": "FAQPage", mainEntity: [{ "@type": "Question", name: "How old is the Heriz rug?", acceptedAnswer: { "@type": "Answer", text: "The Heriz weave is documented from the 1800s." } }] }), schema = (path: string): ChangeProposal => row({ id: `t::${path}::existing_edit::faq_schema`, pagePath: path, pageUrl: `https://fixture.example${path}`, changeFamily: "schema", recommendedChange: { kind: "existing_edit", field: "schema", before: null, after: block, where: "In the page head." }, claims: [{ text: "The Heriz weave is documented from the 1800s.", supportedBy: ["page-copy-1"] }], supportFacts: [{ id: "page-copy-1", fact: "How old is the Heriz rug?\nThe Heriz weave is documented from the 1800s." }] });
    for (const path of ["/heriz", "/tabriz"]) expect(await saveChangeProposal(schema(path))).toBe("saved");
    const section = row({ id: "t::/heriz::existing_edit::missing_answer", pagePath: "/heriz", pageUrl: "https://fixture.example/heriz", changeFamily: "section", recommendedChange: { kind: "existing_edit", field: "section", before: null, after: "Heriz rugs are woven in the villages around Heriz in East Azerbaijan, on a wool pile over a cotton foundation.", where: 'placed after "Heriz Rug"' }, copyStamp: "Heriz Rug|Heriz Rug||", claims: [{ text: "Heriz rugs are woven in East Azerbaijan.", supportedBy: ["page-copy-1"] }], supportFacts: [{ id: "page-copy-1", fact: "Heriz Rug" }] }), stored = (path: string) => (db.rows.find((r) => r.id === `t::${path}::existing_edit::faq_schema`)!.payload as { proposal: ChangeProposal }).proposal;
    expect(await saveChangeProposal({ ...section, semanticReview: { of: copyKey(section), version: REVIEW_CONTRACT, claims: [{ i: 0, entailed: true, by: ["page-copy-1"] }], materialChange: true, editor: { pageFit: true, usefulAndNatural: true, placementCorrect: true, resolvesDiagnosis: true, implementableNow: true, improvesPage: true, wouldHandToCustomer: true, notes: "Says where the rugs are woven." } } as never })).toBe("saved");
    expect([stored("/heriz").status, stored("/heriz").obligation, stored("/heriz").limitations.at(-1), stored("/tabriz").status, stored("/tabriz").obligation]).toEqual(["needs_review", { kind: "review" }, "the page content this block describes changed; the block is re-derived from the current page", "ready", undefined]);
    const remint = async (): Promise<string> => { await saveChangeProposal(schema("/heriz")); return stored("/heriz").status; }, flip = async (): Promise<string> => String(await transitionProposalToImplemented("t", section.id, "ship-1")), walk: string[] = [await remint()]; // the next $0 pass re-derives the block from the page, which settles the reopened row
    walk.push(await saveChangeProposal({ ...section, limitations: ["Measured against the stored results page."] }), stored("/heriz").status, await flip(), stored("/heriz").status, await remint(), await flip(), stored("/heriz").status); // a Ready row re-saved with new caveats and the same status is written, and is not a landing
    expect(walk, "re-mint settles it; a same-status re-save leaves it; the implemented flip reopens it; a second flip of the same row does not").toEqual(["ready", "saved", "ready", "true", "needs_review", "ready", "true", "ready"]); });
  it("settles when a redraft hands back the exact words already retired", () => {
    const retired = row({ status: "needs_review", faults: ["f"], previousCopy: { after: "A finished title for this page", retiredBecause: "r", at: new Date().toISOString(), attempts: 1 } });
    const back = preferFinished(retired, null); expect([back.obligation?.kind, nextObligation(back)?.kind], "the same words back again are the answer, not a second attempt").toEqual(["terminal", "terminal"]); });
  it("owes the corrective draft before another reading, once a reviewer has already refused these exact words", () => {
    const reviewed = row({ status: "needs_review", changeFamily: "factual_correction", claims: [{ text: "c", supportedBy: ["fact-1"] }], supportFacts: [{ id: "fact-1", fact: "f" }] }); expect(nextObligation(reviewed), "with nothing known against it, the reading is what is owed").toEqual({ kind: "review" });
    const stale = { ...reviewed, semanticReview: { of: copyKey(reviewed), version: 4, claims: [{ i: 0, entailed: true, by: ["fact-1"] }], materialChange: true } as never, faults: ["the reading on file was made under an older review contract, so it is read again before these words are offered"] };
    const composed = `it did not pass the re-read of a stored change against the rules that stand today: ${stale.faults[0]}`, current = { ...stale, semanticReview: { ...(stale.semanticReview as object), version: REVIEW_CONTRACT } as never, faults: [composed] }; expect(unreviewed(current), "the live verdict owes no reading here").toBeNull();
    expect([nextObligation(stale), nextObligation({ ...stale, faults: [composed] }), nextObligation({ ...stale, faults: [...stale.faults, "it lands in the wrong place"] }), nextObligation(current)], "A REVIEW OWED IS NOT A REDRAFT WEARING A FAULT, raw or as the sweep composes it: sixteen live rows carried the cutover's own sentence as a typed fault and each owed a paid rewrite of words nothing had faulted, and six more carried the composed form; a real fault beside it still buys the redraft; and a stale composed fault on file while the live verdict owes nothing is still a reading, never a redraft (audit, 2026-09-14)").toEqual([{ kind: "review" }, { kind: "review" }, { kind: "redraft", attempt: 1, instruction: "it lands in the wrong place" }, { kind: "review" }]); });
  it("owes no semantic reading on a schema block, whose truth is the canon's visible-content proof", () => {
    const withFact = { claims: [{ text: "c", supportedBy: ["fact-1"] }], supportFacts: [{ id: "fact-1", fact: "https://www.britannica.com/nowruz carries it" }], status: "needs_review" as const }; expect(nextObligation(row({ ...withFact, changeFamily: "section", recommendedChange: { kind: "existing_edit", field: "section", before: null, after: "A finished section.", where: 'A new section headed "H"' } })), "prose citing a checked source owes the reading").toEqual({ kind: "review" }); expect(nextObligation(row({ ...withFact, changeFamily: "section", recommendedChange: { kind: "existing_edit", field: "schema", before: null, after: '{"@context":"https://schema.org","@type":"FAQPage","mainEntity":[]}' } })), "the same claims inside JSON-LD owe nothing to a reader of prose").toBeNull(); });
  it("owes no redraft for a gain nobody named and never settles a lever its own diagnosed cause cannot use", () => { const gainless = row({ status: "needs_review", changeFamily: "section", recommendedChange: { kind: "existing_edit", field: "section", before: null, after: "A finished section that adds something.", where: 'A new section headed "How the forms differ"' } }); expect([nextObligation(gainless), openHold(gainless).advisories.map((a) => a.kind)], "REPLACES the redraft the gain receipt used to buy: a body lacking current editor authorization owes review, never a speculative rewrite").toEqual([{ kind: "review" }, []]); const unfit = row({ status: "needs_review", diagnosisCause: "weak_opening" }); expect([nextObligation(unfit)?.kind, openHold(unfit).advisories.map((a) => a.kind)], "REPLACES the terminal settlement on a mismatched lever: the ladder settles only on a defect it cannot fix or on the operator, never on an advisory").toEqual([undefined, ["role_uncertain"]]); });
});
describe("what a sweep may take back", () => {
  beforeEach(() => { db.rows = []; });
  /** A $0 produce inside the publish phase withdrew SEVEN drafted descriptions, the actors line seven minutes after a paid redraft carried it to Ready, on "the producer that owns this family rewrote it and did not re-emit this card". A brief producer's silence says nothing about paid words already written, and the withdrawal it writes is a cache of that silence rather than a decision about the work. */ it("revives a swept row on the next save, keeps refusing the one the operator put away, and never sweeps drafted words", async () => {
    const drafted = row({ id: "t::/actors::existing_edit::missing_description", pagePath: "/actors", changeFamily: "meta", status: "needs_review", basis: "b1", recommendedChange: { kind: "existing_edit", field: "meta", before: "Old", after: "A finished description of the actors page." } });
    expect(await saveChangeProposal(drafted)).toBe("saved");
    Object.assign(db.rows[0]!, { terminal_disposition: "withdrawn", withdrawn_reason: "swept: the producer that owns this family rewrote it and did not re-emit this card" });
    expect(await saveChangeProposal(drafted), "a swept withdrawal is a cache of one pass's silence, so the next save revives the row").toBe("saved");
    Object.assign(db.rows[0]!, { terminal_disposition: "dismissed", withdrawn_reason: null });
    expect(await saveChangeProposal(drafted), "the operator's own putting-away is a decision and still refuses").toBe("refused"); });
});
describe("the store merge protects words, never a caller's decision about the same words", () => {
  beforeEach(() => { db.rows = []; });
  it("keeps a same-words demotion exactly as the caller decided it, and still keeps finished words under a re-minted brief", async () => {
    const finished = row({ claims: [{ text: "c", supportedBy: ["page-copy-1"] }], supportFacts: [{ id: "page-copy-1", fact: "f" }], copyStamp: "T|H|D|O", workKey: "w1" });
    expect(await saveChangeProposal(finished)).toBe("saved");
    expect(await saveChangeProposal({ ...finished, status: "needs_review", faults: ["it names iranopedia 3 times"], limitations: ["it names iranopedia 3 times"] })).toBe("saved"); // identical words, so there is nothing to preserve and the demotion stands
    expect([held().status, held().faults, held().obligation?.kind]).toEqual(["needs_review", ["it names iranopedia 3 times"], "redraft"]);
    await saveChangeProposal({ ...finished, status: "needs_review", researchOnly: true, recommendedChange: { kind: "existing_edit", field: "title", before: "Old", after: "The exact title is not written yet." } });
    expect((held().recommendedChange as { after: string }).after, "a brief's words differ, so the merge still protects the finished ones").toBe("A finished title for this page"); });
  /** IDENTITY IS THE WORK, NOT THE QUEUE POSITION (operator, 2026-09-04). The ranking receipt was inside the payload fingerprint and the score is computed against neighbours, so one card moving re-minted twenty-six untouched rows in a pass and this account reached proposal_version 2,271. The receipt still persists, on its own column. */ it("writes one version for two identical saves, moves nothing but the receipt column when only the rank moved, and still writes a new version when the number on the card moves", async () => {
    const scored = (score: number): ChangeProposal => ({ ...row(), rankingReceipt: { score, directional: false, basis: "b", factors: [] } });
    expect(await saveChangeProposal(row()), "the $0 producers mint unranked").toBe("saved");
    expect([await saveChangeProposal(scored(10)), (db.rows[0]!.payload as { proposal: { rankingReceipt?: unknown } }).proposal.rankingReceipt != null], "and a row's FIRST receipt is written into the payload once, so nothing on file is ever unable to say why it ranked where it did").toEqual(["saved", true]);
    const first = { version: db.rows[0]!.proposal_version, payload: JSON.stringify(db.rows[0]!.payload), at: db.rows[0]!.updated_at };
    expect(await saveChangeProposal(scored(10)), "the same decision said twice is not a second decision").toBe("unchanged");
    expect(await saveChangeProposal(scored(41)), "and a neighbour moving is not this row changing").toBe("unchanged");
    expect(await saveChangeProposal({ ...scored(41), limitations: [...scored(41).limitations, "The exact description lands on the next pass; it is still owed, and this card is what is owed. No action needed from you until it does."] }), "an owed note is display, not identity").toBe("unchanged");
    expect([db.rows.length, db.rows[0]!.proposal_version, JSON.stringify(db.rows[0]!.payload), db.rows[0]!.updated_at], "one row, one version, the same payload bytes and the same timestamp").toEqual([1, first.version, first.payload, first.at]);
    expect((db.rows[0]!.ranking_receipt as { score: number }).score, "the receipt itself is refreshed where it lives, so the order stays inspectable").toBe(41);
    expect(await saveChangeProposal({ ...scored(41), impactScore: 999 }), "the clicks printed ON the card are what an operator acts on, so that number moving IS a new version").toBe("saved");
    expect(db.rows[0]!.proposal_version).toBe((first.version as number) + 1); });
  it("cleans an accepted row's stale brief and operator ask only after defects are resolved, preserving its honest caveat", async () => {
    expect(await saveChangeProposal({ ...row(), status: "ready", research: { missing: "a description", next: "The exact wording lands on this card once the next funded pass writes it." }, redraftRequested: "2026-09-01T00:00:00.000Z",
      faults: [], limitations: ["Snippet may truncate if rendered with wider characters"] })).toBe("saved");
    expect([held().status, held().research, held().redraftRequested, held().faults, held().limitations, held().obligation], "the brief, the ask and the gate's own sentences go; the honest caveat about these exact words stays").toEqual(["ready", undefined, undefined, [], ["Snippet may truncate if rendered with wider characters"], undefined]); });
  /** A STAMP CAN OUTLIVE THE ROW IT STAMPS (live, 2026-09-04): at 06:45Z five cards were still served as ready seven minutes after the store had demoted all five, because the ready lane was cut on the release's stamp alone. */ it("serves the ready lane off the row's own status, so a demoted card stops rendering as finished the moment it is demoted", async () => {
    const at = (id: string, status: ChangeProposal["status"]) => ({ ...row({ id, basis: "b1", status }), pagePath: `/${id.split("::")[1]}` });
    for (const [i, p] of [at("t::/keeps::existing_edit::title", "ready"), at("t::/demoted::existing_edit::title", "needs_review")].entries()) {
      db.rows.push({ id: p.id, tenant_id: "t", basis: "b1", status: p.status, terminal_disposition: null, superseded_by: null, withdrawn_reason: null, proposal_version: 1, queue_rank: i + 1, queue_lane: "rel-9::ready", payload: JSON.parse(JSON.stringify({ v: 1, proposal: p })) }); }
    const lane = await readQueuePage("t", "ready", "b1", 0, 10);
    expect([lane.release, lane.rows.map((p) => p.id)], "the ranking is still the one on file, and only the row that IS ready is in its lane").toEqual(["rel-9", ["t::/keeps::existing_edit::title"]]); });
  it("stamps ONE typed next step, or none, on every row it stores, and the stored payload decodes wearing exactly that", async () => {
    for (const [owed, p] of [["draft", row({ id: "t::/p1::existing_edit::title", researchOnly: true, status: "needs_review" })], ["redraft", row({ id: "t::/p2::existing_edit::title", status: "needs_review", faults: ["it lands in the wrong place"] })],
      [undefined, row({ id: "t::/p3::existing_edit::title", modeledOn: undefined })], [undefined, row({ id: "t::/p4::existing_edit::title" })]] as Array<[string | undefined, ChangeProposal]>) {
      db.rows = []; expect(await saveChangeProposal(p)).toBe("saved");
      const back = deserializeChangeProposal(JSON.stringify(db.rows[0]!.payload))!; // the stored payload, decoded exactly as any later pass reads it back
      expect([back.obligation?.kind, nextObligation(back)?.kind], `${p.id} owes ${owed ?? "nothing"} on file and computes the same answer from the row alone`).toEqual([owed, owed]); } });
  it("key order is not identity: a finding minted in the producer's order and the same finding in schema order hash alike, and a re-mint carrying one reads unchanged (reviewer, 2026-09-04: the fingerprint was key-order sensitive, so an identical re-mint wrote a new version every tick and erased the retirement receipt on the way)", async () => {
    const producerOrder = { cause: "ctr_snippet", action: "meta", evidenceKeys: ["e1"], competingExplanations: [], notConsidered: [], explanation: "x", falsifier: "y" } as unknown as ChangeProposal["causeFinding"]; const schemaOrder = { cause: "ctr_snippet", action: "meta", evidenceKeys: ["e1"], competingExplanations: [], falsifier: "y", explanation: "x", notConsidered: [] } as unknown as ChangeProposal["causeFinding"]; const base = row(); expect(proposalFingerprint({ ...base, causeFinding: producerOrder })).toBe(proposalFingerprint({ ...base, causeFinding: schemaOrder }));
    db.rows = []; expect(await saveChangeProposal({ ...base, causeFinding: producerOrder })).toBe("saved"); expect(await saveChangeProposal({ ...base, causeFinding: producerOrder }), "decoded in schema order, minted in the producer's, one identity").toBe("unchanged"); });
});
describe("the words a first-named cause retired", () => {
  const HERIZ = "Heriz Rug: a bold Persian rug from Iran's Heriz region, known for geometric motifs, vivid colors, and durable, hand-knotted wool.", CITY = "Best Persian restaurants in Fresno with authentic Iranian food, from casual spots to fine-dining options and grilled kebabs nearby.", ASSIGNMENT = "Write a description of about 150 characters that says what only this page answers.", UNWRITTEN = "The exact wording has not been written yet.";
  const brief = (over: Partial<ChangeProposal> = {}, after = UNWRITTEN): ChangeProposal => row({ id: "t::/heriz::existing_edit::missing_description", pagePath: "/heriz", changeFamily: "meta", status: "needs_review", researchOnly: true, diagnosisCause: "ctr_snippet", copyStamp: "Heriz Rug|Heriz Rug||", modeledOn: undefined, research: { missing: ASSIGNMENT, next: "The exact wording lands on this card once the next funded pass writes it." }, recommendedChange: { kind: "existing_edit", field: "meta", before: null, after }, ...over });
  const stamped = (after: string, at = "2026-09-04T16:30:08.519Z") => ({ previousCopy: { after, retiredBecause: "the diagnosed cause changed", at, attempts: 2 } }), proof = { claims: [{ text: "Heriz rugs are hand-knotted wool from Iran's Heriz region.", supportedBy: ["fact-1"] }], supportFacts: [{ id: "fact-1", fact: "britannica.com: Heriz rugs are hand-knotted wool from the Heriz region of Iran" }] };
  const onFile = async (p: ChangeProposal) => { db.rows = []; expect(await saveChangeProposal(p), "the row exactly as the incident left it").toBe("saved"); return saveChangeProposal(brief({ pagePath: p.pagePath, copyStamp: p.copyStamp })); }; // and then the ordinary re-mint of the same brief, under the same identity, which is what carries the words back
  it("leave a row alone when a later pass already wrote finished copy onto it, whatever its receipt says (reviewer, 2026-09-04)", async () => {
    await onFile(brief({ ...proof, ...stamped(HERIZ), researchOnly: false }, "Achaemenid flag: a description written today.")); expect([(held().recommendedChange as { after: string }).after, held().previousCopy?.retiredBecause], "the newer paid words stand and the receipt is untouched").toEqual(["Achaemenid flag: a description written today.", "the diagnosed cause changed"]); });
  it("stay history under any other receipt, and come back to be refused by name for the praise its own page never backs, and for the shell only its template siblings can prove", async () => {
    for (const [why, p] of [["a receipt naming a real move says the copy is genuinely stale", brief({ previousCopy: { ...stamped(HERIZ).previousCopy, retiredBecause: "the diagnosed cause changed; the page's own content changed under it" } }, ASSIGNMENT)], ["a receipt from outside the minutes the faulty code was serving is an ordinary retirement", brief({ ...stamped(HERIZ, "2026-09-05T09:00:00.000Z") }, ASSIGNMENT)], ["copy whose claims name evidence nobody banked can no longer be checked", brief({ ...stamped(HERIZ), claims: proof.claims, supportFacts: [] }, ASSIGNMENT)], ["a retirement of the row's own brief was never copy", brief({ ...stamped(ASSIGNMENT) }, ASSIGNMENT)]] as Array<[string, ChangeProposal]>) {
      await onFile(p); expect([(held().recommendedChange as { after: string }).after, held().researchOnly, held().previousCopy?.retiredBecause.slice(0, 27)], why).toEqual([UNWRITTEN, true, "the diagnosed cause changed"]); }
    await onFile(brief({ pagePath: "/california-persian-cities/fresno", copyStamp: "Best Persian Restaurants in Fresno|Best Persian Restaurants in Fresno||", researchOnly: false, research: undefined }, CITY)); const { staleCopyReasons } = await import("@/domains/decision/drafted-copy"); // twenty California city pages share one shell, and this finished line for one of them says nothing a sibling's would not
    const LINE = { title: "Best Persian Restaurants in Fresno", h1: "Best Persian Restaurants in Fresno", metaDescription: null, outline: [] }; // WHAT A PAGE WITH NO FAMILY IN HAND OWES: its own words, judged on their own. The words every sibling repeats are the siblings' to name, so with none of them read the shell question is not asked at all, and what stands is the praise the page itself never backs. AND THE PAGE'S OWN COPY IS WHAT SAYS THE PAGE NEVER BACKS IT (measured, 2026-09-05): asked with only the title and the heading in hand, this refused eight live descriptions for a word all eight pages carry in their bodies, so the question is asked of the page or it is not asked at all.
    const own = (words: string) => new Map([["https://own.test/california-persian-cities/fresno", { url: "https://own.test/california-persian-cities/fresno", title: LINE.title, h1: LINE.h1, metaDescription: null, headings: [LINE.h1], passages: [words], openingSample: null, vocabulary: words, cardTexts: [], faqs: [], entityNames: [], internalLinks: [], fetchedAt: null, completeness: "complete" as const, contentHash: null, heldNote: "" }]]);
    const quiet = "Fresno kitchens serve grilled kebabs and stews, with food options from casual spots to fine dining nearby.";
    expect([(held().recommendedChange as { after: string }).after, held().researchOnly, staleCopyReasons({ ...held(), pageUrl: "https://own.test/california-persian-cities/fresno" }, own(quiet) as never, [], LINE), staleCopyReasons({ ...held(), pageUrl: "https://own.test/california-persian-cities/fresno" }, own(`${quiet} The most authentic Persian cooking in town.`) as never, [], LINE), staleCopyReasons(held(), new Map(), [], null)], "a weak line is recovered into review like any other and refused there BY NAME for the one thing a page with no siblings in hand can still be asked, its own copy read: it promises warmth its own page never claims; a page whose body does carry the word is not promising anything it lacks, and a door holding none of the page's copy may not answer the question at all").toEqual([CITY, false, ['it calls the subject "authentic", a word this page\'s own copy never carries, so the line promises a searcher warmth, fame or growth nothing on file backs'], [], []]);
    const sibling = (slug: string, c: string, tail: string) => ({ url: `https://own.test/california-persian-cities/${slug}`, title: `Best Persian Restaurants in ${c}`, h1: `Best Persian Restaurants in ${c}`, metaDescription: null, headings: [`Best Persian Restaurants in ${c}`], passages: [`Explore our list of the best Iranian restaurants in ${c}, featuring some of the most authentic Persian cuisine in the area. We are actively curating this list. ${tail}`], openingSample: null, vocabulary: "", cardTexts: [], faqs: [], entityNames: [], internalLinks: [], fetchedAt: null, completeness: "complete" as const, contentHash: null, heldNote: "" }); // AND WITH THE FAMILY IN HAND THE SAME LINE ANSWERS THE OTHER QUESTION, by derivation and not by a written word list: what it says past its own heading is what every page off this shell already says
    const kin = [sibling("fresno", "Fresno", "Fresno kitchens serve grilled kebabs and stews, with food options from casual spots to fine dining nearby."), sibling("modesto", "Modesto", "Modesto kitchens serve grilled kebabs and stews, with food options from casual spots to fine dining nearby."), sibling("chico", "Chico", "Chico kitchens serve grilled kebabs and stews, with food options from casual spots to fine dining nearby.")];
    expect(staleCopyReasons({ ...held(), pageUrl: kin[0]!.url }, new Map(kin.map((b) => [b.url, b])) as never, [], LINE), "the same line, its two siblings read, is refused for the question only the family can answer").toContain("the line carries fewer than three words beyond the page heading and the words every such page shares, so it says nothing about this page");
    db.rows = []; await saveChangeProposal(brief({ status: "ready" })); expect([held().status, (held().recommendedChange as { after: string }).after], "and a row that says it has no copy is never stored finished, whatever status a caller hands over").toEqual(["needs_review", UNWRITTEN]); });
  it("never restores refused wildlife table previousCopy, even when banked facts still support it", async () => {
    const why = (name: string) => `This draft names "${name}", and that distinguishing group label is not on your page or in the evidence read for it.`, mk = (table: string, hints: string[], facts: string, whyName = "Species") => brief({ id: "t::/wildlife::existing_edit::missing_answer", pagePath: "/wildlife", pageUrl: "https://fixture.example/wildlife", changeFamily: "answer_block", primaryQuery: "which animals live in the reserve", evidence: { query: "which animals live in the reserve", hints, evidenceRefCount: 1 }, recommendedChange: { kind: "existing_edit", field: "answer_block", before: null, after: UNWRITTEN, where: 'One section placed after "Reserve wildlife"' }, claims: [{ text: "The reserve table lists habitats.", supportedBy: ["page-copy-1"] }], supportFacts: [{ id: "page-copy-1", fact: facts }], previousCopy: { after: table, retiredBecause: why(whyName), at: "2026-09-06T00:00:00.000Z", attempts: 1 } });
    const supported = "| Species | Survey habitat |\n| --- | --- |\n| Otter | reserve rivers |\n| Heron | reserve wetlands |", recovered = preferFinished({ ...mk(supported, [], supported), previousCopy: undefined }, mk(supported, [], supported)); expect([(recovered.recommendedChange as { after: string }).after, recovered.researchOnly, recovered.status, recovered.previousCopy?.after]).toEqual([UNWRITTEN, true, "needs_review", supported]);
    const unicorn = "| Species | Survey habitat |\n| --- | --- |\n| Unicorn | reserve rivers |\n| Heron | reserve wetlands |", blocked = preferFinished({ ...mk(unicorn, ["A note says Unicorn appears on this page."], supported, "Unicorn"), previousCopy: undefined }, mk(unicorn, ["A note says Unicorn appears on this page."], supported, "Unicorn")); expect([(blocked.recommendedChange as { after: string }).after, blocked.researchOnly, blocked.status]).toEqual([UNWRITTEN, true, "needs_review"]);
    const emDash = "| Species | Survey habitat |\n| --- | --- |\n| Otter | reserve rivers |\n| Heron | reserve wetlands — seasonal |", kept = preferFinished({ ...mk(emDash, [], emDash), previousCopy: undefined }, mk(emDash, [], emDash)); const { validateProposal } = await import("@/domains/decision/validate-proposal"); expect([kept.status, validateProposal({ ...kept, status: "ready" }).reasons.some((r) => /em or en dash/i.test(r))]).toEqual(["needs_review", false]);
  });
});
describe("the assignment a row is issued is the assignment its gates judge", () => {
  const serp = (...t: string[]) => ({ ownedPages: [], sources: [], scope: { tenantId: "t", site: "iranopedia.com" }, research: { serpEvidence: [{ observedAt: null, query: "iranian cat", aiOverview: [], aiMode: [], paa: [], related: [], organic: t.map((title, i) => ({ rank: i + 1, domain: `d${i}.example`, url: `https://d${i}.example/${i}`, title })) }] } });
  const CAT = "Persian Cat (Persian Longhair): domesticated breed from Iran with a dense coat, flat face, 25 - 30 year lifespan, and Not Evaluated status.", FLAG = "Persian Empire Flag: Achaemenid Empire Flag (550-330 BCE) with a red background and a golden Faravahar or eagle emblem.";
  const CITY = "Best Persian restaurants in Fresno with authentic Iranian food, kebabs and stews, from casual spots to fine dining.", AT = "https://www.iranopedia.com/california-persian-cities/fresno";
  it("reads the lead off the ranked titles, so the line that obeys the correction it was issued is the line that earns its backing", async () => { const { shapeBackingOf } = await import("@/domains/decision/drafted-copy"); expect(shapeBackingOf(serp("Persian Cat Breed Profile", "Persian Cat: Care and Grooming", "Cats of Iran") as never, "iranian cat", CAT), 'the held /iran-animals/persian-cat description opens on the subject the ranked pages name; the backing rule counted the QUERY first word instead, which no ranked title carries, so the row could obey its own corrective fault for ever and stay held for a results page already on file').toContain('naming the subject "persian"'); });
  it("judges the cited figure, so a span the page spells with a dash is not a dropped qualifier, and a real one still refuses", async () => { const { deliverableFailures } = await import("@/domains/decision/drafted-copy"); const said = (t: string) => ({ targetUrl: "https://www.iranopedia.com/p", title: "T", h1: "H", metaDescription: null, bodyText: t, headings: [], evidence: { "page-copy-1": t }, trackedQuestion: "q", ownedPaths: [], bannedTerms: [], demand: { preserve: [], vocabulary: [] } }); const why = (after: string, t: string) => deliverableFailures({ targetUrl: "https://www.iranopedia.com/p", actionType: "meta", naturalHeading: null, beforeText: null, placementAnchor: "the description", evidenceIdsUsed: ["page-copy-1"], uncertaintyOrOmitted: [], implementationMinutes: 1, measurementTarget: "ctr", claims: [{ text: "a claim", supportedBy: ["page-copy-1"] }], finalCopy: after } as never, said(t) as never).filter((r) => r.includes("figure")); expect(why(FLAG, "top of page< BackAchaemenid Empire Flag (550-330 BCE)The official flag of the Achaemenid Empire, representing Persian power from 550-330 BCE."), "the page opens its own span with a bare from, which narrows nothing: this refused the live /iran-flags/achaemenid-empire-flag line for dropping it").toEqual([]); expect(why("Ships in 7-21 business days worldwide.", "International shipping is available worldwide, with delivery usually between 7–21 business days."), "and the word that really does narrow the figure still refuses").toEqual(["the figure's own sentence says international, and the copy drops it"]); });
  it("reads recovered words against their own page and rebuilds the record the incident lost, rather than paying to rewrite words no gate faulted", async () => { const { reviewFinishedCopy } = await import("@/domains/decision/drafted-copy"); db.page = { url: AT, title: "Best Persian Restaurants in Fresno", h1: "Best Persian Restaurants in Fresno", metaDescription: "Old line.", headings: ["Persian restaurants in Fresno"], passages: ["Fresno Iranian restaurants serve kebabs and stews, from casual spots to fine dining, and the best of them are authentic Persian kitchens."], vocabulary: "", cardTexts: [], faqs: [], entityNames: [], internalLinks: [], openingSample: null, fetchedAt: "2026-09-04T00:00:00.000Z", completeness: "complete", contentHash: "h", heldNote: null }; const lost = row({ id: "t::/fresno::existing_edit::missing_description", pagePath: "/california-persian-cities/fresno", pageUrl: AT, changeFamily: "meta", status: "needs_review", faults: ["its copy carries no record of what it stands on"], limitations: ["its copy carries no record of what it stands on"], recommendedChange: { kind: "existing_edit", field: "meta", before: "Old line.", after: CITY } }); expect([nextObligation(lost), nextObligation({ ...lost, faults: [...lost.faults!, 'it calls the subject "authentic", a word this page\'s own copy never carries'] })?.kind], "a lost record is READ, and the three states stay apart: bad words are redrafted, a missing record is re-read, missing evidence is bought").toEqual([{ kind: "review" }, "redraft"]); const read = await reviewFinishedCopy(lost, { tenantId: "t", now: new Date("2026-09-04T00:00:00.000Z"), judge: (async (d: { claims: readonly { supportedBy: readonly string[] }[] }) => ({ pageFit: true, resolvesDiagnosis: true, usefulAndNatural: true, placementCorrect: true, implementableNow: true, improvesPage: true, wouldHandToCustomer: true, notes: "It says what this page answers better than the line it replaces.", resolution: "none", claims: d.claims.map((c, i) => ({ i, by: [...c.supportedBy], entailed: true })) })) as never }); expect([(read.row!.recommendedChange as { after: string }).after, (read.row!.claims ?? []).length > 0, (read.row!.claims ?? []).every((c) => c.supportedBy.every((id) => id in Object.fromEntries((read.row!.supportFacts ?? []).map((f) => [f.id, f.fact])))), read.row!.semanticReview?.of === copyKey(read.row!), nextObligation(read.row!)], "not one word changed, every rebuilt claim names an id the page really carries with its exact words banked beside it, the reading is bound to these words, and nothing is owed next").toEqual([CITY, true, true, true, null]); });
  it("retires the store's record sentence with the reading that answers it, and a promotion strips it as gate vocabulary, so a row whose record stands never says it has none", async () => { const { reviewFinishedCopy } = await import("@/domains/decision/drafted-copy"); const { GATE_WORDS } = await import("@/domains/decision/completeness"); const NO_RECORD = "its copy carries no record of what it stands on", NOTE = "Read off the last stored copy of each page, so a description rewritten since that read is not counted here.", COPY = "Rain pools: shallow seasonal ponds on the moor that fill each winter and dry by June.", PAGE = "https://fixture.example/rain-pools"; db.page = { url: PAGE, title: "Rain pools on the moor", h1: "Rain pools on the moor", metaDescription: "Old line.", headings: ["What lives in the pools"], passages: ["Rain pools are shallow seasonal ponds on the moor. They fill each winter and dry by June, and fairy shrimp hatch in them."], vocabulary: "", cardTexts: [], faqs: [], entityNames: [], internalLinks: [], openingSample: null, fetchedAt: "2026-09-04T00:00:00.000Z", completeness: "complete", version: "current", contentHash: "h2", heldNote: null };
    /* A ROW THAT ALREADY HELD ONE CLAIM kept the sentence through a passing reading for ever, because only a claimless row rebuilds its record (probe, 2026-09-05: two live rows, one claim each, three support facts each, a reading bound at the current contract, and the incident's sentence still on both). */
    const held = row({ id: "t::/rain-pools::existing_edit::missing_description", pagePath: "/rain-pools", pageUrl: PAGE, changeFamily: "meta", status: "needs_review", faults: [NO_RECORD], limitations: [NOTE, NO_RECORD], claims: [{ text: COPY, supportedBy: ["page-copy-1"] }], supportFacts: [{ id: "page-copy-1", fact: "Rain pools are shallow seasonal ponds on the moor. They fill each winter and dry by June, and fairy shrimp hatch in them." }], recommendedChange: { kind: "existing_edit", field: "meta", before: "Old line.", after: COPY } });
    expect([nextObligation(held), GATE_WORDS.test(NO_RECORD)], "before the reading nothing is owed by the ladder's own rungs, and the sentence is already gate vocabulary").toEqual([null, true]);
    /* AND THE ROW'S OWN RECORD ANSWERS IT AT NO COST (measured, 2026-09-05): eighteen current rows carry this sentence, none has been re-read since it was made retirable, and one of them holds a claim and three support facts, so it was held for a record its own payload disproves. The reading below is what a claimless row still owes; a row that already has one owes nothing to stop wearing it. */
    for (const t of ["tenant-one", "tenant-two"]) expect([openHold({ ...held, tenantId: t }).why.includes(NO_RECORD), openHold({ ...held, tenantId: t, claims: [], supportFacts: [] }).why.includes(NO_RECORD)], `a row whose record stands is not held for the sentence saying it has none, before any reading and at no cost, and a row with no record still is, on ${t}`).toEqual([false, true]);
    const read = await reviewFinishedCopy(held, { tenantId: "t", now: new Date("2026-09-04T00:00:00.000Z"), judge: (async (d: { claims: readonly { supportedBy: readonly string[] }[] }) => ({ pageFit: true, resolvesDiagnosis: true, usefulAndNatural: true, placementCorrect: true, implementableNow: true, improvesPage: true, wouldHandToCustomer: true, notes: "It says what the page is about better than the line it replaces.", resolution: "none", claims: d.claims.map((c, i) => ({ i, by: [...c.supportedBy], entailed: true })) })) as never });
    expect([read.row!.faults, read.row!.limitations, (read.row!.claims ?? []).map((c) => [c.text, [...c.supportedBy]]), read.row!.semanticReview?.of === copyKey(read.row!), nextObligation(read.row!)], "the sentence is gone from both places, the claim it carried is untouched, the reading is bound to these words, and nothing is owed next").toEqual([[], [NOTE], [[COPY, ["page-copy-1"]]], true, null]); });
  it("stops buying a redraft for an objection no live door writes, on the FAQPage block carrying two of them", () => { const faqs = row({ id: "t::/farsi-numbers::existing_edit::faq_schema", pagePath: "/farsi-numbers", changeFamily: "section", status: "needs_review", claims: [{ text: "c", supportedBy: ["page-copy-1"] }], supportFacts: [{ id: "page-copy-1", fact: "f" }], recommendedChange: { kind: "existing_edit", field: "schema", before: null, after: '{"@context":"https://schema.org","@type":"FAQPage","mainEntity":[]}' }, faults: ['the evidence "The page already carries these two questions and their answe" names is about something else entirely, so this copy argues from support nobody banked', "its copy is 150 long, outside the 15 to 400 this field takes, or carries something nobody can paste"] }); expect([nextObligation(faqs), nextObligation({ ...faqs, faults: ["This structured data is incomplete: mainEntity is empty"] })], "the prose checklist never ran on this block and its word band is a sentence no rule composes any more, so both are history; the schema gate's own finding is what is owed").toEqual([null, { kind: "redraft", attempt: 1, instruction: "This structured data is incomplete: mainEntity is empty" }]); });
});
describe("a row says what its own record holds", () => {
  const SITES = [{ t: "tenant-one", url: "https://alpha.example/tide-pools", path: "/tide-pools", q: "tide pool safety", claim: "Tide pools hold close to the ocean temperature.", src: "https://www.britannica.com/tide-pool says pools hold close to the ocean temperature", subject: "Anemone", right: "a stinging animal fixed to the rock", dish: "tide pool walks" },
    { t: "tenant-two", url: "https://beta.example/reposteria", path: "/reposteria", q: "pan dulce origen", claim: "El pan dulce llego a Mexico con los panaderos franceses.", src: "https://es.wikipedia.org/pan-dulce dice que llego con los panaderos franceses", subject: "Concha", right: "un pan dulce con costra de azucar", dish: "pan dulce" }] as const;
  const finished = (s: (typeof SITES)[number]): ChangeProposal => row({ id: `${s.t}::${s.path}::existing_edit::missing_answer`, tenantId: s.t, pagePath: s.path, pageUrl: s.url, primaryQuery: s.q, changeFamily: "answer_block", status: "ready", researchOnly: false,
    recommendedChange: { kind: "existing_edit", field: "answer_block", before: null, after: s.claim, where: 'One sentence placed after the heading "What lives there"' },
    claims: [{ text: s.claim, supportedBy: ["fact-1", "page-copy-1"] }], supportFacts: [{ id: "fact-1", fact: s.src }, { id: "page-copy-1", fact: "the page's own words" }],
    copyStamp: "the page as it read", workKey: `${s.path}::body::${s.q}::wc4::basis_x::d8::hash::existing_edit::answer_block::add_answer_section::cause::${s.q}::draft::r5:sc2::fact-1,page-copy-1` });
  const reviewed = (p: ChangeProposal): ChangeProposal => ({ ...p, semanticReview: { of: copyKey(p), version: REVIEW_CONTRACT, claims: [{ i: 0, entailed: true, by: ["fact-1", "page-copy-1"] }], materialChange: true } as never });
  it.each(SITES)("says on the finished card what stands behind the words and how many checked sources carry them, and never asks a customer to decide what the card already told them, on $t", async (s) => {
    const { renderToStaticMarkup } = await import("react-dom/server"); const { createElement } = await import("react"); const { ChangeCard } = await import("@/app/(shell)/changes/change-card");
    const props = { rank: 1, caseLine: null, onAside: () => {}, onDone: () => {}, onToast: () => {} };
    const paint = (p: ChangeProposal, o: Record<string, unknown>) => renderToStaticMarkup(createElement(ChangeCard as never, { proposal: p, ...props, ...o } as never)).replace(/<[^>]+>/g, " ").replace(/&#x27;/g, "'").replace(/\s+/g, " ");
    const done = paint(reviewed(finished(s)), { ready: true }), unread = paint(finished(s), { ready: true });
    /* THE ONE LANE THAT RENDERS A CARD IN REVIEW: a change that moves a page, holding no fault of Beacon's own, so the only open question is the operator's. */
    const mover = reviewed({ ...finished(s), status: "needs_review" as const, recommendedChange: { kind: "existing_edit" as const, field: "title" as const, before: "Old", after: "A finished title for this page" }, claims: undefined, supportFacts: undefined, limitations: ["Read off the last stored copy of this page."],
      bundle: { objective: "Settle which page owns that search", metric: "clicks", measurementPlan: "read after 28 days", risks: [], confidenceReasons: [], alternatives: [], dispositions: [], receipt: { items: [], missing: [] }, components: [{ kind: "title", page: s.path, before: "Old", after: "A finished title for this page", risk: "safe", evidenceKeys: [] }, { kind: "canonical", page: s.path, before: null, after: `Point ${s.path}-b at this page.`, risk: "dangerous", evidenceKeys: [] }] } as never });
    const decide = paint(mover, { review: true }), faulted = paint(reviewed({ ...finished(s), status: "needs_review" as const }), { review: true });
    expect([done.includes("Backed by 1 checked source and read for sense before it was offered. Copy it, then press Mark done."), done.includes("What you are deciding"), unread.includes("read for sense"), decide.includes("Backed by"), decide.includes("moves or hides a page"), decide.includes("Read off the last stored copy of this page."), decide.includes("Every other check passed on all 2 pieces. Open it, confirm the move, then make the change."), decide.includes("imperfect starting point"), faulted.includes("Copying it takes an unfinished starting point, not proven work.")],
      "the finished card names its one publisher and its reading and says what to do next; a card whose reading does not name these exact words claims neither; the one card that is genuinely the operator's call names what it moves, carries the row's own caveat off the hold rather than a second composition of it, counts the pieces that passed and says what to do, and never calls checked copy an imperfect starting point; a card Beacon itself faulted still says so")
      .toEqual([true, false, false, false, true, true, true, false, true]);
    expect(paint(reviewed({ ...finished(s), claims: [{ text: s.claim, supportedBy: ["page-copy-1"] }] }), { ready: true }), "a row standing on words this account already publishes says that instead of a bare zero").toContain("Written from words already on your own pages and read for sense before it was offered."); });
  it.each(SITES)("keeps the identity that belongs to the words it keeps, so a free re-mint carrying no support cannot stamp a key that names none, on $t", (s) => {
    const prior = reviewed(finished(s)), brief = { ...prior, workKey: prior.workKey!.replace(/fact-1,page-copy-1$/, ""), supportFacts: undefined, claims: undefined, semanticReview: undefined, researchOnly: true, status: "needs_review" as const, research: { missing: "the answer" } as never, recommendedChange: { kind: "existing_edit" as const, field: "answer_block" as const, before: null, after: "The exact wording has not been written yet.", where: prior.recommendedChange.kind === "existing_edit" ? prior.recommendedChange.where : undefined } };
    const kept = preferFinished(brief as ChangeProposal, prior);
    expect([kept.workKey!.split("::").at(-1), (kept.supportFacts ?? []).map((f) => f.id), kept.workKey!.split("::").slice(0, -1).join("::") === brief.workKey!.split("::").slice(0, -1).join("::"), (kept.recommendedChange as { after: string }).after],
      "the support segment names exactly the support the kept row holds, every other segment is the incoming pass's own so a writer-contract bump still reopens the work, and the words never move")
      .toEqual(["fact-1,page-copy-1", ["fact-1", "page-copy-1"], true, s.claim]);
    expect(preferFinished({ ...brief, workKey: `${s.path}::meta::older-shape` } as ChangeProposal, { ...prior, workKey: `${s.path}::meta::older-shape` }).workKey, "and a key minted under an older shape is left exactly as it is").toBe(`${s.path}::meta::older-shape`); });
  /** THE SETTLED VERDICT, THE COUNT ON THE CARD AND THE PAGE'S OWN WORDS (2026-09-05). Three defects, one shape: a door answered from less than the row holds. A settlement rode the banked copy, so the two rows with no copy had theirs recomputed from nothing by every re-mint and flapped between settled and owing a draft; the publisher count read hostnames out of a banked fact's prose, so a card said two checked sources stood behind an answer whose bank row says one and whose other address quoted nothing; and the re-read asked whether the page's own copy carries a word while holding only its title and headings, refusing eight live descriptions for a word all eight pages carry in their bodies. */
  it.each(SITES)("keeps a settled verdict on a row with no copy at all, until the work itself moves or a person asks for better words, on $t", (s) => {
    const UNWRITTEN_LINE = "The exact wording has not been written yet."; // the live shape: a row the walk's own editor settled and that carries no copy at all, so nothing of it takes the kept path below
    const brief = { ...finished(s), createdAt: new Date().toISOString() /* a settlement stands only while young: after seven days it re-enters the cycle (operator, 2026-09-10) */, status: "needs_review" as const, obligation: undefined, faults: undefined, claims: undefined, supportFacts: undefined, researchOnly: true, research: { missing: "the answer" } as never,
      recommendedChange: { kind: "existing_edit" as const, field: "answer_block" as const, before: null, after: UNWRITTEN_LINE, where: 'One sentence placed after the heading "What lives there"' } };
    const settled = { ...brief, obligation: { kind: "terminal" as const, reason: "no substantive gap named" } };
    expect([nextObligation(preferFinished(brief as ChangeProposal, settled)), nextObligation(preferFinished(brief as ChangeProposal, { ...settled, redraftRequested: "the operator asked for better words" } as ChangeProposal)), nextObligation(preferFinished({ ...brief, copyStamp: "the page as it reads today" } as ChangeProposal, settled))],
      "a pass that mints no verdict leaves the settlement standing, a person who asked for better words outranks it, and a pass that really moves the work decides again from nothing")
      .toEqual([{ kind: "terminal", reason: "no substantive gap named" }, { kind: "draft" }, { kind: "draft" }]); });
  it.each(SITES)("counts the publishers behind the words off the addresses the reading quoted, never off hostnames in its own prose, on $t", async (s) => {
    const { citedPublishers } = await import("@/domains/decision/completeness");
    const banked = { ...finished(s), supportFacts: [{ id: "fact-1", fact: s.src, sources: [{ url: "https://reference.example/a", kind: "encyclopedia" }, { url: "https://reference.example/b", kind: "publisher" }, { url: "https://mirror.example/c", kind: "publisher" }] }, { id: "page-copy-1", fact: "the page's own words" }] };
    const silent = { ...finished(s), supportFacts: [{ id: "fact-1", fact: `https://quiet.example/x says "" ; ${s.src}` }, { id: "page-copy-1", fact: "the page's own words" }] };
    expect([citedPublishers(banked).size, citedPublishers(silent).size, citedPublishers({ ...finished(s), supportFacts: [{ id: "fact-1", fact: s.src, sources: [] }] }).size],
      "two addresses on one host are one publisher, an address the reading quoted nothing from is not a publisher at all, and a reading banked with no quoting address carries none")
      .toEqual([2, 1, 0]);
    const { renderToStaticMarkup } = await import("react-dom/server"); const { createElement } = await import("react"); const { ChangeCard } = await import("@/app/(shell)/changes/change-card");
    const card = renderToStaticMarkup(createElement(ChangeCard as never, { proposal: reviewed(silent as ChangeProposal), rank: 1, ready: true, caseLine: null, onAside: () => {}, onDone: () => {}, onToast: () => {} } as never)).replace(/<[^>]+>/g, " ").replace(/\s+/g, " ");
    expect(card, "and the card prints the number the evidence bar counts, never a second count of its own").toContain("Backed by 1 checked source");
    expect(deserializeChangeProposal(serializeChangeProposal(banked as ChangeProposal))?.supportFacts?.[0]?.sources, "and the provenance the bank writes survives the schema that stores it, rather than being declared and stripped")
      .toEqual([{ url: "https://reference.example/a", kind: "encyclopedia" }, { url: "https://reference.example/b", kind: "publisher" }, { url: "https://mirror.example/c", kind: "publisher" }]); });
  it.each(SITES)("asks whether this page's own copy carries a promise word against the whole page, and says nothing while it holds none of it, on $t", (s) => {
    const line = `Best places in ${s.path.slice(1)} with authentic ${s.dish} and more.`;
    const meta = row({ id: `${s.t}${s.path}::existing_edit::missing_description`, tenantId: s.t, pagePath: s.path, pageUrl: s.url, primaryQuery: s.q, changeFamily: "meta", status: "needs_review", claims: undefined, supportFacts: undefined,
      recommendedChange: { kind: "existing_edit", field: "meta", before: "Old line", after: line } });
    const page = { title: `Best places in ${s.path.slice(1)}`, h1: `Best places in ${s.path.slice(1)}`, metaDescription: "Old line", outline: [] };
    const body = (words: string): ReadonlyMap<string, OwnedPageBody> => new Map([[s.url, { url: s.url, title: page.title, h1: page.h1, metaDescription: page.metaDescription, headings: [], passages: [words], openingSample: words, vocabulary: words, cardTexts: [], faqs: [], entityNames: [], internalLinks: [], fetchedAt: null, completeness: "complete", contentHash: null, heldNote: "" } as OwnedPageBody]]);
    const carries = `This page lists authentic ${s.dish} and where to find it.`, quiet = `This page lists ${s.dish} and where to find it.`;
    const praise = (why: readonly string[]): boolean => why.some((w) => w.includes('calls the subject "authentic"'));
    const published = { ...meta, recommendedChange: { kind: "existing_edit" as const, field: "meta" as const, before: `The most authentic ${s.dish} in town.`, after: line } };
    expect([praise(staleCopyReasons(meta, body(carries), [], page)), praise(staleCopyReasons(published, new Map(), [], { ...page, metaDescription: published.recommendedChange.before })), praise(staleCopyReasons(meta, body(quiet), [], page)), praise(staleCopyReasons({ ...meta, recommendedChange: { kind: "existing_edit", field: "meta", before: null, after: line } }, new Map(), [], null))],
      "a word the page's own body carries is not a manufactured promise, nor is one the page publishes today in the very line this change replaces, a word no part of the page carries still is, and a door holding none of the page's copy may not answer the question at all")
      .toEqual([false, false, true, false]); });
  /** AND THE WRITER'S OWN DOOR ASKS THE IDENTICAL QUESTION OF THE IDENTICAL PAGE (measured, 2026-09-05): the banked re-read was repaired and the door that judges a fresh draft was not, so it went on refusing 15 of this account's 211 published descriptions for a word that very description publishes. One pool, one predicate, the same answer at both doors. */
  it.each(SITES)("judges a promise word at the writer's door against the same page the banked re-read judges it against, and both answer alike, on $t", (s) => {
    const page = { title: `Best places in ${s.path.slice(1)}`, h1: `Best places in ${s.path.slice(1)}`, metaDescription: `The most authentic ${s.dish} in town.`, outline: [] };
    const line = `Best places in ${s.path.slice(1)} with authentic ${s.dish} and more.`, body = `This page lists welcoming ${s.dish} and where to find it.`;
    const packet = (over: Record<string, unknown> = {}): Parameters<typeof deliverableFailures>[1] => ({ targetUrl: s.url, title: page.title, h1: page.h1, metaDescription: page.metaDescription, bodyText: body, headings: [], evidence: {}, trackedQuestion: s.q, ownedPaths: [s.path], bannedTerms: [], demand: { preserve: [], vocabulary: [] }, ...over }) as Parameters<typeof deliverableFailures>[1];
    const draft = (copy: string): Parameters<typeof deliverableFailures>[0] => ({ actionType: "meta", targetUrl: s.url, placementAnchor: "the description field", beforeText: page.metaDescription, finalCopy: copy, naturalHeading: null, claims: [], supportFacts: [], evidenceIdsUsed: [], uncertaintyOrOmitted: [], implementationMinutes: 2, measurementTarget: "clicks" });
    const praised = (why: readonly string[]): string | null => why.find((w) => w.includes("a word this page's own copy never carries"))?.match(/"([a-z]+)"/)?.[1] ?? null;
    const meta = row({ id: `${s.t}${s.path}::existing_edit::missing_description`, tenantId: s.t, pagePath: s.path, pageUrl: s.url, primaryQuery: s.q, changeFamily: "meta", status: "needs_review", claims: undefined, supportFacts: undefined, recommendedChange: { kind: "existing_edit", field: "meta", before: page.metaDescription, after: line } });
    const held = new Map<string, OwnedPageBody>([[s.url, { url: s.url, title: page.title, h1: page.h1, metaDescription: page.metaDescription, headings: [], passages: [body], openingSample: body, vocabulary: body, cardTexts: [], faqs: [], entityNames: [], internalLinks: [], fetchedAt: null, completeness: "complete", contentHash: null, heldNote: "" } as OwnedPageBody]]);
    const bank = (copy: string): string | null => praised(staleCopyReasons({ ...meta, recommendedChange: { kind: "existing_edit", field: "meta", before: page.metaDescription, after: copy } }, held, [], page));
    expect([praised(deliverableFailures(draft(line), packet())), bank(line), praised(deliverableFailures(draft(`A welcoming guide to ${s.dish}.`), packet())), bank(`A welcoming guide to ${s.dish}.`)],
      "the word the line this change replaces already publishes, and the word the page's own body carries, are refused by neither door").toEqual([null, null, null, null]);
    expect([praised(deliverableFailures(draft(`A curated guide to ${s.dish}.`), packet())), bank(`A curated guide to ${s.dish}.`), praised(deliverableFailures(draft(line), packet({ title: null, h1: null, metaDescription: null, bodyText: "" })))],
      "a word no part of the page carries is refused at both doors by name, and a door holding none of the page's copy answers nothing at all").toEqual(["curated", "curated", null]); });
  /** ONE COMPLAINT IS SAID ONCE (measured, 2026-09-05): the account's most watched card printed its one objection twice, once wrapped in the gate opener the composer adds and once raw, because both forms sit in `faults` and the strings differ. */
  it.each(SITES)("says one complaint once, however many doors wrote it down, and keeps every complaint that says something else, on $t", (s) => {
    const raw = "it opens with the search words as a label and a colon, which is how a search box names a topic and not how a reader meets one";
    const composed = `it did not pass the re-read of a stored change against the rules that stand today: ${raw}`, other = "it lands in the wrong place";
    const held = (faults: readonly string[]): ChangeProposal => row({ id: `${s.t}${s.path}::existing_edit::missing_answer`, tenantId: s.t, pagePath: s.path, pageUrl: s.url, primaryQuery: s.q, status: "needs_review", changeFamily: "answer_block", faults: [...faults], limitations: [...faults],
      recommendedChange: { kind: "existing_edit", field: "answer_block", before: null, after: s.claim, where: 'One sentence placed after the heading "What lives there"' } });
    const mine = (faults: readonly string[]): string[] => openHold(held(faults)).why.filter((w) => w.includes(raw) || w === other);
    expect([mine([composed, raw]), mine([raw, composed]), mine([composed, other])],
      "the wrapped sentence goes whichever order the doors wrote it in, and a second complaint that says something else stays").toEqual([[composed], [composed], [composed, other]]); });
  it.each(SITES)("refuses a correction that only names its subject again, at the reader and at the bank, and keeps every one that says something, on $t", async (s) => {
    db.rows = []; const { readFactChecks, recordFactChecks } = await import("@/domains/evidence/pages/fact-checks");
    const stored = (subject: string, proposed: string, current: string) => ({ tenant_id: s.t, page_key: s.path, statement_key: subject.toLowerCase(), subject, current_wording: current, proposed, sources: [{ url: s.src, says: s.src, kind: "encyclopedia" }], agreement: "multiple_agree", confidence: "confirmed", verdict: "page_wrong", also_at: [], note: "", page_content_hash: "h", page_locator: null, source_read_at: null, claim_state: "checked", rules_version: 4, checked_at: "2026-09-05T00:00:00.000Z" });
    db.rows = [stored(s.subject, s.subject, `${s.subject} (${s.right})`), stored(`${s.subject} II`, ` ${s.subject.toUpperCase()}  II `, s.subject), stored(`${s.subject} III`, s.right, s.subject)];
    expect((await readFactChecks(s.t)).map((f) => f.proposed), "banked before this rule and repaired where they are read, at no cost and with no write: the wording that repeats the subject proposes nothing whatever its case, and the wording that says something survives untouched").toEqual([null, null, s.right]);
    const check = (subject: string, proposed: string, current: string) => ({ page: s.path, statementKey: subject.toLowerCase(), subject, current, proposed, literal: null, usage: null, sources: [{ url: s.src, says: s.src, kind: "encyclopedia" as const }], agreement: "multiple_agree" as const, confidence: "confirmed" as const, verdict: "page_wrong" as const, alsoAt: [], note: "", pageContentHash: "h", pageLocator: null, sourceReadAt: null, state: "checked" as const, rulesVersion: 4, evidenceBasis: null, checkedAt: "2026-09-05T00:00:00.000Z" });
    db.rows = []; await recordFactChecks(s.t, s.path, [check(s.subject, ` ${s.subject.toUpperCase()} `, `${s.subject} (${s.right})`)]);
    expect([db.rows.length, db.rows[0]!.proposed], "and the bank never writes one again, whatever its spacing or case").toEqual([1, null]);
    db.rows = []; await recordFactChecks(s.t, s.path, [check(s.subject, s.right, s.subject)]);
    expect(db.rows[0]!.proposed, "a correction that says something about its subject is banked exactly as written").toBe(s.right);
    db.rows = []; });
});
describe("one readiness verdict, at every door", () => {
  const SITES = [{ t: "tenant-one", path: "/tide-pools", url: "https://alpha.example/tide-pools", q: "tide pool safety" }, { t: "tenant-two", path: "/loom-warping", url: "https://beta.example/loom-warping", q: "warp a floor loom" }] as const; const card = (s: (typeof SITES)[number], over: Partial<ChangeProposal> = {}): ChangeProposal => row({ id: `${s.t}::${s.path}::existing_edit::meta`, tenantId: s.t, pagePath: s.path, pageUrl: s.url, primaryQuery: s.q, changeFamily: "meta", recommendedChange: { kind: "existing_edit", field: "meta", before: "Old line.", after: `A finished description of ${s.q} that a reader could act on.` }, ...over }), SIBLINGS = "the only words in it this page does not share with its template siblings are more examples of the subject every sibling names, and this page holds no item, figure or date of its own for the line to name instead";
  it.each(SITES)("$t: hands over complete work whose only objection is the owner's to judge, and holds every defect by its own name", (s) => {
    for (const [fault, kind] of [[SIBLINGS, "conservative_wording"], ["nothing on file says what a reader gains from it that the page does not already say, so it is held until an evaluator reads it against the page and names the gain", "repeats_supported"]] as const) { const one = card(s, { status: "needs_review", faults: [fault] }), v = openHold(one); expect([v.defects, v.advisories.map((a) => a.kind), v.advisories.every((a) => a.weight > 0 && a.say.length > 20), nextObligation(one)], `a description held for "${fault.slice(0, 32)}" is complete work, so it is offered with the caveat and owes nothing paid`).toEqual([[], [kind], true, null]); }
    for (const [what, over] of [["a placeholder", { recommendedChange: { kind: "existing_edit" as const, field: "meta" as const, before: "Old line.", after: "The exact wording has not been written yet" } }], ["a placement nobody named", { recommendedChange: { kind: "existing_edit" as const, field: "section" as const, before: null, after: "A finished section of real prose about this subject.", where: " " } }], ["a citation off the receipt", { bundle: { objective: "o", metric: "m", measurementPlan: "p", scope: { queries: [], prompts: [] }, alternatives: [], risks: [], confidenceReasons: [], components: [{ kind: "meta" as const, label: "Description", before: "Old line.", after: "A finished description.", risk: "safe" as const, evidenceKeys: ["nothing-holds-this"] }], receipt: { items: [{ key: "k1", kind: "gsc_demand", fact: "f", observedAt: "2026-09-01T00:00:00.000Z" }], missing: [], freshestObservedAt: "2026-09-01T00:00:00.000Z" } } }], ["a figure its own checked sentence contradicts", { faults: ["the figure's own sentence says depending on location, and the copy drops it"] }], ["a draft that narrates the page", { faults: ["it points at the page instead of answering"] }]] as const) { const one = card(s, { status: "needs_review", ...(over as Partial<ChangeProposal>) }); expect(openHold(one, { found: actionableProposalFailures(one, { tenantId: s.t, currentBasis: one.basis ?? null }) }).defects.length > 0, `${what} is Beacon's own to fix, so it is named on the row rather than handed to the operator as a caveat`).toBe(true); } });
  it.each(SITES)("$t: gives one answer at the save, the reload, the ladder and the next pass, and re-buys nothing to say it", async (s) => {
    db.rows = []; const drafted = card(s, { status: "ready", claims: [{ text: "The shallowest pools warm first.", supportedBy: ["fact-1"] }], supportFacts: [{ id: "fact-1", fact: 'https://oceans.example/pools says "the shallowest pools warm first" (confirmed)' }] }), sourced = { ...drafted, semanticReview: { of: copyKey(drafted), version: REVIEW_CONTRACT, claims: [{ i: 0, by: ["fact-1"], entailed: true }] } }; expect(await saveChangeProposal(sourced), "the store promotes a row whose defects are empty").toBe("saved");
    expect([held().status, openHold(held()).defects, openHold(held()).advisories.map((a) => a.kind), openHold(held()).caveats[0], nextObligation(held()), held().semanticReview?.version, await saveChangeProposal(held()), await saveChangeProposal({ ...held(), status: "implemented_pending_verification" as const })], "the reload and the ladder give the store's own answer, one credible source is a caveat naming its count, the reading banked before the policy moved is untouched, the next pass over unmoved evidence writes nothing at all, and no save may walk a row into implemented behind the mark-done transaction").toEqual(["ready", [], ["single_source"], "Backed by 1 checked source. Add a second before publishing if being wrong here would cost you.", null, REVIEW_CONTRACT, "unchanged", "failed"]); });
  it.each(SITES)("$t: reads the deleted holds' stored sentences as the caveats they became, un-settles finished words no rule still refuses, and holds the empty no-op and the instruction to write it yourself", (s) => {
    const legacy = [["This change works on something other than how this page opens, which is what this page's own evidence names, so it is held for review rather than handed over as ready to paste.", "role_uncertain"],
      [`1 of the 2 pages coming up for "${s.q}" get no words from this change (/other), so the split it names is not fully answered and this is held for review rather than handed over as ready to paste.`, "role_uncertain"],
      ["The bar for what counts as worth your time has risen and this one no longer clears it, so it stays held rather than offered.", "benefit_uncertain"]] as const;
    for (const [sentence, kind] of legacy) { const one = card(s, { status: "needs_review", faults: [sentence], limitations: [sentence] }), v = openHold(one); expect([v.defects, v.advisories.map((a) => a.kind), nextObligation(one)], `a row the old doors demoted with "${sentence.slice(0, 30)}" is finished work under today's rule and owes no paid corrective draft (journey review, 2026-09-06)`).toEqual([[], [kind], null]); }
    const unsourced = card(s, { faults: ["It states what a country's national symbol is and stands only on this page saying so, which is not a source, so it is held until one is on file."] }); expect([openHold(unsourced).defects.length > 0, nextObligation(unsourced) != null]).toEqual([true, true]); const settled = { kind: "terminal" as const, reason: "two corrective drafts failed the same gates, so this is settled rather than retried" };
    expect([nextObligation(card(s, { status: "needs_review", obligation: settled })), nextObligation(card(s, { status: "needs_review", createdAt: new Date().toISOString(), obligation: settled, recommendedChange: { kind: "existing_edit", field: "meta", before: "Old line.", after: "The exact wording has not been written yet" } }))?.kind],
      "a settlement stands while the one verdict still holds a defect on these words and not a day longer: finished words no rule refuses owe nothing, a young placeholder stays settled and an aged one re-enters the cycle by design (operator, 2026-09-10)").toEqual([null, "terminal"]);
    const same = card(s, { recommendedChange: { kind: "existing_edit", field: "meta", before: "The old description of this page.", after: "The old  description of this page." } }), told = card(s, { recommendedChange: { kind: "existing_edit", field: "meta", before: "Old line.", after: `Write two lines here about ${s.q}, in your own words.` } });
    expect([openHold(same).defects, openHold(told).defects], "the empty no-op and the instruction to write it yourself are the defects the policy names").toEqual([["it changes nothing: the new words are the words the page already carries"], ["it describes the work instead of being it"]]); });
  /* RETIRED WITH SHIP MODE (operator, 2026-09-10): this case pinned a taste gate or the packet regime that no longer refuses additive body work; parked, not deleted, so the inventory shows exactly what was cut. */
it.skip("re-judges the account's own captured rows at no cost: the narration draft stays held by name and the empty no-op stays settled", () => {
    const rows = (JSON.parse(readFileSync("tests/fixtures/harness/hub-rows.json", "utf8")) as { payload: { proposal: ChangeProposal } }[]).map((r) => r.payload.proposal), narrating = rows.find((p) => (p.faults ?? []).some((f) => f.includes("points at the page")))!, settled = rows.find((p) => p.obligation?.kind === "terminal")!;
    expect([openHold(narrating).defects.includes("it points at the page instead of answering"), openHold(narrating).advisories.map((a) => a.kind), nextObligation(narrating)?.kind, (nextObligation(narrating) as { instruction?: string }).instruction, nextObligation(settled)?.kind], "narration is a defect the writer fixes and rides the redraft as its instruction, the register judgement beside it is the owner's call, and a line carrying only the current line's own words stays settled").toEqual([true, ["conservative_wording"], "redraft", "it points at the page instead of answering", "terminal"]); });
});
describe("retained factual scope and publisher voice", () => {
  it("saves qualified legacy body copy as Ready, clears only superseded findings and leaves unchanged replay free", async () => {
    db.rows = []; const after = "Otters inhabit rivers and herons inhabit wetlands.", fault = "it points at the page instead of answering";
    const p = row({ changeFamily: "section", recommendedChange: { kind: "existing_edit", field: "section", before: null, after, where: "At the end of the main article" }, claims: [{ text: after, supportedBy: ["page-copy-1"] }], supportFacts: [{ id: "page-copy-1", fact: after }], faults: [fault], limitations: [fault] });
    const editor = { pageFit: true, resolvesDiagnosis: true, usefulAndNatural: true, placementCorrect: true, implementableNow: true, improvesPage: true, wouldHandToCustomer: true, notes: "Supported subject explanation." };
    expect(await saveChangeProposal({ ...p, semanticReview: { of: copyKey(p), version: REVIEW_CONTRACT, editor, claims: [{ i: 0, by: ["page-copy-1"], entailed: true }] } })).toBe("saved");
    expect([held().status, held().faults, nextObligation(held()), await saveChangeProposal(held())]).toEqual(["ready", [], null, "unchanged"]);
  });
  const packet = (after: string) => row({ recommendedChange: { kind: "existing_edit", field: "answer_block", before: null, after, where: "After the opening" } });
  it("binds figures to independent fact sentences and refuses real qualifier loss", () => { const fact = "As of 2001, 20 mammal species and 14 bird species were endangered.", marketing = "From the national animals to the many mammals, discover wildlife.Persian Onager factsGoitered", check = AEO_BAR.copyRefusals.figures; expect(check(fact, [marketing, fact].join("\n"))).toEqual([]); for (const copy of ["Tickets cost 20 dollars.", "Tickets cost 20 dollars. Details come from the museum."]) expect(check(copy, "Tickets cost from 20 dollars.")).toEqual(["the figure's own sentence says from, and the copy drops it"]); expect(check("Tickets cost from 20 dollars.", "Tickets cost from 20 dollars.")).toEqual([]); expect(check("International shipping takes 7–21 days.", "International shipping takes from 7 to 21 days.")).toEqual([]); });
  it("holds body copy without contextual editor authorization, including otherwise ordinary subject facts", () => { for (const lead of ["Wildlife detail here is a status summary.", "This guide describes wildlife.", "Wildlife is grouped here by habitat.", "Otters inhabit rivers and herons inhabit wetlands."]) expect(unreviewed(packet(`${lead}\n## Species recorded in rivers\nOtters inhabit rivers.`))).toMatch(/complete editor acceptance/); });
});
