/** structured-drafter strict-gateway transport: the seam returns parsed VALUES (no prose recovery), a refusal fails closed with no artifact, retry is bounded and paid for, and a cache hit costs $0. */
import { describe, it, expect, vi } from "vitest";
import { callStructuredLLM, draftAtomicEditStructured, type CompleteFn } from "@/domains/decision/llm/structured-drafter";
import type { CacheImpl, LlmCallCacheEntry } from "@/domains/decision/llm/call-cache";
import { normalizeStructuredValue } from "@/domains/decision/llm/responses-envelope"; import { SCHEMA_BY_KIND } from "@/domains/decision/llm/schemas"; import { COPY_RULES } from "@/domains/decision/copy-sanitize"; import type { SourcePacket } from "@/domains/decision/drafted-copy";
const VALID_ATOMIC_EDIT = { // A schema-valid AtomicEditDraft value (the simplest kind, no source-verify / word-count / superlative machinery in the way of the transport assertions).
  field: "title", before: "Nowruz", after: "Nowruz Traditions: Persian New Year Customs and Haft-Seen", rationale: "The current title is one word and misses the customs searchers ask about.",
  evidenceRefs: [{ source: "gsc", detail: "strong impressions for nowruz traditions with a low click rate" }], confidence: "high" };
const REQ = {
  kind: "atomic_edit" as const, tenantId: "tenant-fixture",
  system: "You improve one on-page field. Return the field, before, after, rationale, evidenceRefs, confidence.",
  user: "Page: Nowruz. Field to edit: title. Current title: Nowruz.",
  grounded: "nowruz traditions persian new year customs haft-seen",};
/** A `complete` double that replays a queue and counts how many times it ran. */
function seam(responses: Array<{ value: unknown } | { error: string; retryable: boolean; costUsd?: number }>): { complete: CompleteFn; calls: () => number } {
  let i = 0, calls = 0; const complete: CompleteFn = async () => { calls += 1; return responses[Math.min(i++, responses.length - 1)]!; };
  return { complete, calls: () => calls };}
describe("structured-drafter strict transport", () => {
  it("normalizes publishable punctuation without changing literal anchors, replaced text or addresses", async () => {
    const exact = { ...VALID_ATOMIC_EDIT, before: "Nowruz—Customs", after: "Nowruz—Persian New Year Customs", placementAnchor: "Stored—heading", rationale: "Kept to 58 characters, https://docs.example/a—b" }, out = await callStructuredLLM({ ...REQ, complete: seam([{ value: exact }]).complete });
    expect(out.status === "drafted" && [out.value.before, out.value.after, out.value.placementAnchor, out.value.rationale], "rationale is the writer's reasoning, never scanned as copy: its 58 is not an invented figure").toEqual([exact.before, "Nowruz - Persian New Year Customs", exact.placementAnchor, exact.rationale]);
    for (const [after, count, status] of [["Nowruz Customs: 14 Traditions", 3157, "validation_failed"], ["Nowruz Customs: 3157 Traditions", 3157, "validation_failed"], [VALID_ATOMIC_EDIT.after, 3157, "drafted"], [VALID_ATOMIC_EDIT.after, 9999, "validation_failed"]] as const) { const value = { ...VALID_ATOMIC_EDIT, after, evidenceRefs: [{ source: "gsc", detail: `${count} impressions` }] }, judged = await callStructuredLLM({ ...REQ, observationGrounded: "GSC recorded 3157 impressions", complete: seam([{ value }]).complete }); expect(judged.status, "observed traffic may support a diagnostic ref, never a factual count in paste copy, and a fabricated diagnostic count is refused too").toBe(status); } });
  it("grounds a number the assignment lines show and the current year, and still refuses one a rival line shows or one from nowhere", async () => { // audit 2026-09-14: a figure in the assignment was refused as invented; review 2026-09-14: a rival's figure never grounds copy
    const drive = (after: string) => callStructuredLLM({ ...REQ, user: `${REQ.user}\nrival-1: the winning page lists 21 haft-seen items.`, assignmentGrounded: "name the 13 haft-seen items", now: new Date("2026-09-14T00:00:00Z"), complete: seam([{ value: { ...VALID_ATOMIC_EDIT, after } }]).complete });
    for (const [after, status] of [["Nowruz Traditions: 13 Haft-Seen Customs", "drafted"], ["Nowruz Traditions for 2026 and 2025", "drafted"], ["Nowruz Traditions: 21 Customs", "validation_failed"]] as const) expect((await drive(after)).status, after).toBe(status); });
  it("re-buys once a cached answer that fails today's rules, and overwrites the entry with the new answer", async () => { // audit 2026-09-14: a stale hit was schema_invalid at $0 forever
    const written: unknown[] = [], stale = { ...VALID_ATOMIC_EDIT, after: "Nowruz Traditions: 21 Customs" } as unknown as LlmCallCacheEntry["value"], fresh = seam([{ value: VALID_ATOMIC_EDIT }]);
    const out = await callStructuredLLM({ ...REQ, complete: fresh.complete, cacheImpl: { read: async (tenantId, key) => ({ value: stale, tenantId, key } as LlmCallCacheEntry), write: async (_t, e) => { written.push(e.value); }, recentTexts: async () => [] } });
    expect([out.status, out.status === "drafted" && out.cached, fresh.calls(), (written[0] as { after: string } | undefined)?.after]).toEqual(["drafted", undefined, 1, VALID_ATOMIC_EDIT.after]); });
  it("refuses a draft argued from analytics alone, and takes the same draft once it also cites a search", async () => {
    const refs = (r: unknown[]) => ({ value: { ...VALID_ATOMIC_EDIT, evidenceRefs: r } }); const clarity = [{ source: "clarity", detail: "people stop scrolling about halfway down the page" }];
    const bad = await callStructuredLLM({ ...REQ, complete: seam([refs(clarity), refs(clarity)]).complete }); // both attempts, still nothing about a search
    expect([bad.status, bad.status === "validation_failed" && bad.reason.startsWith("evidenceRefs: analytics alone")]).toEqual(["validation_failed", true]);
    const good = await callStructuredLLM({ ...REQ, complete: seam([refs([...clarity, { source: "gsc", detail: "strong impressions with a low click rate" }])]).complete });
    expect(good.status).toBe("drafted"); }); // ga4 and clarity are welcome BESIDE evidence of the search, never instead of it
  /** AND SAYING SO IS NOT ENOUGH (live, 2026-08-31). The link brief forbade marking the anchor in the plainest words available, and the writer still returned "[Zanjan Rug]", so the placeholder firewall refused both attempts and the candidate bought nothing twice. The words were right and the punctuation around them was the model's own, so code takes the punctuation off rather than paying again to ask nicely. */
  it("takes the writer's markup off an anchor that is otherwise exactly right, and still refuses a real placeholder", async () => {
    const drive = async (after: string) => callStructuredLLM({ kind: "atomic_edit" as const, tenantId: "t", system: "s", user: "u", unmarkPhrase: "Zanjan Rug", grounded: "Zanjan rugs run 100 to 150 knots per square inch and the page earns 1400 impressions in 90 days", complete: seam([{ value: { ...VALID_ATOMIC_EDIT, after } }]).complete });
    for (const marked of ["Kashan knot counts run higher than the [Zanjan Rug], which sits between 100 and 150.", "Kashan knot counts run higher than the **Zanjan Rug**, which sits between 100 and 150.", "Kashan knot counts run higher than the [Zanjan Rug](/persian-rugs/zanjan-rug), which sits between 100 and 150."]) {
      const out = await drive(marked);
      expect([out.status, out.status === "drafted" && (out.value as { after: string }).after], `the words survive and only the writer's own markup comes off: ${marked.slice(30, 60)}`)
        .toEqual(["drafted", "Kashan knot counts run higher than the Zanjan Rug, which sits between 100 and 150."]); }
    const holes = await drive("Kashan knot counts run higher than the [insert rug name], which sits between 100 and 150.");
    expect([holes.status, holes.status === "validation_failed" && holes.reason.includes("placeholder")], "an unfilled hole is not markup around the right words, and is refused exactly as before").toEqual(["validation_failed", true]);
    const edit = await callStructuredLLM({ kind: "atomic_edit" as const, tenantId: "t", system: "s", user: "u", grounded: "Zanjan Rug knot density", unmarkPhrase: "Zanjan Rug", // AND A LINK IS DRAFTED THROUGH THE ATOMIC EDITOR, not the older link kind, which is why the first repair fired on nothing: only the caller knows which words are the anchor, so it says so, and every field is cleaned rather than one.
      complete: seam([{ value: { ...VALID_ATOMIC_EDIT, after: "Kashan pile is denser than the [Zanjan Rug] weave.", placementAnchor: "Link the words **Zanjan Rug** in that sentence" } }]).complete });
    expect([edit.status, edit.status === "drafted" && (edit.value as { after: string }).after, edit.status === "drafted" && (edit.value as { placementAnchor: string }).placementAnchor], "the anchor the caller resolved is unwrapped in the copy AND in the anchor, because the firewall reads both").toEqual(["drafted", "Kashan pile is denser than the Zanjan Rug weave.", "Link the words Zanjan Rug in that sentence"]);
    const banked = { ...VALID_ATOMIC_EDIT, after: "Kashan pile is denser than the [Zanjan Rug] weave." } as unknown as LlmCallCacheEntry["value"]; // A HIT RETURNS BEFORE THE FIREWALLS, so a draft banked under an older prompt version would serve the brackets the fresh path takes off: what the customer reads may not depend on which door the answer came through.
    const served = await callStructuredLLM({ kind: "atomic_edit" as const, tenantId: "t", system: "s", user: "u", grounded: "Zanjan Rug", unmarkPhrase: "Zanjan Rug", complete: seam([{ error: "should-never-run", retryable: false }]).complete,
      cacheImpl: { read: async (tenantId, key) => ({ value: banked, tenantId, key } as LlmCallCacheEntry), write: async () => {}, recentTexts: async () => [] } });
    expect([served.status, served.status === "drafted" && served.cached, served.status === "drafted" && (served.value as { after: string }).after],
      "the cached answer is cleaned exactly like a fresh one, and still costs nothing").toEqual(["drafted", true, "Kashan pile is denser than the Zanjan Rug weave."]); });
  it("drafts a VALUE, retries a recoverable answer once and no more, and never pays twice for one answer", async () => {
    const one = seam([{ value: VALID_ATOMIC_EDIT }]); // a parsed value, no text parsing, on one call
    const first = await callStructuredLLM({ ...REQ, complete: one.complete }); expect(first.status === "drafted" && [(first.value as { after: string }).after.includes("Nowruz Traditions"), one.calls()]).toEqual([true, 1]);
    const boom = await callStructuredLLM({ ...REQ, complete: seam([{ error: "network boom", retryable: true }]).complete }); expect(boom.status === "validation_failed" && boom.costUsd).toBe(0); const thrown = vi.fn(async () => { throw new Error("a completion failed before returning its receipt"); }), allowance = { left: 1 }; const missing = await callStructuredLLM({ ...REQ, attempts: allowance, complete: thrown }); expect([thrown.mock.calls.length, allowance.left, missing.status, missing.status === "validation_failed" && missing.failure, missing.status === "validation_failed" && missing.errors]).toEqual([1, 0, "validation_failed", "transient", ["llm_completion did not return an outcome"]]);
    const paid = await callStructuredLLM({ ...REQ, complete: seam([{ error: "incomplete", retryable: false, costUsd: 0.0042 }]).complete }); expect(paid.status === "validation_failed" && paid.costUsd).toBe(0.0042);
    const again = seam([{ value: {} }, { value: VALID_ATOMIC_EDIT }]); // a rejection CAN recover
    const out = await callStructuredLLM({ ...REQ, complete: again.complete }); expect(out.status === "drafted" && [out.retried, again.calls()]).toEqual([true, 2]);
    const refused = await callStructuredLLM({ ...REQ, complete: seam([{ error: "refusal", retryable: false, costUsd: 0.0123 }]).complete });
    expect(refused.status === "validation_failed" && refused.costUsd).toBe(0.0123); // no retry on a refusal, its real cost
    const now = new Date("2026-07-23T00:00:00Z").toISOString();
    const entry = { key: "ignored-key-is-derived", tenantId: "tenant-fixture", kind: "atomic_edit", promptId: "draft.atomic_edit",
      promptVersion: 1, value: VALID_ATOMIC_EDIT, primaryText: VALID_ATOMIC_EDIT.after, createdAt: now, lastUsedAt: now } as LlmCallCacheEntry;
    const cacheImpl: CacheImpl = { read: async (tenantId, key) => ({ ...entry, tenantId, key }), write: async () => {}, recentTexts: async () => [] }; const hit = seam([{ error: "should-never-run", retryable: false }]);
    const cached = await callStructuredLLM({ ...REQ, complete: hit.complete, cacheImpl, attempts: { left: 0 }, stopBy: 0 }); for (const ceiling of [0, 1, 2]) { const a = { left: ceiling }, paid = seam([{ value: {} }, { value: VALID_ATOMIC_EDIT }]), out = await callStructuredLLM({ ...REQ, attempts: a, complete: async (r) => ({ ...await paid.complete(r), httpAttempts: 1 }) }); expect([paid.calls(), a.left, out.status, out.status === "validation_failed" || out.status === "drafted" ? out.attempts : -1], "each actual request, including retry, takes the shared allowance before the wire").toEqual([ceiling, 0, ceiling === 2 ? "drafted" : "validation_failed", ceiling]); } const at = Date.now(), clock = vi.spyOn(Date, "now").mockReturnValue(at); try { let calls = 0; const out = await callStructuredLLM({ ...REQ, stopBy: at + 1, complete: async () => (calls += 1, clock.mockReturnValue(at + 2), { value: {}, httpAttempts: 1 }) }); expect([calls, out.status, out.status === "validation_failed" && out.attempts], "a failed first response cannot start a retry after the caller deadline").toEqual([1, "validation_failed", 1]); } finally { clock.mockRestore(); }
    expect(cached.status === "drafted" && [cached.cached, cached.costUsd, hit.calls()]).toEqual([true, 0, 0]); const blocked = seam([{ error: "blocked_budget", retryable: false }]);
    const stopped = await callStructuredLLM({ ...REQ, complete: blocked.complete }); // a budget block fired no call
    expect(stopped.status === "validation_failed" && [stopped.costUsd, blocked.calls()]).toEqual([0, 1]); const refunded = { left: 1 }, noWire = await callStructuredLLM({ ...REQ, attempts: refunded, complete: async () => ({ error: "blocked_budget", retryable: false, httpAttempts: 0, costUsd: 0 }) }); expect([refunded.left, noWire.status === "validation_failed" && noWire.attempts, noWire.status === "validation_failed" && noWire.costUsd], "a proven pre-network refusal refunds its reservation without claiming a review").toEqual([1, 0, 0]); const unknown = { left: 1 }, lost = await callStructuredLLM({ ...REQ, attempts: unknown, complete: async () => { throw new Error("receipt lost"); } }); expect([unknown.left, lost.status === "validation_failed" && lost.attempts], "a thrown transport is never rewritten as proof that no request crossed the wire").toEqual([0, 1]); }); });
describe("publication-only copy checks", () => {
  it("treats citation markers in a fact verdict as data, while rejecting them in publication copy", async () => {
    const copy = await callStructuredLLM({ ...REQ, complete: seam([{ value: { ...VALID_ATOMIC_EDIT, after: "Nowruz Traditions [ 1 ]" } }]).complete });
    expect(copy.status).toBe("validation_failed");
    const VERDICT = { verdict: "page_correct", confidence: "likely", proposed: "", literal: "light", usage: "given name", note: 'the page quotes its source as "light [ 1 ]"', supporting: [], subjects: [] }; // A VERDICT IS NOT A PAGE (live, 2026-08-30): the judge quotes the page's own citation markers, so a schema-valid judgement carrying "[ 1 ]" DRAFTS; the bracket rule guards only copy a customer could paste (the atomic_edit above still refuses it).
    const ruled = await callStructuredLLM({ kind: "fact_claim_judgement", tenantId: "t", system: "You judge one claim.", user: "Judge it.", grounded: "a passage", complete: seam([{ value: VERDICT }]).complete } as never);
    expect(ruled.status, "a citation marker in a verdict is data, never an unfilled placeholder").toBe("drafted"); });

});
/** The body transport preserves publication structure and exact predecessor scope, not an answer-length quota. */
import { withoutCta } from "@/domains/decision/drafted-copy";
describe("structured body delivery", () => {
  it("retains complete units, practical steps and preservation beyond atomic field limits", async () => {
    const fact = "Leave before incoming water covers the return route.", before = (fact + " ").repeat(50), preservation = [{ text: fact, disposition: "kept", why: "The replacement retains this guidance." }];
    const units = [{ kind: "heading", level: 3, text: "When should you leave?" }, { kind: "paragraph", text: before.replaceAll("return route", "**return route**") }, { kind: "ordered_list", items: ["Check the return route before entering."] }, { kind: "unordered_list", items: [fact] }];
    const complete: CompleteFn = async (ask) => { expect(ask.kind).toBe("body_edit"); return { value: { ...VALID_ATOMIC_EDIT, field: "answer_block", units, preservation, claims: Array.from({ length: 25 }, () => ({ text: fact, supportedBy: ["fact-1"] })) } }; };
    const out = await draftAtomicEditStructured({ field: "answer_block", query: "return route", pageLabel: "Return route", currentValue: null, unmarkPhrase: "return route", replaces: before, outline: [], evidenceHints: [before], tenantId: "body-fixture" }, { complete, bypassCache: true });
    expect(out.status).toBe("drafted"); if (out.status !== "drafted") throw new Error(JSON.stringify(out));
    expect([out.value.before, out.value.preservation, out.value.claims.length]).toEqual([before, preservation, 25]);
    expect(out.value.after).toBe(`### When should you leave?\n\n${before}\n\n1. Check the return route before entering.\n\n- ${fact}`); expect(withoutCta(out.value.after, "section")).toBe(out.value.after); });
  /** THE PAGE IS SENT ONCE (audit, 2026-09-14): page.body, page-copy-N and comparison.owned.held carried the same page three times and the assignment rode twice, so a body call was 50,000 plus characters. */
  it("sends a 10,000 character page to the writer once, with the page-copy ids as the citable index", async () => {
    const passages = Array.from({ length: 40 }, (_, i) => `Passage ${i + 1} of the flood guide explains one part of the return route in plain words for the reader who needs it. `.repeat(3).trim()), bodyText = passages.join("\n\n"); expect(bodyText.length).toBeGreaterThan(10_000);
    const evidence = COPY_RULES.pageEvidence(passages, "", 12_000).evidence, packet: SourcePacket = { targetUrl: "https://example.org/flood", title: "Flood guide", h1: "Flood guide", metaDescription: null, bodyText, headings: [], evidence: { ...evidence, "fact-1": "Leave before incoming water covers the return route." }, trackedQuestion: "when to leave", ownedPaths: [], bannedTerms: [], demand: { preserve: [], vocabulary: [] } };
    let user = ""; const complete: CompleteFn = async (ask) => { user = ask.user; return { error: "captured", retryable: false }; }; await draftAtomicEditStructured({ field: "answer_block", query: "when to leave", pageLabel: "Flood guide", currentValue: null, outline: [], evidenceHints: ["THE ASSIGNMENT: add the leaving rule"], packet, tenantId: "packet-fixture" }, { complete, bypassCache: true });
    const body = (JSON.parse(user.slice(user.indexOf("{", user.indexOf("SHARED EVIDENCE PACKET")), user.lastIndexOf("}") + 1)) as { page: { body: string }; evidence: { id: string }[] });
    const ids = Object.values(evidence); expect([user.length < 2.2 * bodyText.length, ids.length + body.page.body.split("\n").length, ids.some((t) => body.page.body.includes(t)), (user.match(/THE ASSIGNMENT/g) ?? []).length], `prompt ${user.length} chars for a ${bodyText.length} char page`).toEqual([true, passages.length, false, 1]); }); // the ids carry what the budget covered, page.body carries only the rest
  /** A SOURCES ROW PARSES (audit, 2026-09-14): the strict provider schema makes every optional source field required-and-nullable, and the normalizer never descended the z.preprocess wrapper around `sources`, so a body draft naming ONE real reading failed strict decode on its nulls and lost the paid attempt. */
  it("accepts a body answer whose one sources row carries provider nulls, and drops a blank row", async () => {
    const units = [{ kind: "paragraph", text: "Leave before incoming water covers the return route." }], row = { url: "https://example.org/tides", title: "Tide tables", domain: "example.org", retrievedAt: "2026-09-14", claim: "Leave before incoming water covers the return route.", authority: "weak", verified: false, verifiedAt: null, supportingExcerpt: null, finalUrl: null, contentHash: null, fetchBlocked: null };
    const wire = { ...VALID_ATOMIC_EDIT, field: "answer_block", units, preservation: [], claims: [{ text: units[0]!.text, supportedBy: ["fact-1"] }], sources: [row, { ...row, url: "" }] };
    const value = normalizeStructuredValue(wire, SCHEMA_BY_KIND.body_edit) as { sources: unknown[] }; expect(value.sources[0]).toEqual({ url: row.url, title: row.title, domain: row.domain, retrievedAt: row.retrievedAt, claim: row.claim, authority: "weak", verified: false }); const out = await callStructuredLLM({ kind: "body_edit", tenantId: "t", system: "s", user: "u", grounded: "Leave before incoming water covers the return route. 2026-09-14", complete: seam([{ value }]).complete, bypassCache: true });
    expect([out.status, out.status === "drafted" && (out.value as { sources: unknown[] }).sources.length], "one real reading survives, the blank row is the empty list").toEqual(["drafted", 1]); });
});
