/**
 * worklist-export (2026-06-25) — turn the ranked opportunity feed into a clean,
 * shareable Markdown work doc the operator can hand to a developer/VA (the offshore
 * team). Pure + dependency-free so it's testable and reused by the client download
 * button. Each row becomes an actionable checklist item with the page, the move,
 * and the clicks at stake — no jargon, no internal IDs.
 */

export type ExportItem = {
  kind: string;
  query: string;
  page: string;
  clicksAtStake: number;
  detail?: string;
};

const KIND_VERB: Record<string, string> = {
  recover: "Recover lost ground on",
  win: "Win the top spot for",
  cite: "Get cited by AI for",
  build: "Build a page for",
  edit: "Improve",
  tool: "Build a tool for",
  snippet: "Rewrite the snippet for",
  consolidate: "Consolidate self-competing pages for",
  rising: "Double down on rising demand for",
  answer: "Add an answer block for",
  expand: "Expand the thin content for",
  leverage: "Fix once, win several ways —",
};

function pretty(url: string): string {
  const s = url.split("?")[0]!.split("#")[0]!.replace(/\/$/, "");
  return s.split("/").filter(Boolean).pop()?.replace(/[-_]+/g, " ").trim() || url;
}

/**
 * Build the Markdown worklist. `dateLabel` is injected (no Date dependency) so the
 * doc is reproducible/testable. Items are assumed already ranked (highest first).
 */
export function buildWorklistMarkdown(
  items: ExportItem[],
  opts: { siteName?: string; dateLabel?: string } = {},
): string {
  const site = opts.siteName?.trim() || "your site";
  const date = opts.dateLabel?.trim();
  const total = items.reduce((s, i) => s + Math.max(0, i.clicksAtStake), 0);

  const lines: string[] = [];
  lines.push(`# ${site} — SEO worklist`);
  if (date) lines.push(`_Generated ${date}_`);
  lines.push("");
  lines.push(
    `**${items.length} prioritized tasks · ~${total.toLocaleString()} monthly clicks at stake.** Work top-down — each is ordered by impact.`,
  );
  lines.push("");

  items.forEach((it, i) => {
    const verb = KIND_VERB[it.kind] ?? "Improve";
    lines.push(`### ${i + 1}. ${verb} "${it.query}"`);
    lines.push(`- **Page:** ${it.page} (${pretty(it.page)})`);
    lines.push(`- **Impact:** ~${Math.max(0, it.clicksAtStake).toLocaleString()} clicks/mo at stake`);
    if (it.detail?.trim()) lines.push(`- **Why:** ${it.detail.trim()}`);
    lines.push("");
  });

  lines.push("---");
  lines.push("_Generated by Beacon. Each task is grounded in your Google Search Console data._");
  return lines.join("\n");
}

/** RFC-4180 cell escaping: wrap in quotes + double internal quotes when needed. */
function csvCell(value: string): string {
  const v = value ?? "";
  return /[",\n]/.test(v) ? `"${v.replace(/"/g, '""')}"` : v;
}

/**
 * Build the worklist as CSV for import into a sheet / tracker (Jira, Asana, Sheets).
 * Columns: Priority, Task, Page, Topic, ClicksAtStake, Why. Items assumed ranked.
 */
export function buildWorklistCsv(items: ExportItem[]): string {
  const header = ["Priority", "Task", "Page", "Topic", "ClicksAtStake", "Why"];
  const rows = items.map((it, i) => {
    const verb = KIND_VERB[it.kind] ?? "Improve";
    return [
      String(i + 1),
      `${verb} "${it.query}"`,
      it.page,
      pretty(it.page),
      String(Math.max(0, it.clicksAtStake)),
      it.detail?.trim() ?? "",
    ]
      .map(csvCell)
      .join(",");
  });
  return [header.join(","), ...rows].join("\n");
}
