/**
 * service-area-gaps (RANK-5, 2026-07-06) - PURE.
 *
 * The local-service money-maker: from a tenant's configured service-area cities
 * x services, find the city x service pages the business should have but does not
 * (a market where competitors compete and the tenant is absent), and shape them
 * into ready-to-emit create_page gaps.
 *
 * GENERIC + config-driven: cities + services come from the caller (tenant config
 * / GSC geo terms), NEVER hardcoded. No city, no trade, no vertical is baked in.
 * A tenant with NO locations/services config produces an EMPTY list - byte-
 * identical to a world without this engine (a content tenant like an encyclopedia
 * is a no-op here).
 *
 * The city x service matrix itself is generated by the SHIPPED page factory
 * (generateCityServiceCandidates) - this module does NOT fork it, it adds the
 * competitive-gap ranking on top: a candidate becomes a real gap only when the
 * geo coverage matrix shows the tenant is ABSENT or WEAK in that city AND a rival
 * already has pages there (proof the market is real). When no coverage signal
 * exists for a city, the candidate still stands (the config declared it a market
 * the tenant should compete in) but ranks below coverage-proven gaps.
 *
 * Every gap carries `needsDemandValidation` from the factory - no search volume
 * is invented here; the create-page demand verdict confirms it before a Move
 * publishes anything.
 *
 * PURE FUNCTION. Pinned by service-area-gaps.test.ts.
 */

import {
  generateCityServiceCandidates,
  type CityServiceCandidate,
} from "@/domains/page-factory/city-service-factory";
import { normalizeCity } from "@/domains/geo/normalize";
import type { CityCoverage } from "@/domains/geo/types";

export type ServiceAreaGap = {
  /** URL-safe slug for the missing city x service page. */
  slug: string;
  /** Human page title (from the factory). */
  title: string;
  /** The service-area city this gap targets. */
  city: string;
  /** The service this gap targets. */
  service: string;
  /**
   * Competitor pages the coverage matrix sees in this city (0 when no coverage
   * signal exists yet - the config alone declared the market).
   */
  competitorPages: number;
  /** Coverage status for the city from the geo matrix, or null when unknown. */
  coverageStatus: CityCoverage["coverage_status"] | null;
  /** 1 when the service echoes the tenant's own vocabulary, else 0.5. */
  relevance: number;
  needsDemandValidation: boolean;
};

export type DetectServiceAreaGapsInput = {
  /** Service-area cities (tenant config locations). */
  cities: string[];
  /** Services the tenant offers (tenant config services). */
  services: string[];
  /** Owned page URLs - for dedup (never propose a page that already exists). */
  ownedUrls: string[];
  /**
   * Optional per-city coverage from computeGeoCoverage. Used to RANK gaps and
   * to attach the competitor-pages proof; never REQUIRED (an unconnected tenant
   * still gets config-declared gaps, just unranked by coverage).
   */
  cityCoverage?: ReadonlyArray<CityCoverage>;
  /** Optional brand/qualifier woven into the page title (e.g. the industry). */
  titleQualifier?: string;
  maxGaps?: number;
};

const DEFAULT_MAX_GAPS = 12;

/** Coverage strength ordering - absent + weak cities are the real openings. */
function coverageRank(status: CityCoverage["coverage_status"] | null): number {
  switch (status) {
    case "absent":
      return 3;
    case "weak":
      return 2;
    case "moderate":
      return 1;
    case "strong":
      return 0;
    default:
      // Unknown coverage: the config declared this a market, so it still ranks
      // above a city we already cover strongly, but below a proven opening.
      return 1;
  }
}

/**
 * Detect missing city x service pages for a local-service tenant. PURE.
 *
 * Empty-safe: no cities OR no services -> [] (a content tenant with no service
 * areas gets byte-identical behavior). Returns the highest-value openings first
 * (coverage-proven absence + a competing rival, then config relevance).
 */
export function detectServiceAreaGaps(
  input: DetectServiceAreaGapsInput,
): ServiceAreaGap[] {
  const cities = (input.cities ?? []).map((c) => c.trim()).filter(Boolean);
  const services = (input.services ?? []).map((s) => s.trim()).filter(Boolean);
  // No configured service areas -> not a local-service tenant -> no-op.
  if (cities.length === 0 || services.length === 0) return [];

  const max = input.maxGaps ?? DEFAULT_MAX_GAPS;

  // Reuse the SHIPPED factory for the deduped city x service matrix (owned-URL
  // aware). We over-generate (max x 3, capped) so the coverage ranking below has
  // a real pool to prioritize from before we slice to `max`.
  const candidates: CityServiceCandidate[] = generateCityServiceCandidates({
    cities,
    services,
    ownedUrls: input.ownedUrls ?? [],
    titleQualifier: input.titleQualifier,
    maxCandidates: Math.min(max * 3, 90),
  });
  if (candidates.length === 0) return [];

  // Index coverage by canonical city so a config city ("Palo Alto") matches the
  // coverage matrix's normalized key ("palo alto"). Same normalizer coverage.ts
  // itself uses - no divergence.
  const coverageByCity = new Map<string, CityCoverage>();
  for (const c of input.cityCoverage ?? []) {
    coverageByCity.set(normalizeCity(c.city).canonical, c);
  }

  const gaps: ServiceAreaGap[] = candidates.map((c) => {
    const cov = coverageByCity.get(normalizeCity(c.city).canonical) ?? null;
    return {
      slug: c.slug,
      title: c.title,
      city: c.city,
      service: c.service,
      competitorPages: cov?.competitor_pages ?? 0,
      coverageStatus: cov?.coverage_status ?? null,
      relevance: c.relevance,
      needsDemandValidation: c.needsDemandValidation,
    };
  });

  // Rank: coverage-proven openings first (absent > weak), then a rival actually
  // competing there (competitorPages), then config relevance, then stable slug.
  gaps.sort(
    (a, b) =>
      coverageRank(b.coverageStatus) - coverageRank(a.coverageStatus) ||
      b.competitorPages - a.competitorPages ||
      b.relevance - a.relevance ||
      a.slug.localeCompare(b.slug),
  );

  return gaps.slice(0, max);
}
