/**
 * W3 Step 3.2 (2026-05-01) — cross-tenant brain stub.
 *
 * Defines the contract every later phase will fill in. The current
 * implementation returns `[]` deterministically — Beacon is single-
 * tenant single-user today; "cross-tenant patterns" is the
 * post-MVP concept that lets the brain say "this edit shape moves
 * citations 73% of the time across the 4 builders we've seen ship
 * it." Activation lives behind `BEACON_CROSS_TENANT_BRAIN=1` (env
 * gate, not yet wired) and a real producer that aggregates
 * anonymized outcomes across `tenant_audit_log` rows.
 *
 * Founder direction (master plan §1.2 + §5.1):
 *   - Cross-tenant brain is "the brain seed." Today it has nothing
 *     to seed. The contract lands now so the W3 evidence packet
 *     can carry the field unchanged once a real producer exists.
 *   - "Stub only, no real cross-tenant logic yet" (operator scope,
 *     2026-05-01).
 *
 * Hard rules:
 *   - Pure. No I/O. No LLM. No env reads at module top-level.
 *   - The stub returns `[]` for every call regardless of input.
 *   - Type shape is operator-locked: the LLM provider in W3 Step
 *     3.4 will accept this exact field. Do not widen / narrow
 *     without a coordinated update there.
 */

/**
 * One pattern row the cross-tenant brain emits when it activates.
 *
 * `helpingRate` is the only signal that matters for grounding —
 * "edits with this match key helped on N of M shipped attempts." 0
 * if no helping outcomes, NaN-safe (always 0..1 inclusive).
 *
 * `sampleSize` reports how many tenant ships were aggregated.
 * Below the operator-locked threshold (TBD in 3.4) the LLM is
 * instructed to ignore the row.
 *
 * `description` is operator-facing copy ("3 of 4 builders saw
 * citations rise after adding a kitchen-cost FAQ"). Generated by
 * the producer, not the LLM.
 */
export type CrossTenantPattern = {
  /**
   * Stable identifier — same `(matchKey, schemaVersion)` always
   * resolves to the same `patternId`. Lets the LLM cite the
   * pattern by id in its reasoning without leaking tenant data.
   */
  patternId: string;
  /**
   * What the pattern matched on. Tokens chosen by the producer
   * from a closed vocabulary (e.g. "edit_type:add_h2_section",
   * "intent:cost_question", "geo_kind:bay_area"). String form so
   * the producer can grow vocabulary without forcing a packet
   * type bump.
   */
  matchKey: string;
  /** Total shipped attempts aggregated, across tenants, anonymized. */
  sampleSize: number;
  /** 0..1 helping-outcome rate (rounded to 2dp). */
  helpingRate: number;
  /** Operator-facing one-sentence summary. */
  description: string;
};

/**
 * Args for the (future) producer. Today's stub ignores them; the
 * shape is locked so callers can pass real values once the
 * producer exists.
 */
export type GetCrossTenantPatternsArgs = {
  /** Tenant requesting the patterns. Used by the producer to
   *  exclude self-data from the aggregate (no tenant should learn
   *  from its own data via this surface). */
  tenantId: string;
  /** Action types the rec engine may emit. Producer filters to
   *  patterns whose matchKey references one of these types. */
  actionTypes: ReadonlyArray<string>;
  /** Cluster context for filtering — `clusterKind` ("geo" | "topic"
   *  | null) + label. Producer scopes patterns to similar
   *  clusters across tenants. */
  clusterKind: "geo" | "topic" | null;
  clusterLabel: string | null;
};

/**
 * Stub. Always returns `[]`. Wire to a real producer in W3 Step
 * 3.4+ behind `BEACON_CROSS_TENANT_BRAIN=1`.
 *
 * Callers MUST treat this as an empty signal, not as "missing
 * data" — the LLM provider falls back to the rest of the evidence
 * packet (aiSearchSignal + competitorPageBlueprints + per-prompt
 * descriptors) and produces grounded edits without it.
 */
export function getCrossTenantPatterns(
  // Underscore prefix marks the args as deliberately unused in the
  // stub. The signature stays stable for the future producer.
  _args: GetCrossTenantPatternsArgs,
): CrossTenantPattern[] {
  return [];
}
