/**
 * Recommendation Execution Layer v1 — 2026-05-13 P0 follow-up.
 *
 * Resolves a decoded recommendation detail route id to a row in the
 * current persisted snapshot. The list and detail pages share the same
 * row source (`loadPersistedRecommendationQueueForPage` →
 * `buildRecommendationActionRows`), so a single request snapshot is
 * always internally consistent. Drift happens ACROSS requests:
 *
 *   T0  — list page renders. Card hrefs are stamped from row.id.
 *   T1  — operator (or cron / background task) accepts / dismisses /
 *         regenerates the rec. `recommended_edits` mutates.
 *   T2  — operator clicks the card. The detail page reads the new
 *         persisted snapshot. The URL's id no longer matches any row.
 *
 * Before this resolver, the user saw a scary "no longer active" dead
 * end. With the resolver, we try four ladder steps before giving up:
 *
 *   1. EXACT — `row.id === decodedId`. The 99% case.
 *   2. BY EDIT — split decodedId on the FIRST `::` to recover the
 *      `edit.id` tail; find any row whose `sourceEditId` matches. The
 *      paired-FAQ case sometimes produces a different row id shape
 *      (`${stableKey}::faq-pair::${hash}`) for the same underlying
 *      edit, so this catches "shape changed under us" drift.
 *   3. BY REC — find any actionable row whose `sourceRecommendationId`
 *      equals the URL's leading stable key. Catches "rec was
 *      regenerated; the H2 hash changed but the rec is the same."
 *   4. MISS — no useful fallback. The not-found component shows a
 *      calm "this recommendation was replaced or already handled"
 *      with an action-type hint (when parseable from the URL) and a
 *      back button.
 *
 * Hard rules:
 *   - NEVER resurrect a dismissed / shipped row as a "replacement"
 *     for a missing one. The exact-match path STILL renders dismissed
 *     and shipped rows (the operator may want to see their resolved
 *     state) — but fallback steps 2 and 3 filter them out.
 *   - NEVER produce a redirect loop. Step 1 (exact) short-circuits;
 *     steps 2 and 3 only resolve to actionable rows whose id != the
 *     decoded input.
 *   - NEVER lie about the source. When a fallback fires, the page
 *     returns a redirect to the canonical URL so the URL bar reflects
 *     the actually-rendered row.
 *
 * Pure / deterministic / no I/O / no React. Safe to import from server
 * and client code.
 */

import type { RecommendationActionRow } from "./recommendation-action-rows";

// ── Types ─────────────────────────────────────────────────────────────────

export type ResolveRecommendationDetailResult =
  | { kind: "exact"; row: RecommendationActionRow }
  | {
      kind: "redirect";
      row: RecommendationActionRow;
      /** Diagnostic — which ladder step produced this match. */
      via: "edit_id" | "rec_stable_key";
    }
  | {
      kind: "miss";
      /** Best-effort hints parsed from the decoded id, for the
       *  not-found component to render. All fields may be null. */
      hint: {
        stableKey: string | null;
        editId: string | null;
        actionType: string | null;
      };
    };

// ── Helpers ───────────────────────────────────────────────────────────────

/**
 * "Actionable" = the operator hasn't already resolved this row. Used
 * to gate fallback steps 2 and 3 so a missing URL never gets quietly
 * redirected at a row the operator has already moved on from.
 *
 * Note: the EXACT match path does NOT call this. If the URL resolves
 * exactly to a dismissed row, we render that row (operator may want
 * to review the resolution).
 */
function isActionable(row: RecommendationActionRow): boolean {
  if (row.status === "dismissed" || row.status === "shipped") return false;
  if (row.responseStatus === "dismissed") return false;
  return true;
}

/**
 * Split a decoded recommendation detail id into `(stableKey, tail)` on
 * the FIRST `::`. Returns `(null, null)` when no separator is present.
 *
 * The split is on the FIRST `::` because `stableKey` itself may contain
 * colons (`create_cluster_page:geo:Palo Alto`) but never a `::` —
 * stable keys are machine-generated by templating functions that never
 * double a colon. The tail (the post-`::` substring) is what the row
 * builder calls `edit.id` for shape #2 rows and `${metaKind}` for shape
 * #3 rows.
 */
function splitRouteId(decoded: string): {
  stableKey: string | null;
  tail: string | null;
} {
  const idx = decoded.indexOf("::");
  if (idx < 0) return { stableKey: null, tail: null };
  return {
    stableKey: decoded.slice(0, idx),
    tail: decoded.slice(idx + 2),
  };
}

/**
 * Extract an action_type from an `edit.id` tail. `edit.id` shape is
 * `${recId}__${actionType}__${elementKey ?? "null"}`, so the
 * action_type is the second-to-last `__`-separated segment.
 * Returns null when the tail doesn't match the shape (e.g., it's a
 * meta-kind like "review_decision" rather than an edit.id).
 */
function actionTypeFromEditId(editIdTail: string): string | null {
  const parts = editIdTail.split("__");
  if (parts.length < 3) return null;
  return parts[parts.length - 2];
}

// ── Public API ────────────────────────────────────────────────────────────

/**
 * Resolve a decoded URL id to a current row, or to a structured "miss"
 * the not-found UI can render usefully.
 *
 * Pure. Deterministic. Never mutates input.
 */
export function resolveRecommendationDetail(
  allRows: ReadonlyArray<RecommendationActionRow>,
  decodedId: string,
): ResolveRecommendationDetailResult {
  // Step 1 — exact match.
  const exact = allRows.find((r) => r.id === decodedId);
  if (exact) return { kind: "exact", row: exact };

  // Step 2 — by edit id.
  const { stableKey, tail } = splitRouteId(decodedId);
  if (tail !== null) {
    const byEdit = allRows.find(
      (r) => r.sourceEditId === tail && r.id !== decodedId && isActionable(r),
    );
    if (byEdit) {
      return { kind: "redirect", row: byEdit, via: "edit_id" };
    }
  }

  // Step 3 — by source recommendation stable key. Prefer the highest-
  // ranked (smallest rank index) actionable row for the same rec.
  if (stableKey) {
    const byRec = allRows
      .filter(
        (r) =>
          r.sourceRecommendationId === stableKey &&
          r.id !== decodedId &&
          isActionable(r),
      )
      .sort((a, b) => a.rank - b.rank);
    if (byRec.length > 0) {
      return { kind: "redirect", row: byRec[0], via: "rec_stable_key" };
    }
  }

  // Step 4 — no resolution. Surface the most actionable hint the URL
  // carries so the not-found component renders something useful.
  const actionType =
    tail && tail.includes("__") ? actionTypeFromEditId(tail) : null;
  return {
    kind: "miss",
    hint: { stableKey, editId: tail, actionType },
  };
}
