/** Draft quality gates (the customer-copy floor): every promise below is stated in its own sentence beside the case that pins it, with real prose fixtures as inputs. The four promises about `evaluateDraftQuality` went with that door on 2026-09-05: it had no production caller and its rules were measured against all 56 stored body drafts, where its 80-word band refused every one of them and every other rule it held fired on nothing. The one promise of its that was about a LIVE rule, a dated authoritative fact carrying a draft that contradicts a stale page, is kept word for word and now asks the door that really runs it. */
import { describe, it, expect } from "vitest";
import { evaluateTitleMetaQuality } from "@/domains/decision/drafts/draft-quality";
const meta = (o: Parameters<typeof evaluateTitleMetaQuality>[0]) => { const r = evaluateTitleMetaQuality(o); return [r.status, r.copyAllowed] as const; };
describe("operator correction (page is stale, dated evidence backs the draft)", () => {
  const RECIPES_ANSWER =
    "Referencepedia now lists 4500 Persian recipes in its growing collection, spanning regional dishes, holiday specialties, and everyday family meals from every corner of Iran and its many worldwide diaspora communities. Each recipe entry includes a short history of the dish alongside step by step cooking instructions contributed by home cooks and professional chefs. Readers can filter the collection by region, occasion, or main ingredient to find dishes suited to a specific holiday table or an everyday weeknight meal. New recipes are added every month as contributors submit family recipes passed down across several generations of home cooking.";
  const STALE_PAGE = "Referencepedia lists 3000 Persian recipes in its growing collection, spanning regional dishes and everyday family meals across Iran. Readers can filter the collection by region, occasion, or main ingredient.";
  it("lets a dated authoritative fact carry a draft that contradicts a stale page, and blocks the same contradiction without one", () => {
    const backed = evaluateTitleMetaQuality({ before: null, after: RECIPES_ANSWER, field: "section", pageBodyText: STALE_PAGE, authoritativeFacts: [{ source: "your site's recipe count", date: "2026-07-01", detail: "4500 recipes are currently published" }], sources: [{ domain: "britannica.com", claim: "Referencepedia's collection spans regional Persian dishes and holiday specialties", verified: true, supportingExcerpt: RECIPES_ANSWER }] });
    const bare = evaluateTitleMetaQuality({ before: null, after: RECIPES_ANSWER, field: "section", pageBodyText: STALE_PAGE });
    expect([backed.status, backed.corrections?.some((c) => c.includes("4500") && c.includes("2026-07-01")), bare.status, bare.copyAllowed, bare.corrections], "the backed draft stays ready AND carries the correction; the same number with no authoritative fact is blocked and corrects nothing").toEqual(["ready", true, "unverified_claim", false, undefined]); });});
describe("evaluateTitleMetaQuality - atomic edits", () => {
  it("passes an entity-forward rewrite, flags a new count for review, refuses one that drops the entity, and never source-gates a formatting-only edit", () => {
    expect([meta({ before: "Meet the Persian Wolf (Iranian Wolf) | Iran Animals & Wildlife", after: "Persian Wolf (Iranian Wolf): Range, Behavior, Conservation", field: "title" }), meta({ before: "Popular Iranian First and Last Names with Meanings", after: "Persian Surnames: 150+ Last Names and Meanings", field: "title" }), meta({ before: "Persian Wolf Range and Behavior", after: "Range, Behavior, and Conservation Status", field: "title", contextTokens: ["wolf"] }), meta({ before: "Persian Holidays: Explore the Traditions", after: "Persian Holidays and Traditions Explained", field: "title" })], "rec-0 Persian Wolf is ready with no source of any kind, rec-9 150+ surnames is useful but needs review, a rewrite that drops the entity is refused, and a formatting-only edit is never missing_source") .toEqual([["ready", true], ["useful_but_needs_review", true], ["relevance_rejected", false], ["ready", true]]);
    const JERSEY = "Iran national football team jersey kit history: traditionally the home kit is white and the away kit is red. Iran World Cup jersey kits are shown for 1978, 1998, 2006, 2014, 2018, and 2022.", BODY = "Iran World Cup Jerseys. 1978 kit. 1998 kit. 2006 kit. 2014 kit. 2018 kit. 2022 kit. The home kit is white and the away kit is red.";
    expect([meta({ before: null, after: JERSEY, field: "section", pageBodyText: BODY }), meta({ before: null, after: `${JERSEY} The 1930 kit was blue.`, field: "section", pageBodyText: BODY, evidenceText: "The 1930 kit was blue." }), meta({ before: null, after: JERSEY, field: "meta", pageBodyText: BODY })], "A FACT THE PAGE ITSELF CARRIES IS NOT NEW IN A BODY FIELD EITHER: the years are the page's own section headings and `before` is empty for a new section, so the live jersey answer block was held for introducing six facts it had only restated; a year the page does not carry still owes a source, and a description behaves exactly as it did").toEqual([["ready", true], ["missing_source", false], ["ready", true]]); });});
