/** Draft quality gates (the customer-copy floor): every promise below is stated in its own sentence beside the case that pins it, with real prose fixtures as inputs. */
import { describe, it, expect } from "vitest";
import { evaluateDraftQuality, evaluateTitleMetaQuality } from "@/domains/decision/drafts/draft-quality";
const NOWRUZ_ANSWER = "Nowruz Activities USA refers to community and cultural events held across the United States to observe Nowruz, the Persian New Year, each spring. Local Iranian-American associations in cities such as Los Angeles, Washington, and Houston organize Haft-Seen table displays, traditional Persian music performances, and folk dance shows during the two-week celebration window that follows the spring equinox. Families gather for shared meals, poetry readings, and craft workshops for children, while community centers coordinate a public calendar of events. Many gatherings also host a small Nowruz market selling sweets, herbs, and handmade goods from Persian vendors.";
const NOWRUZ_SOURCE = { domain: "britannica.com", verified: true as const, supportingExcerpt: NOWRUZ_ANSWER, claim: "Nowruz marks the Persian new year and is celebrated with community gatherings and Haft-Seen displays" };
const CHEETAH = "Iran's national animal is the Asiatic cheetah, a critically endangered subspecies native to the country's central plateau and its arid steppe grasslands. Conservation programs coordinated by the Department of Environment work to protect the small remaining population across a network of protected reserves and national parks, including Miandasht and Touran. Camera-trap surveys and radio-collar tracking studies help researchers estimate population trends and identify the roads and fences that fragment the cheetah's remaining range. International partners have supported captive-breeding research as a hedge against further decline, though wild recovery remains the primary conservation goal for the coming decade.";
const CHEETAH_CLAIM = "the Asiatic cheetah is Iran's national animal and is critically endangered"; const seen = (o: Parameters<typeof evaluateDraftQuality>[0]) => { const r = evaluateDraftQuality(o); return [r.status, r.copyAllowed, r.canRegenerate] as const; };
const meta = (o: Parameters<typeof evaluateTitleMetaQuality>[0]) => { const r = evaluateTitleMetaQuality(o); return [r.status, r.copyAllowed] as const; };
describe("evaluateDraftQuality - answer blocks", () => {
  /** contextTokens are the page's own words, exactly as the producer derives them. Dormant-kind evaluators (section drafts, internal-link/CRO formatting, prepared-pack dispatch) have zero production callers since the Foundation rebuild; their pins were retired 2026-07-24 with the dormant machinery. Deliberately claim-free so these isolate the LENGTH decision from J-69. */
  it("rejects a dictionary opening, a punt and a page-talking non-answer, holds an unsourced fact until its source arrives, and never source-gates claim-free copy", () => {
    expect([seen({ contextTokens: ["nowruz"], answer: "A gift is a voluntarily transferred item, service, or gesture given without payment or legally required compensation. Gifts can be tangible or intangible and are exchanged in social, cultural, ceremonial, or commercial contexts. Legal, tax, and ethical considerations can affect gift giving." }), seen({ answer: NOWRUZ_ANSWER, sources: [NOWRUZ_SOURCE] }), seen({ answer: "The most-followed Iranian on Instagram changes over time; follower counts and rankings vary. For an accurate answer, check the individual profiles or consult up-to-date social-media analytics sites." }).slice(0, 2), seen({ answer: "The Referencepedia page summarizes reported designs, colors, and symbolic elements attributed to those banners. The team has documented this topic and cites wrmea.org as a source; consult that citation for details on Persian Empire flags and their history over time." }).slice(0, 2), seen({ answer: CHEETAH, evidenceRefs: 0 }), seen({ answer: CHEETAH, evidenceRefs: 0, sources: [{ domain: "britannica.com", claim: CHEETAH_CLAIM, verified: true, supportingExcerpt: CHEETAH }] }).slice(0, 2), evaluateDraftQuality({ answer: "" }).status, evaluateDraftQuality({ answer: null }).status, seen({ contextTokens: ["your first visit"], answer: "Plan ahead for your first visit by choosing your route, packing lightly, and leaving early so the trip goes smoothly from the moment you leave home until the moment you arrive back again. Give yourself extra time at the entrance during busy weekends, and check ahead for any schedule changes before you go so your plans do not need to change once you arrive at the gate with everyone ready to head inside together, and remember to bring comfortable shoes." }).slice(0, 2)], "ab-1 gifts is generic, ab-2 Nowruz USA is a contextual definitional opener, ab-5 punt and rec-5/rec-12 meta talk about the page, ab-9 cheetah (J-69) is held unsourced and never regeneratable, the same claim is ready once an authoritative source is attached, an empty answer is malformed, and a claim-free formatting draft with zero sources is never source-gated") .toEqual([["generic_rejected", false, true], ["ready", true, false], ["too_thin", false], ["too_thin", false], ["missing_source", false, false], ["ready", true], "malformed", "malformed", ["ready", true]]); });});
describe("evaluateDraftQuality - G5 needs_source_check (honest unfetchable-source hold)", () => {
  it("holds an authority-strong citation nobody could read, grants no trust for a block, and still requires verified coverage before ready", () => {
    const blocked = evaluateDraftQuality({ answer: CHEETAH, evidenceRefs: 0, sources: [{ url: "https://www.britannica.com/animal/asiatic-cheetah", domain: "britannica.com", verified: false, fetchBlocked: true, claim: CHEETAH_CLAIM }] });
    expect([[blocked.status, blocked.copyAllowed, blocked.canRegenerate], blocked.reasons[0], seen({ answer: CHEETAH, sources: [{ domain: "britannica.com", claim: "the Asiatic cheetah is Iran's national animal", verified: false, fetchBlocked: true }] }).slice(0, 2), evaluateDraftQuality({ answer: CHEETAH, sources: [{ domain: "some-blog.example", claim: "the Asiatic cheetah is Iran's national animal", verified: false, fetchBlocked: true }] }).status, seen({ answer: CHEETAH, authoritativeSourceDomains: ["heritage-encyclopedia.example"], sources: [{ domain: "britannica.com", claim: "blocked one", verified: false, fetchBlocked: true }, { domain: "heritage-encyclopedia.example", verified: true, supportingExcerpt: CHEETAH, claim: CHEETAH_CLAIM }] }).slice(0, 2)], "a robots-blocked authority is needs_source_check rather than missing_source and names the domain it could not read, a blocked authority alone is NEVER ready, a block on a non-authoritative domain is still plain missing_source, and a verified covering source wins even beside a blocked one") .toEqual([["needs_source_check", false, false], "I could not read britannica.com myself (it blocks robots). Check this citation before you paste.", ["needs_source_check", false], "missing_source", ["ready", true]]); });});
describe("evaluateDraftQuality - J-71 word band, quotability, and factual entailment (N8)", () => {
  const BASE =
    "Nowruz begins each year on the March equinox and marks the start of the Persian calendar new year across Iran, Afghanistan, and many neighboring countries. Families spend the final days before the holiday cleaning their homes from top to bottom, a custom known as khouneh tekouni, and setting a haft-seen table with seven symbolic items that each start with the Persian letter sin. Relatives visit each other's homes across the full two-week holiday, starting with the oldest members of the family first, and children receive small gifts of money tucked inside books or handed over directly by grandparents and uncles. Markets fill with fresh greens, painted eggs, goldfish, and pastries such as baklava and nan-e nokhodchi in the weeks leading up to the holiday, and many cities in Iran and across the Persian diaspora host public concerts, poetry readings, and craft fairs timed to the same two-week celebration window that closes with a picnic on the thirteenth day known as Sizdah Bedar.";
  const THREE_THOUSAND =
    "Nowruz has been celebrated in Iran for more than 3000 years, marking the arrival of spring with family gatherings, music, poetry readings, and shared meals across the region every March. It runs for nearly two weeks, and most families travel to visit relatives during that stretch, starting with grandparents first. The custom of a deep clean happens beforehand, and a table is set with seven symbolic items that each start with the same letter. The celebration closes with a shared picnic on the thirteenth day, out in the open air with the whole family together.";
  const words = (n: number): string => { const w = BASE.trim().split(/\s+/).slice(0, n).join(" "); return /[.!?]$/.test(w) ? w : `${w}.`; };
  it("holds the 80 to 150 word band from both sides, and a draft over it is trimmed rather than rewritten", () => {
    const under = evaluateDraftQuality({ answer: words(79) }), over = evaluateDraftQuality({ answer: words(151) });
    expect([under.status, under.reasons[0]?.includes("80-150"), evaluateDraftQuality({ answer: words(80) }).status, evaluateDraftQuality({ answer: words(150) }).status, over.status, over.canRegenerate], "79 words is too thin and says the band, 80 clears the floor, 150 is still ready, and 151 is not quotable and may be asked again").toEqual(["too_thin", true, "ready", "ready", "not_quotable", true]); });
  it("refuses copy that never names its subject or carries a number the page cannot support, and passes clean sourced copy with no figure at all", () => {
    const pronoun = evaluateDraftQuality({ sources: [NOWRUZ_SOURCE], answer: "It is a traditional Persian celebration held every year in the spring across Iran and neighboring countries, marked by family gatherings, music, and shared meals that continue for nearly two weeks each season. Extended families travel long distances to reunite for the occasion, often visiting several relatives' homes across a single week. Children receive small gifts of money from older relatives, and homes are cleaned and decorated well before the celebration begins. Markets fill with fresh herbs, pastries, and goldfish sold specifically for the holiday table, and many cities host public concerts and craft fairs timed to the same two-week window." });
    const unsupported = evaluateDraftQuality({ answer: THREE_THOUSAND, evidenceRefs: 1, pageBodyText: "Nowruz is the Persian new year, celebrated in Iran with family gatherings, music, poetry readings, and shared meals marking the arrival of spring every March. The holiday runs for nearly two weeks with visits to relatives and closes with a picnic on the thirteenth day." });
    expect([pronoun.status, pronoun.reasons.some((x) => x.toLowerCase().includes("name the subject")), evaluateDraftQuality({ answer: NOWRUZ_ANSWER, sources: [NOWRUZ_SOURCE] }).status, [unsupported.status, unsupported.copyAllowed], unsupported.reasons[0]?.includes("3000"), unsupported.reasons[0]?.includes("that number is not on your page"), evaluateDraftQuality({ answer: THREE_THOUSAND, evidenceRefs: 1, pageBodyText: "Nowruz is a 3000 year old Persian tradition celebrated in Iran, marking the arrival of spring every March with family gatherings, music, and poetry readings. The holiday runs for nearly two weeks and closes with a picnic on the thirteenth day.", sources: [{ domain: "britannica.com", claim: "Nowruz has been celebrated in Iran for more than 3000 years", verified: true, supportingExcerpt: "Nowruz has been celebrated in Iran for more than 3000 years, marking the arrival of spring with family gatherings, music, poetry readings, and shared meals across the region every March." }] }).status, meta({ before: "Persian New Year Traditions", after: "Persian New Year: 3000 Years of Nowruz Traditions in Iran", field: "title", pageBodyText: "Nowruz is the Persian new year, celebrated across Iran every spring." })], "an opening pronoun is not quotable and says so, a clean sourced draft with no number or date is ready, a number the page body does not carry is refused by name, the same claim passes once the body supports it, and an atomic rewrite that introduces one is refused too") .toEqual(["not_quotable", true, "ready", ["unverified_claim", false], true, true, "ready", ["unverified_claim", false]]); });});
describe("operator correction (page is stale, dated evidence backs the draft)", () => {
  const RECIPES_ANSWER =
    "Referencepedia now lists 4500 Persian recipes in its growing collection, spanning regional dishes, holiday specialties, and everyday family meals from every corner of Iran and its many worldwide diaspora communities. Each recipe entry includes a short history of the dish alongside step by step cooking instructions contributed by home cooks and professional chefs. Readers can filter the collection by region, occasion, or main ingredient to find dishes suited to a specific holiday table or an everyday weeknight meal. New recipes are added every month as contributors submit family recipes passed down across several generations of home cooking.";
  const STALE_PAGE = "Referencepedia lists 3000 Persian recipes in its growing collection, spanning regional dishes and everyday family meals across Iran. Readers can filter the collection by region, occasion, or main ingredient.";
  it("lets a dated authoritative fact carry a draft that contradicts a stale page, and blocks the same contradiction without one", () => {
    const backed = evaluateDraftQuality({ answer: RECIPES_ANSWER, evidenceRefs: 1, pageBodyText: STALE_PAGE, authoritativeFacts: [{ source: "your site's recipe count", date: "2026-07-01", detail: "4500 recipes are currently published" }], sources: [{ domain: "britannica.com", claim: "Referencepedia's collection spans regional Persian dishes and holiday specialties", verified: true, supportingExcerpt: RECIPES_ANSWER }] });
    const bare = evaluateDraftQuality({ answer: RECIPES_ANSWER, evidenceRefs: 1, pageBodyText: STALE_PAGE });
    expect([backed.status, backed.corrections?.some((c) => c.includes("4500") && c.includes("2026-07-01")), bare.status, bare.copyAllowed, bare.corrections], "the backed draft stays ready AND carries the correction; the same number with no authoritative fact is blocked and corrects nothing").toEqual(["ready", true, "unverified_claim", false, undefined]); });});
describe("evaluateTitleMetaQuality - atomic edits", () => {
  it("passes an entity-forward rewrite, flags a new count for review, refuses one that drops the entity, and never source-gates a formatting-only edit", () => {
    expect([meta({ before: "Meet the Persian Wolf (Iranian Wolf) | Iran Animals & Wildlife", after: "Persian Wolf (Iranian Wolf): Range, Behavior, Conservation", field: "title" }), meta({ before: "Popular Iranian First and Last Names with Meanings", after: "Persian Surnames: 150+ Last Names and Meanings", field: "title" }), meta({ before: "Persian Wolf Range and Behavior", after: "Range, Behavior, and Conservation Status", field: "title", contextTokens: ["wolf"] }), meta({ before: "Persian Holidays: Explore the Traditions", after: "Persian Holidays and Traditions Explained", field: "title" })], "rec-0 Persian Wolf is ready with no source of any kind, rec-9 150+ surnames is useful but needs review, a rewrite that drops the entity is refused, and a formatting-only edit is never missing_source") .toEqual([["ready", true], ["useful_but_needs_review", true], ["relevance_rejected", false], ["ready", true]]);
    const JERSEY = "Iran national football team jersey kit history: traditionally the home kit is white and the away kit is red. Iran World Cup jersey kits are shown for 1978, 1998, 2006, 2014, 2018, and 2022.", BODY = "Iran World Cup Jerseys. 1978 kit. 1998 kit. 2006 kit. 2014 kit. 2018 kit. 2022 kit. The home kit is white and the away kit is red.";
    expect([meta({ before: null, after: JERSEY, field: "section", pageBodyText: BODY }), meta({ before: null, after: `${JERSEY} The 1930 kit was blue.`, field: "section", pageBodyText: BODY, evidenceText: "The 1930 kit was blue." }), meta({ before: null, after: JERSEY, field: "meta", pageBodyText: BODY })], "A FACT THE PAGE ITSELF CARRIES IS NOT NEW IN A BODY FIELD EITHER: the years are the page's own section headings and `before` is empty for a new section, so the live jersey answer block was held for introducing six facts it had only restated; a year the page does not carry still owes a source, and a description behaves exactly as it did").toEqual([["ready", true], ["missing_source", false], ["ready", true]]); });});
