import { describe, it, expect, vi, beforeEach } from "vitest";
import { renderToStaticMarkup } from "react-dom/server"; import { createRoot } from "react-dom/client"; import { act, createElement, type ReactElement } from "react"; import { createRequire } from "node:module";
import type { ChangeProposal } from "@/domains/decision";
import { confirmedVersion as versionOf } from "@/domains/decision/completeness";
import { actionableProposalFailures as failures } from "@/domains/decision/validate-proposal";
import type { ChangesView } from "@/app/(shell)/changes-data"; import ChangeDetailPage from "@/app/(shell)/changes/[id]/page";
vi.mock("next/cache", () => ({ revalidatePath: vi.fn() }));
vi.mock("next/navigation", () => { const redirected = (u: string) => { throw new Error(`NEXT_REDIRECT:${u}`); };
  return { redirect: redirected, permanentRedirect: redirected, notFound: () => { throw new Error("NEXT_NOT_FOUND"); },
    usePathname: () => "/changes", useRouter: () => ({ refresh: surfaceCalls.refresh, push: vi.fn() }), useSearchParams: () => new URLSearchParams() }; });
vi.mock("@/domains/account/lifecycle", () => ({ requireReadyAccount: vi.fn(async () => ({ access: { kind: "ready", account: { status: "active" } } })),
  resolveAccountAccess: vi.fn(async () => ({ kind: "ready", account: { status: "active" } })), AccountUnavailableError: class extends Error {} }));
vi.mock("@/lib/tenant-context", async () => ({ ...(await vi.importActual<typeof import("@/lib/tenant-context")>("@/lib/tenant-context")),
  currentTenantId: vi.fn(async () => "t") }));
const meta = vi.hoisted(() => ({ load: vi.fn(), produce: vi.fn(), current: vi.fn() }));
vi.mock("@/domains/decision", async () => { const loadChangeProposal = meta.load; return { ...(await vi.importActual<typeof import("@/domains/decision")>("@/domains/decision")),
  loadChangeProposal, implementationGuard: async (t: string, id: string, v: string) => { const p = await loadChangeProposal(t, id) as ChangeProposal | null;
    return p?.tenantId === t && p.id === id && versionOf(p) === v ? { proposal: p, rowVersion: 1, payload: p } : null; },
  resolveCurrentBasis: meta.current, produceProposalsForTenant: meta.produce, saveChangeProposal: vi.fn(async () => "saved"), answerReviewedProposal: vi.fn(async () => ({ status: "promoted" as const })) }; });
vi.mock("@/app/(shell)/changes-data", async () => ({ ...(await vi.importActual<typeof import("@/app/(shell)/changes-data")>("@/app/(shell)/changes-data")),
  loadChangesView: vi.fn() }));
const publish = vi.hoisted(() => ({ allowed: true, paused: true }));
vi.mock("@/lib/auth/can-publish", () => ({ canPublishForCurrentTenant: async () => publish.allowed }));
const shipped = vi.hoisted(() => ({ records: [] as unknown[], held: [] as any[] }));
const surfaceCalls = vi.hoisted(() => ({ n: 0, refresh: vi.fn() }));
const { proofRun, prepareRun, nextRun } = vi.hoisted(() => ({ proofRun: vi.fn(), prepareRun: vi.fn(), nextRun: vi.fn() }));
vi.mock("@/domains/runtime", async () => { const real = await vi.importActual<typeof import("@/domains/runtime")>("@/domains/runtime"); return { ...real, researchPermission: async () => publish.paused ? "paused" : "running", atomicProof: { ...real.atomicProof, run: proofRun, finishPage: prepareRun, prepareNext: nextRun,
  currentMetaSuccessor: (tenant: string, id: string, basis: string | null) => real.atomicProof.currentMetaSuccessor(tenant, id, basis, { load: meta.load, produce: meta.produce, current: meta.current, permission: async () => publish.paused ? "paused" : "running" }) } }; });
vi.mock("@/domains/measurement", async () => ({ ...(await vi.importActual<typeof import("@/domains/measurement")>("@/domains/measurement")),
  loadShippedChanges: async () => shipped.held, captureChangeMeta: async () => null, loadProofLedgerPersisted: async () => shipped.held,
  recordShipment: async (r: unknown, opts?: { proposal?: { complete: boolean } }) => { const f = r as { proposalId: string; proposalVersion: string };
    const held = shipped.held.find((x) => x.proposalId === f.proposalId && x.proposalVersion === f.proposalVersion); // the REAL door's idempotency, mirrored: same proposal and version answers the row already on file and writes nothing
    if (held) return { shipmentId: held.id, measurement: held.measurementState ?? "measuring", proposalImplemented: opts?.proposal?.complete === true };
    shipped.records.push(r); return { shipmentId: "rec-1", measurement: "measuring", proposalImplemented: opts?.proposal?.complete === true }; } }));
const captures = (tenantId: string, url: string): NonNullable<ChangeProposal["reviewedCaptures"]> => [{ tenantId, url, pageId: `page-${new URL(url).pathname}`, captureId: `snap-${new URL(url).pathname}-1`, latestCaptureId: `snap-${new URL(url).pathname}-1`, captureVersion: 1, sourceRevision: "0123456789abcdef" }];
const NOW = "basis_now::d4", AUTH = "4b926534-2d8f-4ad8-a84b-15137b8aa007", EXACT = "Iranian Comedians: the 12 names people actually search for";
const ID = "t::/famous-iranian-comedians::existing_edit::bundle";
const SEEN = new Date(Date.now() - 2 * 86_400_000).toISOString();
const bundled = (basis: string, id = ID): ChangeProposal => ({
  id, tenantId: "t", kind: "existing_edit", pagePath: "/famous-iranian-comedians", pageUrl: "https://site.example/famous-iranian-comedians", reviewedCaptures: captures("t", "https://site.example/famous-iranian-comedians"), pageLabel: "Famous Iranian comedians", primaryQuery: "iranian comedians",
  whyItMatters: "This page lost 163 clicks last month.", opportunityType: "Answer the exact search", estimatedEffortMinutes: 6, upsidePerMonth: 163,
  confidence: "high", riskLevel: "low", status: "ready", basis, limitations: [], changeFamily: "title", createdAt: SEEN,
  modeledOn: "the stored results page for this search, whose top titles share this shape", recommendedChange: { kind: "existing_edit", field: "title", before: "Comedians", after: EXACT },
  bundle: { objective: "Answer the exact question people search", metric: "clicks from that search", measurementPlan: "I compare the next 28 days with the last 28.",
    scope: { queries: ["iranian comedians"], prompts: [] }, confidenceReasons: ["163 clicks lost in 4 weeks"], alternatives: [], risks: [],
    components: [{ kind: "title", label: "Title", risk: "safe", before: "Comedians", after: EXACT, evidenceKeys: ["k1"] }],
    receipt: { items: [{ key: "k1", kind: "gsc_demand", fact: "163 clicks lost in 4 weeks.", observedAt: SEEN }], missing: [], freshestObservedAt: SEEN } },
} as unknown as ChangeProposal);
const emptyView = (demotedStaleBasis: number): ChangesView => ({ proposals: [], ready: [], toDo: [], research: [], aiCases: { state: "read" as const, rows: [] },
  summary: { todo: 0, ready: 0, research: 0, implemented: 0, measuring: 0, results: 0 }, measuringCountCanonical: 0, demotedStaleBasis, decidedCountCanonical: 0,
  readyZeroHint: null, receiptLine: null, surfaceComputedAt: "2026-07-27T00:00:00.000Z", surfaceBuilding: false });
const renderDetail = async (): Promise<string> => renderToStaticMarkup(await ChangeDetailPage({ params: Promise.resolve({ id: encodeURIComponent(ID) }) }) as ReactElement);
async function renderChanges(view: ChangesView): Promise<string> {
  vi.mocked((await import("@/app/(shell)/changes-data")).loadChangesView).mockResolvedValue(view);
  return renderToStaticMarkup(await (await import("@/app/(shell)/changes/page")).ChangesSection() as ReactElement);}
describe("a direct link renders only what the ranked list would, and always lands somewhere honest", () => {
  beforeEach(() => vi.clearAllMocks());
  async function link(p: ChangeProposal | null, retired: ChangeProposal | null = null, reason: string | null = null, successor: ChangeProposal | Error | null = null): Promise<string> {
    const { loadChangeProposal, resolveCurrentBasis } = await import("@/domains/decision"); vi.mocked(resolveCurrentBasis).mockResolvedValue(NOW);
    vi.mocked(loadChangeProposal).mockImplementation(async (_t, id, o) => {
      o?.canonicalRow?.({ proposal_version: id === ID ? 24 : 25, terminal_disposition: id === ID && retired ? successor ? "superseded" : "withdrawn" : null, withdrawn_reason: reason, superseded_by: id === ID && reason && successor ? "t::replacement" : null });
      return id !== ID ? successor instanceof Error ? Promise.reject(successor) : successor : o?.retired === "include" ? retired ?? p : p;
    }); return renderDetail();}
  it("hands over the exact edits for current work, and no copy at all for a change whose own receipt does not resolve", async () => {
    const live = await link(bundled(NOW)); // the row IS the current bar's work
    expect([live.includes(EXACT), live.includes("Mark done"), live.includes("This idea was set aside")]).toEqual([true, true, false]); const current = { ...bundled(NOW), status: "needs_review", bundle: undefined, reviewedCaptures: undefined, obligation: { kind: "review" }, rankingReceipt: { factors: [{ name: "readiness", input: "These words were faulted here, so a corrective draft is owed" }] } } as unknown as ChangeProposal, held = await link(current), refused = await link({ ...current, faults: ["it answers a different reader task"], obligation: { kind: "redraft", attempt: 1, instruction: "Answer the assigned comparison" } }); expect([held.includes("Beacon will review the finished copy and its sources."), held.match(/data-held-reason="true"[^>]*>(.*?)<\/p>/)?.[1]?.includes("corrective draft is owed") === true, held.includes("Mark done"), held.includes("Prepare best edit on this page"), refused.includes("Beacon will revise the saved copy: it answers a different reader task")]).toEqual([true, false, false, true, true]);
    const obsolete = { ...bundled(NOW), bundle: undefined, status: "needs_review", recommendedChange: { kind: "existing_edit", field: "meta", before: "Old description", after: "Draft" }, obligation: { kind: "terminal", reason: "The current meta description differs from the exact line this edit would replace; requalify the current page." } } as ChangeProposal;
    expect((await link(obsolete)).includes("Prepare best edit on this page")).toBe(true);
    expect((await link({ ...obsolete, obligation: { kind: "terminal", reason: "Different terminal cause" } } as ChangeProposal)).includes("Prepare best edit on this page")).toBe(false);
    const historical = { ...bundled(NOW), status: "needs_review" } as ChangeProposal, reason = "Withdrawn: the authoritative quotes do not carry every word of the proposal, so part of the wording stands only on an ordinary source.";
    const archived = await link(null, historical, reason); expect([archived.includes(reason), archived.includes("Archived version 24"), archived.includes(EXACT), archived.includes("data-archived-copy"), archived.includes("data-successor")]).toEqual([true, true, true, true, false]); expect(archived).not.toMatch(/data-copy-after|data-finish-one=|data-set-aside=|Mark done/);
    for (const replacement of [bundled(NOW, "t::replacement"), { ...bundled(NOW, "t::replacement"), status: "needs_review" }, { ...bundled(NOW, "t::replacement"), tenantId: "foreign" }, bundled("old", "t::replacement"), { ...bundled(NOW, "t::replacement"), reviewedCaptures: undefined }, null, new Error("unreadable")]) {
      const html = await link(null, historical, reason, replacement as ChangeProposal | Error | null); expect(html.includes("data-successor")).toBe(replacement != null && !(replacement instanceof Error) && replacement.status === "ready" && replacement.tenantId === "t" && replacement.basis === NOW && !!replacement.reviewedCaptures); }
    expect((await link(null, { ...historical, tenantId: "foreign" }, reason)).includes("data-archived-copy")).toBe(false);
    const older = await link(bundled("basis_old::d2")); expect([older.includes(EXACT), older.includes("This idea was set aside")], "copy drafted under rules that no longer stand is history, never an actionable handoff").toEqual([false, true]); const broken = bundled(NOW); const stale = await link({ ...broken, bundle: { ...broken.bundle!, components: [{ ...broken.bundle!.components[0]!, evidenceKeys: ["nothing-holds-this"] }] } } as ChangeProposal); expect([stale.includes("This idea was set aside"), stale.includes("See the work that stands now")]).toEqual([true, true]); expect(stale).not.toMatch(new RegExp(`${EXACT}|Comedians</p>|Mark done`)); });
  it("refuses a merge filed as ready at the direct link, while a dated reading is handed over with its date", async () => {
    const b = bundled(NOW).bundle!, cold = new Date(Date.now() - 120 * 86_400_000).toISOString();
    const bundle = { ...b, components: [{ ...b.components[0]!, kind: "consolidation", label: "Merge the two pages", risk: "dangerous" }] };
    const html = await link({ ...bundled(NOW), bundle } as ChangeProposal); expect([html.includes(EXACT), html.includes("Mark done")], JSON.stringify(bundle.components[0])).toEqual([false, false]);
    const dated = await link({ ...bundled(NOW), bundle: { ...b, receipt: { items: [{ ...b.receipt.items[0]!, observedAt: cold }], missing: [], freshestObservedAt: cold } } } as ChangeProposal); expect([dated.includes(EXACT), dated.includes("Mark done")], "REPLACES the cold-evidence refusal: the exact work is handed over and the date its readings carry is a caveat on the card").toEqual([true, true]); });
  it("opens the picker on the pieces nobody has recorded yet", async () => {
    const b = bundled(NOW).bundle!;
    shipped.held = [{ proposalId: ID, page: "https://site.example/famous-iranian-comedians", componentsApplied: [{ id: "0:title", ...b.components[0] }] }];
    const html = await link({ ...bundled(NOW), bundle: { ...b, components: [b.components[0]!, { ...b.components[0]!, kind: "meta", label: "Description", after: "Twelve comedians span stand-up, television and film, with their best-known performances." }] } } as ChangeProposal); const boxes = [...html.matchAll(/<input type="checkbox"[^>]*>/g)].map((m) => m[0]); shipped.held = []; expect([boxes.length, boxes[0]!.includes("disabled"), boxes.some((x) => x.includes("checked")), html.includes("already recorded")]).toEqual([2, true, false, true]); });
  it("expires no change for the age of its readings, and refuses the one whose piece cites evidence the receipt never carried", () => {
    const cold = new Date(Date.now() - 40 * 86_400_000).toISOString(), ctx = { tenantId: "t", currentBasis: NOW }, b = bundled(NOW).bundle!, item = b.receipt.items[0]!;
    const { bundle: _b, ...atomic } = bundled(NOW), undated = { ...bundled(NOW), createdAt: cold, bundle: { ...b, receipt: { items: [{ ...item, observedAt: null }], missing: [], freshestObservedAt: null } } } as ChangeProposal;
    const unresolved = { ...bundled(NOW), bundle: { ...b, components: [{ ...b.components[0]!, evidenceKeys: ["nothing-holds-this"] }] } } as ChangeProposal;
    expect([failures(bundled(NOW), ctx).length, failures({ ...atomic, createdAt: cold } as ChangeProposal, ctx).length, failures(undated, ctx).length, failures(unresolved, ctx).length > 0], "REPLACES the thirty day freshness window (owner's editorial policy, 2026-09-06): an atomic row drafted forty days ago and a receipt with no date on it are both work, and the card names the date; a piece pointing at evidence the receipt never carried is still a defect that holds it").toEqual([0, 0, 0, true]); });
  it("refuses a receipt that no longer resolves, and holds a page-mover until the operator confirms it here", async () => {
    shipped.records = [];
    const b = bundled(NOW).bundle!; const mark = async (p: ChangeProposal, args: Record<string, unknown> = {}) => { await link(p); return (await import("@/app/(shell)/changes/actions")).markProposalImplementedAction({ proposalId: p.id, expectedVersion: versionOf(p), ...args }); }; const broken = { ...bundled(NOW), bundle: { ...b, components: [{ ...b.components[0]!, evidenceKeys: ["nothing-holds-this"] }] } } as ChangeProposal; expect([(await mark(broken)).success, shipped.records.length]).toEqual([false, 0]);
    const merge = { ...bundled(NOW), status: "needs_review", riskLevel: "high", bundle: { ...b, risks: ["The old address stops answering."], components: [{ ...b.components[0]!, kind: "consolidation", label: "Merge the two pages", risk: "dangerous", redirectTo: "https://site.example/keep" }] } } as unknown as ChangeProposal;
    const refused = await mark(merge); expect([refused.success, refused.error?.includes("still being reviewed"), shipped.records.length]).toEqual([false, true, 0]); expect([(await mark(merge, { destructiveConfirmed: true })).success, shipped.records.length]).toEqual([false, 0]);
    const { confirmDangerousChangeAction: confirm } = await import("@/app/(shell)/changes/actions"), { confirmedVersion, answerReviewedProposal: promote } = await import("@/domains/decision");
    const safe = { ...merge, bundle: { ...merge.bundle!, components: [b.components[0]!] } } as ChangeProposal;
    await link(merge); const html = await renderDetail(), stale = await confirm({ proposalId: merge.id, version: "a version nobody is looking at" });
    await link(safe); const wrong = await confirm({ proposalId: safe.id, version: confirmedVersion(safe) });
    await link(merge); const ok = await confirm({ proposalId: merge.id, version: confirmedVersion(merge) }), sent = vi.mocked(promote).mock.calls.at(-1);
    expect([html.includes("Confirm this version"), html.includes("Mark done"), stale.success, stale.error?.includes("rewritten since"), wrong.success, wrong.error?.includes("does not move or hide a page"), ok.success, vi.mocked(promote).mock.calls.length, sent?.[1], sent?.[2] === confirmedVersion(merge)]).toEqual([true, false, false, true, false, true, true, 1, merge.id, true]); });
  it("refuses a hand-made Mark done request for an incomplete whole-page replacement", async () => { shipped.records = []; const b = bundled(NOW).bundle!, whole = { ...bundled(NOW), changeFamily: "full_rewrite", bundle: { ...b, components: [{ ...b.components[0]!, kind: "full_rewrite", target: { mode: "whole_body", anchorKind: null, anchor: null } }] } } as ChangeProposal;
    await link(whole); const result = await (await import("@/app/(shell)/changes/actions")).markProposalImplementedAction({ proposalId: whole.id, expectedVersion: versionOf(whole) }); expect([result.success, result.error?.includes("not a complete publication"), shipped.records.length]).toEqual([false, true, 0]); }); });
describe("an account that skipped the connectors still reaches its own Today", () => {
  it("calls an account a demo only when it truly holds nothing, never merely because it connected nothing", async () => {
    const gate = async (repo: () => unknown) => {
      vi.resetModules();
      vi.doMock("@/lib/seed-data.server", () => ({ hasActiveExperiment: async () => false }));
      vi.doMock("@/lib/connector-store", () => ({ hasAnyConnectedDataSource: async () => false }));
      vi.doMock("@/lib/persistence/repositories", () => ({ getRepository: repo }));
      return (await import("@/app/(shell)/today-gate-data")).loadTodayV2GateData();};
    const held = (tracked: unknown[]) => () => ({ forTenant: () => ({ getPromptAnswerObservations: async () => [], getTrackedPrompts: async () => tracked }) }); expect([(await gate(held([{ is_active: true, tags: ["core_v1"] }]))).isDemoMode, (await gate(held([]))).isDemoMode]).toEqual([false, true]);
    const blind = await gate(() => { throw new Error("database unreachable"); }); // A read I could not take is not proof the account is empty, so it may not send them to the connect prompt.
    expect([blind.isDemoMode, blind.unreadable]).toEqual([false, true]);
    for (const m of ["@/lib/seed-data.server", "@/lib/connector-store", "@/lib/persistence/repositories"]) vi.doUnmock(m);
    vi.resetModules(); }); });
describe("an empty Changes queue reads as a decision, not an empty screen", () => {
  beforeEach(() => vi.clearAllMocks());
  it("shows every open opportunity with zero ready, never calls a draft finished, and counts the same on both screens", async () => {
    const { buildTodayViewFromChanges } = await import("@/app/(shell)/today-view-data"); const draft = { ...bundled(NOW, "t::draft"), status: "needs_review" } as ChangeProposal;
    const missing = 'The results page for "iranian comedians" has not been read, and that read is what turns this into exact work.';
    const idea = { ...bundled(NOW, "t::idea"), status: "needs_review", researchOnly: true, bundle: undefined, opportunityType: "Find out what took the clicks from /famous-iranian-comedians",
      operatorSteps: [missing, "The exact change lands on this card once that read is on file"], recommendedChange: { kind: "existing_edit", field: "section", before: null, after: missing },
      research: { missing, next: "The exact change lands on this card once that read is on file" } } as unknown as ChangeProposal;
    const view = { ...emptyView(0), proposals: [draft, idea], ready: [], toDo: [draft], research: [idea], summary: { ...emptyView(0).summary, todo: 1, research: 1 } }; const html = await renderChanges(view), today = buildTodayViewFromChanges(view);
    expect(html).toContain("1 change needs more work before it is ready to apply, and 1 opportunity does not yet have a finished change."); expect(html).toMatch(/Scheduled research is paused[^<]*individual saved change/); // Outstanding counts never claim that paused work is running.
    for (const never of ["Copy draft", "Why it is held", "Needs your review", "Beacon must improve", "Written and being checked", "What you are deciding", "waiting on the final review", EXACT]) expect(html).not.toContain(never);
    expect(html).not.toMatch(/Proven|Mark done|Still missing/);
    expect([today.readyTotal, today.nextOpportunities, today.topEdit, today.headerSentence, today.preparing]).toEqual([0, [], undefined, "No finished change is ready today. When Beacon finishes a change, it appears here.", { written: 1, researching: 1 }]); // Today previews finished work alone and carries the same two counts
    expect(html.match(/data-change-card="true"/g) ?? []).toHaveLength(0); }); // no unfinished work wears a card
  it("takes a yes on judgement alone and refuses one on a fact about the work", async () => {
    const { reviewDraftAction } = await import("@/app/(shell)/changes/actions"), { confirmedVersion, loadChangeProposal, resolveCurrentBasis } = await import("@/domains/decision");
    const link = async (p: ChangeProposal) => { vi.mocked(resolveCurrentBasis).mockResolvedValue(NOW); vi.mocked(loadChangeProposal).mockResolvedValue(p); }; const soft = { ...bundled(NOW, "t::draft"), status: "needs_review" } as ChangeProposal;
    const hard = { ...soft, faults: ["no serious editor would hand this to a customer"] } as ChangeProposal; // a DEFECT of the one verdict (narration), never the old split sentence: a split settled on only some of its pages is the owner's call under the editorial policy of 2026-09-06 and rides the card as a caveat
    await link(soft); const yes = await reviewDraftAction({ proposalId: soft.id, version: confirmedVersion(soft), decision: "approve" });
    await link(hard); const no = await reviewDraftAction({ proposalId: hard.id, version: confirmedVersion(hard), decision: "approve" });
    await link(soft); const better = await reviewDraftAction({ proposalId: soft.id, version: confirmedVersion(soft), decision: "improve" }); const { answerReviewedProposal: answer } = await import("@/domains/decision");
    expect([yes.success, no.success, no.error?.includes("hand this to a customer"), better.success, vi.mocked(answer).mock.calls.map((c) => (c[4] as { kind: string }).kind)]) .toEqual([true, false, true, true, ["promote", "redraft"]]); });
  it.each([false, true])("keeps selected finishing separate from explicit global preparation (%s)", async (next) => {
    const wire = next ? nextRun : proofRun; wire.mockResolvedValueOnce(next ? { success: true, reason: "ready_saved", readySaved: 1, run: { id: "t:run", status: "paused", progress: {} }, meter: { modelCalls: 2, modelReservedUsd: 0.04, externalCalls: 1, externalReservedUsd: 0.05 }, accountedUsd: 0.004748 } : { success: true, reason: "stored_ready_substantive_and_complete", meter: { providerCalls: 1, costUsd: 0.004748 } });
    const { finishOneProposalAction } = await import("@/app/(shell)/changes/actions"), { SetAsideChange } = await import("@/app/(shell)/changes/change-controls");
    const args = next ? { prepareNext: true as const } : { proposalId: ID }; vi.mocked((await import("@/domains/decision")).resolveCurrentBasis).mockResolvedValue(NOW); const out = await finishOneProposalAction(args);
    expect(wire).toHaveBeenCalledWith(next ? { tenantId: "t", currentBasis: NOW, eligible: (await import("@/app/(shell)/changes/types")).default.isManualEditProofWork } : { tenantId: "t", proposalId: ID, currentBasis: NOW, maxOpenAiCalls: 1, maxOpenAiUsd: 0.05 });
    expect([out.success, next ? out.modelRequests : out.providerCalls, next ? out.reservedUsd : out.costUsd, Object.keys(out).includes("stored"), out.note?.includes("$0.004748"), next ? out.providerCalls === undefined && out.run?.id === "t:run" && out.sourceRequests === 1 && out.sourceReservedUsd === 0.05 : true]).toEqual([true, next ? 2 : 1, next ? 0.09 : 0.004748, false, true, true]);
    if (next) { wire.mockResolvedValueOnce({ success: false, reason: "partial_saved", readySaved: 0, run: { id: "t:run", status: "paused", progress: { evidenceOwed: [{ kind: "factual_source" }] } }, meter: { modelCalls: 1, modelReservedUsd: 0.03 }, accountedUsd: null }); const held = await finishOneProposalAction(args), mixed = await finishOneProposalAction({ ...args, proposalId: ID } as never); expect([held.success, held.readySaved, held.evidenceOwed, held.error?.includes("No new finished change"), held.error?.includes("unavailable"), held.error?.includes("Research settings were not changed"), mixed.success, wire.mock.calls.length]).toEqual([false, 0, 1, true, true, true, false, 2]); wire.mockResolvedValueOnce({ success: false, readySaved: 0, reason: "partial_saved", run: null, meter: null, accountedUsd: null }); await finishOneProposalAction({ prepareNext: true, limitToOneDollar: true }); expect(wire.mock.calls.at(-1)?.[0]).toMatchObject({ tenantId: "t", limitToOneDollar: true }); expect((await finishOneProposalAction({ prepareNext: true, limitToOneDollar: false } as never)).success).toBe(false); await finishOneProposalAction({ prepareNext: true, maxTotalUsd: 0.90 }); expect(wire.mock.calls.at(-1)?.[0]).toMatchObject({ tenantId: "t", maxTotalUsd: 0.90 }); for (const maxTotalUsd of [undefined, null, "0.90", NaN, Infinity, -1, 0, 1.051]) { const calls = wire.mock.calls.length; expect([(await finishOneProposalAction({ prepareNext: true, maxTotalUsd } as never)).success, wire.mock.calls.length]).toEqual([false, calls]); } for (const invalid of [{ proposalId: ID, maxTotalUsd: 0.90 }, { proposalId: ID, prepare: true, maxTotalUsd: 0.90 }, { prepareNext: true, limitToOneDollar: true, maxTotalUsd: 1.01 }]) { const counts = [proofRun.mock.calls.length, prepareRun.mock.calls.length, nextRun.mock.calls.length]; expect([(await finishOneProposalAction(invalid as never)).success, [proofRun.mock.calls.length, prepareRun.mock.calls.length, nextRun.mock.calls.length]]).toEqual([false, counts]); } } else { proofRun.mockResolvedValueOnce({ success: false, reason: "proof_admission_refused_overrun", meter: { providerCalls: 0, costUsd: 0 } }); const failed = await finishOneProposalAction(args); proofRun.mockResolvedValueOnce({ success: false, reason: "candidate_preflight:This repeats the answer already on the page.", meter: null }); const preflight = await finishOneProposalAction(args); expect([failed.error, preflight.error]).toEqual(["Today's internal spend breaker is still closed. No provider call was made. Receipt: 0 OpenAI calls, $0.00; DataForSEO $0.", "This repeats the answer already on the page. No provider call was made. Receipt: 0 OpenAI calls, $0.00; DataForSEO $0."]); }
    const before = wire.mock.calls.length; publish.allowed = false; const denied = await finishOneProposalAction(args); publish.allowed = true; expect([denied.success, wire.mock.calls.length]).toEqual([false, before]);
    const shown = renderToStaticMarkup(createElement(SetAsideChange, { proposalId: next ? undefined : ID, finishable: true, prepareNext: next })), hidden = renderToStaticMarkup(createElement(SetAsideChange, { proposalId: ID }));
    expect([shown.includes(next ? "Prepare next change" : "Finish this one"), shown.includes(next ? "saved research" : "Free page and evidence checks run first"), shown.includes(next ? "$1.05 in total request reservations" : "$0.05"), shown.includes(next ? "one named source" : "DataForSEO $0"), shown.includes("Research stays paused"), hidden.includes("Finish this one"), next ? !shown.includes("data-set-aside") : true]).toEqual([true, true, true, true, true, false, true]); });
  it("prepares the selected page only with disclosed ceilings and never calls a reservation an invoice", async () => {
    const { finishOneProposalAction } = await import("@/app/(shell)/changes/actions"), { SetAsideChange } = await import("@/app/(shell)/changes/change-controls"), { loadChangeProposal, resolveCurrentBasis } = await import("@/domains/decision");
    const question = "why is allahu akbar written 22 times on the iran flag", debt = { ...bundled(NOW), bundle: undefined, status: "needs_review", researchOnly: false, primaryQuery: question, recommendedChange: { kind: "existing_edit", field: "section", before: null, after: "Unfinished answer." }, obligation: { kind: "evidence", need: { kind: "factual_source", query: question, proposalId: ID, reasonCode: "causal_answer_source_unconfirmed" } } } as ChangeProposal, missingOutcome = { success: false, proposalId: ID, reason: "no_new_ready_substantive_edit", preferredRetiredReason: "missing", captured: true, allowance: { modelCalls: 0, externalCalls: 0, modelReservedUsd: 0, externalReservedUsd: 0 } }; vi.mocked(resolveCurrentBasis).mockResolvedValue(NOW); const fallbacks = [null, debt, null, { ...debt, basis: "old_basis" }]; vi.mocked(loadChangeProposal).mockImplementation(async (_t, _id, o) => o?.retired === "include" ? null : (fallbacks.shift() ?? null) as ChangeProposal | null);
    prepareRun.mockResolvedValueOnce({ ...missingOutcome, preferredRetiredReason: "blocked", allowance: { ...missingOutcome.allowance, modelReservedUsd: 0.2, externalReservedUsd: 0.002 }, evidenceOwed: [{ kind: "factual_source", query: "regional weave", proposalId: ID }, { kind: "serp", query: "unrelated private query", proposalId: "other" }] }).mockResolvedValueOnce({ success: false, reason: "proof_admission_replayed", allowance: null }).mockResolvedValueOnce({ success: false, reason: "openai_not_configured_in_this_runtime", allowance: null }).mockResolvedValueOnce(missingOutcome).mockResolvedValueOnce({ ...missingOutcome, preferredRetiredReason: undefined, preferredOutcome: "evidence_required", evidenceOwed: [{ kind: "serp", query: "named source", proposalId: ID }, { kind: "serp", query: "private other", proposalId: "other" }] }).mockResolvedValueOnce(missingOutcome).mockResolvedValueOnce({ ...missingOutcome, evidenceOwed: [{ kind: "factual_source", query: question, proposalId: ID }] }).mockResolvedValueOnce({ ...missingOutcome, evidenceOwed: [{ kind: "factual_source", query: question, proposalId: ID }] });
    const failed = await finishOneProposalAction({ proposalId: ID, prepare: true, authorizationId: AUTH }), used = await finishOneProposalAction({ proposalId: ID, prepare: true, authorizationId: AUTH }), missing = await finishOneProposalAction({ proposalId: ID, prepare: true, authorizationId: AUTH }), retired = await finishOneProposalAction({ proposalId: ID, prepare: true, authorizationId: AUTH }), owed = await finishOneProposalAction({ proposalId: ID, prepare: true, authorizationId: AUTH }), active = await finishOneProposalAction({ proposalId: ID, prepare: true, authorizationId: AUTH }), staleReceipt = await finishOneProposalAction({ proposalId: ID, prepare: true, authorizationId: AUTH }), wrongBasis = await finishOneProposalAction({ proposalId: ID, prepare: true, authorizationId: AUTH }); expect(prepareRun).toHaveBeenCalledWith({ tenantId: "t", proposalId: ID, currentBasis: NOW, maxOpenAiCalls: 8, maxOpenAiUsd: 2, maxDataForSeoCalls: 3, maxDataForSeoUsd: 0.4, authorizationId: AUTH });
    expect([failed.success, failed.error?.includes("not invoices"), failed.error?.includes("regional weave"), failed.error?.includes("unrelated private query"), failed.error?.includes("exact edit is held"), failed.error?.includes("complete current page capture"), failed.error?.includes("0 provider calls"), failed.error?.includes("Research stays paused"), used.error?.includes("already used"), missing.error?.includes("not configured"), retired.error?.includes("no longer includes this exact edit"), owed.error?.includes("named evidence"), owed.error?.includes("named source"), owed.error?.includes("private other"), active.error?.includes("Still needs factual source"), active.error?.includes("no longer includes this exact edit"), staleReceipt.error?.includes("no longer includes this exact edit"), wrongBasis.error?.includes("no longer includes this exact edit")]).toEqual([false, true, true, false, true, true, true, true, true, true, true, true, true, false, true, false, true, true]);
    prepareRun.mockResolvedValueOnce(missingOutcome); const limited = await finishOneProposalAction({ proposalId: ID, prepare: true, limitToOneDollar: true, authorizationId: AUTH }), misuse = await finishOneProposalAction({ proposalId: ID, limitToOneDollar: true } as never); expect([limited.success, misuse.success, prepareRun.mock.calls.at(-1)?.[0]]).toEqual([false, false, { tenantId: "t", proposalId: ID, currentBasis: NOW, maxOpenAiCalls: 8, maxOpenAiUsd: 0.8, maxDataForSeoCalls: 3, maxDataForSeoUsd: 0.2, authorizationId: AUTH }]); publish.allowed = false; const denied = await finishOneProposalAction({ proposalId: ID, prepare: true, authorizationId: AUTH }); publish.allowed = true; expect([denied.success, prepareRun.mock.calls.length]).toEqual([false, 9]);
    for (const next of [false, true]) { const wire = next ? nextRun : prepareRun; const { JSDOM } = createRequire(import.meta.url)("jsdom"), dom = new JSDOM("<div id='root'></div>", { url: "https://site.example" }), popup = vi.fn(() => false); dom.window.confirm = popup; vi.stubGlobal("window", dom.window); vi.stubGlobal("document", dom.window.document); vi.stubGlobal("IS_REACT_ACT_ENVIRONMENT", true);
    const root = createRoot(dom.window.document.getElementById("root")), repainted = vi.fn(); let release!: (value: unknown) => void; wire.mockClear(); surfaceCalls.refresh.mockClear(); wire.mockImplementationOnce(() => new Promise((resolve) => { release = resolve; }));
    try { await act(async () => root.render(createElement(SetAsideChange, { proposalId: next ? undefined : ID, finishable: true, prepare: !next, prepareNext: next, displayedVersion: versionOf(debt), ...(next ? { onFinished: repainted } : {}) }))); const button = dom.window.document.querySelector("[data-finish-one]") as HTMLButtonElement; expect(dom.window.document.body.textContent).toContain(next ? "Up to $1.05 in total request reservations" : "Each attempt reuses saved evidence; up to $2 OpenAI and $0.40 DataForSEO."); const limit = dom.window.document.querySelector(next ? "[data-max-total]" : "[data-limit-one]") as HTMLInputElement | null; expect(limit).not.toBeNull(); if (next && limit) { expect(limit.value).toBe("1.05"); for (const amount of ["", "0", "1.06", "0.901", "0.90"]) { await act(async () => { limit.value = amount; limit.dispatchEvent(new dom.window.Event("input", { bubbles: true })); }); expect(button.disabled).toBe(!["0.901", "0.90"].includes(amount)); if (amount === "0.901") expect(dom.window.document.body.textContent).toContain("Up to $0.901 in total"); if (button.disabled) await act(async () => button.click()); } expect(dom.window.document.body.textContent).toContain("Up to $0.9 in total request reservations"); expect(dom.window.document.body.textContent).toContain("$0.05 for a source within that total"); } else if (limit) { expect(limit.checked).toBe(false); await act(async () => limit.click()); expect(dom.window.document.body.textContent).toContain("Authorize up to $1 in requests"); expect(dom.window.document.body.textContent).toContain("Request reservation ceilings: $0.80 OpenAI and $0.20 DataForSEO"); } expect(wire).not.toHaveBeenCalled(); await act(async () => button.click());
      expect(popup).not.toHaveBeenCalled(); expect(button.disabled).toBe(true); if (next) expect((dom.window.document.querySelector("[data-max-total]") as HTMLInputElement).disabled).toBe(true); expect(wire).toHaveBeenCalledOnce(); expect(wire.mock.calls[0]?.[0]).toMatchObject(next ? { tenantId: "t", currentBasis: NOW, maxTotalUsd: 0.90 } : { proposalId: ID, maxOpenAiUsd: 0.8, maxDataForSeoUsd: 0.2, authorizationId: expect.stringMatching(/^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i) }); await act(async () => { button.click(); release(next ? { success: false, reason: "partial_saved", readySaved: 0, run: null, meter: null, accountedUsd: null } : { success: false, reason: "no_new_ready_substantive_edit", allowance: null }); }); expect(wire).toHaveBeenCalledOnce(); expect(button.disabled).toBe(false); expect([repainted.mock.calls.length, surfaceCalls.refresh.mock.calls.length]).toEqual(next ? [1, 0] : [0, 1]);
      if (!next) { const error = dom.window.document.querySelector(".text-red-500")!.textContent; await act(async () => root.render(createElement(SetAsideChange, { key: "archived", proposalId: ID, historyOnly: true }))); expect([dom.window.document.body.textContent?.includes(error!), dom.window.document.body.textContent?.includes(`Version displayed when started: ${versionOf(debt)}`), dom.window.document.querySelector("button"), wire.mock.calls.length]).toEqual([true, true, null, 1]); await act(async () => root.render(createElement(SetAsideChange, { key: "foreign", proposalId: "other::draft", historyOnly: true }))); expect(dom.window.document.body.textContent).toBe(""); }
      { if (!next) await act(async () => root.render(createElement(SetAsideChange, { key: "resumed", proposalId: ID, finishable: true, prepare: true, displayedVersion: versionOf(debt) }))); const currentButton = dom.window.document.querySelector("[data-finish-one]") as HTMLButtonElement, lost = vi.spyOn(await import("@/app/(shell)/changes/actions"), "finishOneProposalAction").mockRejectedValueOnce(new Error("Action response unavailable after durable work changed")); await act(async () => currentButton.click()); expect([lost.mock.calls.length, wire.mock.calls.length, repainted.mock.calls.length, surfaceCalls.refresh.mock.calls.length, dom.window.document.body.textContent?.includes("The action response was unavailable"), dom.window.document.body.textContent?.includes("outcome and charges are not confirmed"), dom.window.document.querySelector("[data-finish-one-done]")]).toEqual([1, 1, next ? 2 : 0, next ? 0 : 2, true, true, null]); lost.mockRestore();
        const saved = next ? null : vi.spyOn(await import("@/app/(shell)/changes/actions"), "finishOneProposalAction").mockResolvedValueOnce({ success: true, note: "A finished edit on this page is ready in Changes. Nothing was published." }); if (next) wire.mockResolvedValueOnce({ success: true, reason: "ready_saved", readySaved: 1, run: { id: "t:run", status: "paused", progress: {} }, meter: null, accountedUsd: null });
        await act(async () => currentButton.click()); expect([repainted.mock.calls.length, surfaceCalls.refresh.mock.calls.length, wire.mock.calls.length]).toEqual(next ? [3, 0, 2] : [0, 3, 1]); expect(dom.window.document.body.textContent).toContain(next ? "1 finished change saved." : "A finished edit on this page is ready in Changes."); saved?.mockRestore(); }
    } finally { await act(async () => root.unmount()); dom.window.close(); vi.unstubAllGlobals(); } }
  });
  it("hands an obsolete description to its exact saved successor before funding, and refuses an unproved handover", async () => {
    const { finishOneProposalAction } = await import("@/app/(shell)/changes/actions"), { loadChangeProposal, produceProposalsForTenant, resolveCurrentBasis } = await import("@/domains/decision");
    const oldId = "t::/famous-iranian-comedians::existing_edit::previous_meta", newId = "t::/famous-iranian-comedians::existing_edit::missing_description";
    const old = { ...bundled(NOW, oldId), bundle: undefined, status: "needs_review", recommendedChange: { kind: "existing_edit", field: "meta", before: "An obsolete description.", after: "A better description." }, obligation: { kind: "terminal", reason: "The current meta description differs from the exact line this edit would replace; requalify the current page." } } as ChangeProposal;
    const next = { ...old, id: newId, researchOnly: true, workKey: "current-basis-meta-work", recommendedChange: { kind: "existing_edit", field: "meta", before: null, after: "" }, obligation: { kind: "draft" } } as ChangeProposal;
    let transferred = false; vi.mocked(resolveCurrentBasis).mockResolvedValue(NOW);
    vi.mocked(loadChangeProposal).mockImplementation(async (_t, id, opts) => { opts?.canonicalRow?.({ proposal_version: id === oldId ? 16 : 18, terminal_disposition: id === oldId && transferred ? "superseded" : null, superseded_by: id === oldId && transferred ? newId : null } as never); return id === oldId ? old : id === newId && transferred ? next : null; });
    vi.mocked(produceProposalsForTenant).mockImplementation(async () => { transferred = true; return { outcome: "proposals_persisted", persisted: 1 } as never; });
    prepareRun.mockResolvedValue({ success: true, allowance: null });
    const landed = await finishOneProposalAction({ proposalId: oldId, prepare: true, authorizationId: AUTH });
    expect([landed.success, vi.mocked(produceProposalsForTenant).mock.calls.length, prepareRun.mock.calls[0]?.[0]?.proposalId]).toEqual([true, 1, newId]);
    vi.mocked(produceProposalsForTenant).mockClear(); const retry = await finishOneProposalAction({ proposalId: oldId, prepare: true, authorizationId: AUTH });
    expect([retry.success, vi.mocked(produceProposalsForTenant).mock.calls.length, prepareRun.mock.calls[1]?.[0]?.proposalId]).toEqual([true, 0, newId]);
    transferred = false; prepareRun.mockClear(); vi.mocked(produceProposalsForTenant).mockResolvedValue({ outcome: "no_actionable_candidate", persisted: 0 } as never);
    const refused = await finishOneProposalAction({ proposalId: oldId, prepare: true, authorizationId: AUTH });
    expect([refused.success, refused.error?.includes("no paid finishing attempt"), prepareRun.mock.calls.length]).toEqual([false, true, 0]);
  });
  it("revalidates a stored release against the exact current basis before serving any row", async () => {
    const { withCurrentBasisOnly } = await vi.importActual<typeof import("@/app/(shell)/changes-data")>("@/app/(shell)/changes-data");
    const mixed = { ...emptyView(2), proposals: [bundled("basis_old::d2", "t::old"), bundled(NOW, "t::now"), { ...bundled("", "t::none"), basis: undefined }], // demotedStaleBasis 2 OVERLAPS the 3 listed rows in an old-rule release: 3, never 5.
      ready: [bundled("basis_old::d2", "t::old")], summary: { todo: 0, ready: 1, measuring: 0, results: 0 } } as ChangesView;
    const held = withCurrentBasisOnly(mixed, { tenantId: "t", currentBasis: NOW }); // the current row survives; it was never set aside
    expect([held.proposals.length, held.ready.length, held.summary.ready], "only the current-basis row survives; a stale row and a basis-less row are history, and an old ready stamp cannot attach to the survivor").toEqual([1, 0, 0]);
    const faulted = { ...bundled(NOW, "t::faulted"), faults: ["it points at the page instead of answering"] } as ChangeProposal, byFault = withCurrentBasisOnly({ ...emptyView(0), proposals: [faulted], ready: [faulted], summary: { todo: 0, ready: 1, measuring: 0, results: 0 } } as ChangesView, { tenantId: "t", currentBasis: NOW }); // the current bar rechecks a stored Ready stamp even when all proposal rows pass the basis check
    expect([byFault.ready.length, byFault.toDo.length, byFault.summary.ready], "and a stored ready row held by a typed fault re-sorts out of the lane: the release reads the verdict's defects, never the hard arms alone (journey review, 2026-09-06)").toEqual([0, 1, 0]);
    const uniformlyStale = { ...emptyView(0), proposals: [bundled("basis_old::d3", "t::old")], ready: [bundled("basis_old::d3", "t::old")],
      summary: { todo: 0, ready: 1, measuring: 0, results: 0 } } as ChangesView;
    const stale = withCurrentBasisOnly(uniformlyStale, { tenantId: "t", currentBasis: NOW }); // ONE bar, and it is not mine: consistency is not currency
    expect([stale.proposals.length, stale.ready.length, stale.summary.ready], "a release whose every row was stamped in an earlier generation is withheld rather than represented as current work").toEqual([0, 0, 0]);
    const current = { ...emptyView(0), proposals: [bundled(NOW)], ready: [bundled(NOW)] } as ChangesView;
    expect(withCurrentBasisOnly(current, { tenantId: "t", currentBasis: NOW }).proposals).toHaveLength(1); // my own bar, untouched
    expect(withCurrentBasisOnly(current, { tenantId: "t", currentBasis: null }).proposals, "an unreadable basis fails closed because no saved row can be proved current").toHaveLength(0); });
  it("keeps an independently paged Ready change when the global first page contains a stale row", async () => { const { withCurrentBasisOnly } = await vi.importActual<typeof import("@/app/(shell)/changes-data")>("@/app/(shell)/changes-data"); const ready = bundled(NOW, "t::off-page-ready"), stale = { ...bundled("basis_old::d2", "t::first-page-stale"), status: "needs_review", researchOnly: true } as ChangeProposal, release = { ...emptyView(0), proposals: [stale], ready: [ready], research: [stale], summary: { ...emptyView(0).summary, ready: 1, todo: 19, research: 157 } } as ChangesView, shown = withCurrentBasisOnly(release, { tenantId: "t", currentBasis: NOW }); expect([shown.proposals.map((p) => p.id), shown.ready.map((p) => p.id), shown.summary.ready, shown.summary.todo, shown.summary.research, shown.laneById?.[ready.id], (await renderChanges(shown)).includes(EXACT)]).toEqual([[ready.id], [ready.id], 1, 19, 156, "ready", true]); });
});
describe("bulk Mark Done is one batch, durable before acknowledged", () => {
  const readyRow = (id: string, over: Partial<ChangeProposal> = {}): ChangeProposal => ({ id, tenantId: "t", kind: "existing_edit", pagePath: `/${id.split("::")[1] ?? "p"}`.replace("//", "/"), pageUrl: `https://iranopedia.com${`/${id.split("::")[1] ?? "p"}`.replace("//", "/")}`, pageLabel: id, primaryQuery: "q", opportunityType: "Capture clicks",
    changeFamily: "meta", status: "ready", basis: NOW, reviewedCaptures: captures("t", `https://iranopedia.com${`/${id.split("::")[1] ?? "p"}`.replace("//", "/")}`), modeledOn: 'the results page for "q": 3 ranked titles read, 2 of them leading with "q", and this line leads with it too',
    recommendedChange: { kind: "existing_edit", field: "meta", before: "Old.", after: "A finished, specific description of the page, written from its own stored words." },
    whyItMatters: "w", estimatedEffortMinutes: 3, riskLevel: "low", confidence: "high", limitations: [], evidence: { query: "q", hints: [], evidenceRefCount: 1 }, impactScore: 5, upsidePerMonth: null, publish: "manual", createdAt: SEEN, ...over } as unknown as ChangeProposal);
  const wire = async (rows: Map<string, ChangeProposal>, ledger: unknown[]) => {
    vi.resetModules(); surfaceCalls.n = 0; shipped.records = []; shipped.held = ledger as never;
    let ledgerReads = 0;
    vi.doMock("next/server", async () => ({ ...(await vi.importActual<typeof import("next/server")>("next/server")), after: (fn: () => unknown) => { void Promise.resolve().then(fn as never); } }));
    vi.doMock("@/app/(shell)/surface-release", () => ({ invalidateCoreSurfaces: async () => { surfaceCalls.n += 1; } }));
    vi.doMock("@/domains/runtime", async () => ({ ...(await vi.importActual<typeof import("@/domains/runtime")>("@/domains/runtime")), ensureResearchRunOnVisit: () => {} }));
    vi.doMock("@/domains/decision", async () => ({ ...(await vi.importActual<typeof import("@/domains/decision")>("@/domains/decision")),
      loadChangeProposals: async () => rows, proposalDisposition: async () => null, loadChangeProposal: async (_t: string, id: string) => rows.get(id) ?? null,
      resolveCurrentBasis: async () => NOW, implementationGuard: async (t: string, id: string, v: string) => { const p = rows.get(id);
        return p?.tenantId === t && versionOf(p) === v ? { proposal: structuredClone(p), rowVersion: 1, payload: structuredClone(p) } : null; } }));
    vi.doMock("@/domains/measurement", async () => ({ ...(await vi.importActual<typeof import("@/domains/measurement")>("@/domains/measurement")),
      loadShippedChanges: async () => { ledgerReads += 1; return shipped.held; }, captureChangeMeta: async () => null,
      recordShipment: async (r: unknown, opts?: { proposal?: { rowVersion: number; payload: ChangeProposal; complete: boolean } }) => { const f = r as { proposalId: string; proposalVersion: string }, guard = opts?.proposal, row = rows.get(f.proposalId);
        if (!guard || !row || row.tenantId !== (r as { tenantId: string }).tenantId || guard.rowVersion !== 1
          || versionOf(row) !== versionOf(guard.payload) || !["ready", "implemented_pending_verification"].includes(row.status)) throw new Error("stale atomic recording");
        const held = (shipped.held as Array<{ id: string; proposalId: string; proposalVersion: string; measurementState?: string }>).find((x) => x.proposalId === f.proposalId && x.proposalVersion === f.proposalVersion);
        if (row.status === "implemented_pending_verification" && !held) throw new Error("stale atomic recording");
        if (guard.complete) row.status = "implemented_pending_verification";
        if (held) return { shipmentId: held.id, measurement: held.measurementState ?? "measuring", proposalImplemented: guard.complete };
        shipped.records.push(r); return { shipmentId: `rec-${shipped.records.length}`, measurement: "measuring", proposalImplemented: guard.complete }; } }));
    return { markManyImplementedAction: (await import("@/app/(shell)/changes/actions")).markManyImplementedAction, reads: () => ledgerReads };
  };
  it("records a deduped batch with one ledger read, one Shipment per success, per-id results, and no per-row rebuild", async () => {
    const rows = new Map(["a", "b", "c"].map((k) => { const r = readyRow(`t::/${k}::existing_edit::missing_description`); return [r.id, r] as const; }));
    const { markManyImplementedAction, reads } = await wire(rows, []);
    const ids = [...rows.keys()];
    const res = await markManyImplementedAction({ proposals: [...ids, ids[0]!].map((id) => ({ id, expectedVersion: versionOf(rows.get(id)!) })) }); // a duplicated input id is one press
    expect([res.success, res.done, res.already, res.failed.length], "three recorded, none failed, the duplicate deduped").toEqual([true, 3, 0, 0]);
    expect(res.results.map((r) => r.outcome), "per-id results say what each row became").toEqual(["recorded", "recorded", "recorded"]);
    expect(res.results.every((r) => !!r.shipmentId), "every success names its Shipment").toBe(true);
    expect([shipped.records.length, reads(), [...rows.values()].every((r) => r.status === "implemented_pending_verification")], "one Shipment per success, ONE ledger read for the whole batch, each proposal settled with its record").toEqual([3, 1, true]);
    expect(surfaceCalls.n, "one surface refresh for the whole batch, never one per row").toBe(1);
    const written = shipped.records as Array<{ proposalId: string; proposalVersion: string; componentsApplied: unknown[] }>;
    const replay = await wire(rows, written.map((r, i) => ({ ...r, id: `rec-${i + 1}`, implementedAt: SEEN })));
    const retry = await replay.markManyImplementedAction({ proposals: ids.map((id) => ({ id, expectedVersion: versionOf(rows.get(id)!) })) });
    expect([retry.done, retry.already, shipped.records.length]).toEqual([0, 3, 0]); });
});
