/** Runtime acquisition executes EVERY kind the requirement union declares, through the machinery that already  exists: serp through the serp unit, competitor_page through the winning-pages unit's priority-query read,  page_source through that unit's owned-read seat, and factual_source through the fact-check pass. Two of the  four kinds used to be typed dead ends: minted by producers, refused at the one consumer with "nothing here  can buy a competitor_page", so the requirement system promised readings the runtime could never make. */
import { describe, expect, it, vi } from "vitest";
const CALLS = vi.hoisted(() => ({ serp: [] as string[][], win: [] as { qs: string[]; owned: string | null }[] }));
const STATE = vi.hoisted(() => ({ done: ["iran flag"] as string[] })); vi.mock("@/domains/evidence/funnel/state", async (actual) => ({ ...(await actual<Record<string, unknown>>()), loadFunnelState: async () => ({ rowVersion: 1, state: { serps: { queries: STATE.done.map((query) => ({ query, status: "done" })) } } }) })); // LANDED MEANS ON FILE: the acquisition reads the state back and counts only a query that stands done there
vi.mock("@/domains/evidence", async (actual) => ({ ...(await actual<Record<string, unknown>>()),
  serpAnalysisUnit: (_d: unknown, qs: string[]) => async () => (CALLS.serp.push(qs), { status: "done", cursor: null, progress: {} }),
  winningPagesUnit: (_d: unknown, qs: string[] = [], _i: unknown = null, owned: string | null = null) => async () => (CALLS.win.push({ qs, owned }), { status: "advanced", cursor: null, progress: {} }) }));
import { defaultSteps } from "@/domains/runtime/ops/research-steps";
describe("acquireEvidence is exhaustive over the requirement union", () => {
  it("routes serp, competitor_page and page_source to the existing units, and factual_source to the fact-check pass", async () => {
    expect((await defaultSteps.acquireEvidence("t1", { kind: "serp", query: "iran flag" }, "b", 5_000)).acquired).toBe(true); expect((await defaultSteps.acquireEvidence("t1", { kind: "competitor_page", query: "iran flag", url: "https://rival.example/flags" }, "b", 5_000)).acquired).toBe(true);
    expect((await defaultSteps.acquireEvidence("t1", { kind: "page_source", query: "iran flag", url: "https://me.example/flags" }, "b", 5_000)).acquired).toBe(true); expect(CALLS.serp).toEqual([["iran flag"]]); // the exact search, through the exact unit the funnel already uses
    expect(CALLS.win).toEqual([{ qs: ["iran flag"], owned: null }, { qs: [], owned: "https://me.example/flags" }]); // the winner read by priority query; the own page by the owned seat
    const facts = await defaultSteps.acquireEvidence("t1", { kind: "factual_source", query: "iran flag", url: "https://me.example/flags" }, "b", 1_000); expect(facts.detail).toContain("fact check"); // the pass RAN; hermetically it banks nothing, which is an honest not-acquired, never "nothing here can buy a factual_source"
    expect((await defaultSteps.acquireEvidence("t1", { kind: "serp", query: "x" }, null, 5_000)).acquired).toBe(false); // no confirmed basis, no read: unchanged fail-closed rule
    STATE.done = []; expect(await defaultSteps.acquireEvidence("t1", { kind: "serp", query: "iran flag" }, "b", 5_000), "a unit that answers done for its agenda while the named page is on no row is not an acquisition").toEqual({ acquired: false, detail: 'results page for "iran flag": not on file under b after the unit finished' });
    expect((await defaultSteps.acquireEvidence("t1", { kind: "page_source", query: "x" }, "b", 5_000)).detail).toContain("names no page"); // a malformed requirement refuses loudly instead of guessing a url
    const ROWS: Record<string, unknown>[] = [], wrote: Record<string, unknown>[] = [], WORKED: string[] = [], REOPENED: Array<[string, string | undefined]> = []; vi.resetModules();
    vi.doMock("@/domains/evidence/pages/fact-checks", async (a) => ({ ...(await a<Record<string, unknown>>()), readFactChecks: async () => ROWS, recordOwedClaims: async () => 1, recordFactChecks: async (_t: string, _p: string, rs: Record<string, unknown>[]) => (wrote.push(...rs), ROWS.splice(0, ROWS.length, ...rs), rs.length), reopenObsoleteChecks: async (_t: string, _p: string, rs: { statementKey: string }[], why?: string) => (REOPENED.push([rs[0]!.statementKey, why]), 1) })); vi.doMock("@/domains/evidence/snapshot-loader", async (a) => ({ ...(await a<Record<string, unknown>>()), loadEvidenceSnapshot: async () => ({ ownedPages: [{ url: "https://me.example/hub", search: { impressions90d: 9_000, topQueries: [] } }, { url: "https://me.example/flags", search: { impressions90d: 10, topQueries: [] } }], research: {}, sources: [], scope: { tenantId: "t1", site: "me.example" } }) })); vi.doMock("@/domains/evidence/pages/owned-context", async (a) => ({ ...(await a<Record<string, unknown>>()), loadOwnedPageBodies: async (_t: string, us: string[]) => (WORKED.push(us[0]!), new Map([[us[0]!, { title: "Persian Cobra", h1: "Persian Cobra", headings: [], passages: ["A venomous snake of the Persian plateau."] }]])) }));
    const { pageHashOf, claimIdentity, claimTypeOf } = await import("@/domains/evidence/pages/fact-check-run"), { deriveSupport } = await import("@/domains/evidence/pages/claim-support"), { defaultSteps: steps } = await import("@/domains/runtime/ops/research-steps"), key = claimIdentity("are there cobras in iran", "", "missing"); const put = (over: Record<string, unknown>) => ROWS.splice(0, ROWS.length, { page: "/cobra", statementKey: key, subject: "are there cobras in iran", current: "", proposed: "Iran has AH-1 Cobra attack helicopters.", verdict: "undecidable", state: "checked", rulesVersion: 5, sources: [], pageContentHash: pageHashOf("Persian Cobra\nPersian Cobra\nA venomous snake of the Persian plateau."), ...over });
    const seed = async () => { wrote.length = 0; await steps.acquireEvidence("t1", { kind: "factual_source", query: "are there cobras in iran", url: "https://me.example/cobra", missingTopic: "are there cobras in iran" }, "b", 1_000); return wrote.filter((w) => w.statementKey === key).map((w) => [w.state, w.note]); };
    const FLAGS = "https://me.example/flags", ASK = "iran flag before 1979", PROP = "Before 1979, Iran used a tricolour flag of green, white, and red with the Lion and Sun emblem at the center; it remained in use until the 1979 Islamic Revolution", CARRIES = "Before 1979 the flag of Iran was a tricolour of green, white and red charged at the center with the Lion and Sun emblem of the Islamic state.";
    const ctx = { tenantId: "t1", page: "/hub", statementKey: "flag-gap", pageLocator: "missing", subject: ASK, claimKind: claimTypeOf(ASK, PROP, "missing"), current: "", proposed: PROP, url: "https://en.wikipedia.org/f", kind: "encyclopedia" as const, quote: CARRIES, titleContext: null }, own = { proposed: null, literal: null, usage: null, sources: [], agreement: "none_found", confidence: "unsupported", verdict: "undecidable", alsoAt: [], note: "", evidenceBasis: null, sourceReadAt: null, pageContentHash: "h", checkedAt: "2026-09-01T00:00:00.000Z" };
    ROWS.splice(0, ROWS.length, { ...own, page: "/hub", statementKey: "median-empire-flag", subject: "Median Empire Flag", current: "The Median Empire flag is described here.", state: "owed", rulesVersion: 4, pageLocator: null }, { ...own, page: "/flags", statementKey: "flag-owed", subject: ASK, current: "", state: "owed", rulesVersion: 5, pageLocator: "missing" }, { ...own, page: "/hub", statementKey: "flag-gap", subject: ASK, current: "", proposed: PROP, pageLocator: "missing", sources: [{ url: ctx.url, kind: "encyclopedia", says: CARRIES, support: deriveSupport(ctx) }], agreement: "single_source", confidence: "likely", verdict: "page_correct", sourceReadAt: "2026-09-01T00:00:00.000Z", state: "checked", rulesVersion: 4 });
    WORKED.length = 0; REOPENED.length = 0; await steps.factCheck("t1", 1_000, undefined);
    expect([WORKED, REOPENED, deriveSupport(ctx) != null], "A MISSING ANSWER IS A CUSTOMER'S WAITING ANSWER BLOCK: the page holding an owed question is worked before a hub holding nine hundred times its demand in inventory claims. AND THE RULES-STALE FLAG IS THE ROW'S OWN: this row is what the second slice selects, its artifacts are current under the proposition identity so nothing else would ever hand it back, and it is owed again once, in the account's own words").toEqual([[FLAGS], [["flag-gap", "Reopened: the rules that judge a missing answer changed."]], true]);
    put({}); const once = await seed(), twice = await seed(); expect([once, twice, (put({ verdict: "page_correct" }), await seed()), (put({ proposed: null }), await seed()), (put({ verdict: "page_correct", rulesVersion: 4 }), await seed())], "THE HELICOPTER ROW IS RE-RESEARCHED ONCE: a checked row holding an undecided statement answered a different subject, so it is owed again in the account's own words; the reopened row, a row whose answer IS about this page's own subject, and one that proposed nothing are all left alone. AND A QUESTION JUDGED UNDER 4, the rules a correction is judged under, is not read as researched at this version however sound its verdict looks: nothing else re-judges it").toEqual([[["owed", "Reopened: the answer must be about this page's own subject."]], [], [], [], [["owed", "Reopened: the rules that judge a missing answer changed."]]]); });
});
