import { describe, expect, it, vi } from "vitest";
const CALLS = vi.hoisted(() => ({ serp: [] as string[][], win: [] as { qs: string[]; owned: string | null; competitor?: string }[], cursors: [] as Record<string, unknown>[] }));
const STATE = vi.hoisted(() => { const at = (q: string) => `https://rival.example/${q.replace(/\s+/g, "-")}`; return { done: ["iran flag"] as string[], read: ["iran flag"] as string[], winner: (query: string) => ({ url: at(query), domain: "rival.example", engines: [], examplePrompts: [], appearances: [{ kind: "serp_organic", query, rank: 1, citedUrl: at(query), observedAt: "2026-09-05T00:00:00.000Z" }], extract: { url: at(query), wordCount: 900, mainText: "what the page winning that search says", truncated: false, fetchedAt: "2026-09-05T00:00:00.000Z" }, readOutcome: null }) }; });
vi.mock("@/domains/evidence/funnel/state", async (actual) => ({ ...(await actual<Record<string, unknown>>()), loadFunnelState: async () => ({ rowVersion: 1, state: { serps: { queries: STATE.done.map((query) => ({ query, status: "done", observedAt: new Date().toISOString(), organic: [] })), analyzed: STATE.done.length }, winningPages: STATE.read.map((q) => STATE.winner(q)), prompts: { pairs: [], intendedPairs: 0 }, discovery: { retained: [], counts: { raw: 0, retained: 0 }, caseCompetitors: [] }, pageComparisons: [], ownedReads: [], cycle: { cacheHits: 0, spentUsd: 0 } } }) })); // LANDED MEANS ON FILE: the acquisition reads back a current, dated exact results page; an undated done marker cannot satisfy the named ask
vi.mock("@/domains/evidence", async (actual) => ({ ...(await actual<Record<string, unknown>>()),
  serpAnalysisUnit: (_d: unknown, qs: string[]) => async (_t: string, cursor: Record<string, unknown>) => (CALLS.serp.push(qs), CALLS.cursors.push(cursor), { status: "done", cursor: null, progress: {} }),
  winningPagesUnit: (_d: unknown, qs: string[] = [], _i: unknown = null, owned: string | null = null, _b: unknown = null, competitor: string | null = null) => async (_t: string, cursor: Record<string, unknown>) => (CALLS.win.push({ qs, owned, ...(competitor ? { competitor } : {}) }), CALLS.cursors.push(cursor), { status: "advanced", cursor: null, progress: {} }) }));
import { canonicalUrlKey } from "@/domains/evidence/snapshot"; // the fakes below key their answer exactly as the real reader does (host and path), or a raw-url lookup would pass here and miss in production
import { claimIdentity } from "@/domains/evidence/pages/fact-check-run";
import type { EvidenceRequirement } from "@/domains/decision/producers/contract";
import { defaultSteps } from "@/domains/runtime/ops/research-steps";
describe("acquireEvidence is exhaustive over the requirement union", () => {
  it("settles only the exact current complete saved page, even when the model door is held", async () => {
    vi.resetModules();
    const url = "https://me.example/flags", need = { kind: "page_source" as const, url, query: "iran flag", workKey: "capture" };
    let body: Record<string, unknown> | null = null;
    vi.doMock("@/domains/evidence/pages/owned-context", async (a) => ({ ...(await a<Record<string, unknown>>()), loadOwnedPageBodies: async () => new Map(body ? [[canonicalUrlKey(url), body]] : []) }));
    vi.doMock("@/lib/cost/credit-breaker", async (a) => { const mod = await a<{ CREDIT_BREAKER: Record<string, unknown> }>(); return { ...mod, CREDIT_BREAKER: { ...mod.CREDIT_BREAKER, peek: async () => "held" } }; });
    try {
      const { defaultSteps: steps } = await import("@/domains/runtime/ops/research-steps");
      const fresh = { version: "current", finalUrl: url, contentHash: "capture-hash", completeness: "complete", fetchedAt: new Date().toISOString(), faqs: [] };
      for (const [capture, acquired] of [[null, false], [{ ...fresh, completeness: "partial" }, false], [{ ...fresh, version: "stale_known_good" }, false], [{ ...fresh, fetchedAt: "2000-01-01" }, false], [fresh, true]] as const) {
        body = capture; expect((await steps.acquireEvidence("t1", need, "b", 25_000)).acquired).toBe(acquired);
      }
      expect(await steps.acquireEvidence("t1", { ...need, kind: "serp" }, "b", 25_000)).toMatchObject({ acquired: false, attempted: false });
    } finally { vi.doUnmock("@/domains/evidence/pages/owned-context"); vi.doUnmock("@/lib/cost/credit-breaker"); vi.resetModules(); CALLS.win.length = 0; CALLS.cursors.length = 0; }
  });
  it("refuses unowned or changed causal source debt before a paid source pass", async () => {
    vi.resetModules(); const url = "https://me.example/flags", need = { kind: "factual_source" as const, reasonCode: "causal_answer_source_unconfirmed" as const, query: "why is the sign written 22 times", missingTopic: "why is the sign written 22 times", url, proposalId: "t1::/flags::why", ownerVersion: "page-hash", workKey: "work-d9" }, body = { url, finalUrl: url, version: "current", completeness: "complete", sourceCapture: { complete: true }, contentHash: "page-hash", fetchedAt: new Date().toISOString() }; let row: Record<string, unknown> = { tenantId: "t1", status: "needs_review", basis: "b", workKey: need.workKey, pageUrl: url, pagePath: "/flags", obligation: { kind: "evidence", need } }, capture: Record<string, unknown> = body;
    vi.doMock("@/domains/decision/proposal-store", async (a) => ({ ...(await a<Record<string, unknown>>()), loadChangeProposal: async () => row })); vi.doMock("@/domains/evidence/pages/owned-context", async (a) => ({ ...(await a<Record<string, unknown>>()), loadOwnedPageBodies: async () => new Map([[canonicalUrlKey(url), capture]]) })); vi.doMock("@/lib/cost/credit-breaker", async (a) => { const mod = await a<{ CREDIT_BREAKER: Record<string, unknown> }>(); return { ...mod, CREDIT_BREAKER: { ...mod.CREDIT_BREAKER, peek: async () => "clear" } }; }); vi.doMock("@/domains/decision/llm/gateway", async (a) => ({ ...(await a<Record<string, unknown>>()), creditBreakerHeld: async () => true }));
    try { const { defaultSteps: steps } = await import("@/domains/runtime/ops/research-steps"), denied = async (n = need) => { const result = await steps.acquireEvidence("t1", n, "b", 1_000); expect([result.acquired, result.attempted, result.detail.includes("exact proposal"), CALLS.serp, CALLS.win]).toEqual([false, false, true, [], []]); }; CALLS.serp.length = 0; CALLS.win.length = 0; await denied({ ...need, proposalId: undefined } as never); await denied({ ...need, ownerVersion: undefined } as never); row = { ...row, tenantId: "t2" }; await denied(); row = { ...row, tenantId: "t1", pageUrl: null, pagePath: "/another" }; await denied(); row = { ...row, pagePath: "/flags" }; capture = { ...body, completeness: "partial" }; await denied(); } finally { vi.doUnmock("@/domains/decision/proposal-store"); vi.doUnmock("@/domains/evidence/pages/owned-context"); vi.doUnmock("@/lib/cost/credit-breaker"); vi.doUnmock("@/domains/decision/llm/gateway"); vi.resetModules(); }
  });
  it.each(["tenant-one", "tenant-two"])("does not discharge an exact target from another page or metadata-only extract [%s]", async (tenant) => {
    STATE.read = ["read this"]; const url = "https://rival.example/read-this", need = { kind: "competitor_page" as const, query: "read this", url, workKey: "test-work" };
    expect((await defaultSteps.acquireEvidence(tenant, { ...need, url: "https://rival.example/another-page" }, "b", 5_000)).acquired).toBe(false);
    const winner = vi.spyOn(STATE, "winner"), row = STATE.winner("read this"); winner.mockReturnValue({ ...row, extract: { ...row.extract, mainText: "" } });
    try { expect((await defaultSteps.acquireEvidence(tenant, need, "b", 5_000)).acquired).toBe(false); } finally { winner.mockRestore(); STATE.read = ["iran flag"]; CALLS.win.length = 0; }
  });
  it("routes serp, competitor_page and page_source to the existing units, carries their run receipt, and factual_source to the fact-check pass", async () => { CALLS.cursors.length = 0; const receipt = { runId: "run-1", cycle: "t1:p1:2026-09-20" };
    expect((await defaultSteps.acquireEvidence("t1", { kind: "serp", query: "iran flag", workKey: "test-work" }, "b", 5_000, undefined, "all_changes", receipt)).acquired).toBe(true); expect((await defaultSteps.acquireEvidence("t1", { kind: "competitor_page", query: "iran flag", url: "https://rival.example/iran-flag", workKey: "test-work" }, "b", 5_000, undefined, "all_changes", receipt)).acquired).toBe(true);
    expect((await defaultSteps.acquireEvidence("t1", { kind: "page_source", query: "iran flag", url: "https://me.example/flags", workKey: "test-work" }, "b", 5_000, undefined, "all_changes", receipt)).acquired).toBe(false); expect(CALLS.serp).toEqual([["iran flag"]]); // An advanced unit without the actual saved page leaves the debt open.
    expect([CALLS.win, CALLS.cursors]).toEqual([[{ qs: ["iran flag"], owned: null, competitor: "https://rival.example/iran-flag" }, { qs: [], owned: "https://me.example/flags" }], Array(3).fill({ basis: "b", ...receipt })]);
    const facts = await defaultSteps.acquireEvidence("t1", { kind: "factual_source", query: "iran flag", url: "https://me.example/flags", workKey: "test-work" }, "b", 1_000); expect(facts.detail).toContain("fact check"); // the pass RAN; hermetically it banks nothing, which is an honest not-acquired, never "nothing here can buy a factual_source"
    expect((await defaultSteps.acquireEvidence("t1", { kind: "serp", query: "x", workKey: "test-work" }, null, 5_000)).acquired).toBe(false); // no confirmed basis, no read: unchanged fail-closed rule
    STATE.done = []; expect(await defaultSteps.acquireEvidence("t1", { kind: "serp", query: "iran flag", workKey: "test-work" }, "b", 5_000), "a unit that answers done for its agenda while the named page is on no row is not an acquisition").toEqual({ acquired: false, detail: 'results page for "iran flag": not on file under b after the unit finished' });
    expect([(await defaultSteps.acquireEvidence("t1", { kind: "page_source", query: "x", workKey: "test-work" }, "b", 5_000)).detail.includes("names no page"), (await defaultSteps.acquireEvidence("t1", { kind: "page_source", query: "What is an Iran flag?", url: "https://me.example/flags", reasonCode: "schema_visible_pair_unconfirmed", workKey: "test-work" }, "b", 5_000)).acquired], "a unit advancing its agenda cannot discharge an uncaptured HTML pair").toEqual([true, false]);
    const ROWS: Record<string, unknown>[] = [], wrote: Record<string, unknown>[] = [], WORKED: string[] = [], REOPENED: Array<[string, string | undefined]> = []; vi.resetModules();
    vi.doMock("@/domains/evidence/pages/fact-checks", async (a) => ({ ...(await a<Record<string, unknown>>()), readFactChecks: async () => ROWS, recordOwedClaims: async () => 1, recordFactChecks: async (_t: string, _p: string, rs: Record<string, unknown>[]) => (wrote.push(...rs), ROWS.splice(0, ROWS.length, ...rs), rs.length), reopenObsoleteChecks: async (_t: string, _p: string, rs: { statementKey: string }[], why?: string) => (REOPENED.push([rs[0]!.statementKey, why]), 1) })); vi.doMock("@/domains/evidence/snapshot-loader", async (a) => ({ ...(await a<Record<string, unknown>>()), loadEvidenceSnapshot: async () => ({ ownedPages: [{ url: "https://me.example/hub", search: { impressions90d: 9_000, topQueries: [] } }, { url: "https://me.example/flags", search: { impressions90d: 10, topQueries: [] } }], research: {}, sources: [], scope: { tenantId: "t1", site: "me.example" } }) })); vi.doMock("@/domains/evidence/pages/owned-context", async (a) => ({ ...(await a<Record<string, unknown>>()), loadOwnedPageBodies: async (_t: string, us: string[]) => (WORKED.push(us[0]!), new Map([[canonicalUrlKey(us[0]!), { title: "Persian Cobra", h1: "Persian Cobra", headings: [], passages: ["A venomous snake of the Persian plateau."], version: "current", contentHash: "cobra-hash" }]])) }));
    const { pageHashOf, claimIdentity, claimTypeOf } = await import("@/domains/evidence/pages/fact-check-run"), { deriveSupport } = await import("@/domains/evidence/pages/claim-support"), { defaultSteps: steps } = await import("@/domains/runtime/ops/research-steps"), key = claimIdentity("are there cobras in iran", "", "missing"); const put = (over: Record<string, unknown>) => ROWS.splice(0, ROWS.length, { page: "/cobra", statementKey: key, subject: "are there cobras in iran", current: "", proposed: "Iran has AH-1 Cobra attack helicopters.", verdict: "undecidable", state: "checked", rulesVersion: 5, sources: [], pageContentHash: pageHashOf("Persian Cobra\nPersian Cobra\nA venomous snake of the Persian plateau."), ...over });
    const seed = async () => { wrote.length = 0; await steps.acquireEvidence("t1", { kind: "factual_source", query: "are there cobras in iran", url: "https://me.example/cobra", missingTopic: "are there cobras in iran", workKey: "test-work" }, "b", 1_000); return wrote.filter((w) => w.statementKey === key).map((w) => [w.state, w.note]); };
    const FLAGS = "https://me.example/flags", ASK = "iran flag before 1979", PROP = "Before 1979, Iran used a tricolour flag of green, white, and red with the Lion and Sun emblem at the center; it remained in use until the 1979 Islamic Revolution", CARRIES = "Before 1979 the flag of Iran was a tricolour of green, white and red charged at the center with the Lion and Sun emblem of the Islamic state.";
    const ctx = { tenantId: "t1", page: "/hub", statementKey: "flag-gap", pageLocator: "missing", subject: ASK, claimKind: claimTypeOf(ASK, PROP, "missing"), current: "", proposed: PROP, url: "https://en.wikipedia.org/f", kind: "encyclopedia" as const, quote: CARRIES, titleContext: null }, own = { proposed: null, literal: null, usage: null, sources: [], agreement: "none_found", confidence: "unsupported", verdict: "undecidable", alsoAt: [], note: "", evidenceBasis: null, sourceReadAt: null, pageContentHash: "h", checkedAt: "2026-09-01T00:00:00.000Z" };
    ROWS.splice(0, ROWS.length, { ...own, page: "/hub", statementKey: "median-empire-flag", subject: "Median Empire Flag", current: "The Median Empire flag is described here.", state: "owed", rulesVersion: 4, pageLocator: null }, { ...own, page: "/flags", statementKey: "flag-owed", subject: ASK, current: "", state: "owed", rulesVersion: 5, pageLocator: "missing" }, { ...own, page: "/hub", statementKey: "flag-gap", subject: ASK, current: "", proposed: PROP, pageLocator: "missing", sources: [{ url: ctx.url, kind: "encyclopedia", says: CARRIES, support: deriveSupport(ctx) }], agreement: "single_source", confidence: "likely", verdict: "page_correct", sourceReadAt: "2026-09-01T00:00:00.000Z", state: "checked", rulesVersion: 4 });
    WORKED.length = 0; REOPENED.length = 0; await steps.factCheck("t1", 1_000, undefined);
    expect([WORKED, REOPENED, deriveSupport(ctx) != null], "A MISSING ANSWER IS A CUSTOMER'S WAITING ANSWER BLOCK: the page holding an owed question is worked before a hub holding nine hundred times its demand in inventory claims. AND THE RULES-STALE FLAG IS THE ROW'S OWN: this row is what the second slice selects, its artifacts are current under the proposition identity so nothing else would ever hand it back, and it is owed again once, in the account's own words").toEqual([[FLAGS], [["flag-gap", "Reopened: the rules that judge a missing answer changed."]], true]);
    put({}); const once = await seed(), twice = await seed(); expect([once, twice, (put({ verdict: "page_correct" }), await seed()), (put({ proposed: null }), await seed()), (put({ verdict: "page_correct", rulesVersion: 4 }), await seed())], "THE HELICOPTER ROW IS RE-RESEARCHED ONCE: a checked row holding an undecided statement answered a different subject, so it is owed again in the account's own words; the reopened row and a row whose answer IS about this page's own subject are left alone. AND A ROW THAT PROPOSED NOTHING WITH NO SOURCE READ BEHIND IT IS UNFINISHED RESEARCH (journey review, 2026-09-07): it is read once more where the winner's own heading starts, and the reopened row it becomes is not reopened again. AND A QUESTION JUDGED UNDER 4, the rules a correction is judged under, is not read as researched at this version however sound its verdict looks: nothing else re-judges it").toEqual([[["owed", "Reopened: the answer must be about this page's own subject."]], [], [], [["owed", "Reopened: read once without finding a passage about it, so the winner is read again where its own heading starts."]], [["owed", "Reopened: the rules that judge a missing answer changed."]]]); });
  it.each(["tenant-one", "tenant-two"])("answers for the topic it was sent to research and not for the page it ran on: a topic that is still owed is not acquired, one researched below what the evidence rules allow is a reading that happened and an obligation that did not move, and one that stands is both [%s]", async (tenant) => {
    vi.resetModules(); const ROWS: Record<string, unknown>[] = [];
    vi.doMock("@/domains/evidence/pages/fact-checks", async (a) => ({ ...(await a<Record<string, unknown>>()), readFactChecks: async () => ROWS, recordOwedClaims: async () => 1, recordFactChecks: async (_t: string, _p: string, rs: Record<string, unknown>[]) => (ROWS.splice(0, ROWS.length, ...rs), rs.length) }));
    vi.doMock("@/domains/evidence/snapshot-loader", async (a) => ({ ...(await a<Record<string, unknown>>()), loadEvidenceSnapshot: async () => ({ ownedPages: [{ url: "https://me.example/well", search: { impressions90d: 10, topQueries: [] } }], research: {}, sources: [], scope: { tenantId: tenant, site: "me.example" } }) }));
    vi.doMock("@/domains/evidence/pages/owned-context", async (a) => ({ ...(await a<Record<string, unknown>>()), loadOwnedPageBodies: async (_t: string, us: string[]) => new Map([[canonicalUrlKey(us[0]!), { title: "The Well", h1: "The Well", headings: [], passages: ["A well in the old quarter."], version: "current", contentHash: "well-hash" }]]) }));
    const { pageHashOf, claimIdentity, claimTypeOf } = await import("@/domains/evidence/pages/fact-check-run"), { deriveSupport } = await import("@/domains/evidence/pages/claim-support"), { defaultSteps: steps } = await import("@/domains/runtime/ops/research-steps");
    const URL_ = "https://me.example/well", ASK = "how deep is the well", ANSWER = "The old quarter well is 18 metres deep.", QUOTE = "The old quarter well is 18 metres deep, according to the municipal survey.", SRC = "https://reference.example/wells";
    const hash = pageHashOf("The Well\nThe Well\nA well in the old quarter."), key = claimIdentity(ASK, "", "missing");
    const ctx = { tenantId: tenant, page: "/well", statementKey: key, pageLocator: "missing", subject: ASK, claimKind: claimTypeOf(ASK, ANSWER, "missing"), current: "", proposed: ANSWER, url: SRC, kind: "encyclopedia" as const, quote: QUOTE, titleContext: null };
    const row = (over: Record<string, unknown>) => ROWS.splice(0, ROWS.length, { page: "/well", statementKey: key, subject: ASK, current: "", proposed: ANSWER, pageLocator: "missing", state: "checked", rulesVersion: 5, verdict: "page_correct", agreement: "single_source", confidence: "confirmed", sourceReadAt: "2026-09-01T00:00:00.000Z", checkedAt: "2026-09-01T00:00:00.000Z", evidenceBasis: null, alsoAt: [], note: "", literal: null, usage: null, pageContentHash: hash, sources: [{ url: SRC, kind: "encyclopedia", says: QUOTE, support: deriveSupport(ctx) }], ...over });
    const ask = () => steps.acquireEvidence(tenant, { kind: "factual_source", query: ASK, url: URL_, missingTopic: ASK, workKey: "test-work" }, "b", 1_000);
    row({}); const stands = await ask();
    row({ confidence: "disputed" }); const weak = await ask(); /* BELOW THE BAR IS NOW A GRADE, NOT A DEFAULT (2026-09-05): the evidence rules are proportional to the treatment, so `likely` on an ADDITIVE answer carried by a publisher that was read IS what the copy may stand on and the pin below would no longer be about a reading that failed. `disputed` is what a missing answer may never stand on, which is what this promise has always been about. */
    row({ state: "owed", proposed: null }); const nothing = await ask();
    expect([stands.acquired, stands.unlocked, stands.detail.startsWith("no source was bought for")], "a topic already researched at this version is an obligation that is met, and NOTHING is bought for it: the seed had always answered `already researched` and the pass ran anyway, so a stalled row spent a whole source pass every drive researching other statements of its page").toEqual([true, true, true]);
    expect([weak.acquired, weak.unlocked], "a topic researched and rated below what the copy may stand on is a reading that happened and an obligation that did not move, so it is not bought again today and it is not called a success either").toEqual([true, false]);
    expect(weak.detail, "and the reason is on the receipt in plain words, never as a stored code").toContain("rated disputed and does not meet the evidence rules copy must stand on");
    expect([nothing.acquired, nothing.unlocked], "a topic still owed after the pass is not acquired at all").toEqual([false, false]);
    vi.doUnmock("@/domains/evidence/pages/fact-checks"); vi.doUnmock("@/domains/evidence/snapshot-loader"); vi.doUnmock("@/domains/evidence/pages/owned-context"); vi.resetModules(); });
  it.each(["tenant-one", "tenant-two"])("banks a missing answer the copy may already stand on instead of buying it again, and still reopens one the copy may not [%s]", async (tenant) => {
    vi.resetModules(); const ROWS: Record<string, unknown>[] = [], TARGETS: Array<{ statementKey: string; onUnsupported: string }> = [];
    vi.doMock("@/domains/evidence/pages/claim-support", async (a) => ({ ...(await a<Record<string, unknown>>()), backfillClaimSupport: async (_t: string, targets: Array<{ statementKey: string; onUnsupported: string }>) => (TARGETS.push(...targets), []) }));
    vi.doMock("@/domains/evidence/pages/fact-checks", async (a) => ({ ...(await a<Record<string, unknown>>()), readFactChecks: async () => ROWS, recordOwedClaims: async () => 1, recordFactChecks: async () => 0, reopenObsoleteChecks: async () => 0 }));
    vi.doMock("@/domains/evidence/snapshot-loader", async (a) => ({ ...(await a<Record<string, unknown>>()), loadEvidenceSnapshot: async () => ({ ownedPages: [{ url: "https://me.example/well", search: { impressions90d: 10, topQueries: [] } }], research: {}, sources: [], scope: { tenantId: tenant, site: "me.example" } }) }));
    vi.doMock("@/domains/evidence/pages/owned-context", async (a) => ({ ...(await a<Record<string, unknown>>()), loadOwnedPageBodies: async (_t: string, us: string[]) => new Map([[canonicalUrlKey(us[0]!), { title: "The Well", h1: "The Well", headings: [], passages: ["A well in the old quarter."], version: "current", contentHash: "well-hash" }]]) }));
    const { pageHashOf, claimIdentity } = await import("@/domains/evidence/pages/fact-check-run"), facts = await import("@/domains/evidence/pages/fact-checks"), { defaultSteps: steps } = await import("@/domains/runtime/ops/research-steps");
    const ASK = "how deep is the well", ANSWER = "The old quarter well is 18 metres deep.", QUOTE = "The old quarter well is 18 metres deep, according to the municipal survey.", SRC = "https://reference.example/wells";
    const key = claimIdentity(ASK, "", "missing"), hash = pageHashOf("The Well\nThe Well\nA well in the old quarter.");
    const put = (confidence: string) => { const r = { page: "/well", statementKey: key, subject: ASK, current: "", proposed: ANSWER, pageLocator: "missing", state: "checked", verdict: "page_correct", agreement: "single_source", confidence, sourceReadAt: "2026-09-01T00:00:00.000Z", checkedAt: "2026-09-01T00:00:00.000Z", evidenceBasis: null, alsoAt: [], note: "", literal: null, usage: null, pageContentHash: hash, sources: [{ url: SRC, kind: "encyclopedia", says: QUOTE, support: null }] } as Record<string, unknown>;
      ROWS.splice(0, ROWS.length, { ...r, rulesVersion: facts.rulesVersionFor(r as never) }); TARGETS.length = 0; };
    put("likely"); const usableLikely = facts.authorizedCorrections([ROWS[0] as never], undefined, tenant).length; await steps.factCheck(tenant, 1_000, undefined); const likely = TARGETS.find((t) => t.statementKey === key)?.onUnsupported ?? "not selected";
    put("unsupported"); const usableWeak = facts.authorizedCorrections([ROWS[0] as never], undefined, tenant).length; await steps.factCheck(tenant, 1_000, undefined); const weak = TARGETS.find((t) => t.statementKey === key)?.onUnsupported ?? "not selected";
    expect([usableLikely, likely, usableWeak, weak], "usable likely evidence is reused; unsupported evidence is refused by the same authorization rule the acquisition applies").toEqual([1, "bank", 0, "reopen"]);
    vi.doUnmock("@/domains/evidence/pages/claim-support"); vi.doUnmock("@/domains/evidence/pages/fact-checks"); vi.doUnmock("@/domains/evidence/snapshot-loader"); vi.doUnmock("@/domains/evidence/pages/owned-context"); vi.resetModules(); });
  const SITES = [
    { t: "tenant-kiln", host: "kiln.example", path: "/studio-kilns", title: "Studio Kilns", h1: "Studio Kilns", body: "Studio kilns are built for one small room and fired to a plan.",
      search: "studio kilns", topic: "Firing schedules", rival: "https://ref-kiln.example/studio-kilns", found: "https://found-kiln.example/schedules",
      says: "Firing schedules for studio kilns set the climb rate, the hold at the top temperature and the cooling rate." },
    { t: "tenant-vellum", host: "vellum.example", path: "/vellum-binding", title: "Vellum Binding", h1: "Vellum Binding", body: "Vellum binding covers a board in skin and asks that the skin stay flat.",
      search: "vellum binding", topic: "Repair methods", rival: "https://ref-vellum.example/vellum-binding", found: "https://found-vellum.example/repairs",
      says: "Repair methods for vellum binding begin by humidifying the skin and pressing the board flat again." },
  ] as const;
  const world = async (s: typeof SITES[number], source: string, rivalText: string | null, prospective = false, stale = false, rivalUrls?: string[]) => {
    vi.resetModules(); const raw: Record<string, unknown>[] = [], reads: string[] = [], asked: string[] = [], ownedReads: string[] = [];
    const body = [s.title, s.h1, s.body].join("\n"), TEXT: Record<string, string> = { [s.found]: s.says, ...(rivalText == null ? {} : { [s.rival]: rivalText }) };
    const { supabaseFake } = await import("../helpers/supabase-fake");
    vi.doMock("@/lib/persistence/supabase", () => ({ getSupabaseAdmin: () => supabaseFake({ rows: (t) => t === "page_source_facts" ? raw : [], same: (a, b) => ["tenant_id", "page_key", "statement_key"].every((k) => a[k] === b[k]) }) }));
    vi.doMock("@/domains/evidence/snapshot-loader", async (a) => ({ ...(await a<Record<string, unknown>>()), loadEvidenceSnapshot: async () => ({ ownedPages: prospective ? [] : [{ url: `https://${s.host}${s.path}`, search: { impressions90d: 900, topQueries: [] } }], research: {}, sources: [], scope: { tenantId: s.t, site: s.host } }) }));
    vi.doMock("@/domains/evidence/pages/owned-context", async (a) => ({ ...(await a<Record<string, unknown>>()), loadOwnedPageBodies: async (_t: string, us: string[]) => { ownedReads.push(...us); return prospective ? new Map() : new Map([[canonicalUrlKey(us[0]!), { title: s.title, h1: s.h1, headings: [], passages: [s.body], version: stale ? "stale_known_good" : "current", contentHash: "owned-hash" }]]); } }));
    vi.doMock("@/domains/evidence/dataforseo/capabilities", async (a) => ({ ...(await a<Record<string, unknown>>()),
      providerCall: async (cap: string, input: Record<string, string>) => { reads.push(`${cap} ${input.url ?? input.keyword}`); return { state: "ok", envelope: { cap, input } }; }, collectCapability: async () => null,
      parseCapability: (cap: string, env: { input: Record<string, string> }) => cap === "serp_organic" ? { organic: [{ domain: new URL(s.found).hostname, url: s.found, title: s.topic }] } : { title: s.title, bodyText: TEXT[env.input.url!] ?? "", openingSample: null, headings: [] } }));
    vi.doMock("@/domains/decision/llm/structured-drafter", async (a) => ({ ...(await a<Record<string, unknown>>()), callStructuredLLM: async (i: { kind: string; user: string }) => {
      asked.push(`${i.kind} ${i.user}`); return { status: "drafted", value: i.kind === "fact_claim_extraction" ? { statements: [] } : { verdict: "page_correct", proposed: s.says, confidence: "likely", note: "", supporting: [{ url: source, quote: s.says }], subjects: [{ url: source, sameEntity: true, language: "English", script: null, why: "the source addresses this topic" }] } }; } }));
    const { defaultSteps: steps } = await import("@/domains/runtime/ops/research-steps"), facts = await import("@/domains/evidence/pages/fact-checks");
    const need: EvidenceRequirement & { workKey: string } = { kind: "factual_source", reasonCode: "missing_information", query: `${s.topic} ${s.search}`, ...(prospective ? { topic: { key: `topic:${s.search}`, label: s.search }, missingTopic: `${s.search} ${s.topic}` } : { url: `https://${s.host}${s.path}`, missingTopic: s.topic }), rivalUrl: s.rival, rivalUrls, workKey: "test-work" };
    const got = await steps.acquireEvidence(s.t, need, "b1", 120_000), ROWS = await facts.readFactChecks(s.t);
    const done = () => { for (const m of ["@/lib/persistence/supabase", "@/domains/evidence/pages/fact-checks", "@/domains/evidence/snapshot-loader", "@/domains/evidence/pages/owned-context", "@/domains/evidence/dataforseo/capabilities", "@/domains/decision/llm/structured-drafter"]) vi.doUnmock(m); vi.resetModules(); };
    return { got, ROWS, raw, reads, asked, ownedReads, need, steps, facts, done };
  };
  it.each(SITES)("banks and reuses an exact prospective topic with no owned page or fabricated body hash [$t]", async (s) => {
    const w = await world(s, s.rival, s.says, true);
    try {
      const row = w.ROWS[0]!;
      expect([row.page, row.subject, row.pageContentHash, row.evidenceBasis, row.proposed, row.sources[0]?.support?.supported]).toEqual([w.need.topic!.key, `${s.search} ${s.topic}`, null, "b1", s.says, true]);
      expect([w.got.acquired, w.got.unlocked, w.ownedReads, w.asked.some((u) => u.startsWith("fact_claim_extraction")), w.asked[0]?.includes(`Its intended topic: ${s.search}`)]).toEqual([true, true, [], false, true]);
      const calls = [...w.reads], again = await w.steps.acquireEvidence(s.t, w.need, "b1", 120_000);
      expect([again.acquired, again.unlocked, w.reads, w.raw.length, (await w.facts.readFactChecks("another-tenant")).length]).toEqual([true, true, calls, 1, 0]);
      w.raw[0]!.evidence_basis = "old-basis";
      const refreshed = await w.steps.acquireEvidence(s.t, w.need, "b1", 120_000);
      expect([refreshed.unlocked, (await w.facts.readFactChecks(s.t))[0]?.evidenceBasis, w.raw.length, w.reads.length]).toEqual([true, "b1", 1, calls.length + 1]);
      const before = w.reads.length;
      for (const bad of [{ ...w.need, url: `https://${s.host}/wrong` }, { ...w.need, topic: { key: "/owned-page", label: s.search } }, { ...w.need, missingTopic: undefined }]) expect((await w.steps.acquireEvidence(s.t, bad, "b1", 120_000)).acquired).toBe(false);
      expect(w.reads.length).toBe(before);
    } finally { w.done(); }
  });
  it.each(SITES)("refuses to buy facts against a stale owned-page capture [$t]", async (s) => { const w = await world(s, s.found, null, false, true); try { const pass = await w.steps.factCheck(s.t, 120_000); expect([w.got.acquired, pass.banked, w.raw.length, w.reads.length, w.ownedReads.length], "a stale known-good body is for display continuity, not targeted or ordinary factual-source inventory and paid search").toEqual([false, 0, 0, 0, 2]); } finally { w.done(); } });
  it.each(SITES)("researches a missing subject in the frame of its own search, reads the page the requirement named before buying any search, and banks the answer quoted from that page [$t]", async (s) => {
    const w = await world(s, s.rival, s.says);
    const row = w.ROWS[0] as { subject: string; statementKey: string; state: string; proposed: string | null; rulesVersion: number; sources: { url: string; says: string; support?: { supported: boolean } }[] };
    expect([row.subject, row.statementKey, w.asked.some((a) => a.includes(`Subject: ${s.search} ${s.topic}`))],
      "the acquired subject may be framed by the search, but it stays bound to the original missing-topic atom and the judge reads the framed subject").toEqual([`${s.search} ${s.topic}`, claimIdentity(s.topic, "", "missing"), true]);
    expect(w.reads, "the page the comparison found the subject on is the only thing read: a search is not bought to rediscover a page the requirement already names").toEqual([`onpage_content_parsing ${s.rival}`]);
    expect([row.state, row.proposed, row.sources.map((x) => [x.url, x.says, x.support?.supported === true])],
      "and the answer is banked as a checked statement quoted from that page, with that page named as the source standing behind it").toEqual(["checked", s.says, [[s.rival, s.says, true]]]);
    expect([w.got.acquired, w.got.unlocked], "so the obligation the money was spent on is met on this one acquisition").toEqual([true, true]);
    w.done(); });
  it.each(SITES.flatMap((s) => [false, true].map((nominated) => ({ ...s, nominated }))))("banks an alternative when the first named page is unreadable, using named URLs before search [$t, nominated=$nominated]", async (s) => {
    const w = await world(s, s.found, null, false, false, s.nominated ? [s.rival, s.found] : undefined);
    const row = w.ROWS[0] as { state: string; proposed: string | null; sources: { url: string }[] };
    expect(w.reads, "named candidates are reused before a proposition-specific search is bought").toEqual([`onpage_content_parsing ${s.rival}`, ...(s.nominated ? [] : [`serp_organic ${s.title} ${s.topic}`]), `onpage_content_parsing ${s.found}`]);
    expect([row.state, row.proposed, row.sources.map((x) => x.url), w.got.acquired, w.got.unlocked],
      "and the statement stands on the source the search found, exactly as it did before any page was ever named").toEqual(["checked", s.says, [s.found], true, true]);
    w.done(); });
  it.each(["tenant-one", "tenant-two"])("reads the winners of a search that names no page, through the winning pages unit and never the results page again [%s]", async (tenant) => {
    CALLS.serp.length = 0; CALLS.win.length = 0; STATE.done = ["how deep is the well"]; STATE.read = ["how deep is the well"]; const got = await defaultSteps.acquireEvidence(tenant, { kind: "competitor_page", query: "how deep is the well", workKey: "test-work" }, "b", 5_000);
    expect([got.acquired, CALLS.win, CALLS.serp], "the search alone is enough to buy the reading it owes, and nothing sends it back to the results page it already has").toEqual([true, [{ qs: ["how deep is the well"], owned: null }], []]); });
  it.each(["tenant-one", "tenant-two"])("answers not acquired where no winner of that search carries a reading on file, so the drive counts the attempt instead of buying it again [%s]", async (tenant) => {
    CALLS.win.length = 0; STATE.done = []; STATE.read = []; const got = await defaultSteps.acquireEvidence(tenant, { kind: "competitor_page", query: "how deep is the well", workKey: "test-work" }, "b", 5_000);
    expect([got.acquired, got.detail], "the unit ran, nothing readable came back, and the receipt says exactly that in plain words").toEqual([false, 'winning pages for "how deep is the well": no winner of that search carries a reading on file under b after the unit finished']); });
});
