/**
 * page-brief (2026-06-25) — turn one page's Workbench analysis into a focused,
 * downloadable Markdown brief the operator hands a developer to action that single
 * page. Pure + dependency-free (structural inputs only) so it's testable and reused
 * by the client download button. Distinct from the whole-site worklist export: this
 * is the deep, single-page task sheet (queries it ranks for, the quick wins, the
 * best next move) — no jargon, no internal IDs.
 */

export type PageBriefQuery = { query: string; impressions: number; clicks: number; position: number };
export type PageBriefStriking = { keyword: string; volume: number; position: number };

export type PageBriefInput = {
  path: string;
  canonUrl?: string | null;
  title?: string | null;
  h1?: string | null;
  metaDescription?: string | null;
  topQueries: PageBriefQuery[];
  strikingDistance: PageBriefStriking[];
  /** The single highest-priority move, if the optimizer found one. */
  bestMove?: string | null;
};

function line(label: string, value: string | null | undefined): string {
  return value && value.trim() ? `- **${label}:** ${value.trim()}` : `- **${label}:** _(none)_`;
}

/** Build the single-page Markdown brief. `dateLabel` is injected (no Date dep). */
export function buildPageBriefMarkdown(b: PageBriefInput, opts: { dateLabel?: string } = {}): string {
  const lines: string[] = [];
  lines.push(`# Page brief: ${b.path}`);
  if (b.canonUrl) lines.push(b.canonUrl);
  if (opts.dateLabel?.trim()) lines.push(`_Generated ${opts.dateLabel.trim()}_`);
  lines.push("");

  if (b.bestMove?.trim()) {
    lines.push(`## ▶ Do this first`);
    lines.push(b.bestMove.trim());
    lines.push("");
  }

  lines.push(`## Current on-page`);
  lines.push(line("Title", b.title));
  lines.push(line("H1", b.h1));
  lines.push(line("Meta description", b.metaDescription));
  lines.push("");

  if (b.strikingDistance.length > 0) {
    lines.push(`## Quick wins — ranking just off the top (improve these)`);
    for (const s of b.strikingDistance) {
      lines.push(`- "${s.keyword}" — position ${s.position.toFixed(1)}, ${s.volume.toLocaleString()} searches/mo`);
    }
    lines.push("");
  }

  if (b.topQueries.length > 0) {
    lines.push(`## What this page ranks for (top queries)`);
    lines.push(`| Query | Position | Clicks/mo | Impressions/mo |`);
    lines.push(`| --- | --- | --- | --- |`);
    for (const q of b.topQueries.slice(0, 15)) {
      lines.push(`| ${q.query} | ${q.position.toFixed(1)} | ${q.clicks.toLocaleString()} | ${q.impressions.toLocaleString()} |`);
    }
    lines.push("");
  }

  lines.push("---");
  lines.push("_Generated by Beacon from your Google Search Console data._");
  return lines.join("\n");
}
