-- 2026-07-03 - cron_runs: per-run ledger for every nightly job (BEACON_500 item 85).
CREATE TABLE IF NOT EXISTS public.cron_runs (
  id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id     text,
  job           text NOT NULL,
  started_at    timestamptz NOT NULL,
  finished_at   timestamptz,
  duration_ms   integer,
  ok            boolean NOT NULL DEFAULT false,
  per_source    jsonb,
  notes         jsonb,
  created_at    timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS cron_runs_job_started_idx ON public.cron_runs (job, started_at DESC);
CREATE INDEX IF NOT EXISTS cron_runs_tenant_started_idx ON public.cron_runs (tenant_id, started_at DESC);
ALTER TABLE public.cron_runs ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS deny_anon ON public.cron_runs;
CREATE POLICY deny_anon ON public.cron_runs AS PERMISSIVE FOR ALL TO anon USING (false) WITH CHECK (false);
DROP POLICY IF EXISTS tenant_authenticated_rw ON public.cron_runs;
CREATE POLICY tenant_authenticated_rw ON public.cron_runs AS PERMISSIVE FOR ALL TO authenticated
  USING (tenant_id IS NULL OR is_tenant_member(tenant_id)) WITH CHECK (tenant_id IS NULL OR is_tenant_member(tenant_id));;
