import { describe, it, expect } from "vitest";

import { buildWorklistMarkdown, type ExportItem } from "@/app/(shell)/worklist-export";

const item = (kind: string, query: string, page: string, clicksAtStake: number, detail?: string): ExportItem => ({
  kind,
  query,
  page,
  clicksAtStake,
  detail,
});

describe("buildWorklistMarkdown", () => {
  const items = [
    item("win", "persian girl names", "https://x.com/persian-female-first-names", 342, "pos 5.7"),
    item("recover", "iranian actors", "https://x.com/iranian-actors-actresses", 73),
  ];

  it("renders a titled, numbered, impact-summed work doc", () => {
    const md = buildWorklistMarkdown(items, { siteName: "Iranopedia", dateLabel: "2026-06-25" });
    expect(md).toContain("# Iranopedia — SEO worklist");
    expect(md).toContain("_Generated 2026-06-25_");
    expect(md).toContain("2 prioritized tasks");
    expect(md).toContain("~415 monthly clicks at stake"); // 342 + 73
    expect(md).toContain('### 1. Win the top spot for "persian girl names"');
    expect(md).toContain('### 2. Recover lost ground on "iranian actors"');
    expect(md).toContain("persian female first names"); // prettified slug
    expect(md).toContain("**Why:** pos 5.7");
  });

  it("maps each kind to a plain-English verb", () => {
    const md = buildWorklistMarkdown([
      item("cite", "q", "https://x/p", 10),
      item("build", "q", "https://x/p", 10),
      item("edit", "q", "https://x/p", 10),
    ]);
    expect(md).toContain("Get cited by AI for");
    expect(md).toContain("Build a page for");
    expect(md).toContain("Improve");
  });

  it("omits the date line when not provided + handles negatives", () => {
    const md = buildWorklistMarkdown([item("win", "q", "https://x/p", -5)]);
    expect(md).not.toMatch(/_Generated \d{4}-/); // no date-stamped line (footer "_Generated by Beacon_" is fine)
    expect(md).toContain("~0 clicks/mo at stake"); // clamped
  });
});
